# Generated by Django 4.2.26 on 2025-11-21 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Homepage'), ('blog', 'Blog')], default='home', max_length=32)),
                ('slot', models.CharField(choices=[('hero', 'Hero'), ('suite_card', 'Assessment card'), ('feature_card', 'Feature panel'), ('testimonial', 'Testimonial')], default='feature_card', max_length=32)),
                ('title', models.CharField(max_length=220)),
                ('subtitle', models.CharField(blank=True, max_length=220)),
                ('body', models.TextField(blank=True)),
                ('badge', models.CharField(blank=True, max_length=120)),
                ('cta_label', models.CharField(blank=True, max_length=120)),
                ('cta_url', models.URLField(blank=True)),
                ('secondary_cta_label', models.CharField(blank=True, max_length=120)),
                ('secondary_cta_url', models.URLField(blank=True)),
                ('list_items', models.TextField(blank=True, help_text='For bullet lists. Enter one item per line.')),
                ('meta_items', models.TextField(blank=True, help_text='Optional key/value pairs. Format: Label | Value per line.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('page', 'slot', 'order'),
            },
        ),
    ]
