# Generated by Django 4.2.26 on 2025-11-21 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontentblock',
            name='page',
            field=models.CharField(choices=[('home', 'Homepage'), ('blog', 'Blog'), ('contact', 'Contact'), ('careers', 'Careers'), ('security', 'Security'), ('privacy', 'Privacy'), ('terms', 'Terms'), ('resources', 'Resources')], default='home', max_length=32),
        ),
        migrations.AlterField(
            model_name='sitecontentblock',
            name='slot',
            field=models.CharField(choices=[('hero', 'Hero'), ('page_hero', 'Page hero'), ('page_section', 'Page section'), ('suite_heading', 'Assessment section heading'), ('suite_card', 'Assessment card'), ('feature_card', 'Feature panel'), ('testimonial', 'Testimonial')], default='feature_card', max_length=32),
        ),
    ]
