# Generated by Django 4.2.26 on 2025-11-21 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0002_alter_sitecontentblock_page_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('summary', models.TextField()),
                ('category', models.CharField(choices=[('guide', 'Guide'), ('template', 'Template'), ('toolkit', 'Toolkit')], max_length=32)),
                ('file', models.FileField(upload_to='resources/')),
                ('external_url', models.URLField(blank=True)),
                ('version', models.CharField(blank=True, max_length=40)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('order', 'title'),
            },
        ),
    ]
