# Generated by Django 4.2.26 on 2025-11-12 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.TextField()),
                ('level', models.CharField(choices=[('intro', 'Introductory'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intro', max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(default=20)),
                ('skills_focus', models.JSONField(blank=True, default=list, help_text='List of core skill areas evaluated (stored as strings).')),
                ('scoring_rubric', models.JSONField(blank=True, default=dict, help_text='Optional JSON payload describing scoring methodology.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(blank=True, max_length=80)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('headline', models.CharField(blank=True, max_length=180)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('first_name', 'last_name'),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prompt', models.TextField()),
                ('question_type', models.CharField(choices=[('single', 'Single Select'), ('multi', 'Multi Select'), ('scale', 'Likert Scale'), ('text', 'Free Text')], default='single', max_length=12)),
                ('order', models.PositiveIntegerField(default=1)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Use for extra configuration such as scale labels.')),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, help_text='Relative weight when computing a score.', max_digits=5)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.assessment')),
            ],
            options={
                'ordering': ('assessment', 'order'),
                'unique_together': {('assessment', 'order')},
            },
        ),
        migrations.CreateModel(
            name='RoleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Optional icon token for the front-end (e.g. heroicons-briefcase).', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=255)),
                ('value', models.CharField(blank=True, max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, help_text='Contribution to scoring when this choice is selected.', max_digits=5)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='assessments.question')),
            ],
            options={
                'ordering': ('question', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AssessmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('invited', 'Invited'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('invited_by', models.CharField(blank=True, help_text='Internal hiring manager or recruiter creating the invite.', max_length=120)),
                ('invited_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('score_breakdown', models.JSONField(blank=True, default=dict, help_text='Store per-skill statistics and confidence intervals.')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='assessments.assessment')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='assessments.candidateprofile')),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('candidate', 'assessment')},
            },
        ),
        migrations.AddField(
            model_name='assessment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='assessments.rolecategory'),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer_text', models.TextField(blank=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assessments.question')),
                ('selected_choices', models.ManyToManyField(blank=True, related_name='responses', to='assessments.choice')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assessments.assessmentsession')),
            ],
            options={
                'ordering': ('question__order',),
                'unique_together': {('session', 'question')},
            },
        ),
    ]
