# Generated by Django 4.2.26 on 2025-11-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_assessmentsession_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentsession',
            name='decision',
            field=models.CharField(choices=[('undecided', 'Undecided'), ('advance', 'Advance'), ('reject', 'Reject'), ('hired', 'Hired')], default='undecided', max_length=20),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='decision_notes',
            field=models.TextField(blank=True, help_text='Internal notes regarding the decision.'),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='due_at',
            field=models.DateTimeField(blank=True, help_text='Optional deadline communicated to the candidate.', null=True),
        ),
    ]
