# Generated by Django 4.2.26 on 2025-11-15 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_assessmentsession_decision_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('allowed_assessment_types', models.JSONField(blank=True, default=list, help_text='List of assessment type keys the company can access.')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='assessment',
            name='assessment_type',
            field=models.CharField(choices=[('behavioral', 'Behavioral'), ('skills', 'Skills'), ('technical', 'Technical'), ('case_study', 'Case Study')], default='behavioral', max_length=40),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single', 'Single Select'), ('multi', 'Multi Select'), ('scale', 'Likert Scale'), ('text', 'Free Text'), ('behavioral', 'Behavioral Matrix')], default='single', max_length=12),
        ),
        migrations.CreateModel(
            name='PositionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('assessment_type', models.CharField(choices=[('behavioral', 'Behavioral'), ('skills', 'Skills'), ('technical', 'Technical'), ('case_study', 'Case Study')], default='behavioral', max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position_tasks', to='assessments.assessment')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_tasks', to='assessments.companyprofile')),
            ],
            options={
                'ordering': ('company', 'title'),
            },
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='assessments.companyprofile'),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='position_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='assessments.positiontask'),
        ),
    ]
