# Generated by Django 4.2.26 on 2025-11-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_companyprofile_assessment_assessment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentsession',
            name='behavioral_focus',
            field=models.JSONField(blank=True, default=list, help_text='Subset of behavioural traits targeted for this session.'),
        ),
        migrations.AddField(
            model_name='positiontask',
            name='behavioral_focus',
            field=models.JSONField(blank=True, default=list, help_text='Subset of behavioural traits emphasized for this task.'),
        ),
    ]
