# Generated by Django 4.2.26 on 2025-11-19 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_assessmentsession_behavioral_focus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentsession',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('invited', 'Invited'), ('in_progress', 'In Progress'), ('paused', 'Paused'), ('completed', 'Completed'), ('expired', 'Expired')], default='draft', max_length=20),
        ),
    ]
