# Generated by Django 4.2.26 on 2025-11-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_alter_assessmentsession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentsession',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, help_text='Tracks the most recent time the candidate interacted.', null=True),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='paused_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the candidate paused the assessment.', null=True),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='total_paused_seconds',
            field=models.PositiveIntegerField(default=0, help_text='How long the session has been paused in aggregate.'),
        ),
    ]
