# Generated by Django 4.2.26 on 2025-11-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_assessmentsession_last_activity_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentsession',
            name='telemetry_log',
            field=models.JSONField(blank=True, default=dict, help_text='Raw telemetry such as device info, ip history, paste events.'),
        ),
    ]
