# Generated by Django 4.2.26 on 2026-01-31 21:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0021_alter_clientsessionnote_assessment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UXDesignQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple choice'), ('scenario', 'Scenario based'), ('ranking', 'Ranking / Ordering'), ('behavioral_most', 'Behavioral - most like me'), ('behavioral_least', 'Behavioral - least like me'), ('reasoning', 'Reasoning / open response')], max_length=32)),
                ('difficulty_level', models.PositiveSmallIntegerField(default=3)),
                ('category', models.CharField(choices=[('user_research', 'User Research'), ('information_architecture', 'Information Architecture'), ('interaction_design', 'Interaction Design'), ('visual_design', 'Visual Design'), ('usability_accessibility', 'Usability & Accessibility'), ('design_strategy', 'Design Strategy'), ('behavioral', 'Behavioral')], max_length=32)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('correct_answer', models.JSONField(blank=True, null=True)),
                ('scoring_weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('explanation', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('category', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='UXDesignAssessmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('candidate_id', models.CharField(db_index=True, max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In progress'), ('paused', 'Paused'), ('submitted', 'Submitted')], default='draft', max_length=16)),
                ('question_set', models.JSONField(default=list)),
                ('responses', models.JSONField(blank=True, default=list)),
                ('hard_skill_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('soft_skill_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('category_breakdown', models.JSONField(blank=True, default=dict)),
                ('recommendations', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('last_reminder_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_count', models.PositiveIntegerField(default=0)),
                ('deadline_type', models.CharField(choices=[('none', 'No deadline'), ('relative', 'Days from invite'), ('absolute', 'Specific date')], default='none', max_length=16)),
                ('deadline_days', models.PositiveIntegerField(blank=True, help_text='Days from invite to complete', null=True)),
                ('deadline_at', models.DateTimeField(blank=True, help_text='Absolute deadline', null=True)),
                ('candidate_feedback_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('candidate_feedback_comment', models.TextField(blank=True)),
                ('candidate_feedback_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('candidate_feedback_email', models.EmailField(blank=True, max_length=254)),
                ('candidate_feedback_phone', models.CharField(blank=True, max_length=120)),
                ('candidate_feedback_opt_in', models.BooleanField(default=False)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('total_paused_seconds', models.PositiveIntegerField(default=0)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('telemetry_log', models.JSONField(blank=True, default=dict)),
                ('pipeline_stage', models.CharField(choices=[('invited', 'Invited'), ('in_progress', 'In progress'), ('submitted', 'Assessment submitted'), ('interview', 'Interview'), ('offer', 'Offer extended'), ('hired', 'Hired / onboarded'), ('rejected', 'Not moving forward')], default='invited', max_length=32)),
                ('pipeline_stage_updated_at', models.DateTimeField(blank=True, null=True)),
                ('level', models.CharField(choices=[('junior', 'Junior (0-2 years)'), ('mid', 'Mid-Level (2-5 years)'), ('senior', 'Senior (5+ years)')], default='mid', help_text='Target experience level for this assessment', max_length=10)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ux_sessions', to='clients.clientaccount')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ux_sessions', to='clients.clientproject')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['candidate_id'], name='ux_assessme_candida_f9652b_idx')],
            },
        ),
    ]
