# Generated by Django 4.2.26 on 2025-11-14 04:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('pill_label', models.CharField(max_length=120)),
                ('pill_class', models.CharField(choices=[('accent', 'Accent'), ('success', 'Success'), ('neutral', 'Neutral')], default='accent', max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('publish_date', models.DateField()),
            ],
            options={
                'ordering': ('order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('panel_title', models.CharField(max_length=255)),
                ('panel_subtitle', models.TextField()),
                ('panel_points', models.TextField(help_text='Enter one bullet per line. They will display on the right panel.')),
            ],
            options={
                'ordering': ('order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MarketingCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hero_badge', models.CharField(blank=True, default='Backed by Y\xa0Combinator', max_length=120)),
                ('hero_heading', models.CharField(blank=True, default='Run assessments and hiring decisions from one console', max_length=255)),
                ('hero_subheading', models.TextField(blank=True, default='Sira unifies company workflows and the candidate experience—invite talent, capture evidence, auto score, and advance top performers in minutes.')),
                ('hero_primary_cta', models.CharField(blank=True, default='Book a Demo', max_length=120)),
                ('hero_secondary_cta', models.CharField(blank=True, default='See how it works', max_length=120)),
                ('cta_title', models.CharField(blank=True, default='Get started today.', max_length=255)),
                ('cta_body', models.TextField(blank=True, default='Full-service support for talent teams rolling out assessments across the org.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('quote', models.TextField()),
                ('avatar_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ('order', 'id'),
                'abstract': False,
            },
        ),
    ]
