# Generated by Django 4.2.26 on 2026-01-16 15:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('use_case', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Under Review'), ('approved', 'Approved'), ('credentials_sent', 'Credentials Sent'), ('active', 'Active Integration'), ('declined', 'Declined')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('api_key_issued_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes from the team')),
            ],
            options={
                'verbose_name': 'API Access Request',
                'verbose_name_plural': 'API Access Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
