# Generated by Django 4.2.26 on 2026-01-18 02:26

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_add_newsletter_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="URL slug (e.g., 'marketing' for /assessments/marketing/)", unique=True)),
                ('internal_code', models.CharField(help_text="Maps to ClientAccount.allowed_assessments (e.g., 'marketing')", max_length=50, unique=True)),
                ('title', models.CharField(help_text="Main headline (e.g., 'Marketing IQ Assessment')", max_length=160)),
                ('subtitle', models.CharField(blank=True, help_text='Secondary headline', max_length=220)),
                ('label', models.CharField(help_text="Short label (e.g., 'Marketing IQ')", max_length=60)),
                ('summary', models.TextField(help_text='Brief description for cards and previews')),
                ('description', models.TextField(blank=True, help_text='Extended description for detail page')),
                ('icon_svg', models.TextField(blank=True, help_text='SVG code for the assessment icon')),
                ('featured_image', models.URLField(blank=True, help_text='Hero image URL for detail page')),
                ('duration_minutes', models.PositiveIntegerField(default=30, help_text='Estimated completion time')),
                ('question_count', models.PositiveIntegerField(default=20, help_text='Number of questions')),
                ('difficulty_level', models.CharField(choices=[('adaptive', 'Adaptive'), ('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='adaptive', help_text='Difficulty level indicator', max_length=20)),
                ('skills_tested', models.JSONField(blank=True, default=list, help_text="List of skills: [{'name': '...', 'description': '...'}]")),
                ('focus_areas', models.JSONField(blank=True, default=list, help_text="List of focus areas: ['Paid media', 'SEO', ...]")),
                ('sample_questions', models.JSONField(blank=True, default=list, help_text="Sample questions: [{'question': '...', 'type': '...'}]")),
                ('stats', models.JSONField(blank=True, default=list, help_text="Display stats: [{'label': '...', 'value': '...'}]")),
                ('use_cases', models.JSONField(blank=True, default=list, help_text="Use cases: [{'title': '...', 'description': '...'}]")),
                ('faqs', models.JSONField(blank=True, default=list, help_text="FAQs: [{'question': '...', 'answer': '...'}]")),
                ('scoring_rubric', models.TextField(blank=True, help_text='Scoring methodology explanation')),
                ('overview_content', models.TextField(blank=True, help_text='Full overview content (supports HTML)')),
                ('cta_label', models.CharField(default='Start Free Trial', max_length=60)),
                ('cta_url', models.CharField(blank=True, help_text='Custom CTA URL (defaults to demo request)', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Show on public pages')),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
                ('meta_title', models.CharField(blank=True, help_text='SEO title (defaults to title)', max_length=160)),
                ('meta_description', models.CharField(blank=True, help_text='SEO description (defaults to summary)', max_length=300)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255)),
                ('meta_image', models.URLField(blank=True, help_text='Social sharing image URL')),
                ('preview_key', models.UUIDField(default=uuid.uuid4, help_text='Secret key for preview access')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Public Assessment',
                'verbose_name_plural': 'Public Assessments',
                'ordering': ['order', 'title'],
            },
        ),
    ]
