# Generated by Django 4.2.26 on 2026-02-12 16:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_publicassessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="URL identifier, e.g. 'senior-product-manager'", max_length=120, unique=True)),
                ('title', models.CharField(help_text="Display name, e.g. 'Senior Product Manager'", max_length=200)),
                ('department', models.CharField(help_text='e.g. Marketing, Product, Design, HR, Finance, Leadership', max_length=60)),
                ('seniority_level', models.CharField(choices=[('junior', 'Junior'), ('mid', 'Mid-Level'), ('senior', 'Senior'), ('lead', 'Lead'), ('executive', 'Executive')], default='mid', max_length=20)),
                ('description', models.TextField(help_text='2-3 sentence role description')),
                ('responsibilities', models.JSONField(blank=True, default=list, help_text='JSON list of key responsibilities')),
                ('key_skills', models.JSONField(blank=True, default=list, help_text='JSON list of skills required')),
                ('meta_title', models.CharField(blank=True, max_length=160)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_types', models.ManyToManyField(blank=True, help_text='Which Evalon assessments are relevant for this role', related_name='roles', to='pages.publicassessment')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('behavioral', 'Behavioral'), ('situational', 'Situational'), ('leadership', 'Leadership'), ('culture', 'Culture Fit'), ('problem_solving', 'Problem Solving')], max_length=30)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('what_it_tests', models.CharField(help_text='Brief explanation of what this question evaluates', max_length=200)),
                ('sample_answer_outline', models.TextField(blank=True, help_text='Brief outline of a good answer')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('assessment_type', models.ForeignKey(blank=True, help_text='Links to relevant Evalon assessment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_questions', to='pages.publicassessment')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_questions', to='pages.role')),
            ],
            options={
                'verbose_name': 'Interview Question',
                'verbose_name_plural': 'Interview Questions',
                'ordering': ['order', 'category'],
            },
        ),
    ]
