# Generated by Django 4.2.26 on 2026-03-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_role_interviewquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeCheckerLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('full_name', models.CharField(blank=True, default='', max_length=200)),
                ('ats_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('verdict', models.CharField(blank=True, default='', max_length=50)),
                ('result_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Resume Checker Lead',
                'verbose_name_plural': 'Resume Checker Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
