# Generated by Django 4.2.26 on 2026-03-22 16:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_resumecheckerlead'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(choices=[('professional', 'Professional'), ('modern', 'Modern'), ('minimal', 'Minimal')], default='professional', max_length=20)),
                ('example_summary', models.TextField(help_text='Example professional summary for this role')),
                ('example_experience', models.JSONField(default=list, help_text='[{"title":"...", "company":"...", "duration":"...", "bullets":["..."]}]')),
                ('example_skills', models.JSONField(default=list, help_text='["Skill 1", ...]')),
                ('example_education', models.JSONField(default=list, help_text='[{"degree":"...", "school":"...", "year":"..."}]')),
                ('resume_tips', models.JSONField(default=list, help_text='[{"title":"...", "description":"..."}]')),
                ('keywords_to_include', models.JSONField(blank=True, default=list)),
                ('common_mistakes', models.JSONField(blank=True, default=list)),
                ('faqs', models.JSONField(blank=True, default=list, help_text='[{"q":"...", "a":"..."}]')),
                ('meta_title', models.CharField(blank=True, max_length=160)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('downloads_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume_template', to='pages.role')),
            ],
            options={
                'ordering': ['role__order', 'role__title'],
            },
        ),
        migrations.CreateModel(
            name='ResumeBuilderLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('full_name', models.CharField(max_length=200)),
                ('template_style', models.CharField(blank=True, max_length=20)),
                ('resume_data', models.JSONField(blank=True, null=True)),
                ('downloaded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_builder_leads', to='pages.role')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
