# Generated by Django 4.2.26 on 2025-11-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Evalon', help_text='Used as a default prefix/suffix for titles across the site.', max_length=150)),
                ('meta_title', models.CharField(blank=True, help_text='Default title tag when a page does not override it.', max_length=255)),
                ('meta_description', models.TextField(blank=True, help_text='Default meta description for search and preview cards.')),
                ('meta_keywords', models.CharField(blank=True, help_text='Optional comma-separated keywords for SEO metadata.', max_length=512)),
                ('meta_image', models.FileField(blank=True, help_text='Used for Open Graph/Twitter preview cards.', null=True, upload_to='marketing/meta/')),
                ('favicon', models.FileField(blank=True, help_text='Small icon that appears in browser tabs.', null=True, upload_to='marketing/favicon/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Marketing & SEO Settings',
            },
        ),
    ]
