# Generated by Django 4.2.26 on 2025-11-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingsettings',
            name='favicon_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketingsettings',
            name='favicon_mime',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='marketingsettings',
            name='meta_image_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketingsettings',
            name='meta_image_mime',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='marketingsettings',
            name='favicon',
            field=models.FileField(blank=True, help_text='Upload the icon that appears in browser tabs.', null=True, upload_to='marketing/favicon/'),
        ),
        migrations.AlterField(
            model_name='marketingsettings',
            name='meta_image',
            field=models.FileField(blank=True, help_text='Upload an image used for Open Graph/Twitter preview cards.', null=True, upload_to='marketing/meta/'),
        ),
    ]
