# Generated by Django 4.2.26 on 2025-11-24 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_marketingsettings_email_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketingsettings',
            name='default_from_email',
        ),
        migrations.RemoveField(
            model_name='marketingsettings',
            name='email_host',
        ),
        migrations.RemoveField(
            model_name='marketingsettings',
            name='email_password',
        ),
        migrations.RemoveField(
            model_name='marketingsettings',
            name='email_port',
        ),
        migrations.RemoveField(
            model_name='marketingsettings',
            name='email_use_tls',
        ),
        migrations.RemoveField(
            model_name='marketingsettings',
            name='email_username',
        ),
    ]
