from django.urls import path

from marketing_assessments import views_candidate as marketing_views
from pm_assessments import views_candidate as pm_views
from behavioral_assessments import views_candidate as behavioral_views

from . import views

app_name = "candidate"

urlpatterns = [
    path(
        "<uuid:session_uuid>/",
        views.SessionIntroView.as_view(),
        name="session-entry",
    ),
    path(
        "<uuid:session_uuid>/start/",
        views.SessionAssessmentView.as_view(),
        name="session-start",
    ),
    path(
        "<uuid:session_uuid>/complete/",
        views.SessionCompleteView.as_view(),
        name="session-complete",
    ),
    path(
        "<uuid:session_uuid>/pause/",
        views.SessionPauseActionView.as_view(),
        name="session-pause",
    ),
    path(
        "<uuid:session_uuid>/paused/",
        views.SessionPausedView.as_view(),
        name="session-paused",
    ),
    path(
        "<uuid:session_uuid>/resume/",
        views.SessionResumeView.as_view(),
        name="session-resume",
    ),
    path(
        "<uuid:session_uuid>/send-link/",
        views.SessionSendLinkView.as_view(),
        name="session-send-link",
    ),
    path(
        "<uuid:session_uuid>/practice/",
        views.SessionPracticeView.as_view(),
        name="session-practice",
    ),
    path(
        "marketing/<uuid:session_uuid>/",
        marketing_views.MarketingAssessmentView.as_view(),
        name="marketing-session",
    ),
    path(
        "marketing/<uuid:session_uuid>/complete/",
        marketing_views.MarketingAssessmentCompleteView.as_view(),
        name="marketing-complete",
    ),
    path(
        "marketing/<uuid:session_uuid>/expired/",
        marketing_views.MarketingAssessmentExpiredView.as_view(),
        name="marketing-expired",
    ),
    path(
        "marketing/<uuid:session_uuid>/pause/",
        marketing_views.MarketingSessionPauseView.as_view(),
        name="marketing-pause",
    ),
    path(
        "marketing/<uuid:session_uuid>/paused/",
        marketing_views.MarketingSessionPausedView.as_view(),
        name="marketing-paused",
    ),
    path(
        "marketing/<uuid:session_uuid>/resume/",
        marketing_views.MarketingSessionResumeView.as_view(),
        name="marketing-resume",
    ),
    path(
        "marketing/<uuid:session_uuid>/send-link/",
        marketing_views.MarketingSessionSendLinkView.as_view(),
        name="marketing-send-link",
    ),
    path(
        "pm/<uuid:session_uuid>/",
        pm_views.ProductAssessmentView.as_view(),
        name="pm-session",
    ),
    path(
        "pm/<uuid:session_uuid>/complete/",
        pm_views.ProductAssessmentCompleteView.as_view(),
        name="pm-complete",
    ),
    path(
        "pm/<uuid:session_uuid>/expired/",
        pm_views.ProductAssessmentExpiredView.as_view(),
        name="pm-expired",
    ),
    path(
        "pm/<uuid:session_uuid>/pause/",
        pm_views.ProductAssessmentPauseView.as_view(),
        name="pm-pause",
    ),
    path(
        "pm/<uuid:session_uuid>/paused/",
        pm_views.ProductAssessmentPausedView.as_view(),
        name="pm-paused",
    ),
    path(
        "pm/<uuid:session_uuid>/resume/",
        pm_views.ProductAssessmentResumeView.as_view(),
        name="pm-resume",
    ),
    path(
        "pm/<uuid:session_uuid>/send-link/",
        pm_views.ProductAssessmentSendLinkView.as_view(),
        name="pm-send-link",
    ),
    path(
        "behavioral/<uuid:session_uuid>/",
        behavioral_views.BehavioralAssessmentView.as_view(),
        name="behavioral-session",
    ),
    path(
        "behavioral/<uuid:session_uuid>/complete/",
        behavioral_views.BehavioralAssessmentCompleteView.as_view(),
        name="behavioral-complete",
    ),
    path(
        "behavioral/<uuid:session_uuid>/expired/",
        behavioral_views.BehavioralAssessmentExpiredView.as_view(),
        name="behavioral-expired",
    ),
    path(
        "behavioral/<uuid:session_uuid>/pause/",
        behavioral_views.BehavioralAssessmentPauseView.as_view(),
        name="behavioral-pause",
    ),
    path(
        "behavioral/<uuid:session_uuid>/paused/",
        behavioral_views.BehavioralAssessmentPausedView.as_view(),
        name="behavioral-paused",
    ),
    path(
        "behavioral/<uuid:session_uuid>/resume/",
        behavioral_views.BehavioralAssessmentResumeView.as_view(),
        name="behavioral-resume",
    ),
    path(
        "behavioral/<uuid:session_uuid>/send-link/",
        behavioral_views.BehavioralAssessmentSendLinkView.as_view(),
        name="behavioral-send-link",
    ),
]
