# Generated by Django 4.2.26 on 2025-11-17 15:44

from django.db import migrations, models


def copy_requested_assessments(apps, schema_editor):
    ClientAccount = apps.get_model('clients', 'ClientAccount')
    for account in ClientAccount.objects.all():
        legacy_value = getattr(account, 'requested_assessment', None)
        if legacy_value and not account.requested_assessments:
            account.requested_assessments = [legacy_value]
            account.save(update_fields=['requested_assessments'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaccount',
            name='requested_assessments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(copy_requested_assessments, reverse_code=noop),
        migrations.RemoveField(
            model_name='clientaccount',
            name='requested_assessment',
        ),
    ]
