# Generated by Django 4.2.26 on 2025-11-19 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0002_remove_clientaccount_requested_assessment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaccount',
            name='receive_weekly_summary',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ClientSessionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_type', models.CharField(choices=[('marketing', 'Marketing Assessment'), ('product', 'Product Management Assessment'), ('behavioral', 'Behavioral Assessment')], max_length=32)),
                ('session_uuid', models.UUIDField()),
                ('candidate_id', models.CharField(max_length=120)),
                ('note', models.TextField(blank=True)),
                ('needs_review', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_notes', to='clients.clientaccount')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
