# Generated by Django 4.2.26 on 2025-11-19 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_clientaccount_receive_weekly_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaccount',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('viewer', 'Viewer')], default='manager', max_length=16),
        ),
        migrations.AddField(
            model_name='clientaccount',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='client_logos/'),
        ),
        migrations.CreateModel(
            name='ClientNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('success', 'Success')], default='info', max_length=16)),
                ('link_url', models.URLField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='clients.clientaccount')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
