# Generated by Django 4.2.26 on 2025-11-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_clientaccount_role_clientnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsessionnote',
            name='author_role',
            field=models.CharField(choices=[('manager', 'Manager'), ('recruiter', 'Recruiter'), ('interviewer', 'Interviewer'), ('executive', 'Executive'), ('viewer', 'Viewer')], default='manager', max_length=20),
        ),
        migrations.AddField(
            model_name='clientsessionnote',
            name='decision',
            field=models.CharField(blank=True, choices=[('advance', 'Advance'), ('hold', 'Hold'), ('reject', 'Reject')], max_length=20),
        ),
        migrations.AddField(
            model_name='clientsessionnote',
            name='note_type',
            field=models.CharField(choices=[('comment', 'Comment'), ('decision', 'Decision')], default='comment', max_length=20),
        ),
        migrations.AlterField(
            model_name='clientaccount',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('recruiter', 'Recruiter'), ('interviewer', 'Interviewer'), ('executive', 'Executive'), ('viewer', 'Viewer')], default='manager', max_length=16),
        ),
    ]
