# Generated by Django 4.2.26 on 2025-11-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_clientsessionnote_author_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaccount',
            name='data_retention_days',
            field=models.PositiveIntegerField(default=365),
        ),
    ]
