# Generated by Django 4.2.26 on 2025-11-21 15:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_clientaccount_data_retention_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('role_level', models.CharField(blank=True, max_length=120)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('priority', models.CharField(choices=[('p0', 'Critical'), ('p1', 'High'), ('p2', 'Medium'), ('p3', 'Low')], default='p1', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Actively hiring'), ('on_hold', 'On hold'), ('filled', 'Role filled'), ('archived', 'Archived')], default='active', max_length=16)),
                ('open_roles', models.PositiveIntegerField(default=1)),
                ('target_start_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='clients.clientaccount')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
