# Generated by Django 4.2.26 on 2025-11-22 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_clientproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaccount',
            name='invite_quota',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='clientaccount',
            name='invite_quota_reset',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientaccount',
            name='plan_slug',
            field=models.CharField(default='starter', max_length=32),
        ),
        migrations.AddField(
            model_name='clientaccount',
            name='project_quota',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
