# Generated by Django 4.2.26 on 2025-11-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_clientaccount_invite_quota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaccount',
            name='plan_slug',
            field=models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('growth', 'Growth'), ('enterprise', 'Enterprise')], default='starter', max_length=32),
        ),
    ]
