# Generated by Django 4.2.26 on 2025-11-22 07:39

from django.db import migrations, models


def migrate_growth_to_enterprise(apps, schema_editor):
    ClientAccount = apps.get_model("clients", "ClientAccount")
    ClientAccount.objects.filter(plan_slug="growth").update(
        plan_slug="enterprise", project_quota=0, invite_quota=0
    )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_sync_plan_defaults'),
    ]

    operations = [
        migrations.RunPython(migrate_growth_to_enterprise, noop),
        migrations.AlterField(
            model_name='clientaccount',
            name='plan_slug',
            field=models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='starter', max_length=32),
        ),
    ]
