# Generated by Django 4.2.26 on 2025-11-23 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_alter_clientaccount_plan_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaccount',
            name='logo_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientaccount',
            name='logo_mime',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
    ]
