# Generated by Django 4.2.26 on 2025-11-24 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_migrate_logo_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaccount',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientaccount',
            name='verification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientaccount',
            name='verification_token',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
