# Generated by Django 4.2.26 on 2026-01-05 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_clientaccount_email_verified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaccount',
            name='has_completed_onboarding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientaccount',
            name='onboarding_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientaccount',
            name='onboarding_step_data',
            field=models.JSONField(blank=True, default=dict, help_text='Tracks which steps user has completed: {step_1: true, step_2: false, ...}'),
        ),
    ]
