# Generated by Django 4.2.26 on 2026-01-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_clientaccount_has_completed_onboarding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaccount',
            name='auth_provider',
            field=models.CharField(choices=[('email', 'Email'), ('google', 'Google'), ('linkedin', 'LinkedIn')], default='email', max_length=20),
        ),
    ]
