# Generated by Django 4.2.26 on 2026-01-23 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0017_add_support_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaccount',
            name='receive_completion_alerts',
            field=models.BooleanField(default=True, help_text='Get notified when a candidate completes an assessment'),
        ),
        migrations.AddField(
            model_name='clientaccount',
            name='receive_new_candidate_alerts',
            field=models.BooleanField(default=False, help_text='Get notified when a new candidate starts an assessment'),
        ),
    ]
