# Generated by Django 4.2.26 on 2026-01-26 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0018_add_notification_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaccount',
            name='brand_background_color',
            field=models.CharField(default='#ffffff', help_text='Background color (hex code)', max_length=7),
        ),
        migrations.AddField(
            model_name='clientaccount',
            name='brand_primary_color',
            field=models.CharField(default='#ff8a00', help_text='Primary brand color (hex code, e.g., #ff8a00)', max_length=7),
        ),
        migrations.AddField(
            model_name='clientaccount',
            name='brand_secondary_color',
            field=models.CharField(default='#0e1428', help_text='Secondary/text color (hex code)', max_length=7),
        ),
        migrations.AddField(
            model_name='clientaccount',
            name='custom_email_sender_name',
            field=models.CharField(blank=True, help_text="Custom sender name for assessment emails (e.g., 'Acme Hiring Team')", max_length=100),
        ),
        migrations.AddField(
            model_name='clientaccount',
            name='custom_footer_text',
            field=models.CharField(blank=True, help_text="Custom footer text (replaces 'Powered by Evalon')", max_length=200),
        ),
        migrations.AddField(
            model_name='clientaccount',
            name='custom_welcome_message',
            field=models.TextField(blank=True, help_text='Custom welcome message shown to candidates on assessment intro page'),
        ),
        migrations.AddField(
            model_name='clientaccount',
            name='hide_evalon_branding',
            field=models.BooleanField(default=False, help_text="Hide 'Powered by Evalon' badge (Pro/Enterprise only)"),
        ),
    ]
