# Generated by Django 4.2.26 on 2026-01-26 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0019_add_branding_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaccount',
            name='api_key',
            field=models.CharField(blank=True, help_text='API key for programmatic access', max_length=64),
        ),
        migrations.AddField(
            model_name='clientaccount',
            name='api_key_created_at',
            field=models.DateTimeField(blank=True, help_text='When the API key was generated', null=True),
        ),
        migrations.AddField(
            model_name='clientaccount',
            name='webhook_enabled',
            field=models.BooleanField(default=False, help_text='Enable webhook notifications'),
        ),
        migrations.AddField(
            model_name='clientaccount',
            name='webhook_events',
            field=models.JSONField(blank=True, default=list, help_text="List of event types to trigger webhooks: ['session.created', 'session.started', 'session.completed']"),
        ),
        migrations.AddField(
            model_name='clientaccount',
            name='webhook_secret',
            field=models.CharField(blank=True, help_text='Secret key for signing webhook payloads', max_length=64),
        ),
        migrations.AddField(
            model_name='clientaccount',
            name='webhook_url',
            field=models.URLField(blank=True, help_text='URL to receive webhook notifications'),
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('session.created', 'Session Created'), ('session.started', 'Session Started'), ('session.completed', 'Session Completed'), ('session.expired', 'Session Expired')], max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='pending', max_length=20)),
                ('response_status_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_deliveries', to='clients.clientaccount')),
            ],
            options={
                'verbose_name': 'Webhook Delivery',
                'verbose_name_plural': 'Webhook Deliveries',
                'ordering': ('-created_at',),
            },
        ),
    ]
