# Generated by Django 4.2.26 on 2026-01-31 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0020_add_webhook_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsessionnote',
            name='assessment_type',
            field=models.CharField(choices=[('marketing', 'Marketing Assessment'), ('product', 'Product Management Assessment'), ('behavioral', 'Behavioral Assessment'), ('ux_design', 'UX/UI Design Assessment')], max_length=32),
        ),
    ]
