# Generated by Django 4.2.26 on 2026-02-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0021_alter_clientsessionnote_assessment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsessionnote',
            name='assessment_type',
            field=models.CharField(choices=[('marketing', 'Marketing Assessment'), ('product', 'Product Management Assessment'), ('behavioral', 'Behavioral Assessment'), ('ux_design', 'UX/UI Design Assessment'), ('hr', 'HR Assessment')], max_length=32),
        ),
    ]
