# Generated by Django 4.2.26 on 2026-02-02 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0022_alter_clientsessionnote_assessment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsessionnote',
            name='assessment_type',
            field=models.CharField(choices=[('marketing', 'Marketing Assessment'), ('product', 'Product Management Assessment'), ('behavioral', 'Behavioral Assessment'), ('ux_design', 'UX/UI Design Assessment'), ('hr', 'HR Assessment'), ('finance', 'Finance Manager Assessment')], max_length=32),
        ),
    ]
