# Generated by Django 4.2.26 on 2026-02-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0023_alter_clientsessionnote_assessment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientnotification',
            name='category',
            field=models.CharField(choices=[('assessment_completed', 'Assessment Completed'), ('candidate_started', 'Candidate Started'), ('pipeline_update', 'Pipeline Update'), ('scoring_complete', 'Scoring Complete'), ('decision_recorded', 'Decision Recorded'), ('system', 'System')], default='system', max_length=30),
        ),
        migrations.AlterField(
            model_name='clientnotification',
            name='link_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
