# Generated by Django 4.2.26 on 2026-02-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0024_add_notification_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientproject',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('internship', 'Internship'), ('freelance', 'Freelance')], max_length=20),
        ),
        migrations.AddField(
            model_name='clientproject',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clientproject',
            name='required_skills',
            field=models.TextField(blank=True, help_text='Comma-separated skills'),
        ),
        migrations.AddField(
            model_name='clientproject',
            name='salary_currency',
            field=models.CharField(blank=True, default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='clientproject',
            name='salary_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientproject',
            name='salary_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientproject',
            name='work_model',
            field=models.CharField(blank=True, choices=[('onsite', 'On-site'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], max_length=20),
        ),
    ]
