# Generated by Django 4.2.26 on 2026-02-16 20:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0025_clientproject_employment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaccount',
            name='slug',
            field=models.SlugField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='clientproject',
            name='assessment_type',
            field=models.CharField(blank=True, choices=[('marketing', 'Marketing Assessment'), ('product', 'Product Management Assessment'), ('behavioral', 'Behavioral Assessment'), ('ux_design', 'UX/UI Design Assessment'), ('hr', 'HR Assessment'), ('finance', 'Finance Manager Assessment')], help_text='Assessment candidates take when applying via public careers page', max_length=32),
        ),
        migrations.CreateModel(
            name='PositionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('resume_data', models.BinaryField(blank=True, null=True)),
                ('resume_mime', models.CharField(blank=True, max_length=100)),
                ('resume_filename', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('session_created', 'Session Created'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('assessment_session_uuid', models.UUIDField(blank=True, null=True)),
                ('assessment_type', models.CharField(blank=True, max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='clients.clientaccount')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='clients.clientproject')),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('project', 'email')},
            },
        ),
    ]
