# Generated by Django 4.2.26 on 2026-02-16 20:55

from django.db import migrations, models
from django.utils.text import slugify


def backfill_slugs(apps, schema_editor):
    ClientAccount = apps.get_model("clients", "ClientAccount")
    for account in ClientAccount.objects.filter(slug=""):
        base = slugify(account.company_name)[:200] or "company"
        slug = base
        n = 1
        while ClientAccount.objects.filter(slug=slug).exclude(pk=account.pk).exists():
            slug = f"{base}-{n}"
            n += 1
        account.slug = slug
        account.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0026_add_slug_assessment_type_position_application'),
    ]

    operations = [
        migrations.RunPython(backfill_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='clientaccount',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
    ]
