# Generated by Django 4.2.26 on 2026-02-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0027_backfill_client_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionapplication',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='positionapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('assessment_sent', 'Assessment Sent'), ('session_created', 'Session Created'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
