# Generated by Django 4.2.26 on 2026-02-17 02:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0028_positionapplication_phone_number_status_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiringProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=16)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='clients.clientaccount')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='clientproject',
            name='campaign',
            field=models.ForeignKey(blank=True, help_text='Hiring project this position belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='clients.hiringproject'),
        ),
    ]
