# Generated by Django 4.2.26 on 2026-02-17 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0029_hiringproject_clientproject_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientproject',
            name='nice_to_haves',
            field=models.TextField(blank=True, help_text='Preferred qualifications, one per line'),
        ),
        migrations.AddField(
            model_name='clientproject',
            name='requirements',
            field=models.TextField(blank=True, help_text='Required qualifications, one per line'),
        ),
        migrations.AddField(
            model_name='clientproject',
            name='responsibilities',
            field=models.TextField(blank=True, help_text='Key responsibilities, one per line'),
        ),
    ]
