# Generated by Django 4.2.26 on 2026-02-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0030_clientproject_nice_to_haves_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientproject',
            name='deadline',
            field=models.DateField(blank=True, help_text='Position auto-archives and hides from vacancy page after this date', null=True),
        ),
    ]
