# Generated by Django 4.2.26 on 2026-02-17 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hiring_agent', '0002_fix_candidate_on_delete'),
        ('clients', '0031_add_deadline_to_clientproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionapplication',
            name='pipeline_candidate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to='hiring_agent.pipelinecandidate'),
        ),
    ]
