# Generated by Django 4.2.26 on 2026-03-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0032_add_pipeline_candidate_to_positionapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientproject',
            name='magic_token',
            field=models.CharField(blank=True, db_index=True, help_text='Shareable invite link token', max_length=32, unique=True),
        ),
    ]
