# Generated by Django 4.2.26 on 2026-03-25 20:18

import secrets
from django.db import migrations, models


def populate_magic_tokens(apps, schema_editor):
    ClientProject = apps.get_model("clients", "ClientProject")
    for project in ClientProject.objects.filter(magic_token=""):
        project.magic_token = secrets.token_urlsafe(16)
        project.save(update_fields=["magic_token"])


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0032_add_pipeline_candidate_to_positionapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientproject',
            name='magic_token',
            field=models.CharField(blank=True, db_index=True, help_text='Shareable invite link token', max_length=32, default=''),
        ),
        migrations.RunPython(populate_magic_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='clientproject',
            name='magic_token',
            field=models.CharField(blank=True, db_index=True, help_text='Shareable invite link token', max_length=32, unique=True),
        ),
    ]
