# Generated by Django 4.2.26 on 2025-11-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(unique=True)),
                ('hero_image', models.URLField(blank=True)),
                ('pill_label', models.CharField(default='Insights', max_length=60)),
                ('pill_style', models.CharField(choices=[('accent', 'Accent'), ('success', 'Success'), ('neutral', 'Neutral')], default='accent', max_length=20)),
                ('excerpt', models.TextField(help_text='Short teaser shown on the homepage and list view.')),
                ('body', models.TextField(help_text='Supports Markdown or HTML snippets.')),
                ('author_name', models.CharField(max_length=120)),
                ('author_title', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma separated keywords.', max_length=255)),
                ('meta_image', models.URLField(blank=True, help_text='Social preview image (absolute URL).')),
                ('is_featured', models.BooleanField(default=False, help_text='Surface in the homepage hero slot.')),
            ],
            options={
                'ordering': ('-published_at', '-created_at'),
            },
        ),
    ]
