DESIGN_ROLES = [
    {
        'slug': 'head-of-design',
        'title': 'Head of Design',
        'department': 'Design',
        'seniority_level': 'executive',
        'description': 'Leads the entire design organization, setting the creative vision and design strategy across all products. Builds and mentors a high-performing design team while ensuring design excellence drives measurable business outcomes. Partners with C-suite executives to embed design thinking into company strategy.',
        'responsibilities': [
            'Define and communicate the overarching design vision and strategy for the organization',
            'Build, mentor, and retain a world-class design team across UX, UI, and research disciplines',
            'Partner with CPO, CTO, and CEO to align design initiatives with business objectives',
            'Establish design systems, standards, and processes that scale across multiple product lines',
            'Champion user-centered design practices and advocate for the customer at the executive level',
            'Manage the design department budget, tooling, and resource allocation',
        ],
        'key_skills': [
            'Design leadership and organizational strategy',
            'Executive communication and stakeholder management',
            'Design systems thinking and scalable processes',
            'Team building, mentoring, and talent development',
            'Business acumen and ROI-driven design decision-making',
            'Cross-functional collaboration at the C-suite level',
        ],
        'assessment_slugs': ['ux-design', 'behavioral'],
        'questions': [
            {
                'question_text': 'How would you develop and communicate a unified design vision for a company with multiple product lines serving different user segments?',
                'category': 'leadership',
                'difficulty': 'hard',
                'what_it_tests': 'Ability to create cohesive design strategy across diverse products',
                'sample_answer_outline': 'Should discuss auditing existing products for design consistency, identifying shared principles that transcend individual products, and creating a vision document with stakeholder buy-in. Should mention balancing brand cohesion with segment-specific needs and establishing governance for ongoing alignment.',
            },
            {
                'question_text': 'Describe a time when you had to make a significant organizational change within your design team. What drove the decision, and how did you manage the transition?',
                'category': 'behavioral',
                'difficulty': 'hard',
                'what_it_tests': 'Change management and organizational design capabilities',
                'sample_answer_outline': 'Should provide a concrete example of restructuring, such as moving from embedded to centralized design or vice versa. Should explain the business rationale, how they communicated the change, managed resistance, and measured whether the new structure improved outcomes.',
            },
            {
                'question_text': 'How do you measure the ROI of design investment and communicate design value to a board of directors or executive team that is not design-literate?',
                'category': 'technical',
                'difficulty': 'hard',
                'what_it_tests': 'Business acumen and ability to quantify design impact',
                'sample_answer_outline': 'Should reference specific metrics such as conversion improvements, task completion rates, NPS changes, reduced support costs, and development efficiency gains from design systems. Should discuss framing design outcomes in business language and tying design KPIs to revenue and retention metrics.',
            },
            {
                'question_text': 'Your CEO wants to launch a major product redesign in three months, but your team estimates six months for proper user research and iterative design. How do you handle this?',
                'category': 'situational',
                'difficulty': 'hard',
                'what_it_tests': 'Negotiation skills and ability to balance business urgency with design quality',
                'sample_answer_outline': 'Should discuss understanding the business driver behind the timeline, proposing a phased approach that delivers high-impact changes early, identifying what research can be parallelized, and clearly communicating the risks of cutting corners. Should demonstrate pragmatism without abandoning design principles.',
            },
            {
                'question_text': 'How do you build a culture of design excellence while scaling a team from 10 to 50 designers?',
                'category': 'culture',
                'difficulty': 'hard',
                'what_it_tests': 'Ability to scale team culture and maintain quality during rapid growth',
                'sample_answer_outline': 'Should cover establishing design principles and rituals early, creating structured onboarding, implementing design critique practices, hiring for culture add rather than just skill, and establishing career ladders. Should mention the importance of maintaining psychological safety and creative freedom at scale.',
            },
            {
                'question_text': 'Walk me through how you would evaluate whether your organization should invest in building a comprehensive design system versus continuing with ad-hoc component creation.',
                'category': 'problem_solving',
                'difficulty': 'medium',
                'what_it_tests': 'Strategic thinking about design infrastructure investments',
                'sample_answer_outline': 'Should discuss calculating current costs of inconsistency including developer rework, design debt, and brand fragmentation. Should mention evaluating team size thresholds, number of products, and release velocity. Should propose a business case framework comparing investment cost versus long-term efficiency gains.',
            },
            {
                'question_text': 'How do you ensure accessibility and inclusive design are embedded in your team\'s process rather than treated as an afterthought?',
                'category': 'technical',
                'difficulty': 'medium',
                'what_it_tests': 'Commitment to and practical knowledge of inclusive design at an organizational level',
                'sample_answer_outline': 'Should discuss making accessibility part of the definition of done, integrating WCAG standards into the design system, conducting audits, hiring for diverse perspectives, including users with disabilities in research, and providing ongoing training. Should mention executive accountability and metrics tracking.',
            },
            {
                'question_text': 'Tell me about a time when user research findings contradicted a strongly held executive opinion. How did you navigate this situation?',
                'category': 'behavioral',
                'difficulty': 'medium',
                'what_it_tests': 'Courage to advocate for users while maintaining executive relationships',
                'sample_answer_outline': 'Should describe presenting data respectfully, framing findings in terms of business risk, proposing experiments to validate, and showing willingness to be proven wrong. Should demonstrate diplomatic assertiveness and a commitment to evidence-based decision-making.',
            },
            {
                'question_text': 'A product team ships a feature without going through the design review process your team established. How do you respond?',
                'category': 'situational',
                'difficulty': 'medium',
                'what_it_tests': 'Process enforcement balanced with cross-functional relationship management',
                'sample_answer_outline': 'Should discuss addressing the specific incident without being punitive, understanding why the process was bypassed, strengthening the process to prevent recurrence, and building relationships that make teams want to include design. Should avoid both overreacting and ignoring the issue.',
            },
            {
                'question_text': 'What is your approach to managing creative tension between brand consistency and product innovation?',
                'category': 'leadership',
                'difficulty': 'medium',
                'what_it_tests': 'Ability to balance constraints with creative freedom',
                'sample_answer_outline': 'Should discuss establishing clear brand guardrails that define what is fixed versus flexible, creating safe spaces for experimentation, using A/B testing to validate innovations, and evolving brand guidelines based on what works. Should recognize this as a healthy tension rather than a problem to eliminate.',
            },
            {
                'question_text': 'How do you stay current with design trends and emerging technologies, and how do you decide which ones are worth investing in for your team?',
                'category': 'culture',
                'difficulty': 'easy',
                'what_it_tests': 'Continuous learning mindset and strategic evaluation of trends',
                'sample_answer_outline': 'Should mention specific sources of inspiration, conferences, and communities. Should discuss evaluating trends against user needs and business goals rather than adopting for novelty. Should describe creating learning budgets, exploration sprints, or innovation time for the team.',
            },
            {
                'question_text': 'How would you structure the career growth framework for designers on your team to reduce attrition and increase engagement?',
                'category': 'problem_solving',
                'difficulty': 'easy',
                'what_it_tests': 'People management and talent development strategy',
                'sample_answer_outline': 'Should discuss creating dual IC and management tracks, defining clear level expectations with rubrics, establishing regular growth conversations beyond performance reviews, providing stretch assignments, and connecting individual growth to business impact. Should mention benchmarking compensation and title parity with engineering.',
            },
        ],
    },
    {
        'slug': 'ux-lead',
        'title': 'UX Lead',
        'department': 'Design',
        'seniority_level': 'lead',
        'description': 'Leads a team of UX designers and researchers, owning the end-to-end user experience for a major product area. Balances hands-on design work with people management, driving design quality while mentoring team members. Collaborates closely with product management and engineering leadership to deliver cohesive, user-centered product experiences.',
        'responsibilities': [
            'Lead and mentor a team of UX designers and researchers on complex product initiatives',
            'Own the UX strategy and vision for a major product area or business unit',
            'Conduct design reviews and establish quality standards for team deliverables',
            'Collaborate with product managers and engineering leads to define roadmaps and priorities',
            'Drive adoption and contribution to the design system within the team',
            'Facilitate user research planning and ensure insights inform design decisions',
        ],
        'key_skills': [
            'UX design leadership and team mentorship',
            'Advanced interaction design and information architecture',
            'User research methodology and insight synthesis',
            'Design system stewardship and governance',
            'Stakeholder management and cross-functional collaboration',
            'Design critique facilitation and quality assurance',
        ],
        'assessment_slugs': ['ux-design', 'behavioral'],
        'questions': [
            {
                'question_text': 'How do you balance your time between hands-on design work and leading or mentoring your team?',
                'category': 'leadership',
                'difficulty': 'medium',
                'what_it_tests': 'Self-awareness about the IC-to-manager transition and time management',
                'sample_answer_outline': 'Should discuss prioritizing team unblocking and mentorship, reserving hands-on time for high-impact or ambiguous projects, and being intentional about when to step in versus delegate. Should acknowledge this balance shifts based on team maturity and project phase.',
            },
            {
                'question_text': 'Describe a complex user flow you redesigned that involved multiple entry points, edge cases, and error states. Walk me through your process.',
                'category': 'technical',
                'difficulty': 'hard',
                'what_it_tests': 'Depth of interaction design skill and systematic thinking about complex flows',
                'sample_answer_outline': 'Should walk through mapping the existing flow, identifying pain points through data and research, designing for the happy path and progressively adding edge case handling, and validating with usability testing. Should demonstrate comfort with complexity and attention to error handling and recovery.',
            },
            {
                'question_text': 'Tell me about a time when a designer on your team was underperforming. How did you address it?',
                'category': 'behavioral',
                'difficulty': 'hard',
                'what_it_tests': 'Difficult people management skills and coaching ability',
                'sample_answer_outline': 'Should describe identifying the root cause such as skill gap versus motivation versus personal issues, having honest and empathetic conversations, setting clear expectations with a support plan, and following through. Should mention documenting the process and knowing when escalation is necessary.',
            },
            {
                'question_text': 'Your product manager wants to skip user testing to meet a deadline, arguing the design is based on existing research. What do you do?',
                'category': 'situational',
                'difficulty': 'medium',
                'what_it_tests': 'Ability to advocate for UX process while being pragmatic about constraints',
                'sample_answer_outline': 'Should discuss assessing the actual risk based on how novel the design is, proposing lightweight alternatives like guerrilla testing or internal dogfooding, clearly communicating what risks are being accepted, and documenting the decision. Should show flexibility without being a pushover.',
            },
            {
                'question_text': 'How do you run effective design critiques that improve work quality without demoralizing the team?',
                'category': 'culture',
                'difficulty': 'medium',
                'what_it_tests': 'Ability to foster a constructive feedback culture within a design team',
                'sample_answer_outline': 'Should discuss establishing ground rules separating the work from the person, framing feedback around user goals and business objectives, modeling vulnerability by presenting their own work first, and training the team to give specific and actionable feedback rather than subjective opinions.',
            },
            {
                'question_text': 'You inherit a product with significant UX debt accumulated over years. How do you prioritize what to fix and build a case for investing in UX improvements?',
                'category': 'problem_solving',
                'difficulty': 'hard',
                'what_it_tests': 'Strategic prioritization and ability to build business cases for design work',
                'sample_answer_outline': 'Should discuss auditing the experience using heuristics and analytics, categorizing issues by severity and frequency, mapping UX debt to business metrics like churn or support costs, and proposing a phased remediation plan. Should mention negotiating for dedicated UX debt capacity in each sprint.',
            },
            {
                'question_text': 'Explain your approach to creating and maintaining information architecture for a product with hundreds of features.',
                'category': 'technical',
                'difficulty': 'hard',
                'what_it_tests': 'Information architecture expertise at scale',
                'sample_answer_outline': 'Should discuss card sorting and tree testing with users, using taxonomies and mental models, progressive disclosure principles, establishing navigation patterns that scale, and regular audits as new features are added. Should mention governance to prevent navigation bloat.',
            },
            {
                'question_text': 'Tell me about a time when you had to align multiple designers with different stylistic preferences around a single design direction.',
                'category': 'behavioral',
                'difficulty': 'medium',
                'what_it_tests': 'Conflict resolution and ability to create team alignment',
                'sample_answer_outline': 'Should describe facilitating a structured decision-making process anchored in user data and design principles rather than personal preference. Should mention giving everyone a voice while being decisive, and connecting the final direction back to shared team values.',
            },
            {
                'question_text': 'Two feature teams need your best designer at the same time for high-priority projects. How do you allocate resources?',
                'category': 'situational',
                'difficulty': 'medium',
                'what_it_tests': 'Resource management and prioritization under constraints',
                'sample_answer_outline': 'Should discuss evaluating project impact and timeline urgency, exploring whether one project can be phased, considering whether a more junior designer could stretch with mentoring support, and communicating transparently with both product managers about tradeoffs. Should avoid simply splitting the designer between both projects.',
            },
            {
                'question_text': 'How do you ensure that user research insights are actually used by the team and not just filed away in a report?',
                'category': 'problem_solving',
                'difficulty': 'medium',
                'what_it_tests': 'Ability to operationalize research and drive insight-informed design',
                'sample_answer_outline': 'Should discuss involving designers and PMs in research sessions, creating digestible and actionable insight formats, linking insights to specific design decisions, maintaining a living research repository, and tracking which insights led to changes. Should mention making research a team activity rather than a handoff.',
            },
            {
                'question_text': 'What methods do you use to evaluate design quality before shipping, beyond usability testing?',
                'category': 'technical',
                'difficulty': 'easy',
                'what_it_tests': 'Breadth of quality assurance approaches for design work',
                'sample_answer_outline': 'Should mention heuristic evaluations, accessibility audits, design system compliance checks, content review, performance impact assessment, cross-device and cross-browser testing, and stakeholder walkthroughs. Should discuss building these into a repeatable checklist.',
            },
            {
                'question_text': 'How do you onboard a new designer to your team and get them productive quickly while maintaining quality standards?',
                'category': 'culture',
                'difficulty': 'easy',
                'what_it_tests': 'Thoughtfulness about team onboarding and knowledge transfer',
                'sample_answer_outline': 'Should discuss structured onboarding with a buddy system, providing context on users and product strategy, starting with smaller well-scoped tasks, providing frequent feedback early on, and gradually increasing scope. Should mention documentation of team norms, design system resources, and decision history.',
            },
        ],
    },
    {
        'slug': 'senior-ux-designer',
        'title': 'Senior UX Designer',
        'department': 'Design',
        'seniority_level': 'senior',
        'description': 'Designs end-to-end user experiences for complex product features, working independently from research through high-fidelity prototyping. Serves as a UX subject matter expert within cross-functional teams, influencing product direction through strong design rationale and user advocacy. Mentors junior designers and contributes to the evolution of design systems and team practices.',
        'responsibilities': [
            'Design end-to-end user experiences for complex features from concept through delivery',
            'Conduct and synthesize user research to inform design decisions',
            'Create wireframes, prototypes, and high-fidelity designs for usability testing and development',
            'Collaborate daily with product managers, engineers, and researchers within an agile team',
            'Mentor junior and mid-level designers through pairing and design critiques',
            'Contribute to and evolve the design system with reusable patterns and components',
        ],
        'key_skills': [
            'End-to-end UX design for complex workflows',
            'Prototyping and interaction design using industry-standard tools',
            'User research planning, execution, and synthesis',
            'Design system contribution and component design',
            'Strong written and verbal communication of design rationale',
            'Agile collaboration and iterative design practices',
        ],
        'assessment_slugs': ['ux-design', 'behavioral'],
        'questions': [
            {
                'question_text': 'Walk me through a recent project where you designed a complex multi-step workflow. How did you handle progressive disclosure and error prevention?',
                'category': 'technical',
                'difficulty': 'hard',
                'what_it_tests': 'Ability to design complex interactions with attention to usability principles',
                'sample_answer_outline': 'Should walk through the specific workflow, explain decisions about step breakdown, inline validation, smart defaults, and undo capabilities. Should demonstrate understanding of cognitive load management and how they tested the flow with users to validate assumptions.',
            },
            {
                'question_text': 'Describe a situation where you disagreed with a product manager on the scope or direction of a feature. How did you resolve it?',
                'category': 'behavioral',
                'difficulty': 'medium',
                'what_it_tests': 'Cross-functional collaboration and constructive disagreement skills',
                'sample_answer_outline': 'Should describe the specific disagreement, how they grounded their position in user data or design principles, how they listened to the PM perspective, and how they found a resolution. Should demonstrate both conviction and flexibility.',
            },
            {
                'question_text': 'A stakeholder requests a feature that you believe will harm the user experience based on your research. However, the feature has strong business justification. How do you approach this?',
                'category': 'situational',
                'difficulty': 'hard',
                'what_it_tests': 'Ability to navigate tension between user advocacy and business requirements',
                'sample_answer_outline': 'Should discuss presenting the user research findings clearly, proposing alternative designs that meet the business goal with less user harm, suggesting an experiment or phased rollout to measure actual impact, and being willing to commit to the decision once it is made even if they disagree.',
            },
            {
                'question_text': 'How do you decide what fidelity level to use for different stages of the design process?',
                'category': 'technical',
                'difficulty': 'medium',
                'what_it_tests': 'Understanding of design process efficiency and appropriate tool selection',
                'sample_answer_outline': 'Should discuss using low-fidelity sketches and wireframes for early concept exploration and stakeholder alignment, mid-fidelity for usability testing and developer communication, and high-fidelity for final handoff and edge case documentation. Should mention that higher fidelity too early can anchor feedback on visual details rather than structural issues.',
            },
            {
                'question_text': 'Tell me about a time when usability testing revealed that your design was fundamentally flawed. What did you do?',
                'category': 'behavioral',
                'difficulty': 'hard',
                'what_it_tests': 'Humility, resilience, and ability to iterate based on user feedback',
                'sample_answer_outline': 'Should describe the specific design, what testing revealed, their emotional response and how they managed it, and how they iterated. Should demonstrate openness to being wrong and treating testing as learning rather than validation. Should show how the final design improved as a result.',
            },
            {
                'question_text': 'You are designing a feature that needs to work for both power users and first-time users. How do you approach this tension?',
                'category': 'problem_solving',
                'difficulty': 'hard',
                'what_it_tests': 'Ability to design for multiple user segments within a single interface',
                'sample_answer_outline': 'Should discuss progressive disclosure, sensible defaults with advanced options, contextual help and onboarding, keyboard shortcuts for power users, and customizable interfaces. Should mention creating user personas for each segment and testing with both groups rather than designing for the average.',
            },
            {
                'question_text': 'How do you approach designing for accessibility, and can you give a specific example of an accessibility challenge you solved?',
                'category': 'technical',
                'difficulty': 'medium',
                'what_it_tests': 'Practical accessibility knowledge and commitment to inclusive design',
                'sample_answer_outline': 'Should demonstrate knowledge of WCAG guidelines, screen reader compatibility, keyboard navigation, color contrast, and focus management. Should provide a concrete example such as making a custom component accessible or redesigning a flow that relied on color alone to convey information.',
            },
            {
                'question_text': 'How do you effectively hand off designs to developers to minimize misinterpretation and back-and-forth?',
                'category': 'problem_solving',
                'difficulty': 'easy',
                'what_it_tests': 'Design-development collaboration practices and communication clarity',
                'sample_answer_outline': 'Should discuss detailed specifications with annotations, interactive prototypes, documenting interaction states and edge cases, referencing design system tokens, holding kickoff walkthroughs, and being available for questions during implementation. Should mention that handoff is a conversation, not a document toss.',
            },
            {
                'question_text': 'A junior designer on your team is struggling with a project and the deadline is approaching. How do you help without just doing the work for them?',
                'category': 'leadership',
                'difficulty': 'medium',
                'what_it_tests': 'Mentoring approach and ability to develop others while managing deadlines',
                'sample_answer_outline': 'Should discuss diagnosing what they are struggling with, coaching through questions rather than directives, pairing on the hardest parts, breaking the work into manageable pieces, and escalating timeline concerns early if needed. Should balance growth opportunity with delivery responsibility.',
            },
            {
                'question_text': 'How do you use data and analytics alongside qualitative research to inform your design decisions?',
                'category': 'technical',
                'difficulty': 'medium',
                'what_it_tests': 'Ability to combine quantitative and qualitative insights for design decisions',
                'sample_answer_outline': 'Should discuss using analytics to identify what is happening and research to understand why, triangulating findings from multiple sources, using funnel data to prioritize redesign efforts, and setting measurable goals for design changes. Should mention specific tools and metrics they track.',
            },
            {
                'question_text': 'Describe how you contribute to and use a design system in your daily work.',
                'category': 'culture',
                'difficulty': 'easy',
                'what_it_tests': 'Design system fluency and collaborative contribution mindset',
                'sample_answer_outline': 'Should discuss using existing components as a starting point, proposing new components when patterns repeat, documenting usage guidelines, and coordinating with other designers to maintain consistency. Should mention balancing system constraints with product-specific needs and the process for proposing exceptions.',
            },
            {
                'question_text': 'Your team is adopting a new design tool that you are unfamiliar with. How do you get up to speed quickly while still delivering on your current projects?',
                'category': 'situational',
                'difficulty': 'easy',
                'what_it_tests': 'Adaptability and self-directed learning under real-world constraints',
                'sample_answer_outline': 'Should discuss focused learning through tutorials and practice projects, learning by migrating existing work, leaning on teammates who are already proficient, and setting realistic expectations about a temporary productivity dip. Should show a proactive rather than resistant attitude toward tool changes.',
            },
        ],
    },
    {
        'slug': 'ux-researcher',
        'title': 'UX Researcher',
        'department': 'Design',
        'seniority_level': 'mid',
        'description': 'Plans and conducts user research studies that uncover actionable insights to improve product experiences. Employs a range of qualitative and quantitative research methods, translating findings into clear recommendations for design and product teams. Partners with designers, product managers, and engineers to ensure the user voice is present throughout the product development lifecycle.',
        'responsibilities': [
            'Plan, recruit for, and conduct usability tests, interviews, and surveys',
            'Synthesize research data into actionable insights and clear recommendations',
            'Present findings to cross-functional stakeholders through compelling research reports',
            'Maintain and evolve participant recruitment panels and research repositories',
            'Collaborate with designers and PMs to identify research questions and prioritize studies',
            'Advocate for user-centered practices and build research literacy across the organization',
        ],
        'key_skills': [
            'Qualitative research methods including interviews, usability testing, and diary studies',
            'Quantitative research methods including surveys, A/B testing analysis, and analytics',
            'Research synthesis, affinity mapping, and thematic analysis',
            'Participant recruitment and research operations',
            'Compelling storytelling and research presentation',
            'Research ethics and inclusive research practices',
        ],
        'assessment_slugs': ['ux-design', 'behavioral'],
        'questions': [
            {
                'question_text': 'How do you determine which research methodology to use for a given research question? Walk me through your decision-making process with a recent example.',
                'category': 'technical',
                'difficulty': 'hard',
                'what_it_tests': 'Methodological breadth and ability to match methods to research objectives',
                'sample_answer_outline': 'Should discuss evaluating whether the question is generative or evaluative, whether attitudes or behaviors are being studied, timeline and budget constraints, and desired confidence level. Should provide a specific example showing they considered multiple methods before selecting one and explain why alternatives were less suitable.',
            },
            {
                'question_text': 'Describe a time when your research findings challenged the team\'s assumptions and led to a significant change in product direction.',
                'category': 'behavioral',
                'difficulty': 'hard',
                'what_it_tests': 'Research impact and ability to influence product decisions with data',
                'sample_answer_outline': 'Should describe the initial assumption, the research approach, the surprising findings, how they presented the data persuasively, and the resulting product change. Should demonstrate that they measured the impact of the change to validate the research recommendation.',
            },
            {
                'question_text': 'A product manager asks you to validate a design that is already in development and launching next week. How do you handle this request?',
                'category': 'situational',
                'difficulty': 'medium',
                'what_it_tests': 'Pragmatism about research timing and ability to add value under constraints',
                'sample_answer_outline': 'Should discuss being honest that validation testing this late has limited ability to drive changes, proposing a rapid unmoderated test that could catch critical usability issues, framing the study as a baseline for post-launch iteration, and having a broader conversation about embedding research earlier in the process going forward.',
            },
            {
                'question_text': 'How do you ensure your research participant samples are representative and avoid bias in recruitment?',
                'category': 'technical',
                'difficulty': 'medium',
                'what_it_tests': 'Research rigor and awareness of sampling bias',
                'sample_answer_outline': 'Should discuss defining screener criteria based on user segments, diversifying recruitment channels beyond convenience samples, screening for professional participants, balancing demographic representation, documenting limitations of each sample, and being transparent about who was not included in the study.',
            },
            {
                'question_text': 'Tell me about a research study that did not go as planned. What happened, and what did you learn from it?',
                'category': 'behavioral',
                'difficulty': 'medium',
                'what_it_tests': 'Resilience, self-reflection, and ability to learn from methodological challenges',
                'sample_answer_outline': 'Should describe a specific study failure such as poor recruitment, biased questions, or technology issues. Should explain how they salvaged what they could, what they learned about prevention, and how they improved their process. Should demonstrate honest self-assessment rather than blaming external factors.',
            },
            {
                'question_text': 'Your research reveals that two key user segments have directly conflicting needs. How do you present this finding and help the team decide what to do?',
                'category': 'problem_solving',
                'difficulty': 'hard',
                'what_it_tests': 'Ability to handle ambiguous research findings and support strategic decision-making',
                'sample_answer_outline': 'Should discuss clearly documenting both segments needs with supporting evidence, quantifying the size and value of each segment, presenting options with tradeoffs rather than a single recommendation, and helping the team use business strategy to break the tie. Should mention the possibility of designing differentiated experiences if feasible.',
            },
            {
                'question_text': 'How do you write effective usability test tasks that do not lead participants to the answer?',
                'category': 'technical',
                'difficulty': 'easy',
                'what_it_tests': 'Practical usability testing craft and awareness of leading bias',
                'sample_answer_outline': 'Should discuss using scenario-based tasks rooted in realistic goals, avoiding interface terminology in task descriptions, not revealing the expected path, using open-ended completion criteria, and pilot testing tasks before the real sessions. Should give examples of bad versus good task wording.',
            },
            {
                'question_text': 'How do you build a research repository that the team actually uses, rather than one that collects dust?',
                'category': 'problem_solving',
                'difficulty': 'medium',
                'what_it_tests': 'Research operations thinking and ability to create lasting organizational value',
                'sample_answer_outline': 'Should discuss choosing a tool that integrates with team workflows, tagging insights by theme and product area for discoverability, making it easy to contribute and search, socializing findings in team rituals, and measuring repository usage. Should mention keeping the repository curated rather than becoming a dumping ground.',
            },
            {
                'question_text': 'How do you handle a situation where a stakeholder cherry-picks your research data to support their pre-existing opinion?',
                'category': 'situational',
                'difficulty': 'medium',
                'what_it_tests': 'Research integrity and stakeholder management under pressure',
                'sample_answer_outline': 'Should discuss addressing it directly but diplomatically, providing the full context of the findings, explaining the difference between anecdotes and patterns, and offering to walk through the analysis together. Should mention prevention through clear executive summaries that are hard to misrepresent.',
            },
            {
                'question_text': 'What role should researchers play in the ideation and design process beyond just delivering findings?',
                'category': 'culture',
                'difficulty': 'easy',
                'what_it_tests': 'Understanding of research as a collaborative practice rather than a service function',
                'sample_answer_outline': 'Should discuss participating in design sprints, co-creating personas and journey maps with the team, facilitating stakeholder workshops, helping frame design principles from research themes, and being a thought partner throughout the design process rather than a testing service at the end.',
            },
            {
                'question_text': 'How do you measure the effectiveness of your own research practice over time?',
                'category': 'leadership',
                'difficulty': 'medium',
                'what_it_tests': 'Self-evaluation and continuous improvement mindset for research practice',
                'sample_answer_outline': 'Should discuss tracking metrics like percentage of recommendations implemented, time from insight to product change, stakeholder satisfaction surveys, research citation frequency, and contribution to key product metrics. Should mention retrospecting on study quality and seeking peer feedback on research design.',
            },
            {
                'question_text': 'Explain the difference between attitudinal and behavioral research and give an example of when you would choose each.',
                'category': 'technical',
                'difficulty': 'easy',
                'what_it_tests': 'Foundational research knowledge and ability to explain concepts clearly',
                'sample_answer_outline': 'Should clearly define attitudinal research as what people say they believe or will do versus behavioral research as what people actually do. Should give concrete examples such as surveys for attitudes and analytics or usability testing for behavior, and explain why both are necessary because people often cannot accurately predict their own behavior.',
            },
        ],
    },
    {
        'slug': 'ui-designer',
        'title': 'UI Designer',
        'department': 'Design',
        'seniority_level': 'mid',
        'description': 'Crafts visually polished, pixel-perfect user interfaces that bring wireframes and UX concepts to life. Works within and contributes to the design system, ensuring visual consistency and brand alignment across all product surfaces. Collaborates with UX designers, front-end engineers, and brand teams to deliver interfaces that are both beautiful and functionally sound.',
        'responsibilities': [
            'Design high-fidelity user interfaces for web and mobile applications',
            'Create and maintain reusable UI components within the design system',
            'Ensure visual consistency, brand alignment, and pixel-perfect implementation across products',
            'Collaborate with UX designers to translate wireframes into polished visual designs',
            'Partner with front-end engineers to ensure accurate and performant design implementation',
            'Develop and maintain visual design specifications including typography, color, spacing, and iconography',
        ],
        'key_skills': [
            'Visual design and interface aesthetics with strong attention to detail',
            'Design system component creation and documentation',
            'Typography, color theory, layout, and visual hierarchy',
            'Proficiency in Figma and modern design tooling',
            'Responsive and adaptive design across breakpoints',
            'Understanding of front-end implementation constraints and CSS capabilities',
        ],
        'assessment_slugs': ['ux-design', 'behavioral'],
        'questions': [
            {
                'question_text': 'Walk me through your process for establishing a visual design language for a new product, including typography, color, spacing, and component styles.',
                'category': 'technical',
                'difficulty': 'hard',
                'what_it_tests': 'Ability to create a cohesive and systematic visual foundation from scratch',
                'sample_answer_outline': 'Should discuss starting with brand guidelines and product goals, establishing a type scale with clear hierarchy, defining a color palette with semantic meaning and accessibility in mind, creating a spacing system based on a base unit, and building foundational components. Should mention documenting decisions and rationale for future designers.',
            },
            {
                'question_text': 'Describe a time when you had to redesign an existing interface with significant visual debt while maintaining user familiarity. How did you manage the transition?',
                'category': 'behavioral',
                'difficulty': 'hard',
                'what_it_tests': 'Ability to modernize interfaces without disrupting user mental models',
                'sample_answer_outline': 'Should describe the specific visual debt, how they audited the current state, the strategy for incremental versus big-bang redesign, how they preserved navigation patterns and key affordances, and how they tested the new design with existing users. Should mention managing stakeholder expectations about the pace of change.',
            },
            {
                'question_text': 'An engineer tells you that the animation you designed is causing performance issues on lower-end devices. How do you work through this?',
                'category': 'situational',
                'difficulty': 'medium',
                'what_it_tests': 'Collaboration with engineering and understanding of technical constraints',
                'sample_answer_outline': 'Should discuss understanding the specific performance bottleneck, exploring simpler alternatives that achieve a similar effect, considering progressive enhancement where animations are reduced for lower-end devices, and being willing to simplify while preserving the core purpose of the animation. Should demonstrate respect for engineering constraints.',
            },
            {
                'question_text': 'How do you ensure your designs maintain visual quality and consistency across different screen sizes, from mobile to large desktop monitors?',
                'category': 'technical',
                'difficulty': 'medium',
                'what_it_tests': 'Responsive design knowledge and systematic approach to multi-device design',
                'sample_answer_outline': 'Should discuss designing with a mobile-first or content-first approach, using flexible grid systems, defining clear breakpoints with layout shifts, adapting component sizes and spacing for touch versus pointer interaction, and testing on actual devices. Should mention the design system role in encoding responsive behavior.',
            },
            {
                'question_text': 'Tell me about a time when you received critical feedback on your visual design work. How did you respond?',
                'category': 'behavioral',
                'difficulty': 'easy',
                'what_it_tests': 'Receptiveness to feedback and professional maturity',
                'sample_answer_outline': 'Should describe the specific feedback, their initial reaction, how they evaluated the feedback objectively, and what changes they made. Should demonstrate the ability to separate personal attachment to the work from the goal of creating the best possible design. Should mention how the final result improved.',
            },
            {
                'question_text': 'You notice that the implemented version of your design has subtle but important differences from the Figma mockups. How do you handle this across multiple features?',
                'category': 'problem_solving',
                'difficulty': 'medium',
                'what_it_tests': 'Quality advocacy and systematic approach to design-development fidelity',
                'sample_answer_outline': 'Should discuss establishing a visual QA process, creating a structured way to document discrepancies, prioritizing fixes by user impact, working with engineers to understand why drift happens, and improving the handoff process to prevent future issues. Should mention design tokens and automated checks where possible.',
            },
            {
                'question_text': 'How do you approach designing data-dense interfaces like dashboards or analytics views while keeping them visually clean and scannable?',
                'category': 'technical',
                'difficulty': 'hard',
                'what_it_tests': 'Ability to handle complex information display with visual clarity',
                'sample_answer_outline': 'Should discuss establishing clear visual hierarchy through size, weight, and color, using white space strategically, grouping related data, designing progressive disclosure for detail levels, choosing appropriate chart types, and ensuring color use is meaningful and accessible. Should mention testing with real data volumes rather than idealized sample data.',
            },
            {
                'question_text': 'How do you balance creative expression and visual innovation with the consistency requirements of a design system?',
                'category': 'culture',
                'difficulty': 'medium',
                'what_it_tests': 'Understanding of the tension between creativity and system constraints',
                'sample_answer_outline': 'Should discuss working within system constraints as a creative challenge rather than a limitation, identifying where bespoke design is warranted versus where consistency is more important, proposing system additions when new patterns emerge, and understanding that consistency serves users even when it limits designer expression.',
            },
            {
                'question_text': 'A product team needs a completely new type of component that does not exist in the design system. Walk me through how you would design it and get it adopted.',
                'category': 'problem_solving',
                'difficulty': 'medium',
                'what_it_tests': 'Design system contribution process and component design thinking',
                'sample_answer_outline': 'Should discuss researching whether existing components can be extended, designing the component with multiple states and variants, documenting usage guidelines and edge cases, reviewing with other designers for broad applicability, collaborating with the front-end team on implementation, and going through the team adoption process.',
            },
            {
                'question_text': 'How do you choose between using color, iconography, typography, or spatial relationships to create visual hierarchy in an interface?',
                'category': 'technical',
                'difficulty': 'easy',
                'what_it_tests': 'Foundational visual design knowledge and hierarchy principles',
                'sample_answer_outline': 'Should discuss using size and weight as primary hierarchy tools since they work for all users, using color sparingly for emphasis and status, using spatial grouping and proximity for relationship signaling, and using iconography for recognition and scannability. Should mention accessibility considerations for not relying on color alone.',
            },
            {
                'question_text': 'Your design manager asks you to lead the creation of a dark mode for the product. What is your approach?',
                'category': 'situational',
                'difficulty': 'hard',
                'what_it_tests': 'Systematic thinking about theming and the complexities of dark mode design',
                'sample_answer_outline': 'Should discuss that dark mode is not simply inverting colors, planning semantic color tokens that map to both themes, adjusting elevation and shadow models, reducing image and icon brightness, handling edge cases like user-generated content, testing for contrast compliance in both modes, and planning a rollout strategy.',
            },
            {
                'question_text': 'What is your approach to creating and organizing icon sets for a product?',
                'category': 'culture',
                'difficulty': 'easy',
                'what_it_tests': 'Attention to detail and systematic approach to visual assets',
                'sample_answer_outline': 'Should discuss establishing consistent sizing, stroke weight, and style rules, organizing icons by category with clear naming conventions, designing on a pixel grid for crisp rendering, considering both outlined and filled variants, optimizing SVG exports for performance, and documenting when to use icons versus text labels.',
            },
        ],
    },
]
