ENGINEERING_ROLES = [
    {
        'slug': 'vp-of-engineering',
        'title': 'VP of Engineering',
        'department': 'Engineering',
        'seniority_level': 'executive',
        'description': 'The VP of Engineering is responsible for leading the entire engineering organization, setting technical strategy, and ensuring the team delivers high-quality software at scale. This executive partners with product, design, and business leadership to align engineering investments with company objectives and drives the culture of engineering excellence across the organization.',
        'responsibilities': [
            'Define and execute the engineering strategy and technical roadmap aligned with company goals and product vision',
            'Build, lead, and develop a high-performing engineering organization across multiple teams and disciplines',
            'Establish engineering processes, standards, and best practices that enable the team to ship reliably and at scale',
            'Partner with product and design leadership to prioritize initiatives and balance technical debt against feature development',
            'Own engineering budget, headcount planning, and resource allocation across teams and projects',
            'Report on engineering velocity, quality metrics, and technical risk to the executive team and board',
        ],
        'key_skills': [
            'Engineering leadership and organizational design',
            'Technical strategy and architecture at scale',
            'Talent acquisition, retention, and team development',
            'Cross-functional collaboration with product and business stakeholders',
            'Process optimization and engineering operations',
            'Budget management and resource planning',
        ],
        'assessment_slugs': ['behavioral'],
        'questions': [
            {
                'question_text': 'How would you evaluate and restructure an engineering organization that has grown from 20 to 150 engineers in two years and is now struggling with delivery velocity and coordination across teams?',
                'category': 'technical',
                'difficulty': 'hard',
                'what_it_tests': 'Ability to diagnose organizational scaling problems and design an engineering org structure that enables effective delivery',
                'sample_answer_outline': 'A strong answer covers assessing the current team topology and communication patterns, identifying bottlenecks in the delivery pipeline, and proposing a restructuring plan based on principles like team autonomy, clear ownership boundaries, and reduced cross-team dependencies. The candidate should discuss models like stream-aligned teams, platform teams, and enabling teams, and explain how they would manage the transition without disrupting ongoing delivery.',
            },
            {
                'question_text': 'Explain your approach to building a technology radar for the organization. How do you evaluate emerging technologies, decide what to adopt, and manage the transition without fragmenting the tech stack?',
                'category': 'technical',
                'difficulty': 'medium',
                'what_it_tests': 'Strategic judgment on technology investment decisions and ability to balance innovation with standardization',
                'sample_answer_outline': 'A strong answer presents a structured evaluation framework considering factors like strategic alignment, team capability, total cost of ownership, community maturity, and migration risk. The candidate should describe governance mechanisms such as a technology advisory group or architecture review board, explain how they pilot new technologies before broad adoption, and discuss how they manage the tension between allowing experimentation and preventing uncontrolled proliferation of tools and frameworks.',
            },
            {
                'question_text': 'Tell me about a time when you had to make a difficult decision to cancel or significantly descope a major engineering initiative that your team had invested heavily in. How did you handle it?',
                'category': 'behavioral',
                'difficulty': 'hard',
                'what_it_tests': 'Decision-making under sunk cost pressure and ability to communicate difficult decisions with empathy and transparency',
                'sample_answer_outline': 'The candidate should describe the specific situation and the data or signals that led to the decision, explain how they evaluated the sunk cost against future value, and detail how they communicated the decision to the team and stakeholders. A good answer shows awareness of the emotional impact on the team and demonstrates how they preserved morale and redirected energy productively.',
            },
            {
                'question_text': 'Describe a time when you inherited an engineering organization with significant cultural or performance problems. What did you find, what did you change, and how long did the turnaround take?',
                'category': 'behavioral',
                'difficulty': 'medium',
                'what_it_tests': 'Organizational turnaround experience and ability to diagnose and transform engineering culture',
                'sample_answer_outline': 'The candidate should describe how they assessed the existing culture through listening tours and data gathering, the specific problems they identified such as low trust, poor communication, or lack of accountability, and the changes they introduced in a sequenced manner. A good answer includes honest reflection on what worked and what did not, the timeline for seeing results, and how they measured improvement in team health and performance.',
            },
            {
                'question_text': 'Your CTO wants to rewrite the core platform from a monolith to microservices, but your engineering managers believe it will take 18 months and significantly slow feature delivery. How do you navigate this situation?',
                'category': 'situational',
                'difficulty': 'hard',
                'what_it_tests': 'Ability to balance technical vision with business pragmatism and manage up and down simultaneously',
                'sample_answer_outline': 'A strong candidate would seek to understand the business drivers behind the rewrite, work with engineering managers to build a realistic assessment of effort and risk, and propose an incremental migration strategy such as the strangler fig pattern that delivers value along the way. They should explain how they would present trade-offs to the CTO with data and propose a phased approach that balances modernization with continued feature delivery.',
            },
            {
                'question_text': 'The board is pressuring for faster time-to-market on a major new product, but your teams are already at capacity and technical debt is mounting. How do you respond?',
                'category': 'situational',
                'difficulty': 'medium',
                'what_it_tests': 'Executive communication skills and ability to manage competing pressures from business and engineering realities',
                'sample_answer_outline': 'The candidate should describe presenting a clear and honest assessment of current capacity and technical debt costs, quantifying the risk of cutting corners, and proposing options such as descoping the initial release, hiring or contracting for additional capacity, or temporarily pausing lower-priority work. They should demonstrate the ability to say no constructively while offering alternatives that still advance business objectives.',
            },
            {
                'question_text': 'How do you build a culture of engineering excellence that scales across multiple teams without becoming bureaucratic or stifling innovation?',
                'category': 'leadership',
                'difficulty': 'medium',
                'what_it_tests': 'Ability to establish engineering standards and culture at scale while preserving autonomy and innovation',
                'sample_answer_outline': 'The candidate should discuss establishing shared engineering principles rather than rigid rules, creating communities of practice and guilds for knowledge sharing, investing in developer experience and tooling, and balancing standardization with team autonomy. They should give concrete examples of mechanisms they have used such as architecture review boards, tech radar processes, or internal tech talks, and explain how they measure engineering health beyond velocity metrics.',
            },
            {
                'question_text': 'How do you develop engineering managers into strong leaders who can run their areas autonomously while maintaining alignment with the broader engineering vision?',
                'category': 'leadership',
                'difficulty': 'easy',
                'what_it_tests': 'Investment in growing engineering leadership talent and approach to management development',
                'sample_answer_outline': 'A good answer discusses providing structured mentorship, creating stretch assignments and leadership opportunities, establishing regular feedback and coaching rhythms, and building a peer learning community among managers. The candidate should explain how they assess leadership readiness, how they handle the transition from individual contributor to manager, and how they support managers through difficult situations like performance management or team conflict.',
            },
            {
                'question_text': 'What is your philosophy on engineering culture during periods of rapid growth? How do you preserve what made the team effective while adapting to new scale?',
                'category': 'culture',
                'difficulty': 'medium',
                'what_it_tests': 'Awareness of cultural challenges during scaling and intentional approach to culture building',
                'sample_answer_outline': 'A good answer addresses explicitly identifying and codifying the cultural values worth preserving, adapting practices that do not scale while keeping their underlying intent, investing in onboarding to transmit culture to new hires, and creating feedback mechanisms to detect cultural drift early. The candidate should discuss specific examples of cultural practices they have evolved during growth periods and how they balance consistency with allowing subcultures to emerge in different teams.',
            },
            {
                'question_text': 'How do you approach diversity, equity, and inclusion in engineering hiring and team culture? What specific actions have you taken that produced measurable results?',
                'category': 'culture',
                'difficulty': 'easy',
                'what_it_tests': 'Commitment to building diverse engineering teams and creating inclusive environments',
                'sample_answer_outline': 'The candidate should go beyond stating values to describe specific programs and practices they have implemented, such as structured interviewing, diverse sourcing pipelines, inclusive onboarding, sponsorship programs, and retention-focused initiatives. They should share measurable outcomes and acknowledge areas where they are still learning and improving.',
            },
            {
                'question_text': 'Your engineering organization has a persistent problem with production incidents increasing quarter over quarter despite growing the team. How would you diagnose the root causes and develop a plan to reverse this trend?',
                'category': 'problem_solving',
                'difficulty': 'hard',
                'what_it_tests': 'Systems thinking about reliability and quality, and ability to address systemic engineering problems',
                'sample_answer_outline': 'The candidate should describe analyzing incident patterns by type, severity, team, and system component to identify trends. They should discuss evaluating testing practices, deployment processes, observability infrastructure, and on-call effectiveness. A strong answer proposes a multi-pronged plan covering improved incident review processes, investment in automated testing and CI/CD guardrails, reliability targets like SLOs, and potentially a dedicated reliability investment period.',
            },
            {
                'question_text': 'You are inheriting an engineering organization where two critical systems are maintained by single engineers with no documentation and no bus factor coverage. How do you address this risk without alienating those engineers?',
                'category': 'problem_solving',
                'difficulty': 'medium',
                'what_it_tests': 'Risk management judgment and ability to address knowledge silos diplomatically',
                'sample_answer_outline': 'The candidate should describe first building relationships with those engineers to understand their perspective, then framing knowledge sharing as career growth rather than threat. They should propose concrete steps like pairing sessions, documentation sprints, and gradually expanding team ownership. A good answer addresses both the technical risk and the human dynamics of the situation, and explains how they would prevent similar silos from forming in the future.',
            },
        ],
    },
    {
        'slug': 'engineering-manager',
        'title': 'Engineering Manager',
        'department': 'Engineering',
        'seniority_level': 'lead',
        'description': 'The Engineering Manager leads a team of software engineers to deliver high-quality software on time while fostering professional growth and team health. This role balances people management, technical oversight, and project delivery, serving as the critical link between engineering leadership strategy and day-to-day execution.',
        'responsibilities': [
            'Lead, mentor, and grow a team of software engineers through regular one-on-ones, feedback, and career development planning',
            'Drive sprint planning, backlog refinement, and delivery execution to meet commitments and project timelines',
            'Collaborate with product managers and designers to translate requirements into technical plans and estimates',
            'Conduct performance reviews, manage compensation decisions, and handle hiring for the team',
            'Remove blockers, resolve technical and interpersonal conflicts, and ensure a healthy team dynamic',
            'Maintain sufficient technical depth to participate in architecture decisions and code review when needed',
        ],
        'key_skills': [
            'People management and coaching',
            'Agile project management and delivery execution',
            'Technical architecture and system design understanding',
            'Hiring, interviewing, and team building',
            'Stakeholder communication and expectation management',
            'Conflict resolution and team dynamics management',
        ],
        'assessment_slugs': ['behavioral'],
        'questions': [
            {
                'question_text': 'How do you approach sprint planning and estimation with your team? What techniques do you use to improve estimation accuracy over time and what do you do when estimates are consistently wrong?',
                'category': 'technical',
                'difficulty': 'medium',
                'what_it_tests': 'Understanding of agile estimation practices and ability to improve team delivery predictability',
                'sample_answer_outline': 'A strong answer covers specific estimation techniques like story points or t-shirt sizing, explains how they use historical velocity data to calibrate estimates, and discusses strategies for handling uncertainty such as spikes and timeboxing. The candidate should explain how they track estimation accuracy over time and use retrospectives to continuously improve the process rather than blaming individuals for misses.',
            },
            {
                'question_text': 'How do you approach architecture and design reviews with your team? What level of technical involvement do you maintain as a manager and where do you draw the line between guidance and micromanagement?',
                'category': 'technical',
                'difficulty': 'easy',
                'what_it_tests': 'Appropriate level of technical engagement and ability to empower engineers while maintaining quality oversight',
                'sample_answer_outline': 'A good answer describes establishing design review processes where engineers present proposals to peers, the manager role as facilitator rather than decision-maker, and when the manager should weigh in versus defer to the team. The candidate should explain how they maintain enough technical context to ask good questions and detect risks without micromanaging or becoming a bottleneck on every technical decision.',
            },
            {
                'question_text': 'Tell me about a time when you had to give difficult feedback to a senior engineer who was technically strong but was creating a toxic environment for the rest of the team. What happened?',
                'category': 'behavioral',
                'difficulty': 'hard',
                'what_it_tests': 'Courage to address behavior issues with high-performing individuals and skill in delivering difficult feedback',
                'sample_answer_outline': 'The candidate should describe the specific behaviors and their impact on the team, how they prepared for and delivered the feedback conversation, and the outcome. A good answer shows the candidate did not avoid or delay the conversation, used specific examples rather than generalizations, set clear expectations for behavior change, and followed up consistently to ensure improvement.',
            },
            {
                'question_text': 'Describe a time when you helped an engineer on your team navigate a career transition, such as moving from individual contributor to tech lead or changing specializations. What was your approach?',
                'category': 'behavioral',
                'difficulty': 'easy',
                'what_it_tests': 'Investment in career development and ability to coach engineers through growth transitions',
                'sample_answer_outline': 'The candidate should describe understanding the engineer aspiration, assessing their readiness honestly, creating a development plan with specific milestones, providing stretch opportunities, and offering ongoing coaching. A good answer shows the candidate supported the engineer through challenges during the transition and adjusted the plan as needed based on progress and feedback.',
            },
            {
                'question_text': 'A product manager is pushing your team to commit to an aggressive deadline that your engineers believe is unrealistic. How do you handle the situation without damaging the relationship or demoralizing your team?',
                'category': 'situational',
                'difficulty': 'medium',
                'what_it_tests': 'Ability to advocate for the team while maintaining collaborative relationships with product partners',
                'sample_answer_outline': 'The candidate should describe working with the team to build a detailed estimate, then presenting the trade-offs to the product manager transparently. They should discuss negotiation strategies such as reducing scope, phasing delivery, or identifying what can be parallelized. A good answer demonstrates protecting the team from unrealistic commitments while remaining solution-oriented and collaborative.',
            },
            {
                'question_text': 'You have just taken over a team where the previous manager was beloved but had very different management practices from yours. The team is resistant to changes you want to introduce. How do you handle this?',
                'category': 'situational',
                'difficulty': 'hard',
                'what_it_tests': 'Change management skills and ability to build trust with a new team while evolving practices',
                'sample_answer_outline': 'The candidate should describe investing time to understand the existing team culture and what worked well under the previous manager before making changes. They should explain introducing changes gradually with clear rationale, seeking team input on how to implement improvements, and earning trust through consistent behavior and demonstrated care for the team. A good answer shows patience, humility, and awareness that trust must be earned.',
            },
            {
                'question_text': 'How do you balance the need to deliver features with investing in technical debt reduction and engineering improvements? What is your approach to making this case to product stakeholders?',
                'category': 'leadership',
                'difficulty': 'medium',
                'what_it_tests': 'Strategic thinking about engineering investment and ability to communicate technical needs in business terms',
                'sample_answer_outline': 'A good answer discusses quantifying the impact of technical debt in terms product stakeholders understand, such as delivery velocity trends, incident frequency, or developer onboarding time. The candidate should describe specific allocation strategies like a percentage-based approach or dedicated improvement sprints and explain how they track the return on technical debt investment over time.',
            },
            {
                'question_text': 'How do you run effective one-on-one meetings with your direct reports? What makes a one-on-one valuable versus a waste of time?',
                'category': 'leadership',
                'difficulty': 'easy',
                'what_it_tests': 'Foundational management practice and commitment to investing in individual team members',
                'sample_answer_outline': 'A good answer discusses letting the report drive the agenda, focusing on career development and blockers rather than status updates, maintaining consistency in cadence, and creating space for honest conversation. The candidate should explain how they adapt their approach to different individuals and how they follow through on action items from one-on-ones to build trust.',
            },
            {
                'question_text': 'What does psychological safety mean to you in the context of an engineering team, and how do you actively create and protect it?',
                'category': 'culture',
                'difficulty': 'easy',
                'what_it_tests': 'Understanding of psychological safety and intentional practices to build a safe team environment',
                'sample_answer_outline': 'The candidate should define psychological safety with concrete examples, describe specific practices like blameless postmortems, encouraging questions, admitting their own mistakes, and creating space for dissenting opinions. They should explain how they handle situations that threaten psychological safety and how they know whether their team feels safe.',
            },
            {
                'question_text': 'How do you handle the tension between maintaining team consistency and accommodating individual work style preferences, especially in a hybrid or remote environment?',
                'category': 'culture',
                'difficulty': 'medium',
                'what_it_tests': 'Flexibility in management approach and ability to balance team norms with individual needs',
                'sample_answer_outline': 'The candidate should describe establishing minimum team agreements around availability, communication, and collaboration while allowing flexibility beyond those minimums. They should discuss how they involve the team in setting norms, how they accommodate different working styles, and where they draw the line between flexibility and team cohesion.',
            },
            {
                'question_text': 'Your team has been consistently missing sprint commitments for the last three sprints. Morale is dropping and stakeholders are losing confidence. How do you diagnose and address this?',
                'category': 'problem_solving',
                'difficulty': 'hard',
                'what_it_tests': 'Ability to diagnose systemic delivery issues and address both the practical and emotional dimensions',
                'sample_answer_outline': 'A strong answer describes analyzing the data to identify patterns such as over-commitment, scope creep, unexpected technical complexity, or external interruptions. The candidate should discuss holding an honest team retrospective, resetting expectations with stakeholders, and implementing specific changes such as reducing work-in-progress, improving story readiness criteria, or building in buffer for unknowns. They should address the morale dimension by acknowledging the frustration and celebrating small wins.',
            },
            {
                'question_text': 'Two engineers on your team are proposing competing technical approaches to solve the same problem. Both approaches have merit and the engineers feel strongly about their positions. How do you facilitate a resolution?',
                'category': 'problem_solving',
                'difficulty': 'medium',
                'what_it_tests': 'Facilitation skills for technical disagreements and ability to drive decisions without being autocratic',
                'sample_answer_outline': 'The candidate should describe creating a structured evaluation process that focuses on objective criteria such as maintainability, performance, and alignment with team standards. They should explain how they facilitate a productive discussion, when they let the team reach consensus versus when they need to make the call, and how they ensure the person whose approach was not chosen feels respected and heard.',
            },
        ],
    },
    {
        'slug': 'senior-software-engineer',
        'title': 'Senior Software Engineer',
        'department': 'Engineering',
        'seniority_level': 'senior',
        'description': 'The Senior Software Engineer designs and implements complex software systems, provides technical leadership to the team, and raises the bar for code quality and engineering practices. This role requires deep technical expertise combined with the ability to mentor junior engineers, drive architectural decisions, and deliver high-impact projects independently.',
        'responsibilities': [
            'Design, implement, and maintain complex software systems and features with high code quality and test coverage',
            'Lead technical design discussions and produce architecture documents for significant projects',
            'Mentor junior and mid-level engineers through code review, pairing sessions, and technical guidance',
            'Identify and address technical debt, performance bottlenecks, and reliability risks proactively',
            'Collaborate with product managers and designers to refine requirements and propose technical solutions',
            'Contribute to engineering standards, tooling improvements, and best practices across the team',
        ],
        'key_skills': [
            'Software architecture and system design',
            'Proficiency in multiple programming languages and frameworks',
            'Testing strategies including unit, integration, and end-to-end testing',
            'Performance optimization and scalability',
            'Code review and technical mentorship',
            'Problem decomposition and technical communication',
        ],
        'assessment_slugs': ['behavioral'],
        'questions': [
            {
                'question_text': 'Walk me through how you would design a rate limiting system for a high-traffic API that needs to support multiple rate limiting strategies such as per-user, per-endpoint, and global limits. What data structures and algorithms would you consider?',
                'category': 'technical',
                'difficulty': 'hard',
                'what_it_tests': 'System design skills, knowledge of rate limiting algorithms, and ability to handle distributed systems challenges',
                'sample_answer_outline': 'A strong answer discusses rate limiting algorithms like token bucket, sliding window, and fixed window with their trade-offs. The candidate should address distributed state management using Redis or a similar store, race condition handling, graceful degradation, and how to make the system configurable. They should consider edge cases like burst traffic, clock skew in distributed environments, and providing clear feedback to API consumers.',
            },
            {
                'question_text': 'Explain how you would design a database schema and data access layer for a system that needs to support both high-throughput writes and complex analytical queries without sacrificing performance on either workload.',
                'category': 'technical',
                'difficulty': 'hard',
                'what_it_tests': 'Database design knowledge and understanding of OLTP versus OLAP workload separation strategies',
                'sample_answer_outline': 'The candidate should discuss separating the write-optimized transactional store from the read-optimized analytical store using patterns like CQRS or change data capture. They should address specific technologies and trade-offs, discuss eventual consistency implications, and explain data synchronization strategies. A good answer considers the operational complexity of maintaining multiple data stores and when simpler approaches might be sufficient.',
            },
            {
                'question_text': 'Tell me about a time when you strongly disagreed with an architectural decision made by a more senior engineer or architect. What did you do and what was the outcome?',
                'category': 'behavioral',
                'difficulty': 'medium',
                'what_it_tests': 'Ability to challenge decisions constructively while respecting organizational hierarchy and expertise',
                'sample_answer_outline': 'The candidate should describe the technical disagreement and their reasoning, how they raised their concerns with supporting evidence rather than just opinion, and the outcome of the discussion. A good answer shows the candidate was willing to commit to the decision even if they disagreed after ensuring their perspective was heard, or describes how their input led to a better outcome through collaborative discussion.',
            },
            {
                'question_text': 'Describe a time when you identified and addressed a significant performance bottleneck in a production system. Walk me through your investigation process and the solution you implemented.',
                'category': 'behavioral',
                'difficulty': 'medium',
                'what_it_tests': 'Real-world performance debugging experience and ability to drive optimization from diagnosis to resolution',
                'sample_answer_outline': 'The candidate should describe how they identified the bottleneck using profiling, monitoring, or user reports, the analysis process that led to understanding the root cause, the solution they implemented and why they chose it over alternatives, and the measurable improvement achieved. A good answer demonstrates methodical investigation rather than guesswork and shows the candidate considered the broader system impact of their fix.',
            },
            {
                'question_text': 'You are asked to take over a critical service that has no tests, no documentation, and the original author has left the company. The service handles payment processing. How do you approach this safely?',
                'category': 'situational',
                'difficulty': 'hard',
                'what_it_tests': 'Risk management when dealing with legacy critical systems and methodical approach to understanding unfamiliar code',
                'sample_answer_outline': 'A strong answer describes first understanding the system through code reading, tracing request flows, and analyzing production logs and metrics before making any changes. The candidate should discuss writing characterization tests to capture current behavior, setting up proper monitoring and alerting, and only then making changes incrementally with thorough testing. They should emphasize the importance of not rushing changes to a payment system and communicating risk to stakeholders.',
            },
            {
                'question_text': 'You need to refactor a critical shared library that is used by 12 different services. How do you plan and execute this refactoring without breaking downstream consumers?',
                'category': 'situational',
                'difficulty': 'medium',
                'what_it_tests': 'Ability to plan large-scale refactoring with minimal disruption and manage cross-team dependencies',
                'sample_answer_outline': 'The candidate should discuss strategies like maintaining backward compatibility during the transition, using semantic versioning, creating an adapter or compatibility layer, migrating consumers incrementally, and communicating the change plan to downstream teams. They should explain how they would ensure each step is safe through automated testing, feature flags, or parallel running, and how they would handle teams that are slow to migrate.',
            },
            {
                'question_text': 'How do you approach mentoring a junior engineer who is struggling with code quality? What specific techniques have you found most effective?',
                'category': 'leadership',
                'difficulty': 'easy',
                'what_it_tests': 'Mentorship skills and ability to grow junior engineers effectively without being condescending',
                'sample_answer_outline': 'A good answer discusses pairing sessions where the junior engineer drives, providing constructive code review feedback that explains the why behind suggestions, establishing incremental quality standards, and creating a safe environment for questions. The candidate should emphasize patience, celebrating progress, and adapting their mentoring style to the individual learner rather than applying a one-size-fits-all approach.',
            },
            {
                'question_text': 'How do you decide when a piece of code needs a test and what kind of test it should have? What is your philosophy on testing and how do you communicate it to your team?',
                'category': 'leadership',
                'difficulty': 'medium',
                'what_it_tests': 'Testing philosophy and ability to make pragmatic decisions about testing investment',
                'sample_answer_outline': 'A good answer describes a risk-based approach to testing, where critical paths and complex logic get thorough unit tests, integration boundaries get integration tests, and key user journeys get end-to-end tests. The candidate should discuss the testing pyramid, explain when they would deviate from it, and acknowledge that not all code needs the same level of testing. They should address testing as a tool for confidence rather than coverage metrics.',
            },
            {
                'question_text': 'How do you approach writing code that other engineers will need to maintain? What principles guide your decisions about code readability versus cleverness?',
                'category': 'culture',
                'difficulty': 'easy',
                'what_it_tests': 'Engineering values around maintainability and team-oriented coding practices',
                'sample_answer_outline': 'The candidate should express a clear preference for readable, maintainable code over clever solutions. They should discuss principles like clear naming, appropriate abstraction levels, self-documenting code with strategic comments, and consistent coding patterns. A good answer acknowledges that writing simple code is harder than writing complex code and provides examples of when they simplified an initially complex solution for the benefit of future maintainers.',
            },
            {
                'question_text': 'How do you stay current with evolving technologies and decide when to adopt new tools or frameworks versus sticking with proven solutions? Give a recent example.',
                'category': 'culture',
                'difficulty': 'medium',
                'what_it_tests': 'Balanced approach to technology adoption and professional growth mindset',
                'sample_answer_outline': 'The candidate should describe their learning habits and sources, explain their evaluation criteria for new technologies including maturity, community support, team familiarity, and migration cost, and give examples of technologies they chose to adopt or deliberately chose not to adopt with the reasoning behind each decision. A good answer shows healthy skepticism toward hype combined with genuine curiosity and a willingness to experiment.',
            },
            {
                'question_text': 'A production service is experiencing intermittent latency spikes that affect 5% of requests but only during peak hours. Standard metrics show no obvious issues. How would you investigate this?',
                'category': 'problem_solving',
                'difficulty': 'hard',
                'what_it_tests': 'Systematic debugging skills for complex production issues and knowledge of performance diagnostics',
                'sample_answer_outline': 'A strong answer describes a systematic investigation approach: correlating the spikes with specific request patterns, checking for garbage collection pauses, database connection pool exhaustion, noisy neighbor effects in shared infrastructure, network latency, and downstream service performance. The candidate should discuss using distributed tracing to identify the slow path, analyzing percentile distributions rather than averages, and checking for resource contention or lock contention under load.',
            },
            {
                'question_text': 'You discover that a feature you shipped last week has a subtle bug that corrupts data for approximately 1% of users, but the corrupted data has already been propagated to downstream systems. How do you handle this?',
                'category': 'problem_solving',
                'difficulty': 'medium',
                'what_it_tests': 'Incident response skills and ability to manage data integrity issues across interconnected systems',
                'sample_answer_outline': 'The candidate should describe immediately stopping the data corruption by reverting or fixing the code, assessing the blast radius by identifying all affected users and downstream systems, developing a data remediation plan, and communicating the issue to stakeholders. A good answer discusses the importance of not making things worse during remediation, testing the fix thoroughly before applying it, and conducting a postmortem to prevent similar issues.',
            },
        ],
    },
    {
        'slug': 'devops-engineer',
        'title': 'DevOps Engineer',
        'department': 'Engineering',
        'seniority_level': 'mid',
        'description': 'The DevOps Engineer designs, builds, and maintains the infrastructure, CI/CD pipelines, and operational tooling that enable engineering teams to deliver software reliably and efficiently. This role bridges development and operations, focusing on automation, observability, and platform reliability to accelerate the software delivery lifecycle.',
        'responsibilities': [
            'Design, implement, and maintain CI/CD pipelines that enable fast and reliable software delivery',
            'Manage cloud infrastructure using infrastructure-as-code tools and ensure environments are reproducible and scalable',
            'Build and maintain monitoring, alerting, and observability systems that provide visibility into system health and performance',
            'Automate operational tasks including deployments, scaling, backup, and disaster recovery procedures',
            'Collaborate with development teams to improve deployment practices, container orchestration, and environment management',
            'Participate in on-call rotations and lead incident response for infrastructure and platform issues',
        ],
        'key_skills': [
            'Cloud platforms such as AWS, GCP, or Azure',
            'Infrastructure-as-code tools such as Terraform, CloudFormation, or Pulumi',
            'Container orchestration with Docker and Kubernetes',
            'CI/CD pipeline design and implementation',
            'Monitoring and observability tools such as Prometheus, Grafana, and Datadog',
            'Scripting and automation with Python, Bash, or Go',
        ],
        'assessment_slugs': ['behavioral'],
        'questions': [
            {
                'question_text': 'Walk me through how you would design a CI/CD pipeline for a team that deploys a microservices application to Kubernetes. What stages would you include and what safeguards would you build in?',
                'category': 'technical',
                'difficulty': 'medium',
                'what_it_tests': 'Understanding of CI/CD pipeline design principles, deployment strategies, and quality gates',
                'sample_answer_outline': 'A strong answer covers pipeline stages including code checkout, dependency installation, linting, unit tests, container image building, security scanning, integration testing, deployment to staging, automated smoke tests, manual approval gate, production deployment, and post-deployment verification. The candidate should discuss rollback strategies, canary or blue-green deployments, and how to handle pipeline failures at each stage.',
            },
            {
                'question_text': 'Explain how you would implement infrastructure-as-code for an organization that currently manages all infrastructure manually through the cloud console. What is your migration strategy and how do you get the team on board?',
                'category': 'technical',
                'difficulty': 'hard',
                'what_it_tests': 'Infrastructure-as-code expertise and ability to plan a realistic migration from manual to automated infrastructure management',
                'sample_answer_outline': 'The candidate should discuss choosing an IaC tool based on team skills and requirements, starting by importing existing resources rather than recreating them, establishing a modular and reusable code structure, implementing state management and remote backends, setting up CI/CD for infrastructure changes with plan review and approval stages, and training the team. They should address the challenges of drift detection and handling resources that resist codification.',
            },
            {
                'question_text': 'Tell me about a time when an infrastructure change you made caused an unexpected outage. How did you respond and what did you learn from the experience?',
                'category': 'behavioral',
                'difficulty': 'medium',
                'what_it_tests': 'Accountability during incidents, learning from mistakes, and growth mindset',
                'sample_answer_outline': 'The candidate should describe the change and why the impact was unexpected, how they detected and responded to the outage, the steps taken to resolve it, and the preventive measures implemented afterward. A good answer shows ownership without excessive self-blame, demonstrates structured incident response, and explains concrete process improvements that resulted from the experience.',
            },
            {
                'question_text': 'Describe a time when you automated a process that previously required significant manual effort. What was the impact and what challenges did you encounter during implementation?',
                'category': 'behavioral',
                'difficulty': 'easy',
                'what_it_tests': 'Automation mindset and ability to identify and execute on automation opportunities',
                'sample_answer_outline': 'The candidate should describe the manual process and its pain points, the automation solution they built, challenges encountered during implementation such as edge cases or resistance to change, and the measurable impact in terms of time saved, error reduction, or improved reliability. A good answer shows pragmatic judgment about what to automate and what to leave manual.',
            },
            {
                'question_text': 'Your company is experiencing a major outage during peak business hours. The root cause is unclear and multiple systems appear affected. Walk me through your incident response approach from the moment you are paged.',
                'category': 'situational',
                'difficulty': 'hard',
                'what_it_tests': 'Incident management skills under pressure and ability to coordinate effectively during a crisis',
                'sample_answer_outline': 'The candidate should describe establishing an incident commander role, creating a communication channel, triaging affected systems by business impact, systematically narrowing down the root cause using observability tools, and coordinating with relevant teams. They should discuss communicating status updates to stakeholders, making the decision between a quick fix and a proper resolution, and conducting a blameless postmortem afterward.',
            },
            {
                'question_text': 'A developer complains that the CI pipeline takes 45 minutes and it is killing their productivity. You investigate and find that test execution accounts for 30 minutes. How do you approach reducing this?',
                'category': 'situational',
                'difficulty': 'medium',
                'what_it_tests': 'Pipeline optimization skills and ability to balance speed with quality in CI/CD systems',
                'sample_answer_outline': 'The candidate should discuss strategies like test parallelization, test splitting across multiple runners, caching dependencies and build artifacts, identifying and fixing slow tests, running only affected tests on each change, and separating fast feedback tests from comprehensive test suites. They should consider the trade-off between pipeline speed and test coverage and propose a layered approach that gives developers fast feedback while maintaining comprehensive testing.',
            },
            {
                'question_text': 'How do you advocate for infrastructure investment and reliability work when product teams are pressuring for more feature development resources?',
                'category': 'leadership',
                'difficulty': 'medium',
                'what_it_tests': 'Ability to communicate infrastructure value in business terms and influence without authority',
                'sample_answer_outline': 'A good answer discusses quantifying the cost of poor infrastructure in terms of developer productivity, incident frequency, customer impact, and opportunity cost. The candidate should explain how they frame reliability as a product feature, use SLO frameworks to make data-driven arguments, and build relationships with product stakeholders. They should acknowledge the legitimate tension and show they can find pragmatic compromises.',
            },
            {
                'question_text': 'How do you approach building runbooks and documentation for operational procedures? What makes a good runbook and how do you ensure they stay current?',
                'category': 'leadership',
                'difficulty': 'easy',
                'what_it_tests': 'Commitment to operational excellence and knowledge sharing through documentation',
                'sample_answer_outline': 'A good answer describes writing runbooks that are actionable and step-by-step rather than conceptual, including clear trigger conditions, expected outcomes, and escalation paths. The candidate should discuss keeping runbooks up to date through regular review, testing runbooks during game days, and treating runbook creation as a natural outcome of incident response. They should explain how good documentation reduces on-call burden and enables team scaling.',
            },
            {
                'question_text': 'What does a healthy DevOps culture look like to you? How do you break down silos between development and operations teams in practice?',
                'category': 'culture',
                'difficulty': 'easy',
                'what_it_tests': 'Understanding of DevOps cultural principles beyond just tooling and automation',
                'sample_answer_outline': 'The candidate should discuss shared ownership of reliability, developers participating in on-call, collaborative incident response, and embedding DevOps practices into development workflows rather than keeping them separate. They should explain how they build empathy between development and operations through practices like shared postmortems, cross-training, and collaborative tooling development.',
            },
            {
                'question_text': 'How do you balance security best practices with developer experience when designing infrastructure and deployment processes? Give an example of a time you had to find this balance.',
                'category': 'culture',
                'difficulty': 'medium',
                'what_it_tests': 'Security awareness and ability to implement security without creating friction that developers work around',
                'sample_answer_outline': 'The candidate should discuss implementing security guardrails that are automated and transparent rather than manual and blocking, such as automated secret scanning, policy-as-code, and secure defaults. They should explain how they work with security teams to find pragmatic solutions and describe examples where they made secure practices the path of least resistance for developers.',
            },
            {
                'question_text': 'Your Kubernetes cluster is running at 80% CPU capacity during normal hours and you are seeing pod evictions during peak load. How would you approach solving this without simply throwing more nodes at the problem?',
                'category': 'problem_solving',
                'difficulty': 'hard',
                'what_it_tests': 'Kubernetes resource management knowledge and ability to optimize before scaling',
                'sample_answer_outline': 'A strong answer covers analyzing resource requests versus actual usage to identify over-provisioned pods, implementing horizontal pod autoscaling, reviewing and right-sizing resource limits, evaluating pod priority and preemption policies, checking for resource-inefficient workloads, and considering node autoscaling as a dynamic solution. The candidate should discuss using monitoring data to make informed decisions and the trade-off between cost optimization and reliability margins.',
            },
            {
                'question_text': 'Your monitoring system shows that application error rates are within normal thresholds, but customer support tickets about degraded performance have tripled this week. How do you investigate this disconnect?',
                'category': 'problem_solving',
                'difficulty': 'medium',
                'what_it_tests': 'Observability thinking and ability to identify gaps between monitoring and actual user experience',
                'sample_answer_outline': 'The candidate should investigate whether monitoring thresholds are set appropriately, check for issues not captured by current metrics such as client-side performance, partial failures, or degraded functionality that does not generate errors, and review whether recent changes affected the user experience in ways not reflected in server-side metrics. A good answer discusses implementing synthetic monitoring, real user monitoring, and correlating support tickets with system events to close the observability gap.',
            },
        ],
    },
]
