FINANCE_ROLES = [
    {
        'slug': 'cfo',
        'title': 'Chief Financial Officer',
        'department': 'Finance',
        'seniority_level': 'executive',
        'description': 'The CFO oversees all financial operations, strategy, and reporting for the organization. They serve as a key advisor to the CEO and board on capital allocation, risk management, and long-term financial planning. The CFO ensures fiscal discipline while enabling growth through strategic financial leadership.',
        'responsibilities': [
            'Define and execute the company-wide financial strategy aligned with business objectives',
            'Oversee financial reporting, audit processes, and regulatory compliance',
            'Lead capital allocation decisions including M&A, fundraising, and investment strategy',
            'Present financial performance and forecasts to the board of directors and investors',
            'Build and mentor a high-performing finance organization across FP&A, accounting, and treasury',
            'Manage enterprise risk including foreign exchange, credit, and liquidity exposure',
        ],
        'key_skills': [
            'Strategic financial planning and capital markets expertise',
            'M&A due diligence, valuation, and post-merger integration',
            'Board and investor relations communication',
            'Enterprise risk management and internal controls',
            'Cross-functional executive leadership',
            'GAAP/IFRS reporting and regulatory compliance',
        ],
        'assessment_slugs': ['finance', 'behavioral'],
        'questions': [
            {
                'question_text': 'How would you evaluate whether to fund growth through debt financing versus an equity raise, given current market conditions?',
                'category': 'technical',
                'difficulty': 'hard',
                'what_it_tests': 'Understanding of capital structure optimization and cost of capital trade-offs',
                'sample_answer_outline': 'A strong answer discusses WACC implications, dilution versus leverage risk, debt covenant constraints, current interest rate environment, and the company\'s stage and cash flow predictability. The candidate should weigh tax shields against financial distress costs.',
            },
            {
                'question_text': 'Describe a time when you had to deliver difficult financial news to a board of directors. How did you approach it?',
                'category': 'behavioral',
                'difficulty': 'hard',
                'what_it_tests': 'Executive communication skills and ability to maintain credibility under pressure',
                'sample_answer_outline': 'Look for transparency, preparation of multiple scenarios, proactive framing of remediation plans, and composure. The candidate should show they balanced honesty with constructive forward-looking solutions rather than deflecting blame.',
            },
            {
                'question_text': 'Your company has just acquired a business with $200M in revenue but different accounting systems and standards. How do you approach the financial integration?',
                'category': 'situational',
                'difficulty': 'hard',
                'what_it_tests': 'Post-merger integration planning and ability to harmonize financial operations at scale',
                'sample_answer_outline': 'A thorough answer covers Day 1 readiness for consolidation, chart of accounts mapping, system migration timeline, purchase accounting under ASC 805, synergy tracking, and retention of key finance talent from the acquired entity.',
            },
            {
                'question_text': 'How do you ensure alignment between the finance function and the broader executive leadership team on strategic priorities?',
                'category': 'leadership',
                'difficulty': 'medium',
                'what_it_tests': 'Cross-functional influence and ability to position finance as a strategic partner',
                'sample_answer_outline': 'The candidate should describe building shared KPIs, participating in strategic planning as a thought partner rather than just a scorekeeper, establishing regular cadences with business unit leaders, and translating financial insights into actionable business guidance.',
            },
            {
                'question_text': 'What values do you believe a finance organization must uphold, even when under pressure to hit short-term targets?',
                'category': 'culture',
                'difficulty': 'medium',
                'what_it_tests': 'Ethical grounding and commitment to financial integrity over expediency',
                'sample_answer_outline': 'Look for emphasis on transparency, accuracy, conservatism in reporting, tone from the top, and willingness to push back on aggressive accounting. The candidate should articulate how they embed these values into team culture and incentive structures.',
            },
            {
                'question_text': 'Your company is burning cash faster than forecast and has 8 months of runway. Revenue is 30% below plan. Walk me through your decision framework for the next 90 days.',
                'category': 'problem_solving',
                'difficulty': 'hard',
                'what_it_tests': 'Crisis financial management and structured decision-making under extreme pressure',
                'sample_answer_outline': 'A strong answer prioritizes immediate cash flow stabilization, builds a weekly 13-week cash forecast, identifies discretionary spend to cut, models workforce reduction scenarios, explores bridge financing options, and communicates transparently with the board while preserving optionality.',
            },
            {
                'question_text': 'Explain how you would construct a discounted cash flow model for a high-growth SaaS company with negative free cash flow.',
                'category': 'technical',
                'difficulty': 'hard',
                'what_it_tests': 'Advanced valuation skills and understanding of growth-stage financial modeling',
                'sample_answer_outline': 'The candidate should discuss projecting revenue growth rates, unit economics convergence to profitability, terminal value assumptions, appropriate discount rate selection for high-growth companies, sensitivity analysis on key drivers, and comparison with revenue multiple benchmarks.',
            },
            {
                'question_text': 'Tell me about a time when you had to significantly restructure a finance team. What was your approach and what did you learn?',
                'category': 'behavioral',
                'difficulty': 'medium',
                'what_it_tests': 'Organizational design capability and empathetic leadership through change',
                'sample_answer_outline': 'Look for a structured approach: assessing current capabilities against future needs, creating clear role definitions, managing transitions with respect, communicating the rationale transparently, and measuring the impact on team performance and morale post-restructuring.',
            },
            {
                'question_text': 'A business unit leader wants to pursue a strategic initiative that your financial analysis shows has a negative NPV. How do you handle this?',
                'category': 'situational',
                'difficulty': 'medium',
                'what_it_tests': 'Ability to balance analytical rigor with business partnership and influence',
                'sample_answer_outline': 'The candidate should describe presenting data transparently, exploring whether qualitative strategic benefits justify the investment, stress-testing assumptions collaboratively, and ultimately providing a clear recommendation while respecting the business leader\'s perspective.',
            },
            {
                'question_text': 'How do you develop the next generation of finance leaders within your organization?',
                'category': 'leadership',
                'difficulty': 'medium',
                'what_it_tests': 'Talent development philosophy and commitment to building organizational capacity',
                'sample_answer_outline': 'Look for mentorship programs, stretch assignments, cross-functional rotations, exposure to board and executive presentations, clear career laddering, and a philosophy of delegating meaningful decisions to develop judgment in rising leaders.',
            },
            {
                'question_text': 'How do you foster a culture of intellectual honesty in financial forecasting, where teams feel safe sharing bad news early?',
                'category': 'culture',
                'difficulty': 'easy',
                'what_it_tests': 'Ability to create psychological safety and a data-driven culture in finance',
                'sample_answer_outline': 'A strong answer covers separating forecast accuracy from personal performance evaluation, celebrating early identification of risks, using forecast variance reviews as learning opportunities rather than blame sessions, and modeling vulnerability as a leader.',
            },
            {
                'question_text': 'The audit committee has flagged a potential material weakness in your revenue recognition controls. You have 60 days before the next filing. What is your remediation plan?',
                'category': 'problem_solving',
                'difficulty': 'hard',
                'what_it_tests': 'SOX compliance expertise and ability to execute rapid remediation under regulatory deadlines',
                'sample_answer_outline': 'The candidate should outline scoping the weakness, engaging external auditors immediately, designing compensating controls, reperforming affected transactions, documenting the remediation, training staff, and preparing disclosure language if remediation cannot be completed before filing.',
            },
        ],
    },
    {
        'slug': 'finance-director',
        'title': 'Finance Director',
        'department': 'Finance',
        'seniority_level': 'lead',
        'description': 'The Finance Director leads a major finance function such as FP&A, corporate finance, or controllership, translating executive strategy into operational financial plans. They manage senior-level finance professionals and serve as the bridge between C-suite vision and day-to-day financial execution.',
        'responsibilities': [
            'Lead annual budgeting, quarterly forecasting, and long-range financial planning processes',
            'Manage and develop a team of finance managers and senior analysts',
            'Deliver financial insights and recommendations to senior leadership',
            'Oversee financial modeling for strategic initiatives, pricing decisions, and capital investments',
            'Ensure month-end and quarter-end close processes meet accuracy and timeliness standards',
            'Partner with business unit leaders to drive financial performance and accountability',
        ],
        'key_skills': [
            'Advanced financial modeling and scenario analysis',
            'Team leadership and talent development',
            'Executive-level financial presentation and storytelling',
            'Budgeting, forecasting, and variance analysis',
            'Business partnering and stakeholder management',
            'ERP and financial planning tool expertise',
        ],
        'assessment_slugs': ['finance', 'behavioral'],
        'questions': [
            {
                'question_text': 'Walk me through how you would build a rolling 12-month forecast model for a multi-product business with seasonal revenue patterns.',
                'category': 'technical',
                'difficulty': 'hard',
                'what_it_tests': 'Advanced forecasting methodology and ability to handle business complexity in financial models',
                'sample_answer_outline': 'A strong answer covers driver-based modeling by product line, seasonal adjustment factors, revenue pipeline integration, expense timing assumptions, monthly cadence updates, and variance tracking against both budget and prior forecast to measure forecast accuracy improvement.',
            },
            {
                'question_text': 'Describe a situation where you had to push back on a senior leader who wanted to present overly optimistic financial projections.',
                'category': 'behavioral',
                'difficulty': 'hard',
                'what_it_tests': 'Professional courage and ability to maintain analytical integrity under organizational pressure',
                'sample_answer_outline': 'Look for specific examples of using data to make the case, proposing probability-weighted scenarios instead of single-point estimates, escalating appropriately, and maintaining the relationship while holding firm on analytical standards.',
            },
            {
                'question_text': 'Your company is considering entering a new geographic market. The CEO asks for a financial feasibility analysis within two weeks. How do you scope and deliver this?',
                'category': 'situational',
                'difficulty': 'hard',
                'what_it_tests': 'Ability to deliver high-quality analysis under time pressure with incomplete information',
                'sample_answer_outline': 'The candidate should describe defining key assumptions upfront, identifying data sources, building a simplified P&L model with sensitivity analysis, benchmarking against comparable market entries, flagging key risks, and presenting with clear go/no-go criteria.',
            },
            {
                'question_text': 'How do you set expectations and develop career paths for finance team members who aspire to move into business leadership roles?',
                'category': 'leadership',
                'difficulty': 'medium',
                'what_it_tests': 'People development skills and ability to retain top finance talent through career growth',
                'sample_answer_outline': 'Look for individualized development plans, cross-functional project assignments, business partnering exposure, presentation coaching, mentorship pairing, and honest conversations about readiness gaps and timelines.',
            },
            {
                'question_text': 'How do you balance the need for financial rigor and controls with the desire for speed and agility in a fast-moving business?',
                'category': 'culture',
                'difficulty': 'medium',
                'what_it_tests': 'Ability to adapt finance function culture to match business pace without compromising integrity',
                'sample_answer_outline': 'A good answer discusses tiered approval frameworks based on materiality, pre-approved spending categories, automated controls that do not slow processes, and creating a partnership mindset where finance is seen as an enabler rather than a bottleneck.',
            },
            {
                'question_text': 'Midway through the fiscal year, actual revenue is tracking 20% below budget across all product lines. Walk me through how you would reforecast and what actions you would recommend.',
                'category': 'problem_solving',
                'difficulty': 'hard',
                'what_it_tests': 'Reforecasting methodology and ability to recommend decisive operational changes',
                'sample_answer_outline': 'The candidate should cover root-cause analysis of the shortfall, bottom-up reforecasting by product line, expense reduction scenarios with impact modeling, cash flow implications, board communication strategy, and a framework for monitoring recovery trajectory.',
            },
            {
                'question_text': 'What are the key differences between GAAP and IFRS revenue recognition standards, and how do they affect financial reporting for a SaaS business?',
                'category': 'technical',
                'difficulty': 'medium',
                'what_it_tests': 'Technical accounting knowledge relevant to modern business models',
                'sample_answer_outline': 'A strong answer discusses ASC 606 versus IFRS 15, the five-step revenue recognition framework, treatment of multi-element arrangements, contract modifications, and practical implications for subscription revenue timing and deferred revenue balances.',
            },
            {
                'question_text': 'Tell me about a time you identified a significant financial risk that others had overlooked. What did you do?',
                'category': 'behavioral',
                'difficulty': 'medium',
                'what_it_tests': 'Analytical vigilance and proactive risk identification',
                'sample_answer_outline': 'Look for specific examples showing analytical curiosity, the process of validating the finding, how they communicated the risk to stakeholders, the mitigation actions taken, and the ultimate outcome. The best answers show pattern recognition across financial data.',
            },
            {
                'question_text': 'Two of your direct reports are in conflict over resource allocation for their respective teams. How do you resolve this?',
                'category': 'situational',
                'difficulty': 'medium',
                'what_it_tests': 'Conflict resolution skills and ability to make fair allocation decisions',
                'sample_answer_outline': 'The candidate should describe hearing both sides individually, establishing objective criteria for prioritization, facilitating a data-driven discussion, making a transparent decision, and ensuring both leaders understand the rationale and feel heard.',
            },
            {
                'question_text': 'How do you ensure your finance team stays connected to the business outcomes their work supports, rather than operating in a silo?',
                'category': 'leadership',
                'difficulty': 'easy',
                'what_it_tests': 'Ability to create business context and purpose for finance team members',
                'sample_answer_outline': 'Look for practices like embedding analysts in business unit meetings, sharing customer and product stories, tying financial metrics to real-world impact, rotating team members across business partnering assignments, and celebrating wins tied to business outcomes.',
            },
            {
                'question_text': 'What does a healthy relationship between finance and the rest of the organization look like, and how do you cultivate it?',
                'category': 'culture',
                'difficulty': 'easy',
                'what_it_tests': 'Business partnering philosophy and cross-functional relationship building',
                'sample_answer_outline': 'A good answer describes finance as a trusted advisor rather than a gatekeeper, proactive insight delivery rather than reactive reporting, joint problem-solving, accessible communication style, and building credibility through consistent follow-through.',
            },
            {
                'question_text': 'Your ERP system migration has gone poorly: the month-end close is delayed by two weeks and there are data integrity issues. How do you manage through this?',
                'category': 'problem_solving',
                'difficulty': 'hard',
                'what_it_tests': 'Crisis management skills in a financial operations context',
                'sample_answer_outline': 'The candidate should describe triaging data integrity issues by materiality, establishing manual workarounds for critical processes, communicating timeline impacts to auditors and leadership, prioritizing reconciliation of high-risk accounts, and building a remediation plan with clear milestones.',
            },
        ],
    },
    {
        'slug': 'fpa-manager',
        'title': 'FP&A Manager',
        'department': 'Finance',
        'seniority_level': 'senior',
        'description': 'The FP&A Manager drives the financial planning, budgeting, and analytical processes that inform executive decision-making. They translate complex financial data into actionable insights and partner closely with business leaders to optimize performance and resource allocation.',
        'responsibilities': [
            'Own the annual budget process, monthly forecasting, and variance analysis',
            'Build and maintain financial models for revenue, cost, and profitability analysis',
            'Prepare board-level financial presentations and management reporting packages',
            'Partner with department heads to develop business cases for new initiatives',
            'Analyze key performance metrics and identify trends, risks, and opportunities',
            'Manage and mentor a team of financial analysts',
        ],
        'key_skills': [
            'Financial modeling and Excel/Google Sheets mastery',
            'Variance analysis and management reporting',
            'Business partnering and cross-functional communication',
            'FP&A software tools (Adaptive, Anaplan, or similar)',
            'Data visualization and financial storytelling',
            'Process improvement and automation mindset',
        ],
        'assessment_slugs': ['finance', 'behavioral'],
        'questions': [
            {
                'question_text': 'Walk me through how you would perform a revenue bridge analysis explaining the variance between actual and budgeted revenue for a quarter.',
                'category': 'technical',
                'difficulty': 'medium',
                'what_it_tests': 'Core FP&A analytical skills and ability to decompose financial variances',
                'sample_answer_outline': 'A strong answer breaks the variance into price, volume, mix, and foreign exchange components. The candidate should describe segmenting by product line, geography, or customer cohort, and explain how to present the waterfall chart to non-finance stakeholders.',
            },
            {
                'question_text': 'Describe a time when your financial analysis changed the direction of a business decision. What was the situation and what was the impact?',
                'category': 'behavioral',
                'difficulty': 'medium',
                'what_it_tests': 'Ability to influence business outcomes through financial insight',
                'sample_answer_outline': 'Look for a specific example where analytical rigor uncovered a non-obvious insight, how the candidate communicated the finding to decision-makers, the decision that changed as a result, and the measurable business impact that followed.',
            },
            {
                'question_text': 'The VP of Sales asks you to build a financial model for a new pricing strategy that bundles three products together. How do you approach this?',
                'category': 'situational',
                'difficulty': 'hard',
                'what_it_tests': 'Ability to model complex business scenarios and partner with revenue leaders',
                'sample_answer_outline': 'The candidate should discuss understanding current standalone pricing and margins, modeling cannibalization effects, building scenarios with different adoption rates, accounting for contract length and churn implications, and presenting a recommendation with sensitivity analysis on key assumptions.',
            },
            {
                'question_text': 'How do you coach a junior analyst who produces technically correct but insight-poor financial reports?',
                'category': 'leadership',
                'difficulty': 'medium',
                'what_it_tests': 'Mentoring approach and ability to develop analytical talent',
                'sample_answer_outline': 'Look for teaching the "so what" framework, having the analyst present findings verbally before writing reports, sharing examples of insight-rich analysis, providing real-time feedback on draft reports, and gradually increasing the complexity of assignments.',
            },
            {
                'question_text': 'How do you handle a situation where a business leader disagrees with your forecast and wants to override your numbers?',
                'category': 'culture',
                'difficulty': 'medium',
                'what_it_tests': 'Professional backbone and collaborative approach to forecast ownership disputes',
                'sample_answer_outline': 'A good answer describes seeking to understand the leader\'s perspective and data sources, presenting the assumptions behind the forecast transparently, agreeing on a method to reconcile the differences, and documenting the final agreed forecast with clear ownership.',
            },
            {
                'question_text': 'You discover that the monthly management reports have been overstating gross margin by 2 percentage points for the last three months due to a cost allocation error. What do you do?',
                'category': 'problem_solving',
                'difficulty': 'hard',
                'what_it_tests': 'Error remediation skills and judgment in handling reporting corrections',
                'sample_answer_outline': 'The candidate should describe quantifying the total impact, notifying their manager and the controller immediately, correcting the allocation methodology, restating the affected reports, communicating the correction to stakeholders with root cause and prevention measures, and implementing controls to prevent recurrence.',
            },
            {
                'question_text': 'Explain the difference between a direct and indirect method cash flow forecast, and when you would use each.',
                'category': 'technical',
                'difficulty': 'easy',
                'what_it_tests': 'Foundational cash flow forecasting knowledge',
                'sample_answer_outline': 'A strong answer explains that the direct method tracks actual receipts and disbursements (better for short-term, 13-week forecasts), while the indirect method starts from net income and adjusts for non-cash items (better for longer-term planning). The candidate should articulate use cases for each.',
            },
            {
                'question_text': 'Tell me about a time you had to simplify a complex financial concept for a non-financial audience. How did you approach it?',
                'category': 'behavioral',
                'difficulty': 'easy',
                'what_it_tests': 'Communication skills and ability to translate finance into business language',
                'sample_answer_outline': 'Look for use of analogies, visual aids, focusing on the "so what" rather than the methodology, checking for understanding, and adapting the level of detail to the audience. The best answers show empathy for the audience\'s perspective.',
            },
            {
                'question_text': 'Your annual budget is due in three weeks, but two major business unit leaders have not submitted their department budgets. What do you do?',
                'category': 'situational',
                'difficulty': 'medium',
                'what_it_tests': 'Project management skills and ability to drive cross-functional processes',
                'sample_answer_outline': 'The candidate should describe escalating diplomatically, offering hands-on support to help the leaders build their budgets, building placeholder estimates based on run-rate to keep the process moving, setting clear interim milestones, and communicating the risk of delays to the CFO.',
            },
            {
                'question_text': 'How do you prioritize your team\'s workload when you are asked to deliver an ad-hoc strategic analysis while also managing the routine monthly close and reporting cycle?',
                'category': 'leadership',
                'difficulty': 'easy',
                'what_it_tests': 'Workload management and ability to balance competing priorities for a team',
                'sample_answer_outline': 'Look for assessing urgency and impact, transparent communication with stakeholders about timelines, delegating routine tasks to capable team members, protecting the team from overcommitment, and potentially negotiating scope or timeline on the ad-hoc request.',
            },
            {
                'question_text': 'What role should FP&A play in shaping company strategy versus simply reporting on financial performance?',
                'category': 'culture',
                'difficulty': 'easy',
                'what_it_tests': 'Understanding of the strategic FP&A function versus traditional reporting',
                'sample_answer_outline': 'A good answer articulates FP&A as a strategic partner that provides forward-looking insights, challenges assumptions, models scenarios for strategic decisions, and helps leadership understand the financial implications of different paths, not just a team that produces backward-looking reports.',
            },
            {
                'question_text': 'The CEO wants a profitability analysis by customer segment, but your data systems do not cleanly allocate costs below the gross margin line. How do you approach this?',
                'category': 'problem_solving',
                'difficulty': 'medium',
                'what_it_tests': 'Resourcefulness in delivering analytical value despite data limitations',
                'sample_answer_outline': 'The candidate should describe identifying which costs can be directly attributed versus allocated, proposing a reasonable allocation methodology with clear assumptions, documenting limitations in the analysis, recommending system improvements for future accuracy, and delivering a directionally useful analysis rather than waiting for perfect data.',
            },
        ],
    },
    {
        'slug': 'financial-analyst',
        'title': 'Financial Analyst',
        'department': 'Finance',
        'seniority_level': 'mid',
        'description': 'The Financial Analyst supports the finance team by building models, analyzing performance data, and preparing reports that drive business decisions. They work closely with FP&A leadership and business partners to provide timely, accurate financial insights across the organization.',
        'responsibilities': [
            'Build and maintain financial models for budgeting, forecasting, and scenario analysis',
            'Prepare monthly variance analysis comparing actuals to budget and prior year',
            'Create data visualizations and dashboards for management reporting',
            'Support business partners with ad-hoc financial analysis and business cases',
            'Assist with the annual budget and quarterly forecast processes',
            'Reconcile financial data across systems and investigate discrepancies',
        ],
        'key_skills': [
            'Financial modeling in Excel and Google Sheets',
            'Data analysis and visualization tools (Tableau, Power BI, or similar)',
            'Accounting fundamentals and financial statement literacy',
            'Attention to detail and data accuracy',
            'Written and verbal communication of financial findings',
            'SQL or data query skills for self-service analytics',
        ],
        'assessment_slugs': ['finance', 'behavioral'],
        'questions': [
            {
                'question_text': 'How would you calculate and interpret the operating leverage of a business, and why does it matter for financial planning?',
                'category': 'technical',
                'difficulty': 'medium',
                'what_it_tests': 'Understanding of cost structure analysis and its implications for forecasting',
                'sample_answer_outline': 'A strong answer defines operating leverage as the ratio of fixed to variable costs, explains that high operating leverage means profits are more sensitive to revenue changes, and discusses how this affects budget sensitivity analysis and scenario planning.',
            },
            {
                'question_text': 'Tell me about a time when you found an error in a financial report before it was distributed. How did you catch it?',
                'category': 'behavioral',
                'difficulty': 'easy',
                'what_it_tests': 'Attention to detail and quality control habits in financial work',
                'sample_answer_outline': 'Look for specific validation routines the candidate uses (cross-checking totals, source-to-report reconciliation, reasonableness checks), the process for escalating the error, and any process improvements they implemented to prevent similar errors.',
            },
            {
                'question_text': 'A product manager asks you to quantify the financial impact of launching a new feature. You have limited historical data. How do you approach this?',
                'category': 'situational',
                'difficulty': 'medium',
                'what_it_tests': 'Analytical resourcefulness and ability to build estimates with incomplete information',
                'sample_answer_outline': 'The candidate should describe identifying proxy metrics or comparable feature launches, building a simple model with clearly stated assumptions, using sensitivity analysis to show a range of outcomes, collaborating with product to validate assumptions, and documenting what data would be needed to improve the estimate over time.',
            },
            {
                'question_text': 'If a more junior team member is struggling with a complex Excel model you built, how would you help them without simply doing the work for them?',
                'category': 'leadership',
                'difficulty': 'easy',
                'what_it_tests': 'Peer mentoring approach and patience in knowledge transfer',
                'sample_answer_outline': 'Look for walking through the model logic step by step, explaining the business context behind each section, providing documentation or a model map, letting them attempt fixes before intervening, and checking back to ensure understanding solidified.',
            },
            {
                'question_text': 'How do you stay motivated during repetitive month-end reporting cycles while maintaining accuracy?',
                'category': 'culture',
                'difficulty': 'easy',
                'what_it_tests': 'Work ethic, consistency, and attitude toward essential but routine finance work',
                'sample_answer_outline': 'A good answer discusses finding ways to improve the process each cycle, automating repetitive steps, understanding the downstream impact of accurate reporting, taking pride in reliability, and balancing routine work with higher-value analytical projects.',
            },
            {
                'question_text': 'You are comparing actuals to budget and notice that marketing spend is 40% over budget, but the marketing team says all expenses were pre-approved. How do you investigate?',
                'category': 'problem_solving',
                'difficulty': 'medium',
                'what_it_tests': 'Variance investigation methodology and cross-functional communication',
                'sample_answer_outline': 'The candidate should describe checking whether the variance is timing-related or permanent, reviewing the original budget assumptions versus actual activity levels, examining whether expenses were miscategorized, meeting with marketing to reconcile their records, and preparing a clear variance explanation for leadership.',
            },
            {
                'question_text': 'Explain the relationship between the three financial statements and how a $100 increase in accounts receivable flows through each one.',
                'category': 'technical',
                'difficulty': 'easy',
                'what_it_tests': 'Fundamental accounting knowledge and three-statement linkage understanding',
                'sample_answer_outline': 'A strong answer explains that the $100 AR increase reflects recognized revenue on the income statement, increases current assets on the balance sheet, and appears as a negative adjustment to cash from operations on the cash flow statement since the cash has not been collected yet.',
            },
            {
                'question_text': 'Describe a time when you received critical feedback on your analytical work. How did you respond?',
                'category': 'behavioral',
                'difficulty': 'easy',
                'what_it_tests': 'Receptiveness to feedback and growth mindset',
                'sample_answer_outline': 'Look for openness rather than defensiveness, specific steps taken to address the feedback, follow-up to ensure the issue was resolved, and evidence that the candidate incorporated the learning into subsequent work.',
            },
            {
                'question_text': 'You are asked to prepare an analysis for the CFO by end of day, but you also have month-end deliverables due. Both are marked urgent. What do you do?',
                'category': 'situational',
                'difficulty': 'medium',
                'what_it_tests': 'Prioritization skills and ability to manage competing deadlines',
                'sample_answer_outline': 'The candidate should describe assessing the true urgency and impact of each, communicating proactively with their manager about the conflict, proposing a realistic timeline for both, negotiating scope if needed, and delivering quality work rather than rushing both and producing errors.',
            },
            {
                'question_text': 'What tools or techniques do you use to ensure the financial models you build are error-free and auditable?',
                'category': 'technical',
                'difficulty': 'medium',
                'what_it_tests': 'Model discipline, quality assurance practices, and professional standards',
                'sample_answer_outline': 'Look for version control, consistent formatting, input/calculation/output separation, cell-level checks and balances, peer review processes, documentation of assumptions, named ranges, and stress-testing with extreme inputs to catch formula errors.',
            },
            {
                'question_text': 'How do you approach building a relationship with a business partner who views finance as a bottleneck rather than a resource?',
                'category': 'culture',
                'difficulty': 'medium',
                'what_it_tests': 'Interpersonal skills and ability to reposition finance as a value-adding partner',
                'sample_answer_outline': 'A good answer covers proactively sharing useful insights before being asked, understanding their business priorities, delivering on commitments reliably, simplifying financial information for their context, and gradually demonstrating the value of financial partnership through quick wins.',
            },
            {
                'question_text': 'You discover that the revenue forecast model has a circular reference that inflates projected revenue by 5%. The forecast was already shared with leadership. What do you do?',
                'category': 'problem_solving',
                'difficulty': 'hard',
                'what_it_tests': 'Error handling judgment and professional integrity when mistakes have downstream impacts',
                'sample_answer_outline': 'The candidate should describe fixing the circular reference immediately, quantifying the impact on the forecast, notifying their manager before reissuing, preparing a corrected version with a clear explanation, and implementing a model review checklist to prevent similar issues.',
            },
        ],
    },
    {
        'slug': 'controller',
        'title': 'Controller',
        'department': 'Finance',
        'seniority_level': 'senior',
        'description': 'The Controller is responsible for the integrity and accuracy of all financial reporting, accounting operations, and internal controls. They oversee the general ledger, month-end close process, and compliance with accounting standards, serving as the backbone of the organization\'s financial infrastructure.',
        'responsibilities': [
            'Oversee the month-end and year-end financial close processes to ensure timely and accurate reporting',
            'Maintain the general ledger and chart of accounts in compliance with GAAP or IFRS',
            'Design and enforce internal controls over financial reporting',
            'Manage the external audit process and relationship with auditors',
            'Ensure compliance with tax filing requirements and regulatory obligations',
            'Lead the accounting team and drive continuous improvement in financial operations',
        ],
        'key_skills': [
            'GAAP/IFRS accounting standards expertise',
            'Internal controls design and SOX compliance',
            'Financial close process management and optimization',
            'Audit management and regulatory compliance',
            'ERP system administration (NetSuite, SAP, or similar)',
            'Team leadership and process improvement',
        ],
        'assessment_slugs': ['finance', 'behavioral'],
        'questions': [
            {
                'question_text': 'Walk me through how you would implement ASC 842 lease accounting for a company with 200 leases that has never previously capitalized operating leases.',
                'category': 'technical',
                'difficulty': 'hard',
                'what_it_tests': 'Deep technical accounting knowledge and implementation planning ability',
                'sample_answer_outline': 'A strong answer covers lease inventory and data collection, classification of each lease as finance or operating, calculating right-of-use assets and lease liabilities, transition method selection, system and process changes required, disclosure preparation, and audit readiness documentation.',
            },
            {
                'question_text': 'Tell me about a time when an external auditor disagreed with your accounting treatment of a significant transaction. How did you handle it?',
                'category': 'behavioral',
                'difficulty': 'hard',
                'what_it_tests': 'Professional judgment and ability to defend technical accounting positions',
                'sample_answer_outline': 'Look for the candidate presenting their technical research and supporting documentation, engaging in constructive professional debate, seeking guidance from authoritative literature, being willing to revise their position if the auditor had a stronger argument, and maintaining a collaborative relationship throughout.',
            },
            {
                'question_text': 'Your company is acquiring a business and you need to determine the purchase price allocation. Walk me through your approach under ASC 805.',
                'category': 'situational',
                'difficulty': 'hard',
                'what_it_tests': 'Business combination accounting expertise and practical application of complex standards',
                'sample_answer_outline': 'The candidate should describe identifying and valuing acquired assets and assumed liabilities at fair value, recognizing identifiable intangible assets, calculating goodwill as the residual, engaging third-party valuation specialists, establishing measurement period procedures, and preparing required disclosures.',
            },
            {
                'question_text': 'How do you develop your accounting team to handle increasingly complex transactions as the company grows?',
                'category': 'leadership',
                'difficulty': 'medium',
                'what_it_tests': 'Talent development strategy and ability to scale an accounting function',
                'sample_answer_outline': 'Look for investing in continuing education, assigning complex transactions as learning opportunities with oversight, creating technical accounting memos as training exercises, building a knowledge base of past accounting decisions, and hiring for growth potential alongside technical skills.',
            },
            {
                'question_text': 'How do you maintain a culture of accuracy and thoroughness when there is constant pressure to close the books faster?',
                'category': 'culture',
                'difficulty': 'medium',
                'what_it_tests': 'Ability to protect financial integrity while improving operational efficiency',
                'sample_answer_outline': 'A good answer discusses automating low-risk tasks to free time for high-risk areas, setting materiality thresholds for investigation, pre-close procedures that front-load work before period end, quality checkpoints embedded in the process, and celebrating both speed and accuracy improvements.',
            },
            {
                'question_text': 'During the annual audit, the auditors identify a significant deficiency in your accounts payable process. You believe the finding is overstated. How do you respond?',
                'category': 'problem_solving',
                'difficulty': 'hard',
                'what_it_tests': 'Audit management skills and ability to negotiate findings while maintaining professional relationships',
                'sample_answer_outline': 'The candidate should describe gathering evidence of compensating controls, presenting a documented rebuttal with specific examples, engaging in professional dialogue about the severity assessment, and being prepared to accept the finding if the evidence supports it, along with a remediation plan.',
            },
            {
                'question_text': 'Explain the five-step revenue recognition model under ASC 606 and give an example of how it applies to a software company with multi-element arrangements.',
                'category': 'technical',
                'difficulty': 'medium',
                'what_it_tests': 'Revenue recognition expertise in a common complex scenario',
                'sample_answer_outline': 'A strong answer walks through: identify the contract, identify performance obligations (license, implementation, support), determine the transaction price, allocate to each obligation using standalone selling prices, and recognize revenue as each obligation is satisfied (point-in-time for license, over time for support).',
            },
            {
                'question_text': 'Describe a process improvement you implemented in a previous accounting close process. What was the impact?',
                'category': 'behavioral',
                'difficulty': 'medium',
                'what_it_tests': 'Continuous improvement mindset and ability to drive operational change',
                'sample_answer_outline': 'Look for identification of a specific bottleneck, the solution implemented (automation, resequencing, elimination of redundant steps), measurable results in close timeline or error reduction, and how the candidate secured buy-in from the team for the change.',
            },
            {
                'question_text': 'Your CEO asks you to recognize revenue on a large deal that was verbally agreed but not yet signed by quarter-end. What do you do?',
                'category': 'situational',
                'difficulty': 'hard',
                'what_it_tests': 'Ethical backbone and willingness to uphold accounting standards under executive pressure',
                'sample_answer_outline': 'The candidate should firmly explain that ASC 606 requires an executed contract to identify a contract, describe the criteria that must be met, propose alternatives such as disclosing the deal in the pipeline or earnings call commentary, and document the conversation for the record.',
            },
            {
                'question_text': 'How do you build trust with a new CFO who may have a different style or philosophy about the controllership function?',
                'category': 'leadership',
                'difficulty': 'easy',
                'what_it_tests': 'Adaptability and ability to build relationships with new leadership',
                'sample_answer_outline': 'Look for proactively understanding the CFO\'s priorities and communication preferences, delivering early quick wins to build credibility, being transparent about current strengths and gaps, proposing improvements aligned with their vision, and establishing regular check-ins.',
            },
            {
                'question_text': 'What practices do you follow to ensure your accounting team maintains independence and objectivity, especially when business leaders pressure them on timing or classification of expenses?',
                'category': 'culture',
                'difficulty': 'medium',
                'what_it_tests': 'Commitment to accounting ethics and team protection from inappropriate pressure',
                'sample_answer_outline': 'A good answer covers establishing clear policies, training the team on ethical standards, creating safe channels for reporting pressure, documenting all judgment calls with technical support, and serving as a shield between the team and inappropriate requests.',
            },
            {
                'question_text': 'You take over as controller and discover that the previous team had been capitalizing costs that should have been expensed under GAAP. The cumulative overstatement of assets is material. What is your action plan?',
                'category': 'problem_solving',
                'difficulty': 'hard',
                'what_it_tests': 'Ability to handle a material accounting error with integrity and systematic remediation',
                'sample_answer_outline': 'The candidate should describe quantifying the cumulative impact, consulting with external auditors on restatement versus correction approach, evaluating disclosure requirements, notifying the CFO and audit committee, preparing restated financial statements if necessary, implementing controls to prevent recurrence, and assessing whether the error was intentional.',
            },
        ],
    },
]