HR_ROLES = [
    {
        'slug': 'chro',
        'title': 'Chief Human Resources Officer',
        'department': 'HR',
        'seniority_level': 'executive',
        'description': 'The CHRO serves as the top human resources executive, responsible for developing and executing the people strategy in support of the overall business plan. This role provides strategic leadership by articulating HR needs and plans to the executive management team, board of directors, and shareholders, while driving organizational culture, talent management, and workforce planning at the enterprise level.',
        'responsibilities': [
            'Define and execute the overall people strategy aligned with business objectives',
            'Advise the CEO and board on organizational design, succession planning, and workforce trends',
            'Oversee total rewards strategy including compensation, benefits, and equity programs',
            'Drive diversity, equity, inclusion, and belonging initiatives across the organization',
            'Lead HR digital transformation and people analytics capabilities',
            'Manage employment risk, compliance, and labor relations at the enterprise level',
        ],
        'key_skills': [
            'Executive leadership and C-suite collaboration',
            'Strategic workforce planning and organizational design',
            'Change management at scale',
            'People analytics and data-driven decision making',
            'Employment law and regulatory compliance',
            'Mergers, acquisitions, and integration planning',
        ],
        'assessment_slugs': ['hr', 'behavioral'],
        'questions': [
            {
                'question_text': 'How would you design a three-year people strategy for a company that is pivoting from a product-led to a platform-led business model?',
                'category': 'technical',
                'difficulty': 'hard',
                'what_it_tests': 'Ability to align HR strategy with fundamental business model transformation',
                'sample_answer_outline': 'A strong answer addresses workforce capability assessment against the new model, reskilling roadmaps, changes to organizational structure from product silos to cross-functional platform teams, and revised talent acquisition profiles. The candidate should articulate concrete milestones and metrics tied to business outcomes rather than purely HR activity metrics.',
            },
            {
                'question_text': 'Describe a time when you had to fundamentally reshape an organization\'s culture. What was the catalyst, what approach did you take, and how did you measure success?',
                'category': 'behavioral',
                'difficulty': 'hard',
                'what_it_tests': 'Experience leading large-scale culture transformation with measurable outcomes',
                'sample_answer_outline': 'The candidate should describe the business driver behind the culture shift, the diagnostic process used, how they engaged leadership as culture carriers, specific interventions deployed, and quantitative and qualitative metrics tracked over time. Look for evidence of sustained change rather than one-off initiatives.',
            },
            {
                'question_text': 'Your CEO wants to reduce headcount by 20 percent within 90 days while maintaining morale and retaining top performers. Walk me through your approach.',
                'category': 'situational',
                'difficulty': 'hard',
                'what_it_tests': 'Crisis management, ethical leadership, and balancing business needs with employee wellbeing',
                'sample_answer_outline': 'The response should cover workforce segmentation to identify critical talent, transparent communication strategy, legal and compliance review across jurisdictions, severance and outplacement design, manager enablement for difficult conversations, and a retention plan for remaining employees. The candidate should also address the ethical dimension and push back constructively on timeline if warranted.',
            },
            {
                'question_text': 'How do you ensure the board of directors receives meaningful reporting on human capital risks and opportunities rather than vanity metrics?',
                'category': 'leadership',
                'difficulty': 'hard',
                'what_it_tests': 'Board-level communication skills and understanding of human capital as a strategic asset',
                'sample_answer_outline': 'A strong answer includes translating people data into financial and operational impact language, using leading indicators rather than lagging ones, connecting workforce metrics to enterprise risk frameworks, and providing scenario modeling. The candidate should give examples of specific metrics they have presented to boards and how those drove decisions.',
            },
            {
                'question_text': 'What frameworks do you use to evaluate whether your organization\'s total rewards philosophy is competitive and equitable, and how often should it be revisited?',
                'category': 'technical',
                'difficulty': 'medium',
                'what_it_tests': 'Depth of knowledge in compensation strategy and pay equity practices',
                'sample_answer_outline': 'The candidate should reference market benchmarking methodologies, pay equity audit approaches, total rewards segmentation by employee persona, and the cadence of review tied to business cycles and market shifts. They should demonstrate understanding of both external competitiveness and internal equity dimensions.',
            },
            {
                'question_text': 'Tell me about a time when you disagreed with the CEO on a significant people decision. How did you handle it and what was the outcome?',
                'category': 'behavioral',
                'difficulty': 'medium',
                'what_it_tests': 'Executive presence, courage of conviction, and ability to influence without authority',
                'sample_answer_outline': 'Look for a specific example where the candidate presented a data-backed alternative, managed the relationship respectfully, and either influenced the decision or committed to the chosen path after being heard. The answer should demonstrate both conviction and organizational maturity.',
            },
            {
                'question_text': 'You discover that a high-performing senior executive has been creating a toxic environment in their division, but their business results are exceptional. How do you handle this?',
                'category': 'situational',
                'difficulty': 'hard',
                'what_it_tests': 'Values-driven decision making and willingness to address difficult leadership issues',
                'sample_answer_outline': 'The response should include investigation and documentation, direct conversation with the executive, coaching or performance improvement expectations with clear timelines, escalation to the CEO with evidence, and willingness to recommend termination if behavior does not change. The candidate should articulate why tolerating toxicity undermines long-term business performance.',
            },
            {
                'question_text': 'How do you build a culture of psychological safety across a global organization with vastly different cultural norms?',
                'category': 'culture',
                'difficulty': 'hard',
                'what_it_tests': 'Cultural intelligence and ability to implement universal values through locally relevant practices',
                'sample_answer_outline': 'A strong answer acknowledges that psychological safety manifests differently across cultures, describes adapting programs to local contexts while maintaining core principles, leveraging local HR leaders as cultural translators, and measuring safety through multiple channels including anonymous feedback, attrition patterns, and speak-up rates.',
            },
            {
                'question_text': 'Your company is acquiring a competitor that is half your size with a completely different culture. How do you approach the people integration?',
                'category': 'problem_solving',
                'difficulty': 'hard',
                'what_it_tests': 'M&A integration expertise and structured approach to complex organizational challenges',
                'sample_answer_outline': 'The candidate should outline a phased integration plan covering cultural assessment and compatibility mapping, Day One readiness, leadership selection and organizational design, harmonization of policies, benefits, and systems, retention strategies for critical talent, and communication cadence. They should acknowledge that culture integration takes years, not months.',
            },
            {
                'question_text': 'What is your perspective on the role of AI and automation in HR, and where do you see the greatest risks and opportunities?',
                'category': 'technical',
                'difficulty': 'medium',
                'what_it_tests': 'Forward-thinking perspective on HR technology and awareness of ethical implications',
                'sample_answer_outline': 'The response should cover specific use cases like talent matching, attrition prediction, and benefits optimization, while addressing bias in algorithms, data privacy, the importance of human oversight in employment decisions, and change management for HR teams adopting new technology. The candidate should demonstrate they are neither a blind adopter nor a Luddite.',
            },
            {
                'question_text': 'How do you personally stay connected to the employee experience when you are several layers removed from the front line?',
                'category': 'culture',
                'difficulty': 'medium',
                'what_it_tests': 'Self-awareness and commitment to staying grounded as a senior executive',
                'sample_answer_outline': 'Look for concrete practices such as skip-level meetings, site visits, participation in onboarding, reading unfiltered survey comments, reverse mentoring programs, and maintaining an open-door practice. The candidate should demonstrate genuine curiosity about employee experience rather than performative gestures.',
            },
            {
                'question_text': 'How do you determine the right HR operating model for an organization, and what signals tell you the current model is not working?',
                'category': 'problem_solving',
                'difficulty': 'medium',
                'what_it_tests': 'Understanding of HR operating models and diagnostic capability',
                'sample_answer_outline': 'The candidate should reference common models such as Ulrich, federated, and shared services, explain how business size, complexity, and maturity influence the choice, and identify warning signs like slow decision making, duplicated work, poor business partner relationships, and declining HR NPS. They should demonstrate they do not default to one model but rather diagnose and adapt.',
            },
        ],
    },
    {
        'slug': 'hr-director',
        'title': 'HR Director',
        'department': 'HR',
        'seniority_level': 'lead',
        'description': 'The HR Director leads a major HR function or supports a large business unit, translating enterprise people strategy into operational plans and managing a team of HR professionals. This role bridges strategic intent with day-to-day execution, ensuring HR programs are delivered effectively while maintaining compliance and driving continuous improvement across the employee lifecycle.',
        'responsibilities': [
            'Lead a team of HR managers and specialists to deliver people programs for assigned business units',
            'Partner with senior business leaders to translate strategy into workforce plans',
            'Oversee employee relations, performance management, and talent review processes',
            'Manage HR budgets and vendor relationships for assigned functional areas',
            'Ensure compliance with federal, state, and local employment regulations',
            'Drive continuous improvement in HR service delivery and operational efficiency',
        ],
        'key_skills': [
            'HR program design and implementation',
            'Team leadership and talent development',
            'Business acumen and financial literacy',
            'Employee relations and conflict resolution',
            'Project management and process optimization',
            'Data analysis and HR reporting',
        ],
        'assessment_slugs': ['hr', 'behavioral'],
        'questions': [
            {
                'question_text': 'How do you structure the annual talent review and succession planning process for a business unit of 500 or more employees?',
                'category': 'technical',
                'difficulty': 'hard',
                'what_it_tests': 'Ability to design and execute enterprise talent management processes at scale',
                'sample_answer_outline': 'The candidate should describe the full cycle including pre-work and calibration session design, the nine-box or alternative assessment framework, how they facilitate calibration to reduce bias, succession slate development, and how outcomes connect to development plans, promotions, and retention actions. They should address common pitfalls like recency bias and manager avoidance.',
            },
            {
                'question_text': 'Describe a time when you had to manage a significant organizational restructuring. How did you approach communication, timeline, and stakeholder management?',
                'category': 'behavioral',
                'difficulty': 'hard',
                'what_it_tests': 'Experience managing complex organizational change with multiple stakeholders',
                'sample_answer_outline': 'Look for a structured approach covering business case understanding, legal review, communication strategy for affected and retained employees, manager preparation, timeline management, and post-restructure stabilization. The candidate should demonstrate empathy alongside operational rigor.',
            },
            {
                'question_text': 'A senior manager on your business unit leadership team consistently circumvents HR policies, approving off-cycle raises and making exceptions for favored employees. How do you address this?',
                'category': 'situational',
                'difficulty': 'hard',
                'what_it_tests': 'Courage to hold leaders accountable while maintaining productive business partnerships',
                'sample_answer_outline': 'The response should include gathering data on the pattern and its impact on equity and morale, having a direct conversation grounded in business impact rather than policy for policy sake, escalating to the leader\'s manager if behavior continues, and implementing process guardrails. The candidate should balance firmness with relationship preservation.',
            },
            {
                'question_text': 'How do you develop and coach HR business partners on your team who are strong operationally but struggle with strategic thinking?',
                'category': 'leadership',
                'difficulty': 'medium',
                'what_it_tests': 'Ability to develop team members and elevate HR capability',
                'sample_answer_outline': 'A strong answer includes specific development techniques such as stretch assignments, exposure to business strategy meetings, coached preparation before leadership discussions, and frameworks for connecting HR activity to business outcomes. The candidate should demonstrate patience and a structured approach to capability building.',
            },
            {
                'question_text': 'Walk me through how you would design an employee engagement strategy for a business unit experiencing 30 percent annual turnover.',
                'category': 'problem_solving',
                'difficulty': 'hard',
                'what_it_tests': 'Diagnostic approach to retention problems and ability to design targeted interventions',
                'sample_answer_outline': 'The candidate should start with root cause analysis using exit interviews, stay interviews, engagement survey data, and turnover segmentation by tenure, level, and performance. The strategy should include quick wins and structural changes, with clear accountability and measurement. They should resist jumping to solutions before understanding the problem.',
            },
            {
                'question_text': 'How do you build a culture of accountability without creating a fear-based environment?',
                'category': 'culture',
                'difficulty': 'medium',
                'what_it_tests': 'Understanding of healthy performance culture and practical approaches to building it',
                'sample_answer_outline': 'Look for discussion of clear expectations, regular feedback cadences, separating accountability for outcomes from blame for mistakes, celebrating learning from failure, and modeling accountability as a leader. The candidate should articulate how transparency and psychological safety coexist with high standards.',
            },
            {
                'question_text': 'Explain how you use HR data and analytics to inform your recommendations to business leaders. Give a specific example.',
                'category': 'technical',
                'difficulty': 'medium',
                'what_it_tests': 'Analytical capability and ability to translate data into actionable business insights',
                'sample_answer_outline': 'The candidate should describe a specific situation where they used data such as turnover trends, engagement scores, compensation benchmarks, or time-to-fill metrics to build a business case and influence a decision. They should demonstrate comfort with data while also acknowledging its limitations.',
            },
            {
                'question_text': 'Tell me about a time when an employee relations investigation revealed a systemic issue rather than an isolated incident. What did you do?',
                'category': 'behavioral',
                'difficulty': 'medium',
                'what_it_tests': 'Ability to see patterns and move from reactive to proactive employee relations',
                'sample_answer_outline': 'The response should describe the initial investigation, how the broader pattern was identified, the systemic intervention designed, how it was communicated to leadership, and the outcome measured over time. The candidate should demonstrate both thoroughness in investigation and strategic thinking in response.',
            },
            {
                'question_text': 'You are rolling out a new performance management system and managers are resisting the change. How do you drive adoption?',
                'category': 'situational',
                'difficulty': 'medium',
                'what_it_tests': 'Change management skills and ability to drive adoption of HR programs',
                'sample_answer_outline': 'A strong answer covers understanding the root causes of resistance, involving managers in the design process, providing training and ongoing support, using champions and early adopters, setting clear expectations from senior leadership, and measuring adoption with consequences for non-compliance. The candidate should balance empathy for managers with firmness on expectations.',
            },
            {
                'question_text': 'What is the difference between employee engagement, employee experience, and employee satisfaction, and why does the distinction matter for program design?',
                'category': 'technical',
                'difficulty': 'easy',
                'what_it_tests': 'Conceptual clarity on foundational HR constructs',
                'sample_answer_outline': 'The candidate should clearly distinguish satisfaction as contentment with conditions, engagement as emotional commitment and discretionary effort, and experience as the holistic journey across all touchpoints. They should explain how conflating these leads to misguided interventions, such as adding perks to solve engagement problems that stem from poor management.',
            },
            {
                'question_text': 'How do you ensure your HR team maintains confidentiality while still being approachable and trusted by employees?',
                'category': 'culture',
                'difficulty': 'easy',
                'what_it_tests': 'Understanding of the trust dynamic inherent in HR roles',
                'sample_answer_outline': 'Look for practical approaches such as being transparent about what can and cannot be kept confidential upfront, training the team on information handling, creating clear escalation protocols, and building trust through consistent behavior over time. The candidate should acknowledge the tension rather than oversimplifying it.',
            },
            {
                'question_text': 'How do you prioritize competing HR initiatives when you have limited budget and team capacity?',
                'category': 'problem_solving',
                'difficulty': 'easy',
                'what_it_tests': 'Prioritization skills and resource management',
                'sample_answer_outline': 'The candidate should describe a framework for evaluating impact versus effort, aligning initiatives to business priorities, consulting with stakeholders, and making transparent trade-off decisions. They should demonstrate comfort saying no or not now and communicating rationale clearly.',
            },
        ],
    },
    {
        'slug': 'talent-acquisition-lead',
        'title': 'Talent Acquisition Lead',
        'department': 'HR',
        'seniority_level': 'senior',
        'description': 'The Talent Acquisition Lead owns the end-to-end recruiting strategy and operations for the organization or a major business segment, managing a team of recruiters and sourcers. This role is responsible for building scalable hiring processes, optimizing candidate experience, developing employer branding, and ensuring the organization attracts and selects top talent in competitive markets.',
        'responsibilities': [
            'Develop and execute talent acquisition strategy aligned with workforce planning needs',
            'Manage and mentor a team of recruiters and sourcers across multiple hiring pipelines',
            'Design and optimize the end-to-end recruitment process for efficiency and candidate experience',
            'Build and maintain employer brand presence across relevant channels and platforms',
            'Establish and track recruiting metrics including time-to-fill, quality of hire, and cost-per-hire',
            'Manage relationships with external recruiting agencies, job boards, and technology vendors',
        ],
        'key_skills': [
            'Full-cycle recruiting strategy and execution',
            'Sourcing techniques and talent market intelligence',
            'Employer branding and recruitment marketing',
            'Applicant tracking systems and recruiting technology',
            'Interviewing methodology and assessment design',
            'Diversity recruiting and inclusive hiring practices',
        ],
        'assessment_slugs': ['hr', 'behavioral'],
        'questions': [
            {
                'question_text': 'How would you redesign a hiring process that currently takes 45 days on average and has a 40 percent offer decline rate?',
                'category': 'problem_solving',
                'difficulty': 'hard',
                'what_it_tests': 'Ability to diagnose and fix broken recruiting processes using data and first principles',
                'sample_answer_outline': 'The candidate should approach this diagnostically, examining where time is lost in the funnel, why candidates are declining through declined offer analysis, whether the process is screening effectively or just slowly, and what the competitive landscape looks like. Solutions should address root causes such as approval bottlenecks, poor interview scheduling, uncompetitive offers, or weak candidate engagement rather than just speeding up a broken process.',
            },
            {
                'question_text': 'Describe your approach to building a diverse talent pipeline for a role or function where the available talent pool is historically homogeneous.',
                'category': 'technical',
                'difficulty': 'hard',
                'what_it_tests': 'Strategic thinking about diversity recruiting beyond surface-level tactics',
                'sample_answer_outline': 'A strong answer goes beyond posting on diversity job boards to include expanding sourcing channels, partnering with professional organizations and educational institutions, examining and removing biased job requirements, training hiring managers on inclusive interviewing, using structured interviews, and taking a long-term pipeline building view rather than expecting immediate results.',
            },
            {
                'question_text': 'Tell me about a time when a hiring manager insisted on a candidate you believed was a poor fit. How did you handle the situation?',
                'category': 'behavioral',
                'difficulty': 'medium',
                'what_it_tests': 'Ability to provide consultative pushback while respecting hiring manager ownership',
                'sample_answer_outline': 'The candidate should describe how they presented their concerns with specific evidence from the interview process, the data or observations they used to support their position, how they balanced their advisory role with the hiring manager\'s decision authority, and what the outcome was. Look for professional courage paired with respect for the partnership.',
            },
            {
                'question_text': 'Your company needs to hire 50 engineers in the next quarter, but your team of three recruiters is already at capacity. What is your plan?',
                'category': 'situational',
                'difficulty': 'hard',
                'what_it_tests': 'Resource planning, prioritization, and ability to scale recruiting operations under pressure',
                'sample_answer_outline': 'The response should cover immediate triage of current workload, business case for temporary resources such as contract recruiters or RPO, process optimization to increase throughput, hiring manager enablement for self-service sourcing, referral program activation, and realistic expectation setting with leadership on trade-offs between speed, quality, and cost.',
            },
            {
                'question_text': 'How do you measure quality of hire, and why is it one of the hardest recruiting metrics to get right?',
                'category': 'technical',
                'difficulty': 'medium',
                'what_it_tests': 'Analytical rigor and understanding of recruiting metrics beyond basic throughput measures',
                'sample_answer_outline': 'The candidate should describe multiple proxy measures such as new hire performance ratings, hiring manager satisfaction, time to productivity, retention at 12 months, and promotion rates. They should articulate why quality of hire is difficult due to attribution challenges, time lag, subjective inputs, and the need for cross-functional data integration.',
            },
            {
                'question_text': 'How do you coach a recruiter on your team who is great at sourcing but struggles with candidate closing and offer negotiation?',
                'category': 'leadership',
                'difficulty': 'medium',
                'what_it_tests': 'Team development skills and ability to coach specific recruiting competencies',
                'sample_answer_outline': 'Look for a structured coaching approach that includes diagnosing the specific gap through call shadowing or offer analysis, role-playing negotiation scenarios, teaching the candidate to build relationships and understand candidate motivations throughout the process, and setting measurable improvement goals. The candidate should recognize that closing is a skill that can be developed, not just a personality trait.',
            },
            {
                'question_text': 'A candidate who declined your offer six months ago reaches out saying they are now interested. The role has been filled. How do you handle this interaction?',
                'category': 'situational',
                'difficulty': 'easy',
                'what_it_tests': 'Candidate relationship management and long-term pipeline thinking',
                'sample_answer_outline': 'The candidate should describe maintaining a warm relationship, exploring other open roles that might fit, adding the candidate to a talent community or CRM for future opportunities, and providing a genuine and timely response. This tests whether the recruiter thinks transactionally or relationally about talent.',
            },
            {
                'question_text': 'What is your philosophy on employer branding, and how do you measure its impact on recruiting outcomes?',
                'category': 'technical',
                'difficulty': 'medium',
                'what_it_tests': 'Understanding of employer brand as a strategic recruiting lever',
                'sample_answer_outline': 'A strong answer connects employer brand to measurable outcomes like application volume, inbound versus outbound sourcing mix, offer acceptance rates, and Glassdoor or LinkedIn talent brand metrics. The candidate should describe specific tactics they have used and how they partnered with marketing, and acknowledge that employer brand is built through employee experience, not just marketing campaigns.',
            },
            {
                'question_text': 'Tell me about a time when you had to ramp up recruiting in a completely new market or geography where you had no existing presence.',
                'category': 'behavioral',
                'difficulty': 'hard',
                'what_it_tests': 'Resourcefulness and ability to build recruiting infrastructure from scratch',
                'sample_answer_outline': 'The candidate should describe market research on talent availability and compensation norms, channel strategy development, potential use of local recruiting partners, compliance considerations, cultural adaptation of the employer value proposition, and how they built credibility in an unfamiliar market. Look for a systematic approach combined with creative problem solving.',
            },
            {
                'question_text': 'How do you create an inclusive interview experience for candidates with disabilities without making assumptions about their needs?',
                'category': 'culture',
                'difficulty': 'medium',
                'what_it_tests': 'Commitment to accessible hiring practices and cultural sensitivity',
                'sample_answer_outline': 'The response should include proactively communicating accommodation availability at every stage, training interviewers on inclusive practices, ensuring physical and digital accessibility of the process, asking all candidates about accommodation needs as a standard practice rather than singling anyone out, and regularly auditing the process for barriers.',
            },
            {
                'question_text': 'What are structured interviews and why do you believe they are or are not more effective than unstructured interviews?',
                'category': 'technical',
                'difficulty': 'easy',
                'what_it_tests': 'Foundational knowledge of interview methodology and evidence-based hiring',
                'sample_answer_outline': 'The candidate should define structured interviews as using consistent questions, predetermined evaluation criteria, and standardized scoring. They should reference research showing higher predictive validity, reduced bias, and better legal defensibility. A nuanced answer acknowledges that pure structure can miss important signals and discusses how to balance structure with enough flexibility for authentic conversation.',
            },
            {
                'question_text': 'How do you ensure your recruiting team provides a consistently positive candidate experience even when rejecting applicants?',
                'category': 'culture',
                'difficulty': 'easy',
                'what_it_tests': 'Commitment to candidate experience and brand stewardship even in rejection',
                'sample_answer_outline': 'Look for specific practices such as timely communication at every stage, personalized rejection messages for candidates who interviewed, constructive feedback where appropriate and legally permissible, respectful language, and internal accountability mechanisms like candidate experience surveys. The candidate should understand that rejected candidates are future customers, referral sources, and potential re-applicants.',
            },
        ],
    },
    {
        'slug': 'hr-business-partner',
        'title': 'HR Business Partner',
        'department': 'HR',
        'seniority_level': 'mid',
        'description': 'The HR Business Partner serves as a strategic advisor and hands-on resource to business leaders within an assigned client group, aligning HR practices with business objectives. This role requires balancing strategic consultation with operational HR delivery, acting as the primary point of contact for managers and employees on all people-related matters including performance, development, employee relations, and organizational effectiveness.',
        'responsibilities': [
            'Partner with business leaders to understand objectives and develop supporting people strategies',
            'Coach managers on performance management, employee development, and team effectiveness',
            'Manage employee relations cases including investigations, conflict resolution, and grievances',
            'Support organizational design and change management initiatives within client groups',
            'Analyze workforce data to identify trends and recommend proactive interventions',
            'Facilitate talent review, succession planning, and workforce planning within assigned business units',
        ],
        'key_skills': [
            'Strategic HR consulting and business partnership',
            'Employee relations and workplace investigations',
            'Performance management coaching',
            'Organizational development and change management',
            'HR policy interpretation and application',
            'Stakeholder management and influencing skills',
        ],
        'assessment_slugs': ['hr', 'behavioral'],
        'questions': [
            {
                'question_text': 'How do you approach building credibility with a new business leader who views HR as administrative overhead rather than a strategic partner?',
                'category': 'behavioral',
                'difficulty': 'medium',
                'what_it_tests': 'Ability to establish strategic partnerships and overcome skepticism about HR value',
                'sample_answer_outline': 'The candidate should describe listening first to understand the leader\'s business priorities and pain points, delivering quick wins that demonstrate business impact, speaking in business language rather than HR jargon, bringing data-driven insights proactively, and gradually expanding the relationship from transactional to strategic. Look for patience combined with intentionality.',
            },
            {
                'question_text': 'Walk me through how you would conduct a workplace investigation into allegations of harassment involving a senior leader.',
                'category': 'technical',
                'difficulty': 'hard',
                'what_it_tests': 'Investigation methodology, legal awareness, and ability to handle sensitive situations involving power dynamics',
                'sample_answer_outline': 'A strong answer covers immediate safety assessment, documentation and chain of custody, interview planning starting with the complainant, neutral fact-finding with the respondent and witnesses, maintaining confidentiality, potential interim measures, partnership with legal counsel, written findings and recommendations, and follow-up. The candidate should address the added complexity of seniority and power dynamics without allowing it to compromise the investigation.',
            },
            {
                'question_text': 'A manager comes to you wanting to terminate an employee for poor performance, but there is no documentation in the file. What do you do?',
                'category': 'situational',
                'difficulty': 'medium',
                'what_it_tests': 'Practical employee relations judgment and ability to coach managers through proper process',
                'sample_answer_outline': 'The candidate should describe coaching the manager to document specific performance gaps, implementing a performance improvement plan with clear expectations and timelines, ensuring the employee has support and resources to improve, maintaining regular check-ins, and only proceeding to termination if improvement does not occur. They should balance protecting the organization legally with fairness to the employee.',
            },
            {
                'question_text': 'How do you handle a situation where two peer managers in your client group are in open conflict and it is affecting their teams\' collaboration?',
                'category': 'problem_solving',
                'difficulty': 'medium',
                'what_it_tests': 'Conflict resolution skills and ability to address interpersonal dynamics at the management level',
                'sample_answer_outline': 'The response should include meeting individually with each manager to understand perspectives, identifying root causes which may be structural or personal, facilitating a mediated conversation focused on shared goals and specific behaviors, establishing agreements and follow-up mechanisms, and escalating to their shared leader if resolution is not achieved. The candidate should demonstrate neutrality and focus on business impact.',
            },
            {
                'question_text': 'Describe a time when you used workforce data to identify a problem that business leaders had not yet recognized.',
                'category': 'behavioral',
                'difficulty': 'hard',
                'what_it_tests': 'Proactive use of analytics and ability to surface insights that drive action',
                'sample_answer_outline': 'Look for a specific example where the candidate identified a trend such as rising attrition in a specific segment, declining engagement scores in a growing team, or demographic imbalances in promotions, how they packaged the insight for leadership, the recommendation made, and the business outcome. The answer should demonstrate analytical curiosity and the courage to raise uncomfortable findings.',
            },
            {
                'question_text': 'How do you balance being an advocate for employees with your role as a representative of the organization?',
                'category': 'culture',
                'difficulty': 'hard',
                'what_it_tests': 'Understanding of the dual role of HR and ethical navigation of competing interests',
                'sample_answer_outline': 'A strong answer acknowledges the tension honestly, describes how advocating for fair treatment of employees ultimately serves the organization, explains how they raise employee concerns through appropriate channels with data and business impact framing, and identifies the rare situations where they would escalate or push back strongly. The candidate should reject the false choice of picking one side.',
            },
            {
                'question_text': 'Your client group is going through a rapid growth phase, adding 40 percent headcount in a year. What HR risks do you anticipate and how do you prepare?',
                'category': 'situational',
                'difficulty': 'hard',
                'what_it_tests': 'Strategic foresight and ability to anticipate people challenges during growth',
                'sample_answer_outline': 'The candidate should identify risks including culture dilution, manager span of control expansion, onboarding quality degradation, new hire integration challenges, potential equity compression, and team dynamic disruption. Preparation should include proactive organizational design discussions, manager capability building, onboarding enhancement, pulse surveys, and regular check-ins with new hires and their managers.',
            },
            {
                'question_text': 'How do you coach a manager who gives all their direct reports the same performance rating because they want to avoid difficult conversations?',
                'category': 'leadership',
                'difficulty': 'medium',
                'what_it_tests': 'Coaching ability and capacity to improve manager effectiveness in performance management',
                'sample_answer_outline': 'The response should include helping the manager understand the negative impact of rating compression on top performers and team development, practicing specific feedback delivery, providing frameworks for differentiating performance, role-playing difficult conversations, and following up to ensure behavior change. The candidate should demonstrate empathy for the manager\'s discomfort while being clear about expectations.',
            },
            {
                'question_text': 'What is your process for determining whether a performance issue is actually a performance issue versus a management issue, a role fit issue, or a personal circumstance?',
                'category': 'technical',
                'difficulty': 'medium',
                'what_it_tests': 'Diagnostic rigor in employee relations and ability to see beyond surface-level presenting problems',
                'sample_answer_outline': 'The candidate should describe asking about the employee\'s history of performance, whether expectations were clearly communicated, whether the role has changed, what support has been provided, whether there are personal factors the employee has disclosed, and whether other team members face similar challenges. This demonstrates systems thinking rather than defaulting to the employee as the problem.',
            },
            {
                'question_text': 'Tell me about a time when you had to implement an unpopular HR policy change within your client group. How did you manage the rollout?',
                'category': 'behavioral',
                'difficulty': 'easy',
                'what_it_tests': 'Change management at the tactical level and communication skills',
                'sample_answer_outline': 'Look for how the candidate prepared managers with talking points and rationale before announcing to the broader team, created space for feedback and questions, acknowledged the difficulty honestly, and monitored adoption and sentiment afterward. A strong answer shows the candidate took ownership of the communication rather than hiding behind corporate messaging.',
            },
            {
                'question_text': 'How do you support team culture during a transition to hybrid or remote work within your client group?',
                'category': 'culture',
                'difficulty': 'easy',
                'what_it_tests': 'Practical understanding of remote work challenges and ability to advise managers',
                'sample_answer_outline': 'The candidate should discuss coaching managers on intentional communication practices, ensuring remote employees are not disadvantaged in visibility or career development, recommending team rituals that work across modalities, addressing proximity bias, and monitoring engagement signals. They should demonstrate nuance rather than a one-size-fits-all approach.',
            },
            {
                'question_text': 'What steps do you take when you first join a new client group as their HR Business Partner?',
                'category': 'problem_solving',
                'difficulty': 'easy',
                'what_it_tests': 'Structured onboarding approach and relationship-building methodology',
                'sample_answer_outline': 'A strong answer includes a listening tour with leaders and key employees, reviewing workforce data and prior engagement results, understanding the business strategy and current challenges, identifying quick wins, building relationships with the leadership team, and establishing regular touchpoints. The candidate should demonstrate that they invest in understanding before prescribing solutions.',
            },
        ],
    },
    {
        'slug': 'learning-development-manager',
        'title': 'Learning & Development Manager',
        'department': 'HR',
        'seniority_level': 'mid',
        'description': 'The Learning and Development Manager designs, implements, and evaluates organizational learning programs that build employee capabilities and support business performance. This role owns the learning strategy including leadership development, technical skills training, onboarding programs, and career development frameworks, ensuring that learning investments are aligned with business priorities and deliver measurable impact.',
        'responsibilities': [
            'Design and manage the organizational learning strategy aligned with business capability needs',
            'Develop and deliver leadership development programs for emerging and experienced leaders',
            'Oversee onboarding program design and continuous improvement based on new hire feedback and retention data',
            'Manage the learning management system and evaluate learning technology investments',
            'Create career development frameworks and growth pathways across the organization',
            'Measure and report on learning program effectiveness using Kirkpatrick or similar evaluation models',
        ],
        'key_skills': [
            'Instructional design and adult learning theory',
            'Leadership development program design',
            'Learning management systems and educational technology',
            'Training needs assessment and gap analysis',
            'Program evaluation and ROI measurement',
            'Facilitation and presentation skills',
        ],
        'assessment_slugs': ['hr', 'behavioral'],
        'questions': [
            {
                'question_text': 'How do you conduct a training needs assessment for an organization that has never had a formal learning function?',
                'category': 'technical',
                'difficulty': 'hard',
                'what_it_tests': 'Ability to build learning infrastructure from the ground up using systematic analysis',
                'sample_answer_outline': 'The candidate should describe a multi-method approach including interviews with business leaders about capability gaps, analysis of performance data and business objectives, employee surveys on development needs, benchmarking against industry standards, and prioritization based on business impact and urgency. They should acknowledge the importance of quick wins to build credibility while developing the longer-term learning roadmap.',
            },
            {
                'question_text': 'Describe a learning program you designed that demonstrably improved business outcomes. How did you measure the impact?',
                'category': 'behavioral',
                'difficulty': 'hard',
                'what_it_tests': 'Experience connecting learning programs to measurable business results beyond satisfaction scores',
                'sample_answer_outline': 'A strong answer describes the business problem that prompted the program, the design rationale, delivery method, and specific Level 3 and Level 4 evaluation measures such as behavior change on the job and business metrics improvement. The candidate should be honest about attribution challenges while showing rigor in measurement beyond smile sheets.',
            },
            {
                'question_text': 'Your CEO asks you to build a leadership development program for high-potential managers but gives you a budget that covers only a fraction of what a comprehensive program would cost. What do you do?',
                'category': 'situational',
                'difficulty': 'hard',
                'what_it_tests': 'Creativity in program design under resource constraints and ability to deliver value efficiently',
                'sample_answer_outline': 'The candidate should describe prioritizing the most critical leadership capabilities, leveraging internal leaders as facilitators and mentors, using blended learning with self-directed digital content supplemented by cohort experiences, incorporating action learning projects tied to real business challenges, and building in peer coaching. They should present a phased approach that delivers value immediately while building toward a more comprehensive program.',
            },
            {
                'question_text': 'How do you decide whether to build a training program internally, purchase an off-the-shelf solution, or engage an external vendor?',
                'category': 'problem_solving',
                'difficulty': 'medium',
                'what_it_tests': 'Resource allocation judgment and understanding of build versus buy trade-offs in learning',
                'sample_answer_outline': 'The response should cover evaluation criteria including strategic importance and need for customization, internal expertise availability, time constraints, cost comparison, scalability needs, and intellectual property considerations. The candidate should demonstrate a framework rather than a default preference, and mention examples of when each approach was the right choice.',
            },
            {
                'question_text': 'What is your approach to measuring learning effectiveness beyond participant satisfaction surveys?',
                'category': 'technical',
                'difficulty': 'medium',
                'what_it_tests': 'Understanding of learning evaluation methodology and commitment to demonstrating business value',
                'sample_answer_outline': 'The candidate should reference the Kirkpatrick model or similar frameworks, describing how they measure reaction, learning through knowledge assessments or skill demonstrations, behavior change through manager observations and 360 feedback, and results through business metric correlation. They should acknowledge the increasing difficulty and cost of measuring higher levels and describe practical approaches they have used.',
            },
            {
                'question_text': 'Tell me about a time when you received negative feedback on a program you designed. How did you respond?',
                'category': 'behavioral',
                'difficulty': 'medium',
                'what_it_tests': 'Receptiveness to feedback and continuous improvement mindset',
                'sample_answer_outline': 'Look for a specific example where the candidate received critical feedback, how they separated emotional reaction from professional response, what they did to understand the root cause of the dissatisfaction, the specific changes they made, and how the revised program performed. The candidate should demonstrate humility and genuine commitment to learner experience.',
            },
            {
                'question_text': 'A business unit leader tells you that they cannot afford to have their team spend time in training because they are too busy delivering on quarterly targets. How do you respond?',
                'category': 'situational',
                'difficulty': 'medium',
                'what_it_tests': 'Ability to advocate for learning investment and offer flexible solutions',
                'sample_answer_outline': 'The candidate should empathize with the business pressure, explore what capability gaps are most impacting the team\'s ability to deliver, offer micro-learning and on-the-job learning alternatives that minimize time away from work, quantify the cost of not developing skills such as rework, turnover, or missed targets, and negotiate a realistic commitment. They should not simply accept the objection or force a solution.',
            },
            {
                'question_text': 'How do you create a culture of continuous learning in an organization where people view training as something only underperformers need?',
                'category': 'culture',
                'difficulty': 'hard',
                'what_it_tests': 'Ability to shift organizational mindset about learning and development',
                'sample_answer_outline': 'A strong answer includes strategies such as having senior leaders visibly participate in and champion learning, connecting development to career progression and aspirational goals rather than remediation, showcasing learning success stories from high performers, integrating learning into daily work through knowledge sharing and communities of practice, and rebranding the learning function to signal growth rather than deficit.',
            },
            {
                'question_text': 'How do you mentor and develop junior instructional designers or learning specialists on your team?',
                'category': 'leadership',
                'difficulty': 'medium',
                'what_it_tests': 'Team development approach and ability to build learning and development capability',
                'sample_answer_outline': 'The candidate should describe providing stretch assignments with coaching support, reviewing program designs collaboratively rather than prescriptively, exposing team members to stakeholder interactions, encouraging experimentation with new learning modalities, providing constructive feedback on facilitation skills, and creating space for professional development in the learning field itself.',
            },
            {
                'question_text': 'What role do you see AI and technology playing in corporate learning over the next three years, and how are you preparing for it?',
                'category': 'technical',
                'difficulty': 'medium',
                'what_it_tests': 'Forward-thinking perspective on learning technology and practical readiness',
                'sample_answer_outline': 'The response should address specific applications such as personalized learning paths, AI-generated content, intelligent tutoring systems, virtual reality for skills practice, and analytics for learning effectiveness. The candidate should also discuss risks including quality control, digital equity, and the continued importance of human connection in learning. Look for balanced enthusiasm tempered by critical thinking.',
            },
            {
                'question_text': 'Explain the difference between a learning objective and a performance objective, and why this distinction matters when designing a program.',
                'category': 'technical',
                'difficulty': 'easy',
                'what_it_tests': 'Foundational instructional design knowledge',
                'sample_answer_outline': 'The candidate should explain that a learning objective describes what a participant will know or be able to do at the end of training, while a performance objective describes what they will do differently on the job. The distinction matters because training can meet all learning objectives while failing to change on-the-job behavior if transfer of learning is not designed into the program.',
            },
            {
                'question_text': 'How do you ensure onboarding programs help new hires integrate socially and culturally, not just complete compliance training?',
                'category': 'culture',
                'difficulty': 'easy',
                'what_it_tests': 'Holistic view of onboarding beyond administrative and compliance requirements',
                'sample_answer_outline': 'A strong answer includes buddy or mentor pairing, structured introductions to key stakeholders, cultural immersion activities such as storytelling from long-tenured employees, team-based activities during the first weeks, check-ins at 30, 60, and 90 days, and feedback loops to continuously improve the social integration experience. The candidate should recognize that cultural onboarding is often more predictive of retention than technical onboarding.',
            },
        ],
    },
]
