LEADERSHIP_ROLES = [
    {
        'slug': 'ceo',
        'title': 'Chief Executive Officer',
        'department': 'Leadership',
        'seniority_level': 'executive',
        'description': 'The CEO sets the overall vision, strategy, and direction for the organization, serving as the primary leader accountable to the board and stakeholders. They are responsible for building the executive team, driving company culture, and ensuring the business achieves its strategic and financial objectives.',
        'responsibilities': [
            'Define and communicate the company vision, mission, and strategic direction',
            'Build, lead, and hold accountable a high-performing executive leadership team',
            'Serve as the primary representative to the board of directors, investors, and key stakeholders',
            'Drive organizational culture, values, and employee engagement at scale',
            'Oversee capital allocation, major partnerships, and growth strategy decisions',
            'Ensure the organization adapts to market changes and maintains competitive advantage',
        ],
        'key_skills': [
            'Visionary strategic thinking and long-term planning',
            'Executive team building and talent assessment',
            'Board governance and investor relations',
            'Organizational culture design and stewardship',
            'Crisis leadership and high-stakes decision-making',
            'Industry expertise and market sensing',
        ],
        'assessment_slugs': ['behavioral', 'product'],
        'questions': [
            {
                'question_text': 'How do you evaluate whether your company\'s current strategy is working, and what signals would trigger a strategic pivot?',
                'category': 'technical',
                'difficulty': 'hard',
                'what_it_tests': 'Strategic evaluation frameworks and ability to balance persistence with adaptability',
                'sample_answer_outline': 'A strong answer discusses leading versus lagging indicators, market signal monitoring, customer feedback loops, competitive landscape analysis, regular strategy reviews with the board, and the discipline of distinguishing between execution problems and strategy problems.',
            },
            {
                'question_text': 'Describe a time when you had to make a major decision with incomplete information and significant consequences. What was your process?',
                'category': 'behavioral',
                'difficulty': 'hard',
                'what_it_tests': 'Decision-making under uncertainty and comfort with ambiguity at the highest level',
                'sample_answer_outline': 'Look for a structured approach: gathering available data, identifying what information would change the decision, consulting trusted advisors, setting a decision deadline, committing fully once decided, and monitoring outcomes to course-correct quickly.',
            },
            {
                'question_text': 'Your top-performing executive is creating a toxic culture within their division despite delivering strong financial results. How do you handle this?',
                'category': 'situational',
                'difficulty': 'hard',
                'what_it_tests': 'Values-driven leadership and willingness to make difficult people decisions',
                'sample_answer_outline': 'The candidate should describe addressing the behavior directly with specific examples, setting clear expectations and a timeline for change, providing coaching support, monitoring through 360 feedback, and being prepared to exit the executive if behavior does not change, despite the short-term performance risk.',
            },
            {
                'question_text': 'How do you structure your executive team to ensure both execution and innovation, and how do you manage the inherent tension between the two?',
                'category': 'leadership',
                'difficulty': 'hard',
                'what_it_tests': 'Organizational design thinking and ability to manage ambidextrous organizations',
                'sample_answer_outline': 'A strong answer discusses creating separate structures for core business and innovation, different metrics and incentive systems, protecting innovation teams from quarterly pressure, the role of the CEO in resolving resource allocation conflicts, and examples of balancing short and long-term investments.',
            },
            {
                'question_text': 'What is your philosophy on building and sustaining company culture as the organization scales from 100 to 1000 people?',
                'category': 'culture',
                'difficulty': 'medium',
                'what_it_tests': 'Understanding of culture as a scalable system rather than an organic byproduct',
                'sample_answer_outline': 'Look for codifying values early, hiring for cultural contribution not just fit, embedding values into performance systems and rituals, empowering middle managers as culture carriers, measuring culture health through surveys and retention data, and personally modeling the culture at every stage.',
            },
            {
                'question_text': 'You discover that a key product line generating 40% of revenue is becoming commoditized and margins will compress by half within two years. What is your strategic response?',
                'category': 'problem_solving',
                'difficulty': 'hard',
                'what_it_tests': 'Strategic problem-solving at the enterprise level with long time horizons',
                'sample_answer_outline': 'The candidate should describe validating the threat through market research, exploring differentiation strategies for the existing product, investing in adjacent or new revenue streams, modeling financial scenarios, communicating transparently with the board, and potentially acquiring capabilities to accelerate the pivot.',
            },
            {
                'question_text': 'How do you determine the right pace of growth for your company, and what frameworks do you use to evaluate growth versus profitability trade-offs?',
                'category': 'technical',
                'difficulty': 'medium',
                'what_it_tests': 'Business acumen and understanding of sustainable growth dynamics',
                'sample_answer_outline': 'A strong answer discusses the Rule of 40 for SaaS, unit economics and payback periods, capital efficiency metrics, the relationship between growth rate and valuation, market timing considerations, and the importance of ensuring the organization can absorb growth without breaking.',
            },
            {
                'question_text': 'Tell me about a time you had to rebuild trust with your board or investors after a significant miss or setback.',
                'category': 'behavioral',
                'difficulty': 'hard',
                'what_it_tests': 'Stakeholder management and ability to lead through adversity with transparency',
                'sample_answer_outline': 'Look for taking personal accountability, presenting a clear root-cause analysis, sharing a specific remediation plan with measurable milestones, increasing communication frequency, demonstrating early progress, and rebuilding credibility through consistent execution over time.',
            },
            {
                'question_text': 'Your two strongest executives are in fundamental disagreement about the company\'s product strategy. Both have valid perspectives. How do you resolve this?',
                'category': 'situational',
                'difficulty': 'medium',
                'what_it_tests': 'Ability to mediate high-stakes disagreements and make integrative decisions',
                'sample_answer_outline': 'The candidate should describe hearing both perspectives fully, reframing the debate around shared objectives and customer needs, using data to test hypotheses where possible, making a clear decision with rationale, ensuring the losing side feels heard, and securing commitment from both executives to execute the chosen path.',
            },
            {
                'question_text': 'How do you ensure that you are receiving honest, unfiltered information from your organization rather than only hearing what people think you want to hear?',
                'category': 'leadership',
                'difficulty': 'medium',
                'what_it_tests': 'Self-awareness about the CEO information bubble and strategies to counteract it',
                'sample_answer_outline': 'Look for skip-level meetings, anonymous feedback channels, spending time with frontline employees, creating psychological safety in meetings, rewarding dissent and candor, tracking leading indicators that bypass management filtering, and maintaining an external network for outside perspective.',
            },
            {
                'question_text': 'How do you decide when to prioritize employee well-being over short-term business results, and can you give an example?',
                'category': 'culture',
                'difficulty': 'easy',
                'what_it_tests': 'Authentic commitment to people and long-term organizational health',
                'sample_answer_outline': 'A good answer provides a specific example, discusses the long-term ROI of employee trust, acknowledges the tension honestly, and shows a framework for making these trade-offs rather than pretending there is no tension. Look for authenticity over corporate-speak.',
            },
            {
                'question_text': 'The company is facing simultaneous challenges: declining market share, a key executive departure, and a potential regulatory change. How do you prioritize and sequence your response?',
                'category': 'problem_solving',
                'difficulty': 'hard',
                'what_it_tests': 'Multi-dimensional crisis management and executive composure under pressure',
                'sample_answer_outline': 'The candidate should describe assessing each challenge by urgency and impact, addressing the executive departure first to stabilize leadership, delegating the regulatory response to the appropriate team with clear oversight, personally focusing on the market share issue as the existential threat, and communicating a calm and coherent narrative to the organization.',
            },
        ],
    },
    {
        'slug': 'coo',
        'title': 'Chief Operating Officer',
        'department': 'Leadership',
        'seniority_level': 'executive',
        'description': 'The COO is responsible for translating the company\'s strategy into operational execution, overseeing day-to-day business operations, and ensuring cross-functional alignment. They optimize processes, drive operational efficiency, and scale the business infrastructure to support growth targets.',
        'responsibilities': [
            'Oversee daily business operations and ensure efficient execution of strategic plans',
            'Design and optimize organizational processes, systems, and workflows at scale',
            'Align cross-functional teams around shared operational goals and KPIs',
            'Manage operational budgets and resource allocation across departments',
            'Lead operational due diligence and integration for acquisitions or expansions',
            'Build scalable infrastructure for people, technology, and processes to support growth',
        ],
        'key_skills': [
            'Operational strategy and process optimization',
            'Cross-functional leadership and organizational design',
            'Scaling operations from growth stage to enterprise',
            'Data-driven performance management and KPI frameworks',
            'Change management and business transformation',
            'Vendor management and strategic partnerships',
        ],
        'assessment_slugs': ['behavioral', 'product'],
        'questions': [
            {
                'question_text': 'How would you design an operating cadence (weekly, monthly, quarterly rhythms) for a 500-person company to ensure strategic alignment without creating meeting overload?',
                'category': 'technical',
                'difficulty': 'hard',
                'what_it_tests': 'Operational design thinking and ability to build scalable management systems',
                'sample_answer_outline': 'A strong answer describes tiered meeting structures with clear purposes at each level, information flow design (what escalates up versus resolves locally), decision rights clarity, async communication for status updates, quarterly strategic reviews, monthly operational reviews, and weekly tactical syncs with defined attendees and outputs.',
            },
            {
                'question_text': 'Describe a time when you had to shut down a project or initiative that was not working, despite significant organizational investment and emotional attachment.',
                'category': 'behavioral',
                'difficulty': 'hard',
                'what_it_tests': 'Ability to make tough operational calls and manage sunk cost bias',
                'sample_answer_outline': 'Look for clear criteria used to evaluate the project, data-driven assessment of viability, transparent communication about the decision rationale, compassionate treatment of affected team members, capturing lessons learned, and redirecting resources to higher-impact initiatives.',
            },
            {
                'question_text': 'The company has just doubled in headcount in 12 months and operational processes are breaking down. Customer complaints have tripled. Where do you start?',
                'category': 'situational',
                'difficulty': 'hard',
                'what_it_tests': 'Ability to diagnose and fix operational scaling challenges systematically',
                'sample_answer_outline': 'The candidate should describe triaging the most customer-impacting issues first, mapping current processes to identify bottlenecks, implementing quick wins while designing longer-term solutions, establishing operational metrics and monitoring, and building a phased operational improvement roadmap with clear milestones.',
            },
            {
                'question_text': 'How do you ensure department leaders are held accountable for outcomes without creating a fear-based culture?',
                'category': 'leadership',
                'difficulty': 'medium',
                'what_it_tests': 'Accountability framework design that balances performance with psychological safety',
                'sample_answer_outline': 'Look for clear goal-setting with input from the leaders themselves, regular progress reviews that focus on problem-solving rather than blame, separating accountability for effort from accountability for outcomes, celebrating learning from failures, and modeling vulnerability as a leader.',
            },
            {
                'question_text': 'How do you maintain operational consistency and quality across teams while still encouraging innovation and experimentation?',
                'category': 'culture',
                'difficulty': 'medium',
                'what_it_tests': 'Ability to balance standardization with flexibility in operational culture',
                'sample_answer_outline': 'A good answer discusses defining non-negotiable standards versus areas of autonomy, creating safe spaces for experimentation with defined boundaries, recognizing and scaling successful innovations, building feedback loops between frontline teams and leadership, and embedding continuous improvement into the operating model.',
            },
            {
                'question_text': 'Three critical business functions are each claiming they need the same limited engineering resources for must-have projects this quarter. How do you resolve this?',
                'category': 'problem_solving',
                'difficulty': 'hard',
                'what_it_tests': 'Resource allocation decision-making and ability to manage competing priorities',
                'sample_answer_outline': 'The candidate should describe establishing a common evaluation framework (revenue impact, strategic alignment, urgency, effort), facilitating a prioritization session with all stakeholders present, making a transparent decision with clear rationale, offering creative alternatives for deprioritized projects, and documenting the decision process for future reference.',
            },
            {
                'question_text': 'What operational metrics would you track to assess the health of a multi-product SaaS business, and how do they connect to each other?',
                'category': 'technical',
                'difficulty': 'medium',
                'what_it_tests': 'Operational metrics literacy and systems thinking about business health',
                'sample_answer_outline': 'A strong answer discusses the relationship between customer acquisition cost, time to value, product adoption metrics, NPS, churn/retention, revenue per employee, support ticket volume, and how degradation in upstream metrics predicts downstream business impact.',
            },
            {
                'question_text': 'Tell me about a time when you had to drive a significant operational change that most of the organization initially resisted.',
                'category': 'behavioral',
                'difficulty': 'medium',
                'what_it_tests': 'Change management skills and persistence in driving organizational transformation',
                'sample_answer_outline': 'Look for understanding the root causes of resistance, building a coalition of early adopters, communicating the vision and burning platform clearly, showing quick wins to build momentum, adjusting the approach based on feedback, and measuring adoption and business impact over time.',
            },
            {
                'question_text': 'You inherit an operations team with unclear roles, overlapping responsibilities, and low morale. How do you restructure it in the first 90 days?',
                'category': 'situational',
                'difficulty': 'medium',
                'what_it_tests': 'Organizational design skills and ability to execute a turnaround thoughtfully',
                'sample_answer_outline': 'The candidate should describe a listening tour in the first two weeks, mapping current roles and identifying overlaps, designing a clear organizational structure with defined responsibilities, communicating changes transparently, providing support during the transition, and establishing early wins to rebuild morale.',
            },
            {
                'question_text': 'How do you partner effectively with a CEO whose strengths are in vision and external relationships while yours are in execution and operations?',
                'category': 'leadership',
                'difficulty': 'easy',
                'what_it_tests': 'Executive partnership skills and understanding of the CEO-COO dynamic',
                'sample_answer_outline': 'Look for establishing clear swim lanes, regular alignment meetings, proactive communication about operational realities, translating the CEO\'s vision into executable plans, protecting the CEO\'s time by owning operational decisions, and building mutual trust through consistent delivery.',
            },
            {
                'question_text': 'What does operational excellence mean to you, and how do you embed it into the DNA of an organization rather than making it a one-time initiative?',
                'category': 'culture',
                'difficulty': 'easy',
                'what_it_tests': 'Philosophy on building a continuous improvement culture',
                'sample_answer_outline': 'A good answer discusses making operational excellence a shared value rather than a project, hiring for improvement mindset, building processes for surfacing inefficiencies, celebrating operational improvements alongside revenue wins, and connecting operational quality to customer and employee satisfaction.',
            },
            {
                'question_text': 'Customer onboarding time has increased from 2 weeks to 6 weeks over the past year as the product has grown more complex. Churn at 90 days has spiked. How do you approach this?',
                'category': 'problem_solving',
                'difficulty': 'hard',
                'what_it_tests': 'Root cause analysis of operational problems with customer impact',
                'sample_answer_outline': 'The candidate should describe mapping the current onboarding process step by step, identifying where time is being added, analyzing which customers churn and why, segmenting customers by complexity, creating tiered onboarding paths, automating low-touch steps, and establishing time-to-value as a key operational KPI.',
            },
        ],
    },
    {
        'slug': 'general-manager',
        'title': 'General Manager',
        'department': 'Leadership',
        'seniority_level': 'lead',
        'description': 'The General Manager owns the full profit-and-loss responsibility for a business unit, product line, or geographic region. They operate as a mini-CEO, balancing revenue growth, cost management, and team leadership to deliver on business objectives while aligning with the broader organizational strategy.',
        'responsibilities': [
            'Own full P&L responsibility for a business unit or product line',
            'Set strategic direction and annual objectives for the business unit',
            'Lead cross-functional teams including sales, marketing, product, and operations',
            'Drive revenue growth while managing costs and operational efficiency',
            'Report on business performance to senior leadership and the executive team',
            'Identify market opportunities and competitive threats to inform strategic decisions',
        ],
        'key_skills': [
            'P&L management and business financial acumen',
            'Cross-functional team leadership and alignment',
            'Strategic planning and market analysis',
            'Revenue growth strategy and go-to-market execution',
            'Customer relationship management at strategic level',
            'Data-driven decision-making and performance management',
        ],
        'assessment_slugs': ['behavioral', 'product'],
        'questions': [
            {
                'question_text': 'How do you build and manage a P&L for a business unit, and what are the key levers you focus on to improve profitability?',
                'category': 'technical',
                'difficulty': 'hard',
                'what_it_tests': 'P&L literacy and ability to identify and pull the right financial levers',
                'sample_answer_outline': 'A strong answer covers revenue line management (pricing, volume, mix), gross margin optimization, operating expense control, contribution margin analysis by segment, and the ability to distinguish between investment spend and sustaining spend when making profitability trade-offs.',
            },
            {
                'question_text': 'Describe a time when you had to make a significant trade-off between short-term revenue and long-term strategic positioning.',
                'category': 'behavioral',
                'difficulty': 'hard',
                'what_it_tests': 'Strategic judgment and ability to balance immediate results with long-term value creation',
                'sample_answer_outline': 'Look for a clear articulation of the trade-off, the analysis performed to evaluate both options, how the candidate communicated the decision to stakeholders, the outcome, and what they would do differently in hindsight.',
            },
            {
                'question_text': 'Your business unit is losing market share to a competitor offering a cheaper but lower-quality product. Your sales team is asking for price cuts. What is your strategy?',
                'category': 'situational',
                'difficulty': 'hard',
                'what_it_tests': 'Competitive strategy formulation and ability to resist reactive decision-making',
                'sample_answer_outline': 'The candidate should analyze which customer segments are defecting and why, evaluate whether to compete on price in some segments while defending premium positioning in others, invest in differentiation, improve the value narrative for the sales team, and model the financial impact of various pricing strategies.',
            },
            {
                'question_text': 'How do you align a cross-functional team where each function has different goals and incentives toward a shared business unit objective?',
                'category': 'leadership',
                'difficulty': 'medium',
                'what_it_tests': 'Cross-functional leadership and ability to create shared ownership without direct authority over all functions',
                'sample_answer_outline': 'Look for establishing shared KPIs, creating a business unit mission that transcends functional goals, building personal relationships with functional leaders, recognizing cross-functional contributions, and escalating misalignment quickly rather than letting it fester.',
            },
            {
                'question_text': 'How do you build a winning team culture within a business unit that operates somewhat independently from the broader company?',
                'category': 'culture',
                'difficulty': 'medium',
                'what_it_tests': 'Ability to create sub-culture identity while maintaining alignment with company values',
                'sample_answer_outline': 'A good answer discusses anchoring the business unit culture in company-wide values while adding unit-specific norms, creating team rituals and traditions, celebrating wins together, maintaining connection with the broader organization, and being intentional about the cultural tone set by the GM themselves.',
            },
            {
                'question_text': 'Your largest customer, representing 25% of business unit revenue, is threatening to leave due to service quality issues. The root causes span multiple teams. How do you respond?',
                'category': 'problem_solving',
                'difficulty': 'hard',
                'what_it_tests': 'Customer retention strategy and cross-functional problem-solving under pressure',
                'sample_answer_outline': 'The candidate should describe personally engaging with the customer at the executive level, conducting a rapid root-cause analysis across teams, assembling a cross-functional war room, creating a remediation plan with specific milestones, over-communicating progress, and implementing structural fixes to prevent recurrence.',
            },
            {
                'question_text': 'What market analysis framework do you use to identify new growth opportunities for your business unit?',
                'category': 'technical',
                'difficulty': 'medium',
                'what_it_tests': 'Strategic market analysis skills and growth strategy development',
                'sample_answer_outline': 'A strong answer references frameworks like TAM/SAM/SOM analysis, competitive positioning maps, customer segmentation analysis, adjacency growth models, and explains how they synthesize market data, customer feedback, and internal capabilities to prioritize growth investments.',
            },
            {
                'question_text': 'Tell me about a time when you inherited a underperforming business unit. What did you do in the first 90 days?',
                'category': 'behavioral',
                'difficulty': 'medium',
                'what_it_tests': 'Turnaround leadership skills and diagnostic approach to business problems',
                'sample_answer_outline': 'Look for a structured diagnostic phase (listening, data analysis, customer conversations), quick identification of the 2-3 most impactful issues, early wins to build momentum, team assessment and any personnel changes, and a clear 90-day plan shared with the team and leadership.',
            },
            {
                'question_text': 'The executive team asks you to reduce your business unit headcount by 15% while maintaining current revenue targets. How do you approach this?',
                'category': 'situational',
                'difficulty': 'hard',
                'what_it_tests': 'Ability to execute difficult restructuring decisions while protecting business performance',
                'sample_answer_outline': 'The candidate should describe analyzing which roles are essential to revenue generation, identifying automation opportunities, restructuring work to eliminate redundancy, communicating transparently with the team, supporting affected employees, and presenting a realistic assessment of revenue risk to the executive team.',
            },
            {
                'question_text': 'How do you develop leaders within your business unit who can eventually run their own P&L?',
                'category': 'leadership',
                'difficulty': 'easy',
                'what_it_tests': 'Succession planning and talent development for business leadership roles',
                'sample_answer_outline': 'Look for giving high-potential leaders exposure to full business decisions, delegating P&L components for them to own, providing mentorship on cross-functional thinking, creating opportunities for them to present to senior leadership, and being willing to let them make mistakes in a supported environment.',
            },
            {
                'question_text': 'How do you make decisions when your sales team and product team fundamentally disagree about the direction of the business unit?',
                'category': 'culture',
                'difficulty': 'easy',
                'what_it_tests': 'Decision-making style and ability to mediate functional tensions constructively',
                'sample_answer_outline': 'A good answer discusses creating a shared understanding of customer needs as the tiebreaker, using data to test competing hypotheses, establishing a decision-making process that is respected by both functions, ensuring the losing side understands the rationale, and maintaining psychological safety for dissent.',
            },
            {
                'question_text': 'Your business unit has been asked to achieve aggressive growth targets, but your team is already showing signs of burnout. How do you balance performance pressure with team sustainability?',
                'category': 'problem_solving',
                'difficulty': 'medium',
                'what_it_tests': 'Ability to drive results while maintaining team health and retention',
                'sample_answer_outline': 'The candidate should describe validating the burnout signals through conversations and data, identifying which work is highest-leverage and deprioritizing the rest, negotiating realistic expectations with leadership using data, investing in efficiency improvements, and being transparent with the team about the challenge while protecting their well-being.',
            },
        ],
    },
    {
        'slug': 'department-head',
        'title': 'Department Head',
        'department': 'Leadership',
        'seniority_level': 'lead',
        'description': 'The Department Head leads a functional department, setting direction, managing budgets, and developing talent to deliver on organizational goals. They serve as the senior-most leader within their function, responsible for both strategic planning and operational execution across their team.',
        'responsibilities': [
            'Set departmental strategy, goals, and key performance indicators aligned with company objectives',
            'Manage the department budget and allocate resources to maximize impact',
            'Hire, develop, and retain top talent within the department',
            'Represent the department in cross-functional leadership meetings and strategic planning',
            'Drive continuous improvement in departmental processes and deliverables',
            'Provide regular performance updates and strategic recommendations to the executive team',
        ],
        'key_skills': [
            'Functional domain expertise and thought leadership',
            'Departmental strategy and roadmap planning',
            'Budget management and resource optimization',
            'Talent acquisition, development, and performance management',
            'Cross-functional collaboration and stakeholder influence',
            'Change management and organizational development',
        ],
        'assessment_slugs': ['behavioral', 'product'],
        'questions': [
            {
                'question_text': 'How do you translate company-level OKRs into meaningful departmental objectives that your team can rally around?',
                'category': 'technical',
                'difficulty': 'medium',
                'what_it_tests': 'Strategic alignment skills and ability to cascade goals effectively',
                'sample_answer_outline': 'A strong answer describes understanding the company strategy deeply, identifying the department\'s unique contribution, creating objectives that are ambitious yet achievable, involving the team in key result definition, establishing leading indicators, and reviewing progress frequently to adapt.',
            },
            {
                'question_text': 'Tell me about a time when you had to advocate strongly for your department\'s needs against competing priorities from other departments.',
                'category': 'behavioral',
                'difficulty': 'medium',
                'what_it_tests': 'Advocacy skills and ability to influence without authority in a leadership context',
                'sample_answer_outline': 'Look for preparing a data-driven business case, understanding the competing departments\' perspectives, framing the request in terms of company-wide impact rather than departmental self-interest, being willing to compromise, and maintaining strong relationships regardless of the outcome.',
            },
            {
                'question_text': 'A new company-wide initiative will require your department to take on significant additional work without additional headcount. How do you manage this?',
                'category': 'situational',
                'difficulty': 'hard',
                'what_it_tests': 'Resource constraint management and ability to execute under pressure',
                'sample_answer_outline': 'The candidate should describe assessing the actual scope of work, identifying what existing work can be deprioritized or automated, communicating capacity constraints transparently to leadership, proposing a phased approach, and protecting the team from unsustainable workloads while still demonstrating commitment.',
            },
            {
                'question_text': 'How do you identify and develop high-potential employees within your department for future leadership roles?',
                'category': 'leadership',
                'difficulty': 'medium',
                'what_it_tests': 'Talent identification and development philosophy',
                'sample_answer_outline': 'Look for a systematic approach: defining leadership potential criteria, observing performance across different situations, providing stretch assignments, offering mentorship and coaching, creating visibility with senior leadership, having honest career development conversations, and building succession depth.',
            },
            {
                'question_text': 'How do you foster a culture of ownership and accountability within your department without micromanaging?',
                'category': 'culture',
                'difficulty': 'medium',
                'what_it_tests': 'Management style and ability to empower while maintaining standards',
                'sample_answer_outline': 'A good answer discusses setting clear expectations and outcomes, giving autonomy over methods, creating feedback loops rather than checkpoints, celebrating initiative and problem-solving, being available for guidance without hovering, and holding retrospectives focused on learning rather than blame.',
            },
            {
                'question_text': 'Your department has been underperforming against KPIs for two consecutive quarters. The executive team is losing confidence. What is your turnaround plan?',
                'category': 'problem_solving',
                'difficulty': 'hard',
                'what_it_tests': 'Performance turnaround ability and executive credibility management',
                'sample_answer_outline': 'The candidate should describe conducting an honest root-cause analysis, distinguishing between people, process, and strategy issues, creating a 30-60-90 day recovery plan with measurable milestones, communicating the plan proactively to the executive team, making difficult personnel decisions if needed, and demonstrating early progress to rebuild confidence.',
            },
            {
                'question_text': 'What frameworks do you use for departmental capacity planning, and how do you determine when to hire versus redistribute existing work?',
                'category': 'technical',
                'difficulty': 'medium',
                'what_it_tests': 'Resource planning skills and analytical approach to headcount decisions',
                'sample_answer_outline': 'A strong answer discusses workload analysis, utilization metrics, skill gap assessment, cost-benefit analysis of hiring versus training, contractor versus full-time trade-offs, automation potential, and building a business case for headcount that ties to revenue or strategic impact.',
            },
            {
                'question_text': 'Describe a time when you received tough feedback from your own team about your leadership style. How did you respond?',
                'category': 'behavioral',
                'difficulty': 'medium',
                'what_it_tests': 'Self-awareness, humility, and willingness to grow as a leader',
                'sample_answer_outline': 'Look for genuine vulnerability, active listening without defensiveness, specific actions taken to address the feedback, follow-up with the team to demonstrate change, and the long-term impact on the leader-team relationship.',
            },
            {
                'question_text': 'You have a strong performer who is a cultural detractor, regularly undermining team norms and new initiatives. Other team members have started complaining. How do you address this?',
                'category': 'situational',
                'difficulty': 'hard',
                'what_it_tests': 'Ability to address behavioral issues with high performers and protect team culture',
                'sample_answer_outline': 'The candidate should describe having a direct, private conversation with specific behavioral examples, explaining the impact on the team, setting clear expectations and consequences, providing coaching support, monitoring for improvement, and being prepared to take action if behavior does not change, regardless of individual performance.',
            },
            {
                'question_text': 'How do you ensure your department remains strategically relevant as the company\'s needs evolve, rather than becoming a legacy function?',
                'category': 'leadership',
                'difficulty': 'easy',
                'what_it_tests': 'Strategic foresight and ability to evolve a department proactively',
                'sample_answer_outline': 'Look for staying close to the company\'s strategic direction, regularly reassessing the department\'s value proposition, investing in upskilling the team for emerging needs, proactively proposing new capabilities, seeking feedback from internal customers about unmet needs, and benchmarking against best-in-class departments externally.',
            },
            {
                'question_text': 'What practices do you use to ensure effective communication and information flow within a department of 30 or more people?',
                'category': 'culture',
                'difficulty': 'easy',
                'what_it_tests': 'Communication design and transparency as a department leader',
                'sample_answer_outline': 'A good answer covers regular all-hands meetings, team-level standups, open office hours, written communication for important decisions, feedback channels, manager cascade communication, and being intentional about what information needs to flow up, down, and across the department.',
            },
            {
                'question_text': 'Two of your managers are delivering results but in ways that are unsustainable, leading to team burnout and turnover in their sub-teams. How do you address this without undermining their authority?',
                'category': 'problem_solving',
                'difficulty': 'medium',
                'what_it_tests': 'Ability to coach managers and address systemic team health issues',
                'sample_answer_outline': 'The candidate should describe using data (turnover, engagement scores, exit interview themes) to make the case, coaching each manager individually on sustainable leadership practices, setting team health metrics alongside performance metrics, providing management training resources, and monitoring improvement over time.',
            },
        ],
    },
    {
        'slug': 'team-lead',
        'title': 'Team Lead',
        'department': 'Leadership',
        'seniority_level': 'senior',
        'description': 'The Team Lead is a hands-on leader who manages a small to mid-sized team, balancing individual contribution with people management responsibilities. They are responsible for day-to-day team performance, coaching team members, and ensuring delivery of team objectives while serving as the link between their team and senior leadership.',
        'responsibilities': [
            'Manage day-to-day team performance and ensure timely delivery of team objectives',
            'Conduct regular one-on-ones, provide feedback, and support career development for direct reports',
            'Plan and allocate team workload and resources to meet project deadlines',
            'Facilitate team meetings, retrospectives, and collaborative problem-solving sessions',
            'Serve as the primary escalation point for team blockers and cross-team coordination',
            'Contribute individually to team deliverables while fulfilling management responsibilities',
        ],
        'key_skills': [
            'People management and coaching fundamentals',
            'Task prioritization and workload management',
            'Clear communication and feedback delivery',
            'Conflict resolution and team dynamics management',
            'Project planning and deadline management',
            'Individual contribution in the team\'s domain area',
        ],
        'assessment_slugs': ['behavioral', 'product'],
        'questions': [
            {
                'question_text': 'How do you structure effective one-on-one meetings with your direct reports, and what topics do you consistently cover?',
                'category': 'technical',
                'difficulty': 'easy',
                'what_it_tests': 'Foundational people management skills and one-on-one meeting best practices',
                'sample_answer_outline': 'A strong answer covers letting the report set the agenda, discussing blockers and progress, career development conversations on a regular cadence, providing and soliciting feedback, keeping notes for continuity, and adjusting frequency and format based on individual needs.',
            },
            {
                'question_text': 'Tell me about a time when you had to give difficult performance feedback to a team member who was not meeting expectations.',
                'category': 'behavioral',
                'difficulty': 'medium',
                'what_it_tests': 'Feedback delivery skills and courage in addressing underperformance',
                'sample_answer_outline': 'Look for specific, behavioral feedback rather than personal criticism, private setting, concrete examples, clear expectations for improvement, follow-up support plan, documentation, and the ultimate outcome for both the individual and the team.',
            },
            {
                'question_text': 'A team member comes to you frustrated that a colleague is not pulling their weight on a shared project. How do you handle this?',
                'category': 'situational',
                'difficulty': 'medium',
                'what_it_tests': 'Conflict mediation skills and ability to address performance issues fairly',
                'sample_answer_outline': 'The candidate should describe listening to the frustrated team member, gathering facts before making judgments, having a separate conversation with the other colleague to understand their perspective, identifying whether the issue is capacity, capability, or motivation, and addressing the root cause while maintaining both relationships.',
            },
            {
                'question_text': 'How do you balance your own individual contributor work with your people management responsibilities when both compete for your time?',
                'category': 'leadership',
                'difficulty': 'medium',
                'what_it_tests': 'Self-management and ability to prioritize the leadership multiplier effect',
                'sample_answer_outline': 'Look for prioritizing people management during critical periods, time-blocking for both responsibilities, understanding that unblocking the team has higher leverage than personal contribution, being willing to deprioritize individual work for management needs, and communicating transparently about capacity.',
            },
            {
                'question_text': 'How do you build trust with a new team that you are leading for the first time?',
                'category': 'culture',
                'difficulty': 'easy',
                'what_it_tests': 'Relationship-building approach and emotional intelligence in new leadership situations',
                'sample_answer_outline': 'A good answer covers listening before making changes, learning each person\'s strengths and motivations through one-on-ones, being transparent about leadership style and expectations, delivering on commitments, showing vulnerability, and respecting existing team norms before evolving them.',
            },
            {
                'question_text': 'Your team is committed to a project deadline, but halfway through you realize the original estimate was too aggressive and quality will suffer. What do you do?',
                'category': 'problem_solving',
                'difficulty': 'medium',
                'what_it_tests': 'Project risk management and ability to have difficult conversations about timelines',
                'sample_answer_outline': 'The candidate should describe assessing the gap between current trajectory and the deadline, identifying scope reduction or additional resource options, communicating the risk early to stakeholders with proposed alternatives, negotiating a realistic path forward, and documenting lessons learned for future estimation.',
            },
            {
                'question_text': 'What methods do you use to ensure equitable workload distribution across your team members?',
                'category': 'technical',
                'difficulty': 'easy',
                'what_it_tests': 'Workload management skills and fairness in team resource allocation',
                'sample_answer_outline': 'A strong answer discusses tracking assignments and capacity, considering skill levels and development goals in allocation, checking in regularly about workload perception, rotating less desirable tasks, and being transparent about allocation decisions so the team understands the rationale.',
            },
            {
                'question_text': 'Describe a time when you advocated for a team member who was being overlooked for recognition or advancement.',
                'category': 'behavioral',
                'difficulty': 'easy',
                'what_it_tests': 'Advocacy for team members and willingness to champion others\' growth',
                'sample_answer_outline': 'Look for recognizing the team member\'s contributions, making their work visible to leadership, sponsoring them for opportunities, having honest conversations about what they need to advance, and following through on commitments to support their career progression.',
            },
            {
                'question_text': 'Two of your team members have a persistent interpersonal conflict that is affecting team morale and productivity. They have been unable to resolve it between themselves. How do you intervene?',
                'category': 'situational',
                'difficulty': 'hard',
                'what_it_tests': 'Conflict resolution skills and judgment about when and how to intervene',
                'sample_answer_outline': 'The candidate should describe meeting with each person individually first, identifying the root cause of the conflict, facilitating a mediated conversation with ground rules, focusing on behaviors and impact rather than personalities, agreeing on a path forward with specific commitments, and following up to ensure the resolution holds.',
            },
            {
                'question_text': 'How do you handle a situation where your manager gives you direction that you believe is wrong for your team?',
                'category': 'leadership',
                'difficulty': 'hard',
                'what_it_tests': 'Upward management skills and ability to challenge constructively while maintaining respect for hierarchy',
                'sample_answer_outline': 'Look for seeking to understand the manager\'s reasoning first, presenting a clear alternative with data or evidence, being willing to disagree and commit if the manager holds firm, not undermining the decision in front of the team, and keeping communication channels open for future disagreements.',
            },
            {
                'question_text': 'How do you create an environment where team members feel comfortable sharing mistakes and asking for help?',
                'category': 'culture',
                'difficulty': 'easy',
                'what_it_tests': 'Ability to build psychological safety within a team',
                'sample_answer_outline': 'A good answer covers sharing your own mistakes first, responding constructively when others share errors, focusing on learning rather than blame in retrospectives, normalizing asking for help as a sign of strength, and recognizing and rewarding transparency and collaboration.',
            },
            {
                'question_text': 'You are managing a team where one member is significantly more senior and experienced than the others. They are helpful but sometimes dominate discussions and intimidate newer team members from contributing. How do you address this?',
                'category': 'problem_solving',
                'difficulty': 'medium',
                'what_it_tests': 'Team dynamics management and ability to harness senior talent without stifling others',
                'sample_answer_outline': 'The candidate should describe acknowledging the senior member\'s contributions privately, coaching them on inclusive meeting behaviors, structuring discussions to ensure everyone has voice (round-robin, pre-meeting input), creating opportunities for junior members to lead, and framing the senior member\'s mentorship role as a growth opportunity.',
            },
        ],
    },
]