MARKETING_ROLES = [
    {
        'slug': 'cmo',
        'title': 'Chief Marketing Officer',
        'department': 'Marketing',
        'seniority_level': 'executive',
        'description': 'The Chief Marketing Officer is responsible for overseeing the entire marketing organization, setting brand strategy, and driving revenue growth through integrated marketing initiatives. This executive partners with the CEO and board to align marketing vision with business objectives and market positioning.',
        'responsibilities': [
            'Define and execute the overall marketing strategy aligned with company vision and revenue targets',
            'Lead and develop the marketing organization across all functions including brand, demand gen, product marketing, and communications',
            'Own the marketing budget and allocate resources to maximize ROI across channels and initiatives',
            'Partner with sales, product, and executive leadership to drive go-to-market strategy',
            'Establish brand positioning and ensure consistent messaging across all customer touchpoints',
            'Report on marketing performance to the board and stakeholders with data-driven insights',
        ],
        'key_skills': [
            'Strategic planning and executive leadership',
            'Brand strategy and market positioning',
            'Revenue marketing and pipeline generation',
            'Data-driven decision making and marketing analytics',
            'Cross-functional collaboration and stakeholder management',
            'Budget management and resource allocation',
        ],
        'assessment_slugs': ['marketing', 'behavioral'],
        'questions': [
            {
                'question_text': 'How would you approach building a marketing strategy for a company entering a new market segment where we have zero brand recognition?',
                'category': 'technical',
                'difficulty': 'hard',
                'what_it_tests': 'Ability to build a market entry strategy from scratch and think through positioning, channels, and sequencing',
                'sample_answer_outline': 'A strong answer covers market research and competitive analysis first, then defines target personas and unique value propositions. The candidate should articulate a phased approach starting with awareness building through thought leadership and targeted campaigns, followed by demand generation, and explain how they would measure progress at each stage.',
            },
            {
                'question_text': 'Tell me about a time you had to make a significant pivot in marketing strategy due to unexpected market conditions. What was the outcome?',
                'category': 'behavioral',
                'difficulty': 'hard',
                'what_it_tests': 'Adaptability under pressure and ability to lead an organization through strategic change',
                'sample_answer_outline': 'The candidate should describe a specific scenario with clear context, explain the data or signals that prompted the pivot, and detail how they communicated the change to their team and stakeholders. A good answer includes measurable outcomes and lessons learned from the experience.',
            },
            {
                'question_text': 'Your CEO wants to cut the marketing budget by 30% mid-year but still expects the same pipeline targets. How do you handle this situation?',
                'category': 'situational',
                'difficulty': 'hard',
                'what_it_tests': 'Executive-level negotiation skills, resource optimization, and ability to manage up with data',
                'sample_answer_outline': 'A strong candidate would first seek to understand the business context behind the cut, then present a data-driven analysis showing the impact on pipeline. They should propose a prioritized plan that focuses on highest-ROI channels, explain trade-offs transparently, and negotiate for a realistic adjusted target if needed.',
            },
            {
                'question_text': 'How do you align marketing and sales organizations to ensure both teams are working toward shared revenue goals?',
                'category': 'leadership',
                'difficulty': 'medium',
                'what_it_tests': 'Cross-functional leadership and ability to build collaborative revenue-focused cultures',
                'sample_answer_outline': 'The candidate should discuss establishing shared KPIs and SLAs between marketing and sales, creating regular alignment meetings and feedback loops, and implementing shared dashboards. They should reference specific frameworks like revenue team structures or account-based approaches and explain how they handle conflict between the two organizations.',
            },
            {
                'question_text': 'What is your philosophy on building and maintaining a strong marketing culture, especially in a remote or hybrid environment?',
                'category': 'culture',
                'difficulty': 'medium',
                'what_it_tests': 'Values around team building, creativity, and fostering innovation within a marketing organization',
                'sample_answer_outline': 'A good answer addresses creating psychological safety for creative risk-taking, establishing rituals for collaboration and idea sharing, and investing in professional development. The candidate should give concrete examples of how they have built culture in previous roles and how they adapt for distributed teams.',
            },
            {
                'question_text': 'Our brand perception is strong with technical buyers but weak with business decision-makers. How would you diagnose the root cause and develop a plan to address this gap?',
                'category': 'problem_solving',
                'difficulty': 'hard',
                'what_it_tests': 'Analytical approach to brand perception challenges and ability to develop multi-stakeholder marketing strategies',
                'sample_answer_outline': 'The candidate should outline a diagnostic approach including brand perception surveys, win/loss analysis, and content audits. They should then propose a plan that addresses messaging, channel strategy, and thought leadership specifically targeting business buyers, while explaining how to measure perception shift over time.',
            },
            {
                'question_text': 'How do you determine the right marketing attribution model for a B2B company with a long and complex sales cycle?',
                'category': 'technical',
                'difficulty': 'medium',
                'what_it_tests': 'Understanding of marketing attribution methodologies and analytical rigor in measuring marketing impact',
                'sample_answer_outline': 'A strong answer compares different attribution models such as first-touch, last-touch, linear, and multi-touch, and explains the trade-offs of each. The candidate should discuss how sales cycle length, number of touchpoints, and data availability influence model selection, and describe how they would implement and iterate on the chosen approach.',
            },
            {
                'question_text': 'Describe a time when a major marketing campaign failed to deliver expected results. How did you handle it with your team and the broader organization?',
                'category': 'behavioral',
                'difficulty': 'medium',
                'what_it_tests': 'Accountability, transparency in failure, and ability to extract learnings from underperformance',
                'sample_answer_outline': 'The candidate should own the failure without deflecting, explain how they communicated results honestly to stakeholders, and detail the post-mortem process. A good answer shows how the learnings were applied to future campaigns and how the candidate supported their team through the setback.',
            },
            {
                'question_text': 'A competitor has just launched an aggressive pricing campaign that is impacting our market share. What is your immediate and long-term response?',
                'category': 'situational',
                'difficulty': 'medium',
                'what_it_tests': 'Competitive strategy thinking and ability to respond to market threats without panic',
                'sample_answer_outline': 'The candidate should describe an immediate response focused on intelligence gathering and messaging reinforcement, followed by a longer-term strategy that emphasizes differentiation on value rather than engaging in a price war. They should discuss how to arm sales with competitive battle cards and how to monitor the impact over time.',
            },
            {
                'question_text': 'How do you evaluate whether to build an in-house marketing capability versus outsourcing to an agency or contractor?',
                'category': 'leadership',
                'difficulty': 'easy',
                'what_it_tests': 'Organizational design thinking and resource allocation judgment',
                'sample_answer_outline': 'A good answer considers factors like strategic importance, volume and consistency of need, cost comparison, speed to execution, and institutional knowledge retention. The candidate should provide examples of capabilities they have built in-house versus outsourced and explain the reasoning behind those decisions.',
            },
            {
                'question_text': 'How do you ensure ethical marketing practices while still driving aggressive growth targets?',
                'category': 'culture',
                'difficulty': 'easy',
                'what_it_tests': 'Integrity and values alignment in balancing growth pressure with ethical responsibility',
                'sample_answer_outline': 'The candidate should articulate clear principles around truthful messaging, data privacy, and inclusive representation. They should give examples of times they pushed back on growth tactics that compromised ethics and explain how they embed ethical standards into team processes and review cycles.',
            },
            {
                'question_text': 'Marketing qualified leads are up 40% but sales conversion rates have dropped significantly. Walk me through how you would investigate and solve this problem.',
                'category': 'problem_solving',
                'difficulty': 'medium',
                'what_it_tests': 'Funnel analysis skills and ability to diagnose lead quality versus sales process issues',
                'sample_answer_outline': 'A strong answer starts with examining lead scoring criteria and whether MQL definitions have drifted, then analyzes conversion by source, segment, and sales rep. The candidate should discuss collaborating with sales to understand qualitative feedback and propose adjustments to scoring, nurturing, or handoff processes based on the findings.',
            },
        ],
    },
    {
        'slug': 'marketing-director',
        'title': 'Marketing Director',
        'department': 'Marketing',
        'seniority_level': 'lead',
        'description': 'The Marketing Director leads a team of marketing managers and specialists to execute on the company marketing strategy across multiple channels and programs. This role bridges executive vision with operational execution, managing significant budgets and driving measurable business results.',
        'responsibilities': [
            'Translate marketing strategy into executable plans with clear milestones and KPIs',
            'Manage and mentor a team of marketing managers and individual contributors',
            'Own channel-level budgets and optimize spend allocation based on performance data',
            'Coordinate cross-functional campaigns across content, digital, events, and product marketing',
            'Establish and refine marketing processes, workflows, and reporting standards',
            'Partner with sales leadership to ensure marketing programs support pipeline goals',
        ],
        'key_skills': [
            'Team leadership and talent development',
            'Campaign strategy and multi-channel marketing',
            'Marketing operations and process optimization',
            'Budget management and ROI analysis',
            'Stakeholder communication and project management',
            'Data analysis and performance reporting',
        ],
        'assessment_slugs': ['marketing', 'behavioral'],
        'questions': [
            {
                'question_text': 'Walk me through how you would plan and execute an integrated marketing campaign from strategy through measurement. What frameworks do you use?',
                'category': 'technical',
                'difficulty': 'medium',
                'what_it_tests': 'Campaign planning methodology and understanding of integrated marketing execution',
                'sample_answer_outline': 'A strong answer walks through audience definition, messaging framework, channel selection, creative development, timeline and budget planning, launch execution, and measurement. The candidate should reference specific frameworks they use and explain how they coordinate across teams to ensure consistency.',
            },
            {
                'question_text': 'Tell me about a time you had to manage a team member who was underperforming. What steps did you take and what was the result?',
                'category': 'behavioral',
                'difficulty': 'medium',
                'what_it_tests': 'People management skills and ability to handle difficult performance conversations constructively',
                'sample_answer_outline': 'The candidate should describe a specific situation with empathy and professionalism, explain how they identified the root cause of underperformance, detail the support plan they put in place, and share the outcome. A good answer shows both accountability and compassion.',
            },
            {
                'question_text': 'Two of your marketing managers are in conflict over resource allocation for their respective programs. Both programs are important. How do you resolve this?',
                'category': 'situational',
                'difficulty': 'medium',
                'what_it_tests': 'Conflict resolution skills and ability to make objective resource allocation decisions',
                'sample_answer_outline': 'The candidate should describe hearing both sides objectively, then making a data-driven decision based on business impact, strategic priority, and timing. They should explain how they communicate the decision transparently and ensure the deprioritized manager feels heard and supported.',
            },
            {
                'question_text': 'How do you develop junior marketers into future leaders within your team?',
                'category': 'leadership',
                'difficulty': 'easy',
                'what_it_tests': 'Commitment to talent development and approach to growing team capabilities',
                'sample_answer_outline': 'A good answer discusses creating stretch opportunities, establishing mentorship structures, providing regular feedback beyond formal reviews, and building individual development plans. The candidate should give specific examples of people they have developed and the techniques that were most effective.',
            },
            {
                'question_text': 'How do you foster a culture of experimentation and learning on your marketing team while still maintaining accountability for results?',
                'category': 'culture',
                'difficulty': 'medium',
                'what_it_tests': 'Ability to balance innovation with execution discipline in a team environment',
                'sample_answer_outline': 'The candidate should describe allocating specific budget or time for experimentation, establishing a test-and-learn framework with clear hypotheses and success criteria, and celebrating learnings from failures as well as successes. They should explain how they protect core programs while enabling innovation.',
            },
            {
                'question_text': 'Your content marketing efforts are generating high traffic but very low conversion to leads. Diagnose the potential issues and propose solutions.',
                'category': 'problem_solving',
                'difficulty': 'medium',
                'what_it_tests': 'Funnel optimization thinking and ability to connect content strategy to business outcomes',
                'sample_answer_outline': 'A strong answer examines potential issues at multiple levels including traffic quality and intent, content-to-offer alignment, CTA placement and messaging, landing page experience, and lead capture friction. The candidate should propose a systematic testing approach to identify and fix the breakdown point.',
            },
            {
                'question_text': 'Explain how you would build a marketing reporting dashboard that tells a meaningful story to both your CMO and your team. What metrics would you include and why?',
                'category': 'technical',
                'difficulty': 'hard',
                'what_it_tests': 'Understanding of marketing metrics hierarchy and ability to tailor data storytelling for different audiences',
                'sample_answer_outline': 'The candidate should differentiate between executive-level metrics focused on pipeline and revenue impact versus team-level operational metrics for optimization. They should discuss leading versus lagging indicators, explain how metrics connect to business objectives, and describe how they use the dashboard to drive decisions rather than just report status.',
            },
            {
                'question_text': 'Describe a time when you had to push back on a request from a senior executive that you believed was not the right marketing approach. How did you handle it?',
                'category': 'behavioral',
                'difficulty': 'hard',
                'what_it_tests': 'Ability to manage up with conviction while maintaining strong relationships',
                'sample_answer_outline': 'The candidate should describe the situation and their reasoning, how they prepared a data-driven counter-proposal, how they communicated their perspective respectfully, and the outcome. A good answer shows both courage and diplomacy.',
            },
            {
                'question_text': 'You discover that a significant portion of your marketing spend has been going to a channel that shows strong vanity metrics but poor downstream conversion. Your team loves this channel. What do you do?',
                'category': 'situational',
                'difficulty': 'hard',
                'what_it_tests': 'Data-driven decision making when it conflicts with team preferences and sunk cost bias',
                'sample_answer_outline': 'A strong answer describes presenting the full-funnel data transparently to the team, facilitating a discussion about what the data means, and making a clear decision to reallocate spend. The candidate should explain how they bring the team along rather than just dictating, while still being decisive about following the data.',
            },
            {
                'question_text': 'How do you set goals and priorities for your team at the beginning of each quarter? Walk me through your planning process.',
                'category': 'leadership',
                'difficulty': 'medium',
                'what_it_tests': 'Planning discipline and ability to connect team activities to business objectives',
                'sample_answer_outline': 'The candidate should describe a structured planning process that starts with business objectives, cascades into marketing goals, and breaks down into team and individual priorities. They should discuss how they involve the team in planning, how they handle competing priorities, and how they build in flexibility for changing conditions.',
            },
            {
                'question_text': 'What does a healthy feedback culture look like on a marketing team, and how do you build one?',
                'category': 'culture',
                'difficulty': 'easy',
                'what_it_tests': 'Values around open communication and continuous improvement within creative teams',
                'sample_answer_outline': 'A good answer discusses modeling vulnerability by giving and receiving feedback openly, establishing regular feedback rituals like creative reviews and retrospectives, and separating feedback on work from feedback on people. The candidate should acknowledge the unique challenges of giving feedback on creative work.',
            },
            {
                'question_text': 'Your company is preparing to launch a product in a category where a dominant competitor controls the narrative. How would you develop a positioning strategy that differentiates effectively?',
                'category': 'problem_solving',
                'difficulty': 'hard',
                'what_it_tests': 'Competitive positioning skills and strategic thinking about market differentiation',
                'sample_answer_outline': 'The candidate should describe conducting competitive messaging analysis, identifying gaps or weaknesses in the competitor narrative, finding a unique angle based on genuine product strengths, and building a positioning framework. They should discuss how to validate the positioning with customers and how to amplify the message through the right channels.',
            },
        ],
    },
    {
        'slug': 'growth-marketing-manager',
        'title': 'Growth Marketing Manager',
        'department': 'Marketing',
        'seniority_level': 'senior',
        'description': 'The Growth Marketing Manager drives user acquisition, activation, and retention through data-driven experimentation and optimization across the full marketing funnel. This role combines analytical rigor with creative campaign execution to deliver measurable growth against aggressive targets.',
        'responsibilities': [
            'Design and execute growth experiments across acquisition channels including paid, organic, email, and referral',
            'Analyze funnel performance data to identify bottlenecks and opportunities for conversion improvement',
            'Manage and optimize paid media budgets across platforms to maximize customer acquisition efficiency',
            'Collaborate with product and engineering teams to implement growth features and tracking infrastructure',
            'Build and refine lifecycle marketing programs that improve activation, retention, and expansion',
            'Report on growth metrics and experiment results to leadership with actionable recommendations',
        ],
        'key_skills': [
            'Growth experimentation and A/B testing methodology',
            'Paid media management across multiple platforms',
            'Marketing analytics and data visualization',
            'Conversion rate optimization and funnel analysis',
            'SQL and marketing automation tools proficiency',
            'Lifecycle and retention marketing',
        ],
        'assessment_slugs': ['marketing', 'behavioral'],
        'questions': [
            {
                'question_text': 'Walk me through how you would design a growth experiment from hypothesis to analysis. What is your process for deciding what to test and how to measure results?',
                'category': 'technical',
                'difficulty': 'medium',
                'what_it_tests': 'Experimentation methodology and understanding of statistical rigor in growth marketing',
                'sample_answer_outline': 'A strong answer covers forming a hypothesis based on data analysis, defining the success metric and minimum detectable effect, calculating sample size requirements, designing the test with proper controls, running the experiment for appropriate duration, and analyzing results with statistical significance in mind. The candidate should emphasize avoiding common pitfalls like peeking at results early.',
            },
            {
                'question_text': 'Tell me about a growth experiment that completely failed. What did you learn and how did it influence your subsequent approach?',
                'category': 'behavioral',
                'difficulty': 'easy',
                'what_it_tests': 'Learning orientation and resilience when experiments do not produce desired results',
                'sample_answer_outline': 'The candidate should describe a specific failed experiment with honest reflection on what went wrong, whether it was the hypothesis, execution, or measurement. They should explain the concrete learnings and how those influenced their experimentation framework going forward.',
            },
            {
                'question_text': 'Your customer acquisition cost has increased 50% over the past quarter across all paid channels while conversion rates remain flat. What is your diagnostic and action plan?',
                'category': 'situational',
                'difficulty': 'hard',
                'what_it_tests': 'Ability to diagnose complex performance issues across paid channels and take corrective action',
                'sample_answer_outline': 'A strong answer investigates multiple potential causes including market saturation, increased competition in auctions, audience fatigue, creative staleness, landing page changes, and seasonal factors. The candidate should describe a systematic approach to isolating the cause and propose both immediate optimizations and longer-term strategic shifts like channel diversification.',
            },
            {
                'question_text': 'How do you prioritize which growth initiatives to pursue when you have more ideas than resources? What framework do you use?',
                'category': 'leadership',
                'difficulty': 'medium',
                'what_it_tests': 'Strategic prioritization skills and ability to allocate limited resources for maximum impact',
                'sample_answer_outline': 'The candidate should reference a prioritization framework such as ICE, RICE, or a custom model that considers impact, confidence, ease, and strategic alignment. They should explain how they gather input from cross-functional partners, how they balance quick wins against larger bets, and how they communicate priorities and trade-offs to stakeholders.',
            },
            {
                'question_text': 'Growth marketing can sometimes create tension between short-term metric optimization and long-term brand health. How do you navigate this balance?',
                'category': 'culture',
                'difficulty': 'medium',
                'what_it_tests': 'Awareness of the broader impact of growth tactics and commitment to sustainable growth practices',
                'sample_answer_outline': 'A good answer acknowledges the real tension and provides specific examples of guardrails, such as brand guidelines for ad creative, frequency caps, and user experience standards. The candidate should explain how they set boundaries for aggressive tactics and when they would sacrifice short-term metrics to protect the brand.',
            },
            {
                'question_text': 'You notice that users acquired from your highest-volume paid channel have significantly lower lifetime value than users from organic channels. How do you approach this problem?',
                'category': 'problem_solving',
                'difficulty': 'hard',
                'what_it_tests': 'Ability to think beyond top-of-funnel metrics and optimize for downstream business value',
                'sample_answer_outline': 'The candidate should analyze the issue at multiple levels including audience targeting, ad messaging setting wrong expectations, onboarding experience, and product-market fit for the paid audience. They should propose a plan that could include refining targeting, improving post-acquisition nurturing, adjusting bidding to optimize for LTV rather than volume, or shifting budget.',
            },
            {
                'question_text': 'Explain how you would set up proper marketing attribution and tracking for a multi-channel growth program. What tools and methodologies would you use?',
                'category': 'technical',
                'difficulty': 'hard',
                'what_it_tests': 'Technical knowledge of attribution systems, tracking infrastructure, and data integration',
                'sample_answer_outline': 'A strong answer covers UTM tagging conventions, pixel and server-side tracking implementation, choosing an attribution model appropriate for the business, integrating data across platforms into a single source of truth, and accounting for limitations like cross-device tracking and privacy regulations. The candidate should demonstrate awareness of the iOS privacy changes and their impact.',
            },
            {
                'question_text': 'Describe a time when you had to influence engineers or product managers to prioritize a growth-related feature or infrastructure request. How did you make your case?',
                'category': 'behavioral',
                'difficulty': 'medium',
                'what_it_tests': 'Cross-functional influence skills and ability to communicate marketing needs to technical stakeholders',
                'sample_answer_outline': 'The candidate should describe quantifying the business impact in terms engineers and PMs care about, presenting data and projections clearly, and being flexible on implementation approach while firm on the outcome needed. A good answer shows empathy for engineering priorities and a collaborative rather than demanding approach.',
            },
            {
                'question_text': 'Your CEO asks you to double the lead volume within 60 days without increasing budget. Walk me through your approach.',
                'category': 'situational',
                'difficulty': 'medium',
                'what_it_tests': 'Creative resourcefulness and ability to find leverage within existing programs and assets',
                'sample_answer_outline': 'The candidate should explore conversion rate optimization on existing traffic, referral and viral loops, partnership and co-marketing opportunities, content repurposing for organic channels, email and lifecycle optimization, and community activation. They should be realistic about what is achievable and communicate expected trade-offs.',
            },
            {
                'question_text': 'How do you build a testing roadmap for your team? How far ahead do you plan and how do you balance planned tests versus reactive opportunities?',
                'category': 'leadership',
                'difficulty': 'easy',
                'what_it_tests': 'Planning and organizational skills in a fast-moving growth environment',
                'sample_answer_outline': 'A good answer describes maintaining a testing backlog prioritized by potential impact, planning a quarter ahead at a high level while keeping weekly execution flexible, and reserving capacity for reactive tests. The candidate should explain how they document and share learnings and how they decide when to scale winning experiments.',
            },
            {
                'question_text': 'How do you stay current with changes in digital marketing platforms, privacy regulations, and growth tactics? How has your approach evolved in the past two years?',
                'category': 'culture',
                'difficulty': 'easy',
                'what_it_tests': 'Intellectual curiosity and commitment to continuous learning in a rapidly evolving field',
                'sample_answer_outline': 'The candidate should describe specific resources, communities, and practices they use to stay informed. They should give concrete examples of how recent changes like privacy regulations or AI tools have impacted their work and how they adapted their approach in response.',
            },
            {
                'question_text': 'You are running paid campaigns on three platforms simultaneously. Platform A has the lowest CPA but longest sales cycle, Platform B has moderate CPA with the highest close rate, and Platform C has the highest CPA but the largest deal sizes. How do you allocate your budget?',
                'category': 'problem_solving',
                'difficulty': 'medium',
                'what_it_tests': 'Ability to think about marketing efficiency holistically across multiple dimensions beyond simple CPA',
                'sample_answer_outline': 'A strong answer calculates or estimates the full customer acquisition cost and LTV for each platform rather than optimizing on CPA alone. The candidate should discuss how pipeline velocity, deal size, and close rate factor into a blended ROI analysis, and explain how they would test shifting budget allocation incrementally while monitoring downstream impact.',
            },
        ],
    },
    {
        'slug': 'seo-specialist',
        'title': 'SEO Specialist',
        'department': 'Marketing',
        'seniority_level': 'mid',
        'description': 'The SEO Specialist is responsible for improving organic search visibility and driving qualified traffic through technical optimization, content strategy, and link building. This role requires a blend of technical expertise, content sensibility, and analytical skills to grow organic as a scalable acquisition channel.',
        'responsibilities': [
            'Conduct technical SEO audits and implement fixes for crawlability, indexation, and site performance',
            'Perform keyword research and competitive analysis to identify content opportunities and search demand',
            'Optimize on-page elements including titles, meta descriptions, headings, internal linking, and schema markup',
            'Develop and execute link building strategies that improve domain authority ethically',
            'Monitor search performance using Google Search Console, analytics platforms, and rank tracking tools',
            'Collaborate with content and engineering teams to ensure SEO best practices are embedded in site development',
        ],
        'key_skills': [
            'Technical SEO including site architecture and crawl optimization',
            'Keyword research and search intent analysis',
            'On-page optimization and content SEO',
            'Google Search Console and analytics platforms',
            'HTML, structured data, and basic web development understanding',
            'Link building and off-page SEO strategy',
        ],
        'assessment_slugs': ['marketing', 'behavioral'],
        'questions': [
            {
                'question_text': 'We just migrated our website to a new domain and organic traffic has dropped 40%. Walk me through your step-by-step process for diagnosing and resolving this issue.',
                'category': 'technical',
                'difficulty': 'hard',
                'what_it_tests': 'Deep understanding of site migration SEO and ability to diagnose technical issues systematically',
                'sample_answer_outline': 'A strong answer covers checking redirect mapping for completeness and accuracy, verifying Google Search Console setup for the new domain, analyzing crawl errors and index coverage reports, reviewing robots.txt and sitemap submissions, checking for canonical tag issues, and monitoring backlink profile transfer. The candidate should prioritize actions by likely impact.',
            },
            {
                'question_text': 'Tell me about a time when your SEO recommendation conflicted with what the design or product team wanted to implement. How did you resolve it?',
                'category': 'behavioral',
                'difficulty': 'medium',
                'what_it_tests': 'Ability to advocate for SEO priorities while collaborating effectively with cross-functional teams',
                'sample_answer_outline': 'The candidate should describe a specific conflict, explain how they quantified the SEO impact to make a data-driven case, and show willingness to find a compromise that addressed both SEO needs and design or product goals. A good answer demonstrates diplomatic communication and creative problem solving.',
            },
            {
                'question_text': 'A major competitor just launched a content hub that is ranking for 200 keywords you are targeting. How do you respond?',
                'category': 'situational',
                'difficulty': 'medium',
                'what_it_tests': 'Competitive SEO strategy and ability to respond to competitive threats with a clear plan',
                'sample_answer_outline': 'The candidate should describe analyzing the competitor content hub structure, identifying gaps in their coverage, assessing keyword difficulty and search intent for the contested terms, and developing a content strategy that differentiates on depth, freshness, or unique data. They should prioritize which keywords to contest versus which to find alternative angles for.',
            },
            {
                'question_text': 'How do you communicate the value of SEO to stakeholders who want to see immediate results and do not understand the long-term nature of organic search?',
                'category': 'leadership',
                'difficulty': 'easy',
                'what_it_tests': 'Ability to manage expectations and communicate SEO value to non-technical stakeholders',
                'sample_answer_outline': 'A good answer describes setting realistic timelines upfront, using forecasting models to project organic growth, showing incremental progress through leading indicators like rankings and impressions before traffic materializes, and comparing the compounding ROI of SEO against paid channels over time.',
            },
            {
                'question_text': 'What is your approach to ethical SEO? Where do you draw the line between aggressive optimization and manipulative practices?',
                'category': 'culture',
                'difficulty': 'easy',
                'what_it_tests': 'Professional ethics and understanding of sustainable versus risky SEO practices',
                'sample_answer_outline': 'The candidate should clearly distinguish between white-hat and black-hat practices, explain why sustainable approaches matter for long-term brand health, and give specific examples of tactics they would refuse to implement. They should demonstrate understanding of Google guidelines and the business risk of penalties.',
            },
            {
                'question_text': 'Our blog gets 50,000 monthly organic visitors but contributes very few conversions. How would you investigate this and develop a plan to improve organic conversion rates?',
                'category': 'problem_solving',
                'difficulty': 'medium',
                'what_it_tests': 'Ability to connect SEO traffic to business outcomes and optimize beyond just rankings and traffic',
                'sample_answer_outline': 'A strong answer analyzes search intent alignment for top-traffic pages, evaluates whether the content targets bottom-of-funnel versus informational keywords, reviews on-page conversion paths and CTAs, and proposes a strategy to either better monetize informational traffic through nurturing or shift content investment toward higher-intent keywords.',
            },
            {
                'question_text': 'Explain how you approach technical SEO for a large JavaScript-heavy single-page application. What specific challenges would you anticipate and how would you address them?',
                'category': 'technical',
                'difficulty': 'hard',
                'what_it_tests': 'Technical depth in JavaScript SEO and understanding of rendering, crawling, and indexation challenges',
                'sample_answer_outline': 'The candidate should discuss Googlebot rendering capabilities and limitations, server-side rendering versus dynamic rendering options, ensuring crawlable link structures, handling lazy-loaded content, managing URL routing and history API, and testing with tools like the URL Inspection tool. They should show awareness of the trade-offs between different rendering approaches.',
            },
            {
                'question_text': 'Describe your process for conducting keyword research for a new product or feature launch. How do you go from zero to a prioritized keyword list?',
                'category': 'technical',
                'difficulty': 'medium',
                'what_it_tests': 'Keyword research methodology and ability to align search demand with business objectives',
                'sample_answer_outline': 'A good answer describes starting with seed keywords from product positioning, using tools to expand the keyword universe, analyzing search volume and difficulty and intent, mapping keywords to funnel stages, clustering related terms into topic groups, and prioritizing based on business value and competitive opportunity.',
            },
            {
                'question_text': 'Tell me about a time you identified an SEO opportunity that others had overlooked. What was the insight and what were the results?',
                'category': 'behavioral',
                'difficulty': 'easy',
                'what_it_tests': 'Proactive thinking and ability to uncover non-obvious optimization opportunities',
                'sample_answer_outline': 'The candidate should describe a specific instance where their analysis or curiosity revealed an untapped opportunity, explain the data or insight that led to the discovery, detail the implementation, and share measurable results in terms of rankings, traffic, or conversions.',
            },
            {
                'question_text': 'Google rolls out a core algorithm update and your site loses 25% of its organic traffic overnight. What is your immediate response and long-term recovery plan?',
                'category': 'situational',
                'difficulty': 'hard',
                'what_it_tests': 'Crisis response for algorithm updates and understanding of Google quality guidelines',
                'sample_answer_outline': 'A strong answer starts with analyzing which pages and queries were most affected, comparing against known characteristics of the update, assessing content quality against Google quality rater guidelines, and developing a recovery plan that addresses root causes rather than chasing quick fixes. The candidate should discuss communicating the impact and plan to stakeholders with appropriate urgency and realism.',
            },
            {
                'question_text': 'How do you stay up to date with SEO changes, and how do you differentiate between genuine algorithm shifts and normal ranking fluctuations?',
                'category': 'culture',
                'difficulty': 'easy',
                'what_it_tests': 'Professional development habits and analytical judgment in an industry with frequent changes',
                'sample_answer_outline': 'The candidate should name specific reliable information sources, explain how they validate claims by checking their own data before reacting, and describe their approach to separating signal from noise. They should demonstrate skepticism toward SEO myths and reliance on testing over speculation.',
            },
            {
                'question_text': 'You have limited engineering resources and a list of 15 technical SEO fixes. How do you prioritize which issues to address first and build a business case for engineering time?',
                'category': 'problem_solving',
                'difficulty': 'medium',
                'what_it_tests': 'Prioritization skills and ability to quantify SEO impact for resource allocation decisions',
                'sample_answer_outline': 'The candidate should describe evaluating each issue based on estimated traffic impact, affected page count, implementation effort, and risk if left unresolved. They should explain how to translate technical SEO metrics into business language that resonates with engineering and product managers, and how to package the request to maximize the chance of getting resources allocated.',
            },
        ],
    },
    {
        'slug': 'content-strategist',
        'title': 'Content Strategist',
        'department': 'Marketing',
        'seniority_level': 'mid',
        'description': 'The Content Strategist develops and executes the content strategy that drives brand awareness, audience engagement, and lead generation across all content formats and channels. This role requires deep understanding of audience needs, editorial planning skills, and the ability to measure content effectiveness against business goals.',
        'responsibilities': [
            'Develop and maintain the content strategy and editorial calendar aligned with marketing and business objectives',
            'Research audience personas, pain points, and content consumption preferences to guide content creation',
            'Plan, write, and edit high-quality content across formats including blog posts, whitepapers, case studies, and social media',
            'Establish content governance standards including brand voice, style guidelines, and quality benchmarks',
            'Analyze content performance metrics and use insights to optimize the content program',
            'Collaborate with subject matter experts, designers, and distribution teams to produce and amplify content',
        ],
        'key_skills': [
            'Content strategy and editorial planning',
            'Exceptional writing and editing across formats',
            'Audience research and persona development',
            'Content analytics and performance measurement',
            'SEO content optimization and keyword integration',
            'Project management and editorial workflow coordination',
        ],
        'assessment_slugs': ['marketing', 'behavioral'],
        'questions': [
            {
                'question_text': 'How would you develop a content strategy for a B2B SaaS company entering a crowded market? Walk me through your process from research to editorial calendar.',
                'category': 'technical',
                'difficulty': 'hard',
                'what_it_tests': 'End-to-end content strategy development methodology and ability to differentiate in competitive markets',
                'sample_answer_outline': 'A strong answer covers audience and buyer persona research, competitive content audit to identify gaps and opportunities, defining content pillars tied to product differentiators, mapping content to funnel stages, building a distribution plan alongside the editorial calendar, and establishing KPIs for each content type. The candidate should show how they would create a distinctive editorial voice in a crowded space.',
            },
            {
                'question_text': 'Tell me about a piece of content you created that significantly outperformed expectations. What made it successful and how did you replicate that success?',
                'category': 'behavioral',
                'difficulty': 'easy',
                'what_it_tests': 'Content intuition, ability to analyze what drives content performance, and learning from success',
                'sample_answer_outline': 'The candidate should describe a specific content piece, explain what they believe drove its success whether that was topic timing, format, distribution, or audience resonance, and detail how they applied those lessons systematically. A good answer shows both creative instinct and analytical follow-through.',
            },
            {
                'question_text': 'A senior executive insists on publishing a thought leadership piece that you believe is too self-promotional and will not resonate with your audience. How do you handle this?',
                'category': 'situational',
                'difficulty': 'medium',
                'what_it_tests': 'Ability to protect content quality standards while managing stakeholder relationships diplomatically',
                'sample_answer_outline': 'The candidate should describe acknowledging the executive perspective and the value of their expertise, then making a case for an audience-first approach using data on what content performs well. They should propose a revised angle that incorporates the executive insights while adding genuine value for the reader, and explain how they would handle it if the executive insists on the original approach.',
            },
            {
                'question_text': 'How do you ensure consistent brand voice and quality across content produced by multiple writers, freelancers, and contributors?',
                'category': 'leadership',
                'difficulty': 'medium',
                'what_it_tests': 'Content governance skills and ability to scale quality across a distributed content operation',
                'sample_answer_outline': 'A good answer describes creating comprehensive brand voice and style guidelines with examples, developing content templates and briefs that set clear expectations, establishing an editorial review process with feedback loops, and investing in onboarding and training for new contributors. The candidate should discuss how to balance consistency with allowing individual voices to shine.',
            },
            {
                'question_text': 'What role does empathy play in content strategy? How do you ensure your content genuinely serves the audience rather than just serving company messaging goals?',
                'category': 'culture',
                'difficulty': 'easy',
                'what_it_tests': 'Audience-first mindset and commitment to creating genuinely valuable content',
                'sample_answer_outline': 'The candidate should discuss specific research methods for understanding audience needs like interviews, surveys, community listening, and search intent analysis. They should explain how they balance audience value with business objectives and give examples of times they pushed back on content that prioritized company messaging over reader value.',
            },
            {
                'question_text': 'Your content library has 500 published blog posts but traffic has plateaued and engagement is declining. How would you audit the existing content and develop a plan to reinvigorate performance?',
                'category': 'problem_solving',
                'difficulty': 'hard',
                'what_it_tests': 'Content audit skills and ability to develop a data-driven content optimization and pruning strategy',
                'sample_answer_outline': 'A strong answer describes a systematic content audit categorizing posts by performance, relevance, and quality, then developing a strategy to update and republish high-potential pieces, consolidate thin or overlapping content, prune truly outdated material, and fill identified topic gaps. The candidate should explain the expected impact of each action and how to prioritize.',
            },
            {
                'question_text': 'Explain how you measure content marketing ROI. What metrics do you track at each funnel stage and how do you attribute revenue to content efforts?',
                'category': 'technical',
                'difficulty': 'medium',
                'what_it_tests': 'Understanding of content analytics and ability to connect content performance to business outcomes',
                'sample_answer_outline': 'The candidate should describe a tiered measurement framework covering awareness metrics like traffic and shares, engagement metrics like time on page and scroll depth, conversion metrics like email signups and content downloads, and revenue metrics like influenced pipeline and content-attributed deals. They should discuss attribution challenges and practical approaches to solving them.',
            },
            {
                'question_text': 'Describe a time when you had to produce high-quality content under a very tight deadline with limited resources. How did you manage the situation?',
                'category': 'behavioral',
                'difficulty': 'medium',
                'what_it_tests': 'Ability to maintain content quality under pressure and manage competing demands',
                'sample_answer_outline': 'The candidate should describe a specific scenario, explain how they triaged and prioritized, what shortcuts they took and which quality standards they refused to compromise on, and how the content ultimately performed. A good answer demonstrates both pragmatism and commitment to quality.',
            },
            {
                'question_text': 'Your company is launching a new product in 6 weeks and you need to have a full content package ready including a landing page, launch blog post, email sequence, social campaign, and sales enablement materials. How do you plan and execute this?',
                'category': 'situational',
                'difficulty': 'hard',
                'what_it_tests': 'Project management skills and ability to coordinate multi-format content production under deadline pressure',
                'sample_answer_outline': 'A strong answer starts with gathering product positioning and key messages from product marketing, then builds a reverse-timeline project plan with milestones and dependencies. The candidate should discuss how they would brief designers and writers, establish review cycles, and build in buffer time. They should show awareness of which pieces need to be produced first due to dependencies.',
            },
            {
                'question_text': 'How do you decide when to gate content behind a form versus offering it freely? What is your philosophy on gated content?',
                'category': 'leadership',
                'difficulty': 'easy',
                'what_it_tests': 'Strategic thinking about content distribution and understanding of the trade-off between lead capture and reach',
                'sample_answer_outline': 'A good answer weighs the value exchange from the reader perspective, considers the content type and its position in the buyer journey, and discusses the trade-off between maximizing reach and generating leads. The candidate should present a clear framework for deciding what to gate and show awareness of the trend toward ungating.',
            },
            {
                'question_text': 'How do you approach incorporating AI tools into your content creation workflow while maintaining quality and originality?',
                'category': 'culture',
                'difficulty': 'medium',
                'what_it_tests': 'Thoughtfulness about AI adoption in content creation and commitment to editorial standards',
                'sample_answer_outline': 'The candidate should demonstrate a nuanced view that leverages AI for research, outlines, and drafts while maintaining human oversight for voice, accuracy, and original insight. They should discuss where AI adds genuine value versus where it falls short, and explain their quality control process for AI-assisted content.',
            },
            {
                'question_text': 'You have data showing that short-form social content drives the most engagement but long-form thought leadership generates the most qualified leads. How do you balance your content mix and resource allocation?',
                'category': 'problem_solving',
                'difficulty': 'medium',
                'what_it_tests': 'Strategic resource allocation and ability to optimize content programs across multiple objectives',
                'sample_answer_outline': 'The candidate should analyze this as a portfolio optimization problem, considering the different business objectives each format serves, the team capacity required for each, and how the formats can work together in a content ecosystem. A good answer proposes a mix that supports both objectives and explains how short-form content can amplify and distribute long-form assets.',
            },
        ],
    },
]
