OPERATIONS_ROLES = [
    {
        'slug': 'chief-operating-officer',
        'title': 'Chief Operating Officer',
        'department': 'Operations',
        'seniority_level': 'executive',
        'description': 'The Chief Operating Officer is responsible for overseeing the day-to-day administrative and operational functions of the business, translating company strategy into actionable operational plans. This executive partners with the CEO to ensure organizational efficiency, scalability, and operational excellence across all departments.',
        'responsibilities': [
            'Define and execute the overall operational strategy aligned with company goals and growth targets',
            'Oversee daily operations across all departments ensuring efficiency, quality, and cost-effectiveness',
            'Develop and implement scalable processes, systems, and infrastructure to support business growth',
            'Partner with the CEO, CFO, and executive leadership to align operational capabilities with strategic objectives',
            'Establish operational KPIs and performance management frameworks across the organization',
            'Lead organizational change initiatives and drive continuous improvement culture company-wide',
        ],
        'key_skills': [
            'Strategic planning and executive leadership',
            'Operational excellence and process optimization',
            'Organizational design and change management',
            'Financial acumen and P&L management',
            'Cross-functional collaboration and stakeholder management',
            'Risk management and business continuity planning',
        ],
        'assessment_slugs': ['behavioral'],
        'questions': [
            {
                'question_text': 'How would you approach assessing and redesigning the operational infrastructure of a company that has grown rapidly but is now experiencing significant inefficiencies and scaling challenges?',
                'category': 'technical',
                'difficulty': 'hard',
                'what_it_tests': 'Ability to diagnose systemic operational issues and design scalable solutions at an enterprise level',
                'sample_answer_outline': 'A strong answer covers conducting a thorough operational audit across people, processes, and technology, identifying bottlenecks and single points of failure, and prioritizing improvements based on business impact. The candidate should articulate a phased transformation roadmap that balances quick wins with structural changes, explain how they would build buy-in across the organization, and describe metrics for tracking progress.',
            },
            {
                'question_text': 'Tell me about a time you led a major organizational transformation that faced significant resistance. How did you navigate the change and what was the outcome?',
                'category': 'behavioral',
                'difficulty': 'hard',
                'what_it_tests': 'Change management leadership and ability to drive transformation through resistance',
                'sample_answer_outline': 'The candidate should describe a specific transformation with clear context on the scope and stakes involved. They should explain the sources of resistance, how they built a coalition of supporters, the communication strategy they used, and how they addressed concerns without compromising the vision. A good answer includes measurable outcomes and honest reflection on what they would do differently.',
            },
            {
                'question_text': 'The company is planning to double in headcount over the next 18 months while simultaneously entering two new markets. How do you ensure operational readiness without sacrificing quality or culture?',
                'category': 'situational',
                'difficulty': 'hard',
                'what_it_tests': 'Strategic scaling ability and capacity to plan operational infrastructure ahead of growth',
                'sample_answer_outline': 'A strong candidate would outline a comprehensive scaling plan covering hiring infrastructure, onboarding systems, process documentation, technology investments, and cultural preservation mechanisms. They should discuss phasing the scaling to avoid overwhelming the organization, establishing leading indicators to detect quality degradation early, and building operational playbooks for the new markets.',
            },
            {
                'question_text': 'How do you build and maintain alignment across multiple department heads who have competing priorities and limited shared resources?',
                'category': 'leadership',
                'difficulty': 'medium',
                'what_it_tests': 'Cross-functional leadership and ability to create organizational alignment at the executive level',
                'sample_answer_outline': 'The candidate should discuss establishing shared objectives that transcend departmental boundaries, creating transparent resource allocation frameworks, and facilitating regular cross-functional planning sessions. They should describe how they make difficult trade-off decisions, communicate those decisions clearly, and ensure department heads feel heard even when their requests are not fully met.',
            },
            {
                'question_text': 'What is your philosophy on building an operational culture that balances process discipline with innovation and agility?',
                'category': 'culture',
                'difficulty': 'medium',
                'what_it_tests': 'Values around organizational culture and ability to balance structure with flexibility',
                'sample_answer_outline': 'A good answer addresses the tension between standardization and creativity, explaining how mature processes free up capacity for innovation rather than stifling it. The candidate should give concrete examples of how they have built cultures that value both operational rigor and experimentation, and describe specific mechanisms they use to prevent bureaucracy from slowing the organization down.',
            },
            {
                'question_text': 'A critical vendor that supports 40% of your production capacity has informed you they are going bankrupt within 90 days. Walk me through your immediate response and long-term mitigation strategy.',
                'category': 'problem_solving',
                'difficulty': 'hard',
                'what_it_tests': 'Crisis management capability and strategic thinking about supply chain risk and business continuity',
                'sample_answer_outline': 'The candidate should outline an immediate response including assessing inventory and buffer capacity, activating backup vendor relationships, and communicating with affected stakeholders. The long-term strategy should cover diversifying the vendor base, implementing vendor health monitoring, building safety stock policies, and establishing business continuity protocols. A strong answer demonstrates calm under pressure and systematic risk mitigation thinking.',
            },
            {
                'question_text': 'Explain how you would design an operational metrics framework for a company that currently has no standardized way of measuring operational performance across departments.',
                'category': 'technical',
                'difficulty': 'medium',
                'what_it_tests': 'Understanding of operational metrics design and ability to create measurement systems that drive accountability',
                'sample_answer_outline': 'A strong answer describes starting with business objectives to identify what outcomes matter most, then cascading those into department-level and team-level metrics. The candidate should discuss the difference between leading and lagging indicators, how to avoid metric overload, the importance of data quality and collection infrastructure, and how to use dashboards and reviews to drive accountability without creating a surveillance culture.',
            },
            {
                'question_text': 'Describe a time when you had to make a difficult operational decision with incomplete information and significant financial implications. What was your decision-making process?',
                'category': 'behavioral',
                'difficulty': 'medium',
                'what_it_tests': 'Decision-making under uncertainty and ability to manage risk at the executive level',
                'sample_answer_outline': 'The candidate should describe a specific scenario where they gathered available data, identified key assumptions, assessed potential outcomes and risks, consulted relevant stakeholders, and made a timely decision. A good answer shows a structured decision-making approach, willingness to act without perfect information, and how they managed the consequences and communicated the decision rationale.',
            },
            {
                'question_text': 'Your technology team wants to implement a major ERP system migration that will disrupt operations for 3 months but promises long-term efficiency gains. Your sales team says they cannot afford any disruption during their busiest quarter. How do you navigate this?',
                'category': 'situational',
                'difficulty': 'medium',
                'what_it_tests': 'Ability to balance competing organizational needs and make trade-off decisions that serve the whole business',
                'sample_answer_outline': 'The candidate should analyze the business impact of both timing scenarios, explore phased migration approaches that minimize disruption, and consider parallel running periods. They should discuss how they would quantify the cost of delay versus the cost of disruption, facilitate a discussion between the two teams to find creative solutions, and make a clear recommendation to the CEO with supporting data.',
            },
            {
                'question_text': 'How do you evaluate and develop your direct reports who are themselves senior leaders? What does executive coaching look like in practice for you?',
                'category': 'leadership',
                'difficulty': 'easy',
                'what_it_tests': 'Approach to developing senior leadership talent and commitment to building organizational capability',
                'sample_answer_outline': 'A good answer discusses setting clear expectations and outcomes for senior leaders, providing regular candid feedback, creating stretch assignments and cross-functional exposure, and investing in their professional development. The candidate should describe how they adapt their leadership style for different individuals and how they handle situations where a senior leader is not meeting expectations.',
            },
            {
                'question_text': 'How do you ensure that operational efficiency initiatives do not erode employee experience and morale? Where do you draw the line?',
                'category': 'culture',
                'difficulty': 'easy',
                'what_it_tests': 'Awareness of the human impact of operational changes and commitment to employee well-being alongside efficiency',
                'sample_answer_outline': 'The candidate should demonstrate that they consider employee experience as an input to operational design, not just an afterthought. They should provide examples of times they modified efficiency plans to protect employee well-being, explain how they involve employees in process improvement, and describe their approach to communicating changes that affect how people work.',
            },
            {
                'question_text': 'The company is experiencing a 20% increase in customer complaints about delivery times despite no changes to internal processes. How would you investigate the root cause and develop a resolution plan?',
                'category': 'problem_solving',
                'difficulty': 'medium',
                'what_it_tests': 'Root cause analysis skills and ability to investigate operational issues that span multiple systems and stakeholders',
                'sample_answer_outline': 'A strong answer describes a systematic investigation covering data analysis of delivery times, process mapping to identify where delays are occurring, examination of external factors like logistics partner performance and demand spikes, and customer feedback analysis. The candidate should propose both immediate corrective actions and structural improvements, and explain how they would prevent similar issues through monitoring and early warning systems.',
            },
        ],
    },
    {
        'slug': 'operations-director',
        'title': 'Operations Director',
        'department': 'Operations',
        'seniority_level': 'lead',
        'description': 'The Operations Director leads the operational execution across multiple teams and functions, translating strategic objectives into efficient day-to-day processes and workflows. This role manages operations managers and specialists, owns departmental budgets, and drives continuous improvement initiatives that directly impact business performance.',
        'responsibilities': [
            'Translate executive strategy into operational plans with clear milestones, deliverables, and KPIs',
            'Lead and develop a team of operations managers and specialists across multiple functional areas',
            'Own the operations budget and optimize resource allocation to maximize efficiency and throughput',
            'Design and implement standard operating procedures, quality control frameworks, and compliance programs',
            'Monitor operational performance dashboards and drive corrective actions when metrics deviate from targets',
            'Partner with technology, finance, and commercial teams to align operational capabilities with business needs',
        ],
        'key_skills': [
            'Team leadership and talent development',
            'Process design and continuous improvement',
            'Budget management and cost optimization',
            'Data-driven decision making and performance analytics',
            'Vendor and stakeholder management',
            'Quality assurance and compliance oversight',
        ],
        'assessment_slugs': ['behavioral'],
        'questions': [
            {
                'question_text': 'Walk me through how you would assess the maturity of an operations organization and develop a roadmap to move it from reactive to proactive operational management.',
                'category': 'technical',
                'difficulty': 'hard',
                'what_it_tests': 'Understanding of operational maturity models and ability to build systematic improvement roadmaps',
                'sample_answer_outline': 'A strong answer covers assessing current capabilities across process documentation, metrics visibility, automation level, and team skill sets. The candidate should describe a maturity model framework, explain how they would prioritize improvements based on business impact and effort, and outline a phased roadmap that builds foundational capabilities before advancing to predictive and optimized operations.',
            },
            {
                'question_text': 'Tell me about a time you had to manage a team through a period of significant operational disruption such as a system failure, sudden demand spike, or major process change. How did you keep the team effective?',
                'category': 'behavioral',
                'difficulty': 'medium',
                'what_it_tests': 'Crisis leadership skills and ability to maintain team morale and performance under pressure',
                'sample_answer_outline': 'The candidate should describe a specific disruption, explain how they triaged the immediate situation, communicated clearly to the team and stakeholders, delegated effectively, and maintained composure. A good answer shows both tactical crisis management and emotional intelligence in supporting the team through a stressful period, and includes lessons learned that were applied afterward.',
            },
            {
                'question_text': 'Two of your operations managers are proposing conflicting approaches to a major process redesign. Both approaches have merit. How do you decide and ensure the team stays aligned?',
                'category': 'situational',
                'difficulty': 'medium',
                'what_it_tests': 'Decision-making skills and ability to resolve internal disagreements while maintaining team cohesion',
                'sample_answer_outline': 'The candidate should describe establishing clear evaluation criteria based on business objectives, facilitating a structured discussion where both managers present their cases with supporting data, and making a transparent decision. They should explain how they acknowledge the merit of the unchosen approach, ensure the losing party remains engaged, and potentially incorporate elements from both proposals.',
            },
            {
                'question_text': 'How do you develop operations managers into strong leaders who can run their areas autonomously while still maintaining alignment with your overall operational vision?',
                'category': 'leadership',
                'difficulty': 'medium',
                'what_it_tests': 'Ability to scale leadership through delegation and development while maintaining strategic coherence',
                'sample_answer_outline': 'A good answer discusses setting clear outcomes and guardrails while giving managers autonomy in execution, creating structured development plans, providing coaching and mentorship, and establishing regular alignment cadences. The candidate should give specific examples of managers they have developed and explain how they balance guidance with empowerment.',
            },
            {
                'question_text': 'How do you build a culture of continuous improvement on an operations team without creating change fatigue or a sense that the current work is never good enough?',
                'category': 'culture',
                'difficulty': 'medium',
                'what_it_tests': 'Ability to sustain improvement momentum while keeping team engagement and morale high',
                'sample_answer_outline': 'The candidate should discuss celebrating wins and progress, involving the team in identifying improvements rather than dictating them, pacing changes to allow for stabilization, and framing improvement as growth rather than criticism of current performance. They should describe specific rituals or practices they use to embed continuous improvement as a positive cultural element.',
            },
            {
                'question_text': 'Your operations team consistently meets its output targets, but internal customer satisfaction scores from other departments are declining. How do you diagnose and address this disconnect?',
                'category': 'problem_solving',
                'difficulty': 'hard',
                'what_it_tests': 'Ability to look beyond output metrics and address service quality and stakeholder experience',
                'sample_answer_outline': 'A strong answer investigates what internal customers actually need versus what is being measured, examines whether the metrics are tracking the right things, conducts stakeholder interviews to understand pain points, and analyzes whether the focus on output targets has created blind spots around quality, communication, or responsiveness. The candidate should propose both metric adjustments and process improvements to align operational performance with stakeholder expectations.',
            },
            {
                'question_text': 'Explain how you would design and implement a quality management system for an operations team that currently relies on informal checks and individual judgment.',
                'category': 'technical',
                'difficulty': 'medium',
                'what_it_tests': 'Knowledge of quality management systems and ability to formalize quality processes without creating excessive bureaucracy',
                'sample_answer_outline': 'The candidate should describe defining quality standards based on customer requirements, mapping critical control points in the operational workflow, implementing inspection and verification processes, creating documentation and training programs, and establishing feedback loops for continuous improvement. They should address how to balance thoroughness with efficiency and how to gain team buy-in for the new system.',
            },
            {
                'question_text': 'Describe a time when you identified a significant cost reduction opportunity in operations. How did you build the business case and what was the result?',
                'category': 'behavioral',
                'difficulty': 'easy',
                'what_it_tests': 'Financial awareness and ability to drive cost optimization while maintaining service levels',
                'sample_answer_outline': 'The candidate should describe a specific cost reduction initiative, explain the analysis that identified the opportunity, how they quantified the savings and assessed risks to service quality, and how they presented the business case to leadership. A good answer includes the implementation approach and measurable results achieved.',
            },
            {
                'question_text': 'You are tasked with reducing operational headcount by 15% due to budget constraints while maintaining current service levels. How do you approach this challenge?',
                'category': 'situational',
                'difficulty': 'hard',
                'what_it_tests': 'Ability to make difficult resourcing decisions and find efficiency gains under financial pressure',
                'sample_answer_outline': 'The candidate should first analyze where time is being spent through workload analysis, identify automation and process improvement opportunities that could absorb capacity, assess which activities can be reduced or eliminated with minimal service impact, and develop a fair and transparent approach to workforce reduction. They should address the human side of layoffs including communication, support for affected employees, and maintaining morale among the remaining team.',
            },
            {
                'question_text': 'How do you set priorities and allocate resources across your team when every stakeholder claims their request is the top priority?',
                'category': 'leadership',
                'difficulty': 'easy',
                'what_it_tests': 'Prioritization skills and ability to manage competing demands with limited resources',
                'sample_answer_outline': 'A good answer describes establishing a prioritization framework based on business impact, urgency, and strategic alignment, making the framework transparent so stakeholders understand how decisions are made, facilitating trade-off discussions rather than trying to please everyone, and communicating capacity constraints honestly. The candidate should give examples of tough prioritization decisions and how they maintained stakeholder relationships despite saying no.',
            },
            {
                'question_text': 'What role does transparency play in how you run your operations team? How do you share information and how much visibility do team members have into performance and decisions?',
                'category': 'culture',
                'difficulty': 'easy',
                'what_it_tests': 'Values around organizational transparency and information sharing in operational environments',
                'sample_answer_outline': 'The candidate should articulate a clear philosophy on transparency, discuss specific practices like sharing dashboards, open decision-making processes, and regular communication cadences. They should address where they draw boundaries around sensitive information and explain how transparency builds trust and accountability within the team.',
            },
            {
                'question_text': 'A process that worked well when your team handled 100 transactions per day is now breaking down at 500 transactions per day. The team is frustrated and errors are increasing. How do you approach redesigning the process?',
                'category': 'problem_solving',
                'difficulty': 'medium',
                'what_it_tests': 'Process redesign skills and ability to scale operations beyond the limitations of initial designs',
                'sample_answer_outline': 'A strong answer describes mapping the current process to identify specific failure points at scale, analyzing whether the bottlenecks are people, process, or technology related, and designing a new process that accounts for current and anticipated future volumes. The candidate should discuss involving the team in the redesign, piloting changes before full rollout, and establishing monitoring to detect scaling issues earlier in the future.',
            },
        ],
    },
    {
        'slug': 'business-analyst',
        'title': 'Business Analyst',
        'department': 'Operations',
        'seniority_level': 'mid',
        'description': 'The Business Analyst bridges the gap between business needs and operational solutions by gathering requirements, analyzing processes, and recommending improvements that drive efficiency and effectiveness. This role requires strong analytical skills, clear communication, and the ability to translate complex data into actionable business insights.',
        'responsibilities': [
            'Gather and document business requirements from stakeholders through interviews, workshops, and observation',
            'Analyze current business processes and identify inefficiencies, risks, and improvement opportunities',
            'Create detailed process maps, data flow diagrams, and requirements specifications',
            'Develop business cases with cost-benefit analysis for proposed process improvements and system changes',
            'Support project implementation by validating solutions against requirements and coordinating user acceptance testing',
            'Build reports and dashboards that provide stakeholders with actionable insights into operational performance',
        ],
        'key_skills': [
            'Requirements gathering and documentation',
            'Process mapping and analysis',
            'Data analysis and visualization',
            'Stakeholder communication and facilitation',
            'SQL and business intelligence tools proficiency',
            'Project management fundamentals and agile methodology',
        ],
        'assessment_slugs': ['behavioral'],
        'questions': [
            {
                'question_text': 'Walk me through your process for gathering requirements from stakeholders who have difficulty articulating what they need. What techniques do you use to uncover the real requirements behind vague requests?',
                'category': 'technical',
                'difficulty': 'medium',
                'what_it_tests': 'Requirements elicitation skills and ability to work with non-technical stakeholders effectively',
                'sample_answer_outline': 'A strong answer describes multiple elicitation techniques including contextual inquiry and observation, prototyping and wireframing to make abstract concepts tangible, asking about pain points rather than solutions, using examples and scenarios to draw out specifics, and validating understanding through requirements review sessions. The candidate should explain how they distinguish between stated needs, real needs, and nice-to-haves.',
            },
            {
                'question_text': 'Tell me about a time when your analysis revealed that a stakeholder\'s proposed solution would not actually solve the underlying problem. How did you handle the situation?',
                'category': 'behavioral',
                'difficulty': 'medium',
                'what_it_tests': 'Ability to challenge assumptions diplomatically and redirect stakeholders toward more effective solutions',
                'sample_answer_outline': 'The candidate should describe a specific situation where they used data and analysis to demonstrate the gap between the proposed solution and the actual problem. They should explain how they presented their findings with empathy, proposed an alternative approach, and navigated any pushback. A good answer shows both analytical rigor and interpersonal skill.',
            },
            {
                'question_text': 'You are halfway through a project when a senior stakeholder requests a major scope change that would delay the timeline by two months. The original deadline is tied to a regulatory requirement. How do you handle this?',
                'category': 'situational',
                'difficulty': 'hard',
                'what_it_tests': 'Scope management skills and ability to navigate conflicting constraints with multiple stakeholders',
                'sample_answer_outline': 'The candidate should describe assessing the impact of the scope change on timeline, budget, and resources, then clearly presenting the trade-offs to all stakeholders. They should discuss options such as phasing the scope change, finding ways to fast-track the critical path, or negotiating which elements of the original scope could be deferred. A strong answer demonstrates structured impact analysis and clear communication of options rather than simply saying yes or no.',
            },
            {
                'question_text': 'How do you ensure that your requirements documentation is actually useful to the development or implementation team rather than becoming a document that nobody reads?',
                'category': 'leadership',
                'difficulty': 'easy',
                'what_it_tests': 'Practical approach to documentation and ability to create artifacts that drive results rather than just fulfill process requirements',
                'sample_answer_outline': 'A good answer discusses tailoring documentation format and detail level to the audience, involving the implementation team in requirements reviews, using visual formats like process flows and user stories alongside traditional specifications, and maintaining living documents that evolve with the project. The candidate should give examples of documentation approaches that have been particularly effective.',
            },
            {
                'question_text': 'How do you build trust and credibility with business stakeholders who may be skeptical of analysts telling them how to improve their processes?',
                'category': 'culture',
                'difficulty': 'easy',
                'what_it_tests': 'Interpersonal skills and approach to building collaborative relationships with business stakeholders',
                'sample_answer_outline': 'The candidate should discuss leading with curiosity rather than assumptions, acknowledging the deep domain expertise that business stakeholders bring, positioning themselves as a partner rather than an auditor, and delivering quick wins that demonstrate value. They should explain how they earn the right to make larger recommendations by first proving they understand the business context.',
            },
            {
                'question_text': 'You have been asked to improve a process that involves five different departments, each with their own systems and workflows. Where do you start and how do you approach this cross-functional analysis?',
                'category': 'problem_solving',
                'difficulty': 'hard',
                'what_it_tests': 'Cross-functional analysis skills and ability to navigate complex organizational processes',
                'sample_answer_outline': 'A strong answer describes starting with an end-to-end process mapping exercise involving representatives from all five departments, identifying handoff points and information flows between departments, and focusing analysis on the interfaces where most friction occurs. The candidate should discuss how they handle conflicting perspectives, build consensus around the current state, and develop improvement recommendations that consider the impact on all departments rather than optimizing one at the expense of others.',
            },
            {
                'question_text': 'Explain how you approach data validation when building reports for executive decision-making. What steps do you take to ensure the numbers you present are accurate and reliable?',
                'category': 'technical',
                'difficulty': 'medium',
                'what_it_tests': 'Data quality awareness and rigor in ensuring analytical outputs are trustworthy',
                'sample_answer_outline': 'The candidate should describe a systematic validation approach including cross-referencing data sources, checking for common data quality issues like duplicates and nulls and formatting inconsistencies, performing reasonableness checks against known benchmarks, documenting data lineage and transformation logic, and having a peer review process for critical reports. They should explain the consequences of presenting inaccurate data and how they build confidence in their outputs.',
            },
            {
                'question_text': 'Describe a time when you had to analyze a large and messy dataset to extract meaningful insights. What was your approach and what tools did you use?',
                'category': 'behavioral',
                'difficulty': 'hard',
                'what_it_tests': 'Practical data analysis skills and ability to work with imperfect real-world data',
                'sample_answer_outline': 'The candidate should describe a specific scenario involving data cleaning, transformation, and analysis. They should explain the tools they used such as SQL, Excel, Python, or BI platforms, how they handled data quality issues, what analytical techniques they applied, and how they communicated the findings. A good answer shows comfort with ambiguity and a methodical approach to making sense of complex data.',
            },
            {
                'question_text': 'A department head wants a custom report built that you believe duplicates information already available in an existing dashboard they are not using. How do you handle this request?',
                'category': 'situational',
                'difficulty': 'easy',
                'what_it_tests': 'Ability to manage stakeholder requests efficiently while being helpful and respectful',
                'sample_answer_outline': 'The candidate should describe understanding the underlying need first, then diplomatically showing the existing dashboard and asking what specific information is missing or how the format does not meet their needs. If there is a genuine gap, they should address it. If the existing tool meets the need, they should offer training or a walkthrough. A good answer balances efficiency with service orientation.',
            },
            {
                'question_text': 'How do you prioritize multiple analysis requests from different stakeholders when you cannot complete them all within the requested timeframes?',
                'category': 'leadership',
                'difficulty': 'medium',
                'what_it_tests': 'Time management and stakeholder management skills when demand exceeds capacity',
                'sample_answer_outline': 'A good answer describes a transparent prioritization approach based on business impact, deadline urgency, and effort required. The candidate should explain how they communicate timelines honestly, negotiate scope to deliver partial value faster, and escalate when necessary. They should demonstrate an organized approach to managing their workload and setting realistic expectations.',
            },
            {
                'question_text': 'What does collaboration mean to you in the context of business analysis work? How do you ensure you are not working in isolation from the teams that will implement your recommendations?',
                'category': 'culture',
                'difficulty': 'medium',
                'what_it_tests': 'Collaborative mindset and understanding of the importance of inclusive analysis',
                'sample_answer_outline': 'The candidate should discuss involving implementation teams early in the analysis process, sharing work-in-progress rather than only finished products, creating feedback loops throughout the project lifecycle, and viewing their role as a facilitator who brings people together rather than an individual contributor who hands off reports. They should give examples of how collaboration has improved the quality of their work.',
            },
            {
                'question_text': 'You are tasked with recommending whether the company should build a custom internal tool or buy an off-the-shelf solution. What is your framework for evaluating this decision?',
                'category': 'problem_solving',
                'difficulty': 'medium',
                'what_it_tests': 'Structured decision-making and ability to evaluate complex trade-offs in technology and process decisions',
                'sample_answer_outline': 'A strong answer covers evaluating total cost of ownership for both options including implementation, maintenance, and opportunity cost, assessing how well off-the-shelf solutions meet current and anticipated requirements, considering factors like time to value, customization flexibility, vendor reliability, and integration complexity, and building a decision matrix that makes the trade-offs transparent. The candidate should discuss how they gather input from technical and business stakeholders to inform the recommendation.',
            },
        ],
    },
    {
        'slug': 'project-manager',
        'title': 'Project Manager',
        'department': 'Operations',
        'seniority_level': 'mid',
        'description': 'The Project Manager is responsible for planning, executing, and delivering projects on time, within scope, and on budget across the operations organization. This role requires strong organizational skills, clear communication, and the ability to coordinate cross-functional teams to achieve defined project outcomes.',
        'responsibilities': [
            'Define project scope, objectives, timelines, and resource requirements in collaboration with stakeholders and sponsors',
            'Develop detailed project plans including work breakdown structures, milestones, dependencies, and risk registers',
            'Coordinate and lead cross-functional project teams, facilitating daily standups, status meetings, and retrospectives',
            'Track project progress against plan, identify variances early, and implement corrective actions to keep projects on track',
            'Manage project budgets, vendor relationships, and procurement activities related to project deliverables',
            'Communicate project status, risks, and decisions to stakeholders and executive sponsors through regular reporting',
        ],
        'key_skills': [
            'Project planning and scheduling methodologies',
            'Risk management and mitigation planning',
            'Stakeholder communication and expectation management',
            'Budget tracking and financial project controls',
            'Agile and waterfall project management frameworks',
            'Team facilitation and conflict resolution',
        ],
        'assessment_slugs': ['behavioral'],
        'questions': [
            {
                'question_text': 'Walk me through how you would create a project plan for a complex cross-functional initiative with ambiguous requirements and multiple dependencies. What tools and techniques do you use?',
                'category': 'technical',
                'difficulty': 'medium',
                'what_it_tests': 'Project planning methodology and ability to bring structure to ambiguous initiatives',
                'sample_answer_outline': 'A strong answer covers starting with a project charter to align on objectives and success criteria, conducting a requirements gathering phase to reduce ambiguity, building a work breakdown structure, identifying dependencies and critical path, developing a realistic timeline with buffers, and creating a risk register. The candidate should explain how they iterate on the plan as clarity increases and which tools they use for planning and tracking.',
            },
            {
                'question_text': 'Tell me about a project that went significantly off track. What caused the derailment, how did you get it back on course, and what did you learn?',
                'category': 'behavioral',
                'difficulty': 'medium',
                'what_it_tests': 'Ability to recover failing projects and learn from project management challenges',
                'sample_answer_outline': 'The candidate should describe a specific project with honest reflection on the root causes of the problems, which might include planning gaps, scope creep, resource issues, or external factors. They should explain the recovery actions they took, how they communicated with stakeholders about the situation, and the ultimate outcome. A good answer includes concrete process improvements they implemented afterward.',
            },
            {
                'question_text': 'Three weeks before a major project deadline, your lead technical resource quits unexpectedly and a key vendor informs you of a two-week delay on a critical deliverable. How do you respond?',
                'category': 'situational',
                'difficulty': 'hard',
                'what_it_tests': 'Crisis management in project delivery and ability to replan under extreme pressure',
                'sample_answer_outline': 'The candidate should describe an immediate impact assessment to understand the true effect on the timeline, options for replacing the technical resource such as internal transfers, contractors, or redistributing work, negotiation strategies with the vendor to compress the delay, and scenarios they would present to the project sponsor including revised timelines, scope reductions, or additional resource requests. A strong answer shows composure and structured problem-solving under pressure.',
            },
            {
                'question_text': 'How do you manage a project team where the members do not report to you directly and have competing priorities from their functional managers?',
                'category': 'leadership',
                'difficulty': 'medium',
                'what_it_tests': 'Influence without authority and ability to lead cross-functional teams in a matrix organization',
                'sample_answer_outline': 'A good answer discusses building relationships with functional managers to secure resource commitments, making project work visible and meaningful to team members, removing obstacles that make project participation frustrating, and creating a team identity and sense of shared purpose. The candidate should explain how they handle situations where functional priorities conflict with project needs and how they escalate effectively when necessary.',
            },
            {
                'question_text': 'What does a healthy project team culture look like to you, and how do you create it from the first kickoff meeting through project closure?',
                'category': 'culture',
                'difficulty': 'easy',
                'what_it_tests': 'Values around team dynamics and ability to create a productive and positive project environment',
                'sample_answer_outline': 'The candidate should discuss setting clear norms and expectations at kickoff, creating psychological safety for raising risks and concerns, celebrating milestones and acknowledging contributions, conducting effective retrospectives, and ensuring closure activities recognize the team effort. They should give specific examples of practices that have built strong team cultures on their projects.',
            },
            {
                'question_text': 'You discover midway through a project that the original scope was underestimated by approximately 40%. The budget is fixed and the deadline is firm. What options do you present to the project sponsor?',
                'category': 'problem_solving',
                'difficulty': 'hard',
                'what_it_tests': 'Scope management and ability to navigate the iron triangle under constraints',
                'sample_answer_outline': 'A strong answer presents multiple options including reducing scope to fit the original budget and timeline with clear trade-offs, requesting additional budget to deliver the full scope, proposing a phased delivery where core functionality ships on time and remaining scope follows, or identifying efficiency gains through process changes or automation. The candidate should explain how they facilitate the decision with the sponsor and manage stakeholder expectations throughout.',
            },
            {
                'question_text': 'Explain the differences between how you would manage a project using a traditional waterfall approach versus an agile approach. How do you decide which methodology to apply?',
                'category': 'technical',
                'difficulty': 'easy',
                'what_it_tests': 'Understanding of project management methodologies and ability to select the right approach for the context',
                'sample_answer_outline': 'The candidate should articulate the key differences in planning, execution, stakeholder engagement, and delivery between waterfall and agile approaches. They should discuss factors that influence methodology selection including requirements clarity, rate of change, stakeholder availability, team experience, and organizational culture. A good answer also addresses hybrid approaches and the ability to adapt methodology to the specific project context.',
            },
            {
                'question_text': 'Describe a time when you had to deliver difficult news to a project sponsor or executive stakeholder. How did you prepare and what was the outcome?',
                'category': 'behavioral',
                'difficulty': 'hard',
                'what_it_tests': 'Stakeholder communication skills and courage to deliver bad news proactively and constructively',
                'sample_answer_outline': 'The candidate should describe a specific scenario where they had to communicate a significant project issue, explain how they prepared the message with data and options rather than just presenting the problem, and detail the outcome. A good answer shows they delivered the news promptly rather than hoping the situation would improve, and they maintained the stakeholder relationship through honest and solutions-oriented communication.',
            },
            {
                'question_text': 'Your project team is consistently missing sprint commitments and velocity is declining over the past three iterations. The team says the work is harder than estimated. How do you address this?',
                'category': 'situational',
                'difficulty': 'medium',
                'what_it_tests': 'Ability to diagnose and address team performance issues in an agile environment',
                'sample_answer_outline': 'The candidate should investigate root causes beyond the surface explanation, looking at estimation accuracy, unplanned work and interruptions, technical debt, team capacity changes, and story splitting practices. They should facilitate a retrospective focused on the pattern, work with the team to improve estimation through techniques like reference story comparison, and address any systemic issues. A good answer avoids blame and focuses on systemic improvement.',
            },
            {
                'question_text': 'How do you ensure lessons learned from completed projects are actually captured and applied to future projects rather than just filed away and forgotten?',
                'category': 'leadership',
                'difficulty': 'easy',
                'what_it_tests': 'Commitment to organizational learning and practical approach to knowledge management',
                'sample_answer_outline': 'A good answer describes conducting thorough retrospectives with specific actionable items, integrating lessons into project templates and checklists, creating a searchable knowledge base that is actually consulted during project initiation, and building peer networks where project managers share experiences regularly. The candidate should acknowledge the common failure mode of lessons learned exercises and explain what they do differently to make the learning stick.',
            },
            {
                'question_text': 'How do you approach project communication differently for technical team members versus business stakeholders versus executive sponsors?',
                'category': 'culture',
                'difficulty': 'medium',
                'what_it_tests': 'Communication adaptability and awareness of different audience needs in project reporting',
                'sample_answer_outline': 'The candidate should describe tailoring message content, format, frequency, and level of detail for each audience. Technical teams need granular task-level updates and blocker resolution. Business stakeholders need progress against milestones and impact on their operations. Executives need high-level status, key risks, and decisions needed. A good answer provides specific examples of communication artifacts they use for each audience.',
            },
            {
                'question_text': 'You are managing two concurrent projects that share three team members. Both projects are behind schedule and the team members are burned out from context switching. How do you resolve this resource conflict?',
                'category': 'problem_solving',
                'difficulty': 'medium',
                'what_it_tests': 'Resource management skills and ability to balance competing project demands with team well-being',
                'sample_answer_outline': 'A strong answer analyzes which project has higher business priority and proposes dedicating shared resources to one project at a time rather than splitting attention, negotiates timeline adjustments for the lower-priority project, explores options for temporary additional resources, and addresses the immediate burnout through workload reduction or schedule adjustments. The candidate should discuss how they escalate the resource conflict to leadership with clear data and options.',
            },
        ],
    },
    {
        'slug': 'supply-chain-manager',
        'title': 'Supply Chain Manager',
        'department': 'Operations',
        'seniority_level': 'senior',
        'description': 'The Supply Chain Manager oversees the end-to-end supply chain including procurement, logistics, inventory management, and vendor relationships to ensure timely and cost-effective delivery of goods and services. This role requires deep expertise in supply chain operations, strong analytical skills, and the ability to balance cost optimization with service level requirements.',
        'responsibilities': [
            'Develop and execute the supply chain strategy covering procurement, logistics, warehousing, and distribution',
            'Manage vendor relationships including selection, negotiation, performance evaluation, and contract management',
            'Optimize inventory levels to balance carrying costs against service level targets and demand variability',
            'Monitor and improve supply chain KPIs including lead times, fill rates, cost per unit, and on-time delivery',
            'Identify and mitigate supply chain risks including single-source dependencies, geopolitical exposure, and capacity constraints',
            'Implement supply chain technology solutions and process improvements to enhance visibility and efficiency',
        ],
        'key_skills': [
            'Supply chain strategy and network design',
            'Vendor management and contract negotiation',
            'Inventory optimization and demand planning',
            'Logistics and distribution management',
            'Supply chain analytics and forecasting',
            'Risk management and business continuity planning',
        ],
        'assessment_slugs': ['behavioral'],
        'questions': [
            {
                'question_text': 'Walk me through how you would evaluate and redesign a supply chain network that has grown organically and is now experiencing increasing costs and declining service levels.',
                'category': 'technical',
                'difficulty': 'hard',
                'what_it_tests': 'Supply chain network design expertise and ability to optimize complex multi-node supply chains',
                'sample_answer_outline': 'A strong answer covers conducting a total cost analysis across the current network, mapping material and information flows, analyzing demand patterns by geography and customer segment, modeling alternative network configurations, and evaluating trade-offs between cost, speed, and resilience. The candidate should discuss using network optimization tools, the importance of considering future growth scenarios, and how they would phase the transition to minimize disruption.',
            },
            {
                'question_text': 'Tell me about a time you had to negotiate a critical vendor contract under unfavorable market conditions where the vendor held significant leverage. What was your approach and outcome?',
                'category': 'behavioral',
                'difficulty': 'hard',
                'what_it_tests': 'Negotiation skills under pressure and ability to create value in difficult vendor relationships',
                'sample_answer_outline': 'The candidate should describe the specific market conditions and power dynamics, explain their preparation including BATNA analysis and creative value propositions, detail the negotiation strategy they employed, and share the outcome. A good answer shows that they found ways to create mutual value rather than purely adversarial tactics, and demonstrates long-term relationship thinking even in tough negotiations.',
            },
            {
                'question_text': 'A key raw material that accounts for 25% of your product cost has experienced a sudden 60% price increase due to geopolitical events. Your existing contracts expire in 30 days. What is your action plan?',
                'category': 'situational',
                'difficulty': 'hard',
                'what_it_tests': 'Crisis response in supply chain management and ability to manage commodity risk under pressure',
                'sample_answer_outline': 'The candidate should outline immediate actions including securing available inventory at current prices, engaging alternative suppliers, assessing the impact on product margins and pricing, and communicating with leadership about financial exposure. The medium-term plan should cover diversifying the supply base, exploring substitute materials, hedging strategies, and contract restructuring to include price adjustment mechanisms. A strong answer demonstrates both tactical urgency and strategic risk management.',
            },
            {
                'question_text': 'How do you develop your procurement and logistics team members into supply chain professionals who can think strategically rather than just executing transactions?',
                'category': 'leadership',
                'difficulty': 'medium',
                'what_it_tests': 'Talent development approach and commitment to building strategic capabilities within the supply chain team',
                'sample_answer_outline': 'A good answer discusses exposing team members to cross-functional business context, assigning projects that require analytical and strategic thinking beyond day-to-day transactions, providing mentorship and coaching, encouraging professional certifications and education, and creating opportunities for team members to present recommendations to leadership. The candidate should give specific examples of how they have elevated team capabilities.',
            },
            {
                'question_text': 'How do you balance the drive for cost optimization in supply chain management with ethical sourcing practices and sustainability commitments?',
                'category': 'culture',
                'difficulty': 'medium',
                'what_it_tests': 'Values around ethical supply chain management and ability to integrate sustainability into operational decisions',
                'sample_answer_outline': 'The candidate should articulate a clear philosophy on sustainable and ethical sourcing, explain how they evaluate suppliers on social and environmental criteria alongside cost and quality, discuss specific practices like supplier audits and codes of conduct, and give examples of times they chose a more expensive supplier due to ethical considerations. They should demonstrate that sustainability is integrated into their supply chain strategy rather than treated as an afterthought.',
            },
            {
                'question_text': 'Your demand forecast accuracy has declined from 85% to 60% over the past two quarters, leading to both stockouts and excess inventory. How do you diagnose and improve the forecasting process?',
                'category': 'problem_solving',
                'difficulty': 'hard',
                'what_it_tests': 'Demand planning expertise and analytical approach to improving forecast accuracy',
                'sample_answer_outline': 'A strong answer investigates the root causes of forecast degradation including changes in demand patterns, data quality issues, forecast methodology limitations, and whether market conditions have fundamentally shifted. The candidate should discuss analyzing forecast error by product, segment, and time horizon, evaluating the forecasting model and inputs, incorporating qualitative market intelligence alongside quantitative methods, and implementing a more collaborative sales and operations planning process.',
            },
            {
                'question_text': 'Explain how you would implement a supplier performance management program. What metrics would you track and how would you use them to improve vendor performance?',
                'category': 'technical',
                'difficulty': 'medium',
                'what_it_tests': 'Vendor management expertise and ability to create structured performance improvement frameworks',
                'sample_answer_outline': 'The candidate should describe defining KPIs across quality, delivery, cost, and responsiveness dimensions, establishing a balanced scorecard for each supplier, conducting regular performance reviews with suppliers, linking performance to contract terms and future business allocation, and creating improvement plans for underperforming suppliers. They should discuss how to make the program constructive rather than punitive and how to segment supplier management effort based on strategic importance.',
            },
            {
                'question_text': 'Describe a time when you identified and implemented a significant supply chain improvement that others had not considered. What insight led to the improvement?',
                'category': 'behavioral',
                'difficulty': 'medium',
                'what_it_tests': 'Innovation in supply chain operations and ability to see improvement opportunities that are not obvious',
                'sample_answer_outline': 'The candidate should describe a specific improvement, the data or observation that led to the insight, how they built the case for the change, and the measurable results. A good answer shows curiosity and willingness to challenge established practices, and demonstrates the candidate ability to quantify supply chain improvements in business terms.',
            },
            {
                'question_text': 'Your company is launching a new product line that requires sourcing from suppliers in a region with known logistical challenges and political instability. How do you build a resilient supply chain for this product?',
                'category': 'situational',
                'difficulty': 'medium',
                'what_it_tests': 'Supply chain risk management and ability to design resilient sourcing strategies for challenging environments',
                'sample_answer_outline': 'The candidate should discuss dual-sourcing strategies, building safety stock appropriate to the risk profile, establishing relationships with logistics providers experienced in the region, creating contingency plans with trigger points for activation, monitoring geopolitical risk indicators, and potentially qualifying alternative suppliers in more stable regions as backup. A strong answer balances the business opportunity against the supply chain risks with specific mitigation strategies.',
            },
            {
                'question_text': 'How do you facilitate an effective sales and operations planning process that balances demand, supply, and financial objectives across the organization?',
                'category': 'leadership',
                'difficulty': 'easy',
                'what_it_tests': 'Cross-functional planning skills and ability to drive alignment between commercial and operational teams',
                'sample_answer_outline': 'A good answer describes the S&OP cadence and governance structure, the roles and responsibilities of each participating function, how demand signals are translated into supply and capacity plans, how financial implications are integrated, and how executive decisions are made and communicated. The candidate should discuss how they handle disagreements between sales optimism and operational realism, and how they measure S&OP effectiveness.',
            },
            {
                'question_text': 'How do you stay current with supply chain trends, technologies, and best practices? How has your approach to supply chain management evolved in response to recent global disruptions?',
                'category': 'culture',
                'difficulty': 'easy',
                'what_it_tests': 'Continuous learning mindset and ability to adapt supply chain strategies to changing global conditions',
                'sample_answer_outline': 'The candidate should describe specific resources and professional communities they engage with, discuss how recent disruptions such as pandemic impacts, geopolitical tensions, and sustainability pressures have changed their approach, and give examples of new practices or technologies they have adopted. A good answer shows awareness of industry trends like nearshoring, supply chain digitization, and circular economy principles.',
            },
            {
                'question_text': 'Your warehouse is at 95% capacity, lead times for a new facility are 12 months, and demand is projected to grow 20% in the next 6 months. What creative solutions would you explore to bridge this gap?',
                'category': 'problem_solving',
                'difficulty': 'medium',
                'what_it_tests': 'Creative problem-solving under capacity constraints and ability to find interim solutions for infrastructure limitations',
                'sample_answer_outline': 'A strong answer explores multiple options including third-party logistics overflow capacity, optimizing current warehouse layout and slotting, implementing cross-docking to reduce storage needs, negotiating vendor-managed inventory to push stock upstream, accelerating inventory turns through better demand planning, and evaluating whether all current SKUs justify their warehouse space. The candidate should discuss how they would evaluate and combine these options while maintaining service levels.',
            },
        ],
    },
]
