PRODUCT_ROLES = [
    {
        'slug': 'cpo',
        'title': 'Chief Product Officer',
        'department': 'Product',
        'seniority_level': 'executive',
        'description': 'The Chief Product Officer owns the entire product vision, strategy, and roadmap across all product lines. They align product development with business objectives, drive innovation, and lead the product organization to deliver sustained competitive advantage.',
        'responsibilities': [
            'Define and communicate the company-wide product vision and multi-year strategy',
            'Lead and scale the product management organization across all business units',
            'Drive product-led growth initiatives and establish key product metrics',
            'Collaborate with the C-suite to align product strategy with company revenue and market goals',
            'Oversee portfolio prioritization, resource allocation, and investment trade-offs',
            'Champion a customer-centric culture and ensure product-market fit across all offerings',
        ],
        'key_skills': [
            'Executive product strategy and vision setting',
            'Organizational leadership and talent development',
            'Market analysis and competitive positioning',
            'P&L ownership and business acumen',
            'Stakeholder management at board and investor level',
            'Data-driven decision-making at portfolio scale',
        ],
        'assessment_slugs': ['product', 'behavioral'],
        'questions': [
            {
                'question_text': 'How do you develop and communicate a multi-year product vision that aligns with the overall business strategy?',
                'category': 'leadership',
                'difficulty': 'hard',
                'what_it_tests': 'Ability to craft long-term product vision and align it with corporate objectives.',
                'sample_answer_outline': 'A strong answer describes synthesizing market trends, customer insights, and business goals into a compelling narrative. The candidate should explain how they cascade the vision across teams and measure alignment through OKRs or similar frameworks.',
            },
            {
                'question_text': 'Describe a time when you had to kill a major product line or initiative. How did you make that decision and manage the fallout?',
                'category': 'behavioral',
                'difficulty': 'hard',
                'what_it_tests': 'Decisiveness in sunsetting products and managing organizational change.',
                'sample_answer_outline': 'The candidate should walk through the data and strategic rationale behind the decision, how they communicated it to stakeholders and affected teams, and the steps taken to mitigate customer and revenue impact during the transition.',
            },
            {
                'question_text': 'Your CEO wants to enter an adjacent market that you believe is a distraction from your core product strategy. How do you handle this?',
                'category': 'situational',
                'difficulty': 'hard',
                'what_it_tests': 'Ability to push back on executive pressure with data while maintaining relationships.',
                'sample_answer_outline': 'A strong response involves framing the discussion around opportunity cost and strategic focus, presenting data on the core market opportunity versus the adjacent one, and proposing a structured evaluation framework rather than a flat refusal.',
            },
            {
                'question_text': 'How do you structure and scale a product organization from 10 to 100 product managers?',
                'category': 'leadership',
                'difficulty': 'hard',
                'what_it_tests': 'Experience in building and scaling product organizations at high growth stages.',
                'sample_answer_outline': 'The candidate should discuss team topology decisions such as platform versus feature teams, hiring profiles at different stages, establishing career ladders, and creating shared practices and rituals that maintain culture and quality as the team grows.',
            },
            {
                'question_text': 'How do you approach portfolio-level prioritization when multiple business units compete for shared engineering resources?',
                'category': 'problem_solving',
                'difficulty': 'hard',
                'what_it_tests': 'Strategic resource allocation and cross-organizational trade-off skills.',
                'sample_answer_outline': 'A thorough answer covers establishing transparent prioritization criteria tied to business impact, using frameworks like weighted scoring or RICE at portfolio level, and building governance processes that give business unit leaders voice while maintaining strategic coherence.',
            },
            {
                'question_text': 'What metrics do you use to evaluate the overall health of a product portfolio, and how do you act on them?',
                'category': 'technical',
                'difficulty': 'medium',
                'what_it_tests': 'Fluency with product analytics at a portfolio and business level.',
                'sample_answer_outline': 'The candidate should mention layered metrics including business outcomes like revenue and margin, product health indicators like engagement and retention, and leading indicators like adoption velocity. They should explain how they build dashboards and review cadences to drive portfolio decisions.',
            },
            {
                'question_text': 'Tell me about a time you transformed a product organization from a feature-factory culture to an outcome-driven culture.',
                'category': 'behavioral',
                'difficulty': 'hard',
                'what_it_tests': 'Change management ability and commitment to outcome-oriented product development.',
                'sample_answer_outline': 'The response should detail the initial state, the specific changes introduced such as shifting from output roadmaps to outcome-based OKRs, how they retrained teams, and measurable improvements in product impact and team satisfaction over time.',
            },
            {
                'question_text': 'How do you ensure that product decisions are genuinely customer-centric rather than driven by the loudest internal stakeholders?',
                'category': 'culture',
                'difficulty': 'medium',
                'what_it_tests': 'Commitment to customer-centricity and ability to institutionalize it.',
                'sample_answer_outline': 'A good answer covers establishing regular customer feedback loops, embedding user research into the development process, using data to arbitrate between competing opinions, and creating forums where customer voice is represented in strategic decisions.',
            },
            {
                'question_text': 'A key product has plateaued in growth. Walk me through how you would diagnose the root cause and determine the path forward.',
                'category': 'problem_solving',
                'difficulty': 'medium',
                'what_it_tests': 'Analytical rigor in diagnosing product growth challenges at a strategic level.',
                'sample_answer_outline': 'The candidate should outline a structured diagnostic approach examining market saturation, competitive dynamics, funnel analysis, user segmentation, and willingness to pay. They should discuss how they would decide between doubling down, pivoting, or sunsetting.',
            },
            {
                'question_text': 'How do you balance investment between innovation and incremental improvement in your product portfolio?',
                'category': 'technical',
                'difficulty': 'medium',
                'what_it_tests': 'Strategic thinking about resource allocation between explore and exploit activities.',
                'sample_answer_outline': 'A strong answer references frameworks like the three horizons model or similar, describes how they allocate budget and headcount across bets of different sizes, and explains governance mechanisms for incubation projects versus core product optimization.',
            },
            {
                'question_text': 'What does a healthy relationship between the CPO and CTO look like, and how do you build it?',
                'category': 'culture',
                'difficulty': 'medium',
                'what_it_tests': 'Ability to partner effectively with technology leadership.',
                'sample_answer_outline': 'The candidate should describe shared ownership of outcomes, mutual respect for each domain, regular alignment rituals, and specific examples of how they have navigated tension between product ambition and technical constraints or debt.',
            },
            {
                'question_text': 'You are joining a company where product management has historically been weak and engineering has driven most product decisions. What is your 90-day plan?',
                'category': 'situational',
                'difficulty': 'hard',
                'what_it_tests': 'Ability to establish product leadership credibility in a challenging organizational context.',
                'sample_answer_outline': 'A comprehensive answer covers a listening and learning phase, quick wins to build credibility, a plan for establishing product processes without alienating engineering, and a longer-term vision for building a collaborative product-engineering partnership.',
            },
        ],
    },
    {
        'slug': 'vp-of-product',
        'title': 'VP of Product',
        'department': 'Product',
        'seniority_level': 'lead',
        'description': 'The VP of Product leads a product management function covering one or more major product areas. They translate company strategy into product roadmaps, mentor product managers, and ensure consistent execution across their teams while partnering closely with engineering and design leadership.',
        'responsibilities': [
            'Own the product strategy and roadmap for a major product area or business unit',
            'Manage and mentor a team of senior product managers and product managers',
            'Partner with engineering and design leadership to ensure timely and high-quality delivery',
            'Define success metrics and build reporting structures to track product performance',
            'Represent the product function in cross-functional leadership forums and planning cycles',
            'Drive quarterly and annual planning processes including goal setting and resource allocation',
        ],
        'key_skills': [
            'Product roadmap development and communication',
            'Team management and mentorship of product managers',
            'Cross-functional leadership with engineering and design partners',
            'Data analysis and metrics-driven product management',
            'Stakeholder management with senior executives and external partners',
            'Agile and lean product development methodologies',
        ],
        'assessment_slugs': ['product', 'behavioral'],
        'questions': [
            {
                'question_text': 'How do you build a product roadmap that balances customer needs, technical debt, and business objectives?',
                'category': 'technical',
                'difficulty': 'hard',
                'what_it_tests': 'Strategic roadmap planning skills and ability to navigate competing priorities.',
                'sample_answer_outline': 'The candidate should describe a framework for collecting inputs from customers, engineering, sales, and leadership, then explain how they weigh and sequence initiatives using impact and effort analysis while maintaining a healthy mix of customer value, infrastructure investment, and business-driven features.',
            },
            {
                'question_text': 'Describe a situation where two of your product managers had conflicting priorities and were competing for the same engineering resources. How did you resolve it?',
                'category': 'behavioral',
                'difficulty': 'medium',
                'what_it_tests': 'Conflict resolution and resource allocation skills within a product team.',
                'sample_answer_outline': 'A strong answer shows the candidate facilitating a data-driven discussion about relative impact, establishing clear criteria for the decision, and ensuring both PMs felt heard. They should mention how they prevented similar conflicts going forward through better planning processes.',
            },
            {
                'question_text': 'Your most important product launch is two weeks away and engineering tells you they need to cut three of the five planned features. How do you decide what stays?',
                'category': 'situational',
                'difficulty': 'hard',
                'what_it_tests': 'Ability to make tough scope decisions under pressure while protecting customer value.',
                'sample_answer_outline': 'The candidate should explain how they assess which features are critical for the minimum viable launch by evaluating customer impact, dependency chains, and strategic importance. They should also discuss how they communicate changes to stakeholders and plan for post-launch iterations.',
            },
            {
                'question_text': 'How do you coach a product manager who writes good requirements but struggles to influence engineering teams?',
                'category': 'leadership',
                'difficulty': 'medium',
                'what_it_tests': 'People management and ability to develop product talent.',
                'sample_answer_outline': 'A thoughtful answer discusses diagnosing the root cause, whether it is communication style, lack of technical empathy, or relationship building. The candidate should describe specific coaching techniques like shadowing, role-playing, and creating structured opportunities for the PM to build engineering credibility.',
            },
            {
                'question_text': 'What is your process for identifying whether a product problem is best solved with a new feature, an improvement to an existing feature, or a non-product solution like documentation or process change?',
                'category': 'problem_solving',
                'difficulty': 'medium',
                'what_it_tests': 'Problem framing discipline and resistance to solution bias.',
                'sample_answer_outline': 'The candidate should describe how they start with the problem definition, analyze root causes, consider the full range of solutions including non-product ones, and evaluate each on effort versus impact. They should give a concrete example where the best solution was not building more software.',
            },
            {
                'question_text': 'How do you establish a culture of experimentation within your product team while managing stakeholder expectations about predictability?',
                'category': 'culture',
                'difficulty': 'hard',
                'what_it_tests': 'Ability to foster innovation culture while maintaining organizational trust.',
                'sample_answer_outline': 'A comprehensive answer covers setting up low-cost experimentation frameworks like A/B testing and prototyping, allocating explicit time and resources for experimentation, communicating the portfolio approach to stakeholders so they understand that some bets will fail, and celebrating learning from failed experiments.',
            },
            {
                'question_text': 'Walk me through how you would evaluate a potential partnership or integration opportunity for your product.',
                'category': 'technical',
                'difficulty': 'medium',
                'what_it_tests': 'Strategic evaluation skills for partnerships and build-versus-buy decisions.',
                'sample_answer_outline': 'The candidate should outline evaluation criteria including strategic fit, customer demand, technical complexity, revenue impact, and competitive implications. They should describe a structured assessment process involving multiple stakeholders and explain how they would structure the partnership terms to protect long-term product interests.',
            },
            {
                'question_text': 'Tell me about a time you had to deliver difficult product news to a key customer or group of customers. How did you handle it?',
                'category': 'behavioral',
                'difficulty': 'medium',
                'what_it_tests': 'Customer communication skills and empathy during challenging product situations.',
                'sample_answer_outline': 'The response should demonstrate transparency, empathy, and accountability. The candidate should describe how they prepared the communication, offered alternatives or migration paths, and followed through on commitments made during the conversation.',
            },
            {
                'question_text': 'Your team has been shipping features consistently but key product metrics are not moving. How do you diagnose and address this?',
                'category': 'problem_solving',
                'difficulty': 'hard',
                'what_it_tests': 'Ability to diagnose outcome gaps and shift team focus from output to impact.',
                'sample_answer_outline': 'A strong answer covers analyzing the full funnel from feature delivery to metric impact, checking whether the team is measuring the right things, evaluating whether features are being adopted, and potentially restructuring how the team defines success to focus on outcomes rather than output.',
            },
            {
                'question_text': 'How do you run an effective quarterly planning process that results in clear priorities without becoming a bureaucratic exercise?',
                'category': 'technical',
                'difficulty': 'medium',
                'what_it_tests': 'Process design skills for planning at scale.',
                'sample_answer_outline': 'The candidate should describe a lightweight but rigorous planning process including pre-work expectations, the structure of planning sessions, how they handle disagreements, and the artifacts produced. They should emphasize keeping the process focused on decisions rather than presentations.',
            },
            {
                'question_text': 'A senior engineer on a team you partner with publicly criticizes your product direction in an all-hands meeting. How do you respond?',
                'category': 'situational',
                'difficulty': 'medium',
                'what_it_tests': 'Composure under pressure and ability to handle cross-functional disagreement constructively.',
                'sample_answer_outline': 'The candidate should demonstrate emotional maturity by acknowledging the concern publicly, committing to follow up, and then having a private conversation to understand the root concern. They should describe how they would address any valid points while reinforcing appropriate channels for feedback.',
            },
            {
                'question_text': 'What do you look for when hiring product managers, and how has your hiring criteria evolved over your career?',
                'category': 'leadership',
                'difficulty': 'easy',
                'what_it_tests': 'Thoughtfulness about talent evaluation and self-awareness about evolving judgment.',
                'sample_answer_outline': 'A mature answer covers core attributes they screen for such as analytical ability, customer empathy, communication skills, and bias for action. They should discuss how they have learned to weigh these differently based on team needs and share a specific example of how a past hiring mistake informed their current approach.',
            },
        ],
    },
    {
        'slug': 'senior-product-manager',
        'title': 'Senior Product Manager',
        'department': 'Product',
        'seniority_level': 'senior',
        'description': 'The Senior Product Manager owns a significant product area or complex feature set end-to-end. They drive strategy and execution for their domain, influence cross-functional teams without authority, and serve as a mentor to junior product managers while delivering measurable business outcomes.',
        'responsibilities': [
            'Define and own the strategy and roadmap for a key product area',
            'Lead discovery efforts including user research, competitive analysis, and data analysis',
            'Write detailed product requirements and collaborate with engineering and design through delivery',
            'Drive go-to-market planning in partnership with marketing, sales, and customer success',
            'Mentor associate and mid-level product managers on the team',
            'Establish and track key performance indicators for the product area',
        ],
        'key_skills': [
            'Product discovery and user research methodologies',
            'Data analysis and SQL proficiency for product insights',
            'Clear written and verbal communication of product strategy',
            'Agile product development and backlog management',
            'Stakeholder management across engineering, design, and business teams',
            'A/B testing and experimentation design',
        ],
        'assessment_slugs': ['product', 'behavioral'],
        'questions': [
            {
                'question_text': 'Walk me through how you would approach discovery for a new product area you have been assigned to own.',
                'category': 'technical',
                'difficulty': 'medium',
                'what_it_tests': 'Product discovery methodology and structured approach to understanding a new domain.',
                'sample_answer_outline': 'The candidate should describe a phased approach starting with stakeholder interviews and existing data review, followed by user research, competitive analysis, and market sizing. They should explain how they synthesize findings into opportunity areas and validate assumptions before committing to a roadmap.',
            },
            {
                'question_text': 'Describe a product decision you made that was based on data that conflicted with strong stakeholder opinions. How did you navigate it?',
                'category': 'behavioral',
                'difficulty': 'hard',
                'what_it_tests': 'Data-driven decision-making and stakeholder management under disagreement.',
                'sample_answer_outline': 'A strong answer presents the specific data, explains how the candidate communicated findings to skeptical stakeholders, describes the decision framework used, and shares the outcome. The candidate should demonstrate both analytical rigor and interpersonal skill in how they brought others along.',
            },
            {
                'question_text': 'You have a feature that 20 percent of users love and 80 percent never touch. How do you decide whether to invest further, pivot, or deprecate it?',
                'category': 'problem_solving',
                'difficulty': 'hard',
                'what_it_tests': 'Analytical thinking about feature investment decisions with mixed usage signals.',
                'sample_answer_outline': 'The candidate should discuss segmenting the 20 percent to understand who they are and their value, analyzing whether low adoption is a discovery problem or a value problem, evaluating the cost of maintenance, and making a recommendation tied to the product strategy. They should acknowledge that the answer depends heavily on context.',
            },
            {
                'question_text': 'How do you write a product requirements document that is useful for engineering without being overly prescriptive about implementation?',
                'category': 'technical',
                'difficulty': 'medium',
                'what_it_tests': 'Requirements communication skills and appropriate abstraction level.',
                'sample_answer_outline': 'The candidate should describe focusing on the problem statement, user stories, success criteria, and constraints while leaving implementation decisions to engineering. They should explain how they iterate on the document with the engineering team and use it as a living artifact rather than a waterfall specification.',
            },
            {
                'question_text': 'Tell me about a time when a product launch did not go as planned. What happened and what did you learn?',
                'category': 'behavioral',
                'difficulty': 'medium',
                'what_it_tests': 'Resilience, accountability, and ability to learn from failure.',
                'sample_answer_outline': 'The response should honestly describe what went wrong, the candidate\'s role in both the failure and the recovery, specific actions taken to mitigate impact, and concrete changes they made to their process afterward. The best answers show genuine learning rather than blame deflection.',
            },
            {
                'question_text': 'Your engineering lead wants to spend the next quarter rewriting a core service. Users are not asking for it, but the team says the current system cannot scale. How do you evaluate this request?',
                'category': 'situational',
                'difficulty': 'hard',
                'what_it_tests': 'Ability to evaluate technical investment requests and balance technical and product priorities.',
                'sample_answer_outline': 'A thoughtful answer involves understanding the specific scaling risks and timelines, quantifying the cost of delay if the rewrite is not done, exploring incremental alternatives, and framing the decision in terms of product risk rather than purely technical terms. The candidate should demonstrate respect for engineering concerns while applying product thinking.',
            },
            {
                'question_text': 'How do you design and interpret an A/B test for a significant product change?',
                'category': 'technical',
                'difficulty': 'medium',
                'what_it_tests': 'Experimentation literacy and statistical reasoning.',
                'sample_answer_outline': 'The candidate should cover hypothesis formulation, choosing the right primary metric and guardrail metrics, sample size calculation, test duration, and how they handle ambiguous results. They should also discuss common pitfalls like peeking at results early or running tests that are too small to detect meaningful effects.',
            },
            {
                'question_text': 'How do you maintain alignment between what your team is building and the broader company strategy when priorities shift frequently?',
                'category': 'culture',
                'difficulty': 'medium',
                'what_it_tests': 'Adaptability and strategic alignment in a dynamic environment.',
                'sample_answer_outline': 'The candidate should describe maintaining a clear understanding of the underlying strategic objectives rather than just the current priorities, building flexibility into their roadmap, and establishing regular check-ins with leadership to detect shifts early. They should also discuss how they protect their team from whiplash while remaining responsive.',
            },
            {
                'question_text': 'You are mentoring a junior PM who tends to bring solutions to you rather than problems. How do you help them develop stronger product thinking?',
                'category': 'leadership',
                'difficulty': 'easy',
                'what_it_tests': 'Mentoring ability and commitment to developing others.',
                'sample_answer_outline': 'A good answer describes using questioning techniques to help the PM work backward from solutions to problems, assigning exercises that build problem-framing skills, sharing frameworks for structured thinking, and gradually increasing the PM\'s ownership while providing a safety net.',
            },
            {
                'question_text': 'How do you prioritize your backlog when you have urgent customer escalations, committed roadmap features, and important but non-urgent improvements all competing for attention?',
                'category': 'problem_solving',
                'difficulty': 'medium',
                'what_it_tests': 'Practical prioritization skills under real-world competing demands.',
                'sample_answer_outline': 'The candidate should describe their prioritization framework, how they categorize and triage incoming requests, the role of escalation paths, and how they maintain strategic focus while being responsive to urgent needs. They should demonstrate that they do not simply default to urgency over importance.',
            },
            {
                'question_text': 'A competitor just launched a feature that several of your customers have been requesting. What is your response?',
                'category': 'situational',
                'difficulty': 'medium',
                'what_it_tests': 'Competitive response strategy and composure under market pressure.',
                'sample_answer_outline': 'The candidate should describe evaluating the competitive threat objectively rather than panicking, understanding whether the feature aligns with their own strategy, assessing the quality of the competitor\'s implementation, and deciding whether to fast-follow, differentiate, or stay the course based on strategic fit rather than fear.',
            },
            {
                'question_text': 'What does building a product with accessibility in mind mean to you, and how do you ensure it happens in practice?',
                'category': 'culture',
                'difficulty': 'easy',
                'what_it_tests': 'Awareness of inclusive design principles and ability to operationalize them.',
                'sample_answer_outline': 'The candidate should discuss accessibility as a core product value rather than an afterthought, mention specific standards like WCAG, describe how they include accessibility requirements in their specifications, involve affected users in testing, and hold the team accountable for accessibility in their definition of done.',
            },
        ],
    },
    {
        'slug': 'product-manager',
        'title': 'Product Manager',
        'department': 'Product',
        'seniority_level': 'mid',
        'description': 'The Product Manager is responsible for defining and delivering product features within an established product area. They work closely with engineering and design squads to ship iterative improvements, gather user feedback, and contribute to the product roadmap while developing their strategic product thinking.',
        'responsibilities': [
            'Define feature requirements and user stories for the development squad',
            'Manage the product backlog and facilitate sprint planning and grooming sessions',
            'Conduct user interviews, usability tests, and analyze product usage data',
            'Coordinate cross-functionally with design, engineering, QA, and go-to-market teams',
            'Track feature performance post-launch and iterate based on results',
            'Contribute to quarterly roadmap planning with data-backed proposals',
        ],
        'key_skills': [
            'User story writing and requirements definition',
            'Agile ceremonies facilitation and backlog management',
            'Basic data analysis with SQL and product analytics tools',
            'User research techniques including interviews and usability testing',
            'Clear communication with technical and non-technical stakeholders',
            'Wireframing and low-fidelity prototyping for concept validation',
        ],
        'assessment_slugs': ['product', 'behavioral'],
        'questions': [
            {
                'question_text': 'How do you write a good user story, and what makes a user story ready for engineering to pick up?',
                'category': 'technical',
                'difficulty': 'easy',
                'what_it_tests': 'Understanding of user story best practices and definition of ready.',
                'sample_answer_outline': 'The candidate should describe the standard user story format, acceptance criteria, and the INVEST principles. They should explain their definition of ready including mockups, edge cases, and technical considerations, and how they collaborate with engineering before sprint commitment.',
            },
            {
                'question_text': 'Tell me about a feature you shipped that you are most proud of. What was your role and what impact did it have?',
                'category': 'behavioral',
                'difficulty': 'easy',
                'what_it_tests': 'Track record of delivery and ability to articulate product impact.',
                'sample_answer_outline': 'The candidate should clearly describe the problem they solved, their specific contributions versus the team\'s, the metrics that improved, and what they learned. Strong answers demonstrate ownership of outcomes rather than just activities.',
            },
            {
                'question_text': 'You receive conflicting feedback from five different user interviews about a proposed feature. How do you synthesize this into an actionable decision?',
                'category': 'problem_solving',
                'difficulty': 'medium',
                'what_it_tests': 'Qualitative research synthesis skills and decision-making under ambiguity.',
                'sample_answer_outline': 'A good answer covers looking for underlying patterns rather than surface-level feedback, segmenting users to understand if different personas have different needs, triangulating with quantitative data, and being comfortable making a decision with imperfect information while planning to validate post-launch.',
            },
            {
                'question_text': 'How do you decide what to include in a minimum viable product versus what to save for later iterations?',
                'category': 'technical',
                'difficulty': 'medium',
                'what_it_tests': 'MVP scoping skills and understanding of iterative product development.',
                'sample_answer_outline': 'The candidate should describe starting with the core user problem and identifying the minimum set of features needed to test the key hypothesis. They should discuss techniques for ruthless prioritization, the role of user feedback in informing iterations, and how they manage stakeholder expectations about what is deferred versus cut.',
            },
            {
                'question_text': 'Describe a time when you had to push back on a request from a sales team or a senior leader. How did you handle it?',
                'category': 'behavioral',
                'difficulty': 'medium',
                'what_it_tests': 'Ability to say no constructively while maintaining relationships.',
                'sample_answer_outline': 'The response should show the candidate acknowledging the request\'s value, explaining their reasoning with data or strategic context, offering alternatives, and following up to ensure the relationship remained strong. The best answers show empathy for the requester\'s perspective.',
            },
            {
                'question_text': 'You just launched a feature and adoption is significantly below expectations after two weeks. Walk me through your diagnosis process.',
                'category': 'situational',
                'difficulty': 'medium',
                'what_it_tests': 'Post-launch analytical skills and structured problem-solving.',
                'sample_answer_outline': 'The candidate should describe checking discoverability and awareness first, then examining the user funnel for drop-off points, reviewing qualitative feedback, comparing actual users against the target persona, and formulating hypotheses to test. They should avoid jumping to conclusions and demonstrate a systematic approach.',
            },
            {
                'question_text': 'How do you use data from product analytics tools in your day-to-day work? Give a specific example.',
                'category': 'technical',
                'difficulty': 'easy',
                'what_it_tests': 'Practical experience with product analytics and data-informed decision-making.',
                'sample_answer_outline': 'The candidate should name specific tools they have used, describe a concrete scenario where data changed their understanding or decision, and demonstrate comfort with metrics like retention, conversion, and engagement. They should show they use data as input rather than as the sole decision maker.',
            },
            {
                'question_text': 'A designer on your squad proposes a radically different UX approach that would require significantly more engineering effort. How do you evaluate the trade-off?',
                'category': 'situational',
                'difficulty': 'medium',
                'what_it_tests': 'Cross-functional collaboration and trade-off evaluation between design quality and delivery speed.',
                'sample_answer_outline': 'A balanced answer involves understanding the designer\'s rationale and expected user impact, getting an engineering estimate for both approaches, evaluating the incremental user value against the incremental cost, and potentially proposing a phased approach that captures the core UX improvement without the full engineering investment upfront.',
            },
            {
                'question_text': 'How do you keep your squad motivated and focused when working on a long project with no near-term visible results?',
                'category': 'leadership',
                'difficulty': 'medium',
                'what_it_tests': 'Team motivation skills and ability to maintain morale during long execution cycles.',
                'sample_answer_outline': 'The candidate should discuss breaking the work into meaningful milestones, celebrating progress along the way, connecting daily work to the larger vision, being transparent about the timeline, and checking in with team members individually. They should recognize that different team members may need different types of motivation.',
            },
            {
                'question_text': 'What is your approach to writing and maintaining a product specification that evolves during development?',
                'category': 'technical',
                'difficulty': 'easy',
                'what_it_tests': 'Documentation practices and adaptability during the development process.',
                'sample_answer_outline': 'A practical answer covers starting with a living document that separates the immutable problem definition from the evolving solution, using version control or change logs, communicating changes clearly to the team, and balancing documentation rigor with agility.',
            },
            {
                'question_text': 'How do you build trust with engineers who have previously had negative experiences working with product managers?',
                'category': 'culture',
                'difficulty': 'medium',
                'what_it_tests': 'Relationship-building skills and empathy in cross-functional partnerships.',
                'sample_answer_outline': 'The candidate should describe specific trust-building actions such as involving engineers early in problem definition, being transparent about constraints, following through on commitments, advocating for technical investments, and demonstrating genuine respect for engineering expertise rather than treating engineers as order-takers.',
            },
            {
                'question_text': 'If you had to choose between shipping a feature on time with known minor quality issues or delaying the launch by two weeks to fix them, how would you decide?',
                'category': 'problem_solving',
                'difficulty': 'easy',
                'what_it_tests': 'Judgment about quality versus speed trade-offs in product delivery.',
                'sample_answer_outline': 'A thoughtful answer considers the nature of the quality issues and their user impact, whether there is a hard deadline with business consequences, the reputational cost of quality problems versus the cost of delay, and whether there is a middle path like launching to a limited audience. The candidate should show they evaluate context rather than having a blanket policy.',
            },
        ],
    },
    {
        'slug': 'product-analyst',
        'title': 'Product Analyst',
        'department': 'Product',
        'seniority_level': 'junior',
        'description': 'The Product Analyst supports the product team by turning data into actionable insights. They analyze user behavior, build dashboards, run experiments, and provide the quantitative foundation that informs product decisions, feature prioritization, and success measurement.',
        'responsibilities': [
            'Analyze product usage data to identify trends, opportunities, and issues',
            'Build and maintain dashboards and reports for product KPIs',
            'Support A/B test design, execution, and statistical analysis',
            'Conduct ad hoc analyses to answer product team questions',
            'Document data definitions, methodologies, and key findings',
            'Present insights and recommendations to product managers and stakeholders',
        ],
        'key_skills': [
            'SQL proficiency for querying large datasets',
            'Data visualization with tools like Tableau, Looker, or Metabase',
            'Statistical analysis and A/B testing methodology',
            'Product analytics platforms such as Amplitude, Mixpanel, or Google Analytics',
            'Python or R for data manipulation and analysis',
            'Clear communication of analytical findings to non-technical audiences',
        ],
        'assessment_slugs': ['product', 'behavioral'],
        'questions': [
            {
                'question_text': 'How would you measure the success of a newly launched feature? What metrics would you track and why?',
                'category': 'technical',
                'difficulty': 'easy',
                'what_it_tests': 'Understanding of product metrics and measurement framework basics.',
                'sample_answer_outline': 'The candidate should discuss defining success metrics before launch, choosing leading and lagging indicators, distinguishing between adoption metrics like activation rate and outcome metrics like task completion, and setting up a measurement timeline. They should also mention the importance of guardrail metrics to ensure the feature does not harm other parts of the product.',
            },
            {
                'question_text': 'Describe a time when your analysis revealed something unexpected. How did you validate the finding and communicate it?',
                'category': 'behavioral',
                'difficulty': 'easy',
                'what_it_tests': 'Analytical curiosity, validation rigor, and communication skills.',
                'sample_answer_outline': 'A strong answer describes the unexpected finding, the steps taken to verify it was not a data quality issue, how they investigated root causes, and how they presented the insight in a way that was compelling and actionable for the product team.',
            },
            {
                'question_text': 'A product manager asks you to prove that a feature they want to build will increase retention. How do you approach this request?',
                'category': 'situational',
                'difficulty': 'medium',
                'what_it_tests': 'Analytical integrity and ability to frame analysis appropriately.',
                'sample_answer_outline': 'The candidate should recognize the confirmation bias risk in being asked to prove a predetermined conclusion. A good answer reframes the request as exploring whether there is evidence to support the hypothesis, describes the analysis approach including looking at comparable features or user segments, and presents findings objectively regardless of whether they support the PM\'s thesis.',
            },
            {
                'question_text': 'Walk me through how you would build a product health dashboard from scratch. What would you include and how would you structure it?',
                'category': 'technical',
                'difficulty': 'medium',
                'what_it_tests': 'Dashboard design skills and understanding of product health metrics.',
                'sample_answer_outline': 'The candidate should describe identifying the key audience and their questions, selecting a focused set of metrics organized into categories like acquisition, activation, engagement, retention, and revenue, designing for clarity with appropriate chart types, and planning for drill-down capability. They should emphasize that less is more and that every metric on the dashboard should prompt a decision.',
            },
            {
                'question_text': 'Explain a concept like statistical significance to a non-technical product manager who wants to end an A/B test early because one variant looks like it is winning.',
                'category': 'problem_solving',
                'difficulty': 'easy',
                'what_it_tests': 'Ability to communicate statistical concepts clearly and advocate for analytical rigor.',
                'sample_answer_outline': 'A good answer uses an accessible analogy like coin flipping to explain why early results can be misleading, describes what statistical significance means in practical terms, explains the risks of stopping a test too early, and offers a constructive suggestion like checking what the required sample size is and when the test will reach it.',
            },
            {
                'question_text': 'How do you handle a situation where the data you need for an analysis does not exist or is unreliable?',
                'category': 'situational',
                'difficulty': 'medium',
                'what_it_tests': 'Resourcefulness and problem-solving when facing data limitations.',
                'sample_answer_outline': 'The candidate should describe exploring alternative data sources, using proxy metrics, being transparent about limitations in their analysis, and proactively working with engineering to instrument better tracking for the future. They should demonstrate that missing data does not mean the analysis is impossible, just that it requires creativity and caveats.',
            },
            {
                'question_text': 'What is the difference between correlation and causation in a product context? Give an example of how confusing them could lead to a bad product decision.',
                'category': 'technical',
                'difficulty': 'easy',
                'what_it_tests': 'Foundational statistical literacy and ability to apply it to product decisions.',
                'sample_answer_outline': 'The candidate should clearly explain the concepts, provide a relevant product example such as mistaking power user behavior for behavior that creates power users, and describe how this confusion could lead to building the wrong features. They should also mention techniques for establishing causation like experimentation and causal inference methods.',
            },
            {
                'question_text': 'You discover that a key product metric has dropped significantly over the past week. Walk me through how you would investigate.',
                'category': 'problem_solving',
                'difficulty': 'medium',
                'what_it_tests': 'Root cause analysis skills and structured debugging approach for metric changes.',
                'sample_answer_outline': 'A structured answer covers first verifying the data is correct and there is no instrumentation issue, then segmenting the drop by user cohort, platform, geography, and feature area to isolate the cause. The candidate should describe checking for recent releases, external factors, and seasonality, and explain how they would escalate and communicate findings as they investigate.',
            },
            {
                'question_text': 'How do you prioritize multiple analysis requests from different product managers when you cannot do them all immediately?',
                'category': 'behavioral',
                'difficulty': 'easy',
                'what_it_tests': 'Prioritization and communication skills when managing competing demands.',
                'sample_answer_outline': 'The candidate should describe assessing each request by urgency, decision impact, and effort, communicating timelines transparently, offering quick approximations when a full analysis is not immediately feasible, and setting up self-serve resources like dashboards to reduce repetitive requests over time.',
            },
            {
                'question_text': 'What role should a product analyst play in shaping product strategy, beyond just answering questions from PMs?',
                'category': 'culture',
                'difficulty': 'medium',
                'what_it_tests': 'Understanding of the strategic value of analytics and proactive mindset.',
                'sample_answer_outline': 'A thoughtful answer describes the analyst as a strategic partner who proactively surfaces insights, identifies opportunities the product team may not have considered, brings an objective perspective to strategy discussions, and helps set the measurement framework that shapes how the team defines success. The candidate should give examples of proactive contributions rather than just reactive analysis.',
            },
            {
                'question_text': 'How do you segment users for analysis, and what segmentation approaches have you found most useful for product decisions?',
                'category': 'technical',
                'difficulty': 'medium',
                'what_it_tests': 'User segmentation knowledge and its practical application to product insights.',
                'sample_answer_outline': 'The candidate should discuss behavioral segmentation based on usage patterns, demographic or firmographic segmentation, lifecycle stage segmentation such as new versus activated versus power users, and how different segmentation lenses reveal different insights. They should provide a concrete example of how segmentation changed a product decision.',
            },
            {
                'question_text': 'Your analysis shows that a feature the company is heavily investing in is only used by a small percentage of users. How do you present this finding?',
                'category': 'leadership',
                'difficulty': 'hard',
                'what_it_tests': 'Courage and tact in presenting uncomfortable truths to stakeholders.',
                'sample_answer_outline': 'A mature answer balances honesty with empathy by leading with the data, exploring possible explanations such as the feature being aimed at a specific high-value segment, presenting the findings with context rather than judgment, and offering constructive next steps like deeper investigation into why adoption is low and what could be done about it.',
            },
        ],
    },
]
