SALES_ROLES = [
    {
        'slug': 'vp-of-sales',
        'title': 'VP of Sales',
        'department': 'Sales',
        'seniority_level': 'executive',
        'description': 'The VP of Sales is responsible for defining and executing the overall sales strategy, building a world-class sales organization, and driving predictable, scalable revenue growth. This executive partners with the CEO, board of directors, and cross-functional leaders to align go-to-market motions with company objectives and ensure the business consistently meets or exceeds its revenue targets.',
        'responsibilities': [
            'Define and execute the overall sales strategy aligned with company revenue goals and market opportunity',
            'Build, lead, and develop a high-performing sales organization across all segments and geographies',
            'Establish sales processes, methodologies, and enablement programs that drive consistent pipeline generation and conversion',
            'Own the revenue forecast and provide accurate, transparent reporting to the CEO and board of directors',
            'Partner with marketing, product, and customer success to optimize the full customer acquisition and retention lifecycle',
            'Design compensation structures and incentive plans that attract top talent and align individual motivation with business objectives',
        ],
        'key_skills': [
            'Sales strategy and go-to-market planning',
            'Revenue forecasting and pipeline management',
            'Sales team building and organizational design',
            'Executive stakeholder communication and board reporting',
            'Cross-functional leadership and collaboration',
            'Compensation design and sales operations',
        ],
        'assessment_slugs': ['behavioral'],
        'questions': [
            {
                'question_text': 'How would you approach building a sales organization from the ground up for a company that has achieved initial product-market fit but has no formal sales team, playbook, or repeatable process in place?',
                'category': 'technical',
                'difficulty': 'hard',
                'what_it_tests': 'Ability to design and build a sales organization from scratch including hiring sequencing, process design, and infrastructure decisions',
                'sample_answer_outline': 'A strong answer covers assessing the current state of customer acquisition and win patterns, defining the ideal customer profile and the appropriate sales motion, hiring the first cohort of reps and a frontline manager, establishing a repeatable sales process and playbook grounded in early customer conversations, selecting the right CRM and tooling stack, and setting realistic ramp timelines. The candidate should articulate a phased approach that prioritizes learning and iterating before scaling headcount.',
            },
            {
                'question_text': 'Tell me about a time you had to transform an underperforming sales organization. What was the situation when you arrived, what changes did you make, and what measurable results did you achieve?',
                'category': 'behavioral',
                'difficulty': 'hard',
                'what_it_tests': 'Track record of diagnosing and fixing sales performance issues at an organizational level',
                'sample_answer_outline': 'The candidate should describe the specific performance gaps they identified upon arrival, the diagnostic process they used to uncover root causes such as talent gaps, process breakdowns, territory imbalances, or enablement deficiencies, and the prioritized changes they implemented. A good answer includes measurable before-and-after results on quota attainment and pipeline metrics, and acknowledges the human challenges of organizational change including difficult personnel decisions.',
            },
            {
                'question_text': 'Your company is halfway through the fiscal year and the sales team is tracking 30 percent behind the annual revenue target. The board is demanding answers. How do you assess the situation and develop a credible recovery plan?',
                'category': 'situational',
                'difficulty': 'hard',
                'what_it_tests': 'Crisis management under revenue pressure and ability to develop realistic recovery plans while maintaining executive credibility',
                'sample_answer_outline': 'A strong candidate would first diagnose whether the gap is a pipeline generation problem, a conversion rate problem, or a deal size problem by analyzing funnel metrics at each stage. They should describe developing a recovery plan that includes both quick wins such as deal acceleration and expansion selling and structural fixes such as process or personnel changes. The candidate should explain how they would communicate transparently with the board about what is realistically achievable and what trade-offs are required.',
            },
            {
                'question_text': 'How do you build a culture of accountability on a sales team without creating a fear-based environment that drives unhealthy behavior? What does the right balance look like in practice?',
                'category': 'leadership',
                'difficulty': 'medium',
                'what_it_tests': 'Leadership philosophy and ability to balance rigorous performance expectations with supportive, developmental management',
                'sample_answer_outline': 'The candidate should discuss setting clear expectations and metrics upfront so there are no surprises, providing transparency into performance data across the team, coaching consistently rather than only managing to lagging indicators, celebrating effort and improvement alongside closed-won outcomes, and addressing underperformance directly but with empathy and a clear improvement path. A good answer includes specific examples of how they have built high-performance cultures that people want to be part of rather than flee from.',
            },
            {
                'question_text': 'What is your philosophy on sales culture, and how do you ensure the sales organization represents the company values while still driving aggressive growth targets?',
                'category': 'culture',
                'difficulty': 'medium',
                'what_it_tests': 'Values alignment and ability to build an ethical, high-performing sales culture that sustains over time',
                'sample_answer_outline': 'A good answer addresses hiring for values fit alongside selling skills, setting behavioral expectations in addition to quota expectations, and modeling the desired culture from the top down. The candidate should discuss how they handle situations where a top revenue performer violates cultural norms, and give examples of specific cultural initiatives they have implemented that reinforced integrity and collaboration on sales teams.',
            },
            {
                'question_text': 'Your top-performing sales rep consistently closes the most revenue but also has the highest customer churn rate within the first 12 months. How do you investigate this pattern and what actions do you take?',
                'category': 'problem_solving',
                'difficulty': 'hard',
                'what_it_tests': 'Ability to balance short-term revenue performance against long-term customer health and detect systemic issues in selling practices',
                'sample_answer_outline': 'The candidate should describe analyzing the rep closed deals for patterns such as overpromising capabilities, poor qualification against ideal customer profile, or misaligned use cases. They should discuss reviewing recorded calls and customer feedback from churned accounts, having a direct coaching conversation with the rep grounded in data, and potentially adjusting incentive structures to include retention or customer satisfaction metrics. A strong answer addresses the systemic issue by examining whether the compensation plan inadvertently rewards this behavior.',
            },
            {
                'question_text': 'Describe your approach to building a reliable revenue forecasting process. What methodology do you use, how do you ensure accuracy at scale, and how do you handle the tension between optimism and conservatism?',
                'category': 'technical',
                'difficulty': 'medium',
                'what_it_tests': 'Forecasting rigor and understanding of pipeline management discipline at an executive level',
                'sample_answer_outline': 'A strong answer discusses using multiple forecasting methods such as bottoms-up rep commits, weighted pipeline analysis, historical conversion rates, and top-down capacity models, then triangulating between them to arrive at a range. The candidate should explain how they establish clear forecast categories with objective criteria, run regular deal reviews to pressure-test assumptions, hold reps and managers accountable for forecast accuracy over time, and use data to progressively remove subjectivity from the process.',
            },
            {
                'question_text': 'Tell me about a time you had to make a difficult decision about letting go of a senior sales leader who was well-liked by the team but not delivering results. How did you handle the decision and its aftermath?',
                'category': 'behavioral',
                'difficulty': 'medium',
                'what_it_tests': 'Courage in making tough personnel decisions and ability to manage the impact on team morale and continuity',
                'sample_answer_outline': 'The candidate should describe the data and observations that led to the decision, the steps they took to give the person a fair opportunity to improve through a documented performance plan, how they ultimately made and communicated the decision with dignity and respect, and how they managed the team through the transition including interim coverage and transparent messaging. A good answer shows both decisiveness and compassion.',
            },
            {
                'question_text': 'The product team wants to move upmarket to enterprise accounts, but your current sales team and process are optimized for mid-market velocity deals. How do you plan and execute this transition without losing your existing revenue base?',
                'category': 'situational',
                'difficulty': 'medium',
                'what_it_tests': 'Strategic thinking about sales segment transitions and ability to manage organizational change across selling motions',
                'sample_answer_outline': 'The candidate should discuss assessing the skills gap between mid-market and enterprise selling, building a dedicated enterprise team rather than converting the entire existing team, developing new sales processes suited for longer cycles and multiple stakeholders, investing in enterprise-specific enablement and content, and setting realistic timelines for pipeline build in a new segment. They should explicitly acknowledge the risk of neglecting the mid-market revenue engine during the transition and explain how they would protect it.',
            },
            {
                'question_text': 'How do you structure and run an effective sales leadership team meeting cadence? What rhythms do you establish and what outcomes should each cadence produce?',
                'category': 'leadership',
                'difficulty': 'easy',
                'what_it_tests': 'Operational discipline and ability to manage a sales management layer through structured cadences that drive results',
                'sample_answer_outline': 'A good answer describes a cadence of weekly forecast reviews focused on deal-level accuracy, monthly pipeline deep-dives to assess coverage and quality, quarterly business reviews for strategic assessment, and annual planning for target setting and territory design. The candidate should explain how each meeting drives specific accountability and decisions, discuss one-on-one rhythms with direct reports, and describe how they develop their leadership bench through these interactions.',
            },
            {
                'question_text': 'How do you approach building a diverse and inclusive sales organization? What specific, concrete steps have you taken in previous roles to attract and retain diverse talent?',
                'category': 'culture',
                'difficulty': 'easy',
                'what_it_tests': 'Commitment to building diverse sales teams and awareness of systemic barriers in traditional sales hiring practices',
                'sample_answer_outline': 'The candidate should discuss specific actions such as diversifying sourcing channels beyond traditional sales networks, implementing structured interview processes to reduce unconscious bias, reviewing job descriptions for exclusionary language, building inclusive onboarding programs that support different backgrounds, and creating mentorship opportunities. They should provide concrete examples from their experience and acknowledge both the business performance case and the ethical imperative for diversity in sales organizations.',
            },
            {
                'question_text': 'You are seeing a pattern where enterprise deals are consistently stalling at the procurement and legal review stage, adding four to six weeks to every deal cycle. How do you solve this cross-functional challenge?',
                'category': 'problem_solving',
                'difficulty': 'medium',
                'what_it_tests': 'Cross-functional problem solving and ability to remove systemic blockers from the sales process that span organizational boundaries',
                'sample_answer_outline': 'A strong answer describes analyzing where specifically in the legal and procurement process deals are stalling, partnering with the legal team to pre-approve standard contract terms and create a library of approved fallback positions, establishing a deal desk function to accelerate complex reviews, developing procurement-ready materials and security documentation for buyers, and potentially restructuring deal terms to reduce friction points. The candidate should show they approach this as a systemic issue requiring cross-functional collaboration rather than simply blaming other departments for being slow.',
            },
        ],
    },
    {
        'slug': 'sales-director',
        'title': 'Sales Director',
        'department': 'Sales',
        'seniority_level': 'lead',
        'description': 'The Sales Director leads a team of account executives and frontline sales managers to achieve regional or segment revenue targets. This role bridges executive sales strategy with day-to-day frontline execution, combining hands-on deal involvement with team development, rigorous coaching, and operational discipline to drive consistent quota attainment across the team.',
        'responsibilities': [
            'Lead and coach a team of account executives and frontline managers to consistently achieve and exceed quota targets',
            'Develop and execute territory and account plans that maximize revenue coverage and market penetration across the assigned segment',
            'Conduct regular pipeline reviews and deal inspections to ensure forecast accuracy and healthy deal progression',
            'Recruit, onboard, and ramp new sales talent to maintain a high-performing and fully staffed team at all times',
            'Partner with marketing and sales development to ensure adequate and quality pipeline generation for the team',
            'Analyze sales performance data to identify trends, coaching opportunities, and systemic process improvements',
        ],
        'key_skills': [
            'Sales coaching and team development',
            'Pipeline management and deal inspection',
            'Territory planning and account segmentation',
            'Sales recruiting and talent assessment',
            'Forecasting accuracy and revenue management',
            'Cross-functional collaboration with marketing and product',
        ],
        'assessment_slugs': ['behavioral'],
        'questions': [
            {
                'question_text': 'Walk me through how you would conduct a pipeline review with one of your account executives. What specifically are you looking for, what questions do you ask, and how do you use the review as a coaching opportunity?',
                'category': 'technical',
                'difficulty': 'medium',
                'what_it_tests': 'Pipeline management discipline and ability to coach reps through deal strategy during structured reviews',
                'sample_answer_outline': 'A strong answer describes reviewing pipeline coverage ratios and overall health first, then inspecting individual deals for progression velocity, stakeholder engagement depth, and concrete next steps. The candidate should explain how they use a qualification framework like MEDDPICC to stress-test deals, how they identify stuck opportunities that need intervention, and how they coach reps to develop their own action plans rather than simply interrogating them about deal status.',
            },
            {
                'question_text': 'Tell me about a time you turned around a rep who was consistently missing quota for multiple quarters. What was your diagnostic and coaching approach, and what was the outcome?',
                'category': 'behavioral',
                'difficulty': 'medium',
                'what_it_tests': 'Coaching effectiveness and ability to diagnose root causes of individual performance gaps beyond surface-level activity metrics',
                'sample_answer_outline': 'The candidate should describe diagnosing the specific skills, knowledge, or activity gap through data analysis and direct observation such as call shadowing. They should detail a targeted coaching plan with clear milestones and checkpoints, explain how they invested time in ride-alongs, role-plays, and deal strategy sessions, and track progress against the plan. A good answer includes the outcome honestly, including whether the rep ultimately succeeded or was managed out, and explains what the experience taught them about effective coaching.',
            },
            {
                'question_text': 'It is the last week of the quarter and your team is 15 percent short of the quarterly target. You have several deals in late stage that could close but none are firmly committed. How do you handle this week?',
                'category': 'situational',
                'difficulty': 'hard',
                'what_it_tests': 'End-of-quarter execution skills and ability to drive legitimate urgency without resorting to desperate discounting or pressure tactics',
                'sample_answer_outline': 'A strong candidate would first assess which deals are genuinely closeable this week based on buyer timeline, decision criteria completion, and procurement readiness, then develop specific closing plans for each deal with the owning reps. They should discuss creating legitimate urgency tied to business value rather than artificial deadlines, offering value-based concessions rather than blanket discounts, knowing when to push a deal into next quarter rather than forcing a bad close, and maintaining honest communication with leadership about realistic outcomes.',
            },
            {
                'question_text': 'How do you design territory and account assignments for your team to maximize market coverage while ensuring fairness and minimizing destructive internal conflict?',
                'category': 'leadership',
                'difficulty': 'hard',
                'what_it_tests': 'Territory planning skills and ability to balance revenue optimization with team morale, fairness, and retention',
                'sample_answer_outline': 'The candidate should describe using data to size territories based on total addressable market, account potential, and rep capacity, while considering existing relationships and account history. They should explain how they handle territory transitions when changes are necessary, how they communicate the rationale transparently so reps understand the methodology, and how they manage the inevitable concerns from reps who feel disadvantaged. A good answer acknowledges that perfect fairness is impossible and explains the principles they use to make defensible decisions.',
            },
            {
                'question_text': 'What does a healthy competitive culture on a sales team look like to you? How do you foster productive competition while ensuring it does not undermine collaboration and knowledge sharing?',
                'category': 'culture',
                'difficulty': 'easy',
                'what_it_tests': 'Understanding of sales team dynamics and ability to cultivate competition that elevates everyone rather than creating toxicity',
                'sample_answer_outline': 'A good answer discusses using leaderboards and public recognition to celebrate success while also recognizing collaborative behaviors like sharing winning tactics and helping teammates on deals. The candidate should explain how they set up team-based incentives alongside individual quotas, establish norms around knowledge sharing in team meetings, and intervene decisively when competition becomes cutthroat or undermines team trust. They should give specific examples of rituals or programs that built strong team cohesion.',
            },
            {
                'question_text': 'Your team is losing deals consistently to a specific competitor and win rates against them have dropped from 50 percent to 25 percent over two quarters. How do you diagnose the root cause and develop a tactical response?',
                'category': 'problem_solving',
                'difficulty': 'hard',
                'what_it_tests': 'Competitive analysis skills and ability to develop systematic tactical responses to competitive threats',
                'sample_answer_outline': 'The candidate should describe conducting structured win-loss analysis through customer interviews and detailed rep debriefs, identifying whether the losses are driven by product gaps, pricing pressure, positioning weakness, or sales execution issues. They should then discuss developing updated competitive battle cards with specific objection handling guidance, running targeted training sessions and role-plays focused on competitive scenarios, potentially adjusting deal strategy and qualification criteria for competitive situations, and partnering with product and marketing to address any underlying capability gaps.',
            },
            {
                'question_text': 'Explain how you would build a structured onboarding and ramp program for newly hired account executives joining your team. What milestones would you set and how would you measure true readiness versus just time elapsed?',
                'category': 'technical',
                'difficulty': 'medium',
                'what_it_tests': 'Sales enablement thinking and ability to systematically ramp new hires to full productivity',
                'sample_answer_outline': 'A strong answer outlines a phased ramp program covering product and industry knowledge, sales process and methodology certification, tool proficiency, shadowing experienced reps and then reverse shadowing with coaching, role-play certifications on key selling scenarios, and graduated quota expectations. The candidate should define specific competency milestones at 30, 60, and 90 days, explain how they assess readiness through practical demonstrations rather than knowledge tests alone, and share their typical time-to-first-deal and time-to-full-productivity benchmarks.',
            },
            {
                'question_text': 'Describe a time when you had to deliver difficult feedback to a high-performing rep about their behavior with customers or colleagues. How did you prepare for that conversation and what was the outcome?',
                'category': 'behavioral',
                'difficulty': 'hard',
                'what_it_tests': 'Courage to address behavioral issues even with top revenue producers and skill in delivering constructive feedback that drives change',
                'sample_answer_outline': 'The candidate should describe a specific situation where a top performer exhibited problematic behavior, explain why the behavior needed to change despite strong revenue numbers, detail how they prepared for and delivered the feedback with specific examples and clear expectations for change, and share the outcome including whether the behavior actually changed. A good answer demonstrates that high performance does not excuse unprofessional behavior and shows the candidate ability to hold that line consistently.',
            },
            {
                'question_text': 'Your marketing team is generating a high volume of inbound leads but your reps complain that lead quality is poor and conversion rates are declining. Marketing disagrees and points to their MQL numbers. How do you find the truth and resolve this?',
                'category': 'situational',
                'difficulty': 'medium',
                'what_it_tests': 'Cross-functional collaboration skills and ability to use data rather than opinions to resolve marketing-sales alignment tension',
                'sample_answer_outline': 'The candidate should describe establishing shared, objective definitions for lead quality and qualification criteria, analyzing conversion data by lead source, segment, and campaign to identify where quality is genuinely low versus where rep follow-up is insufficient, sitting in on actual sales calls to assess lead quality firsthand, and facilitating a data-driven conversation between the teams. They should show willingness to hold their own team accountable for follow-up discipline and speed-to-lead while also working with marketing to refine targeting and lead scoring models.',
            },
            {
                'question_text': 'How do you identify and develop future sales leaders from your team of individual contributors? What traits do you look for that distinguish potential managers from career individual contributors?',
                'category': 'leadership',
                'difficulty': 'easy',
                'what_it_tests': 'Talent development orientation and ability to identify and nurture leadership potential beyond just quota attainment',
                'sample_answer_outline': 'A good answer discusses looking for specific traits beyond revenue performance such as naturally coaching peers, thinking strategically about the business, demonstrating empathy and emotional intelligence, and communicating effectively across levels. The candidate should describe creating structured leadership development opportunities like mentoring programs, stretch assignments leading team initiatives, and involvement in strategic projects, and explain how they assess whether someone is truly suited for management versus being a highly effective individual contributor who should be developed on a different track.',
            },
            {
                'question_text': 'How do you think about building trust when you join a new team as their sales director, especially when the team has existing relationships, dynamics, and possibly skepticism about new leadership?',
                'category': 'culture',
                'difficulty': 'medium',
                'what_it_tests': 'Self-awareness and emotional intelligence in earning trust with a new team during a leadership transition',
                'sample_answer_outline': 'The candidate should describe a listening-first approach during the initial weeks, spending substantial time in one-on-ones understanding each person motivations, concerns, and career aspirations. They should discuss avoiding sweeping changes before thoroughly understanding the current state, building credibility through consistent follow-through on small commitments, and being transparent about their leadership style and expectations. A good answer acknowledges that trust is earned through actions over time rather than claimed through title.',
            },
            {
                'question_text': 'Average deal sizes on your team have been shrinking quarter over quarter despite stable product pricing. Reps are hitting activity metrics but total revenue is declining. What do you investigate and how do you course correct?',
                'category': 'problem_solving',
                'difficulty': 'medium',
                'what_it_tests': 'Revenue diagnostic skills and ability to identify whether deal compression is a selling, targeting, or market-driven issue',
                'sample_answer_outline': 'A strong answer investigates multiple potential causes including reps discounting heavily to accelerate closes, gravitating toward smaller accounts that are easier to win, failing to multi-thread and sell to economic buyers who control larger budgets, reduced product scope in proposals, or competitive pressure compressing pricing. The candidate should describe analyzing deal data for patterns across reps, segments, and time periods, reviewing specific deals to understand the story behind the numbers, and implementing corrective actions such as discount governance, value-selling training, revised account targeting criteria, or adjusted compensation incentives.',
            },
        ],
    },
    {
        'slug': 'account-executive',
        'title': 'Account Executive',
        'department': 'Sales',
        'seniority_level': 'mid',
        'description': 'The Account Executive is responsible for managing the full sales cycle from qualified opportunity through close, building deep relationships with key stakeholders, and consistently achieving or exceeding individual quota. This role requires strong consultative selling skills, thorough product knowledge, and the ability to navigate complex buying processes involving multiple decision-makers and competing priorities.',
        'responsibilities': [
            'Manage the full sales cycle from initial discovery through negotiation, contracting, and close for assigned accounts and territories',
            'Conduct thorough discovery to understand prospect business challenges, strategic goals, and internal decision-making processes',
            'Develop and present compelling proposals and tailored demonstrations that connect product capabilities to each prospect specific needs',
            'Build and maintain relationships with multiple stakeholders including economic buyers, technical evaluators, champions, and end users',
            'Maintain accurate and current pipeline data in CRM and provide reliable weekly forecasts to sales leadership',
            'Collaborate with sales development, solutions engineering, and customer success to deliver a seamless end-to-end buyer experience',
        ],
        'key_skills': [
            'Consultative selling and needs-based discovery',
            'Proposal development and solution presentation',
            'Negotiation and objection handling',
            'CRM management and pipeline hygiene',
            'Stakeholder mapping and relationship building',
            'Time management and deal prioritization',
        ],
        'assessment_slugs': ['behavioral'],
        'questions': [
            {
                'question_text': 'Walk me through your discovery process for a new enterprise opportunity. What specific questions do you ask, in what sequence, and how do you use the information you gather to shape your overall deal strategy?',
                'category': 'technical',
                'difficulty': 'medium',
                'what_it_tests': 'Discovery methodology and ability to uncover business pain, quantifiable impact, and decision dynamics in complex sales cycles',
                'sample_answer_outline': 'A strong answer demonstrates a structured discovery framework that starts with understanding the prospect business context and strategic priorities, then drills into specific pain points and their quantifiable business impact, maps the decision-making process including all stakeholders and their individual motivations, uncovers timeline drivers and budget parameters, and identifies potential risks to the deal. The candidate should explain how they adapt their approach based on what they learn and how discovery insights directly inform their proposal and presentation strategy.',
            },
            {
                'question_text': 'Tell me about a significant deal you lost that you genuinely believed you were going to win. What happened, what did you miss, and what did you change about your approach going forward?',
                'category': 'behavioral',
                'difficulty': 'medium',
                'what_it_tests': 'Self-awareness, ability to learn from losses, and honest self-assessment of selling mistakes without deflecting blame',
                'sample_answer_outline': 'The candidate should describe a specific deal with enough context to understand the stakes and complexity, provide an honest assessment of what went wrong whether it was poor qualification, missing a key stakeholder, losing to a competitor on positioning, or an execution misstep, and articulate concrete lessons they applied to subsequent deals. A good answer shows genuine accountability rather than attributing the loss entirely to external factors or bad luck.',
            },
            {
                'question_text': 'You are in the final stages of a large deal and the prospect CFO, whom you have never met or engaged, raises a significant financial objection that threatens to derail the entire deal. How do you handle this?',
                'category': 'situational',
                'difficulty': 'hard',
                'what_it_tests': 'Ability to handle late-stage deal risks from previously unengaged stakeholders and executive-level objection handling',
                'sample_answer_outline': 'A strong candidate would first acknowledge the objection seriously and seek to understand the CFO full concern rather than immediately countering with a rehearsed response. They should describe leveraging their internal champion to get context on the CFO specific priorities and influence, requesting a direct meeting with the CFO, preparing a tailored business case and ROI analysis that addresses the financial objection specifically, and reflecting on how to prevent this scenario in future deals by proactively engaging financial stakeholders much earlier in the process.',
            },
            {
                'question_text': 'How do you manage your time and prioritize effectively across a pipeline with 30 active opportunities at different stages when you know you cannot give equal attention to all of them?',
                'category': 'leadership',
                'difficulty': 'easy',
                'what_it_tests': 'Time management discipline and strategic prioritization skills that are critical for consistent quota attainment',
                'sample_answer_outline': 'A good answer describes a prioritization framework that weighs deal size, close probability, stage advancement velocity, and timeline urgency, combined with disciplined time-blocking and weekly planning rituals. The candidate should explain how they identify which deals require active attention versus which can be progressed through automated nurture, how they resist the pull of inbound requests that distract from priority opportunities, and how they use their CRM and task management to maintain organization across a large book of business.',
            },
            {
                'question_text': 'How do you approach selling in a way that feels authentic and builds genuine trust with prospects rather than being perceived as pushy, scripted, or transactional?',
                'category': 'culture',
                'difficulty': 'easy',
                'what_it_tests': 'Selling philosophy and genuine commitment to consultative, value-based approaches over aggressive closing tactics',
                'sample_answer_outline': 'The candidate should articulate a consultative approach centered on understanding and solving real business problems rather than pushing product features. They should discuss how they qualify out when there is not a genuine fit, how they provide value throughout the sales process through relevant insights and resources even before a deal closes, and how they build trust by being transparent about product limitations when they exist. A good answer includes specific examples of walking away from deals that were not right for the customer and how that honesty built long-term credibility.',
            },
            {
                'question_text': 'A prospect tells you they are very interested in your solution but their current contract with your competitor does not expire for eight months. How do you manage this long timeline while keeping the opportunity alive and your pipeline healthy?',
                'category': 'problem_solving',
                'difficulty': 'medium',
                'what_it_tests': 'Long-cycle deal management skills and ability to maintain meaningful engagement without being intrusive over an extended timeline',
                'sample_answer_outline': 'A strong answer discusses building a mutual action plan working backward from the contract expiry date with specific milestones, providing ongoing value through relevant industry content and insights to maintain the relationship, engaging multiple stakeholders to broaden organizational buy-in beyond a single contact, monitoring for trigger events that could accelerate the timeline such as dissatisfaction with the incumbent, and managing their own overall pipeline to avoid becoming dependent on this single long-dated opportunity. The candidate should discuss how they document nurture activities and follow up systematically.',
            },
            {
                'question_text': 'Explain how you prepare for and deliver a product demonstration for a prospect who has articulated very specific and detailed technical requirements. How do you balance showcasing broad product capabilities against tailoring tightly to their stated needs?',
                'category': 'technical',
                'difficulty': 'hard',
                'what_it_tests': 'Demo preparation rigor and ability to deliver customer-centric presentations that drive deal progression',
                'sample_answer_outline': 'The candidate should describe conducting thorough pre-demo discovery to understand priority use cases, partnering with solutions engineering to build a tailored demo environment that mirrors the prospect workflow, structuring the demo narrative around the prospect business problems rather than delivering a generic feature tour, preparing for likely objections and competitive comparisons, and building in interactive moments to keep the prospect actively engaged. They should also explain how they handle requests to demonstrate features that do not exist or areas where the product has honest limitations.',
            },
            {
                'question_text': 'Describe a time when you successfully navigated a complex deal involving multiple stakeholders who had conflicting priorities and different definitions of success. How did you align everyone and close the deal?',
                'category': 'behavioral',
                'difficulty': 'hard',
                'what_it_tests': 'Complex deal navigation skills and ability to manage multiple stakeholder dynamics and competing agendas simultaneously',
                'sample_answer_outline': 'The candidate should describe a specific multi-stakeholder deal, explain how they mapped the stakeholder landscape and understood each person unique priorities and concerns, detail their strategy for addressing different needs while maintaining a cohesive value narrative, and share how they leveraged their internal champion to help align the buying committee. A good answer shows political awareness, strategic relationship management, and the patience required to orchestrate consensus in complex organizations.',
            },
            {
                'question_text': 'The prospect has shortlisted you and one competitor for the final decision. They ask you directly why they should choose your solution over the alternative. How do you respond in that moment?',
                'category': 'situational',
                'difficulty': 'medium',
                'what_it_tests': 'Competitive positioning skills and ability to differentiate compellingly without disparaging competitors',
                'sample_answer_outline': 'A strong candidate would avoid directly attacking the competitor and instead redirect the conversation to the prospect stated priorities and success criteria from discovery. They should describe highlighting unique differentiators that map specifically to what matters most to this prospect, using relevant customer proof points and case studies from similar organizations, and asking questions that naturally surface areas where their solution excels. The candidate should demonstrate the ability to acknowledge competitor strengths graciously while being clear and confident about where their product wins on the criteria that matter most.',
            },
            {
                'question_text': 'How do you approach negotiation when a prospect pushes hard for a significant discount late in the deal cycle? What is your framework for protecting deal value while preserving the relationship?',
                'category': 'leadership',
                'difficulty': 'medium',
                'what_it_tests': 'Negotiation discipline and ability to protect deal value and company pricing integrity while maintaining the buyer relationship',
                'sample_answer_outline': 'The candidate should describe anchoring value throughout the sales process long before negotiation begins, understanding the prospect underlying budget constraints and procurement process, trading concessions for commitments rather than giving discounts unilaterally, knowing their walk-away point before entering any negotiation, and involving sales leadership strategically when needed. A good answer includes specific negotiation techniques they use regularly and demonstrates understanding that excessive discounting erodes not just this deal but future pricing credibility across the market.',
            },
            {
                'question_text': 'How do you handle a situation where you genuinely believe your product is not the best fit for a prospect who is eager to buy and would likely sign a contract this quarter?',
                'category': 'culture',
                'difficulty': 'medium',
                'what_it_tests': 'Ethical selling standards and willingness to prioritize long-term customer outcomes over short-term quota attainment',
                'sample_answer_outline': 'A good answer demonstrates the courage to be transparent with the prospect about specific fit concerns, clearly explain the areas where the product may fall short of their needs, and potentially recommend a better-suited alternative. The candidate should discuss how being honest in these moments builds long-term professional reputation and generates referral opportunities, while acknowledging the real tension with quota pressure and explaining why they believe this approach produces better outcomes for everyone over a career in sales.',
            },
            {
                'question_text': 'You realize you have been spending most of your time on small, easy-to-close deals rather than pursuing the larger, more strategic opportunities in your territory. How do you recognize this pattern and course correct?',
                'category': 'problem_solving',
                'difficulty': 'easy',
                'what_it_tests': 'Self-awareness about time allocation habits and ability to proactively shift focus toward higher-impact selling activities',
                'sample_answer_outline': 'The candidate should describe recognizing the pattern through honest pipeline analysis and deal size trending, understanding the psychological reasons they are gravitating toward smaller deals such as comfort zone bias or risk aversion, setting explicit weekly time blocks dedicated to enterprise prospecting and strategic account planning, creating a targeting plan for top accounts with specific outreach strategies, requesting coaching from their manager on enterprise selling techniques, and establishing personal accountability mechanisms to sustain the behavioral change.',
            },
        ],
    },
    {
        'slug': 'sales-development-representative',
        'title': 'Sales Development Representative',
        'department': 'Sales',
        'seniority_level': 'junior',
        'description': 'The Sales Development Representative is responsible for generating qualified pipeline for the sales team through disciplined outbound prospecting and rigorous inbound lead qualification. This role serves as the first point of contact for many potential customers and requires strong verbal and written communication skills, resilience in the face of frequent rejection, and the discipline to execute high-volume outreach while maintaining quality conversations.',
        'responsibilities': [
            'Execute outbound prospecting campaigns through cold calling, personalized email sequences, and social selling to generate qualified meetings',
            'Qualify inbound leads against defined criteria to determine fit and buying readiness before handing off to account executives',
            'Research target accounts and key contacts to personalize outreach and identify relevant pain points, triggers, and competitive situations',
            'Maintain accurate and complete records of all prospecting activity, lead data, and conversation notes in the CRM system',
            'Collaborate with account executives to ensure smooth handoff of qualified opportunities and gather feedback on lead quality',
            'Meet or exceed daily, weekly, and monthly activity targets and pipeline generation quotas consistently',
        ],
        'key_skills': [
            'Cold calling and phone-based communication',
            'Email copywriting and outreach sequence design',
            'Lead qualification and initial needs assessment',
            'CRM data management and prospecting tool proficiency',
            'Account research and intelligence gathering',
            'Resilience and consistent daily activity discipline',
        ],
        'assessment_slugs': ['behavioral'],
        'questions': [
            {
                'question_text': 'Walk me through how you would research and prepare for a cold call to a VP of Engineering at a mid-sized software company. What specific information would you look for and how would you use it to craft your opening?',
                'category': 'technical',
                'difficulty': 'easy',
                'what_it_tests': 'Research methodology and ability to prepare personalized, relevant outreach that resonates with senior prospects',
                'sample_answer_outline': 'A good answer describes checking the company website for recent news, funding rounds, or product launches, reviewing the prospect LinkedIn profile for career background, shared connections, and recent posts, looking at job postings to understand team priorities and technology stack, and using this information to craft a relevant opening that connects their specific situation to the product value proposition. The candidate should demonstrate they understand that quality preparation is more important than raw call volume.',
            },
            {
                'question_text': 'Tell me about a time you faced significant rejection or an extended stretch without positive results in a previous role or experience. How did you stay motivated and what specifically did you do to break through?',
                'category': 'behavioral',
                'difficulty': 'easy',
                'what_it_tests': 'Resilience, persistence, and intrinsic motivation in the face of the constant rejection that is inherent in sales development work',
                'sample_answer_outline': 'The candidate should describe a specific period of difficulty with honest detail, explain the emotions they experienced without sugarcoating, and describe the specific actions they took to stay disciplined while adjusting their approach. A good answer shows both mental toughness and the intelligence to seek coaching, experiment with new tactics, or fundamentally change their process rather than simply grinding harder at the same ineffective approach.',
            },
            {
                'question_text': 'You connect with a prospect on a cold call and they say they are somewhat interested but extremely busy this week and ask you to just send an email instead. How do you handle this moment on the phone?',
                'category': 'situational',
                'difficulty': 'medium',
                'what_it_tests': 'Ability to navigate common brush-off objections and create genuine engagement during cold calls without crossing into pushy territory',
                'sample_answer_outline': 'A strong candidate would acknowledge the prospect time constraints respectfully, attempt to ask one or two quick qualifying questions to make the follow-up email highly relevant and personalized, confirm the best email address and propose a specific date and time for a brief follow-up call, and commit to sending a concise, valuable email within the hour. The candidate should demonstrate they understand the balance between professional persistence and genuine respect for the prospect time.',
            },
            {
                'question_text': 'How do you organize and structure your day to balance rapid inbound lead response times with dedicated outbound prospecting blocks while maintaining consistent activity levels throughout the week?',
                'category': 'leadership',
                'difficulty': 'easy',
                'what_it_tests': 'Time management and self-discipline in structuring a productive, sustainable SDR workday without constant manager oversight',
                'sample_answer_outline': 'A good answer describes specific time-blocking strategies such as dedicated morning calling windows when connect rates are highest, designated periods for email follow-up and sequence management, and research blocks for next-day preparation. The candidate should explain how they prioritize inbound leads by response time requirements and lead score, how they protect outbound calling blocks from interruption and administrative tasks, and how they track their own activity metrics throughout the day to stay on pace rather than cramming at the end of the week.',
            },
            {
                'question_text': 'What does being a great teammate look like in an SDR role? How do you contribute to the broader team success beyond just hitting your own individual numbers?',
                'category': 'culture',
                'difficulty': 'easy',
                'what_it_tests': 'Team orientation and willingness to contribute to collective team success beyond personal metrics and recognition',
                'sample_answer_outline': 'The candidate should discuss proactively sharing successful messaging templates and call tactics with teammates, celebrating team wins and supporting colleagues who are in a slump, offering to help peers practice their pitch or prepare for important calls, participating actively in team meetings with constructive ideas rather than staying silent, and providing honest, specific feedback on lead quality to help improve the overall process. A good answer shows the candidate views team success as inseparable from individual success.',
            },
            {
                'question_text': 'You have been executing the same outbound email sequence for three months and response rates have dropped from 8 percent to 2 percent. How do you diagnose what is going wrong and develop a plan to improve results?',
                'category': 'problem_solving',
                'difficulty': 'medium',
                'what_it_tests': 'Analytical thinking and ability to iterate systematically on outreach approaches based on performance data rather than intuition alone',
                'sample_answer_outline': 'A strong answer investigates multiple potential causes including market email fatigue, subject line degradation, messaging relevance decay, target list quality deterioration, send timing issues, and deliverability or spam filter problems. The candidate should describe a systematic A/B testing approach starting with the highest-impact variables like subject lines and opening sentences, explain how they would benchmark their performance against team averages to calibrate expectations, and discuss when they would seek input from their manager or top-performing peers versus experimenting independently.',
            },
            {
                'question_text': 'Explain the difference between a truly qualified lead and one that merely appears qualified on the surface. What specific criteria do you use to determine whether a prospect is genuinely ready for an account executive conversation?',
                'category': 'technical',
                'difficulty': 'medium',
                'what_it_tests': 'Understanding of lead qualification rigor and ability to distinguish genuine buying signals from polite interest or curiosity',
                'sample_answer_outline': 'The candidate should describe a qualification framework covering authority or access to decision-makers, a genuine and articulated business need or pain point, a realistic timeline or trigger event driving urgency, budget awareness or willingness to invest, and active engagement with the next step rather than passive agreement. They should discuss the critical difference between a prospect being polite or curious versus having genuine buying intent, and explain how they resist the temptation to pass marginally qualified leads just to inflate meeting numbers.',
            },
            {
                'question_text': 'Describe a time when you received constructive criticism or tough feedback from a manager or mentor that was genuinely hard to hear. How did you respond in the moment and what changed as a result?',
                'category': 'behavioral',
                'difficulty': 'medium',
                'what_it_tests': 'Coachability, emotional maturity, and ability to receive and act on feedback without defensiveness or resentment',
                'sample_answer_outline': 'The candidate should describe a specific piece of feedback with enough detail to understand why it stung, share their honest initial reaction including any discomfort or defensiveness they felt, explain the deliberate steps they took to internalize and act on the feedback rather than dismiss it, and describe the measurable improvement that resulted. A good answer demonstrates genuine humility, a growth mindset, and the emotional intelligence to separate personal feelings from professional development opportunities.',
            },
            {
                'question_text': 'A prospect you have been nurturing carefully for several weeks finally agrees to a meeting but then reschedules three times in a row. Your manager tells you to stop pursuing them and focus elsewhere. How do you think through this decision?',
                'category': 'situational',
                'difficulty': 'hard',
                'what_it_tests': 'Judgment in balancing persistence with efficiency and ability to follow management direction while also thinking critically about account potential',
                'sample_answer_outline': 'The candidate should discuss evaluating the account strategic potential and the signals embedded in the prospect rescheduling behavior, weighing the sunk cost of weeks of nurturing against the opportunity cost of continued pursuit, and making a data-informed recommendation. A strong answer shows respect for the manager guidance while explaining how they might present their reasoning if they believe the account justifies one more attempt. Critically, they should demonstrate willingness to ultimately accept the manager final decision and redirect their energy productively.',
            },
            {
                'question_text': 'If you were promoted to team lead for the SDR team tomorrow, what is the first thing you would want to understand, change, or improve about how the team currently operates, and why?',
                'category': 'leadership',
                'difficulty': 'medium',
                'what_it_tests': 'Observation skills, initiative, and ability to think about process and team improvement beyond individual task execution',
                'sample_answer_outline': 'The candidate should identify a specific and thoughtful observation based on their experience as a team member, explain the reasoning behind why this area matters, describe how they would investigate before making changes, and show awareness of the complexity of implementing change versus simply having an opinion. A good answer demonstrates that the candidate pays careful attention to team dynamics, processes, and systemic patterns rather than being focused exclusively on their own individual work.',
            },
            {
                'question_text': 'How do you handle the ethical tension when you feel pressure to hit aggressive meeting targets but you suspect that some of the meetings you are setting do not truly meet the qualification bar for account executive time?',
                'category': 'culture',
                'difficulty': 'hard',
                'what_it_tests': 'Integrity under quota pressure and understanding of how lead quality impacts the broader sales organization and company reputation',
                'sample_answer_outline': 'A good answer acknowledges the real and uncomfortable tension between quantity targets and quality standards without pretending it does not exist. The candidate should explain why passing unqualified leads damages the business through wasted account executive time and pipeline inflation, erodes their own credibility with the sales team, and ultimately hurts their long-term career. They should describe how they would raise the concern with their manager using data on conversion rates, and demonstrate that they would choose quality over gaming metrics even when it means a harder month.',
            },
            {
                'question_text': 'You are tasked with breaking into a strategic target account where no one on the team has been able to get a response from any contact despite months of outreach. What creative approaches would you try beyond standard email and phone?',
                'category': 'problem_solving',
                'difficulty': 'hard',
                'what_it_tests': 'Creative prospecting resourcefulness and ability to think beyond standard playbook tactics when conventional approaches have failed',
                'sample_answer_outline': 'A strong answer goes well beyond just increasing email and call volume to describe creative approaches such as leveraging mutual connections or alumni networks for warm introductions, engaging thoughtfully with the prospect published content on social media to build name recognition, identifying trigger events like recent job changes or company announcements that create fresh openings, trying different entry points and personas within the account, using personalized video messages or direct mail to stand out, attending industry events where target contacts will be present, or partnering with marketing on targeted account-based advertising. The candidate should also demonstrate wisdom about when to deprioritize an unresponsive account and redirect energy.',
            },
        ],
    },
]
