# Generated by Django 4.2.26 on 2025-11-17 05:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BehavioralQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block_id', models.PositiveIntegerField(unique=True)),
                ('prompt', models.CharField(default='Select the statements that best describe you.', max_length=255)),
                ('statements', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('block_id',),
            },
        ),
        migrations.CreateModel(
            name='BehavioralAssessmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('candidate_id', models.CharField(db_index=True, max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In progress'), ('submitted', 'Submitted')], default='draft', max_length=16)),
                ('question_set', models.JSONField(default=list)),
                ('responses', models.JSONField(blank=True, default=list)),
                ('trait_scores', models.JSONField(blank=True, default=dict)),
                ('profile_report', models.JSONField(blank=True, default=dict)),
                ('eligibility_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('eligibility_label', models.CharField(blank=True, max_length=64)),
                ('risk_flags', models.JSONField(blank=True, default=list)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=20)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['candidate_id'], name='behavioral__candida_4de4b0_idx')],
            },
        ),
    ]
