# Generated by Django 4.2.26 on 2025-11-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behavioral_assessments', '0003_behavioralassessmentsession_last_reminder_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='behavioralassessmentsession',
            name='candidate_feedback_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='behavioralassessmentsession',
            name='candidate_feedback_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='behavioralassessmentsession',
            name='candidate_feedback_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
