# Generated by Django 4.2.26 on 2025-11-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behavioral_assessments', '0005_behavioralassessmentsession_last_activity_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='behavioralassessmentsession',
            name='candidate_feedback_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='behavioralassessmentsession',
            name='candidate_feedback_opt_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='behavioralassessmentsession',
            name='candidate_feedback_phone',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='behavioralassessmentsession',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In progress'), ('paused', 'Paused'), ('submitted', 'Submitted')], default='draft', max_length=16),
        ),
    ]
