# Generated by Django 4.2.26 on 2026-01-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behavioral_assessments', '0010_behavioralassessmentsession_deadline_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='behavioralassessmentsession',
            name='level',
            field=models.CharField(choices=[('junior', 'Junior (0-2 years)'), ('mid', 'Mid-Level (2-5 years)'), ('senior', 'Senior (5+ years)')], default='mid', help_text='Target experience level for this assessment', max_length=10),
        ),
        migrations.AddField(
            model_name='behavioralquestion',
            name='difficulty_level',
            field=models.PositiveSmallIntegerField(default=3, help_text='1=Easy (Junior), 5=Hard (Senior)'),
        ),
    ]
