"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.26.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import sys
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def load_env_file(path: Path):
    if not path.exists():
        return
    for raw_line in path.read_text().splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        if not key:
            continue
        value = value.strip()
        if (value.startswith('"') and value.endswith('"')) or (
            value.startswith("'") and value.endswith("'")
        ):
            value = value[1:-1]
        os.environ.setdefault(key, value)


# Load .env if present (local dev / CLI)
load_env_file(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
_default_insecure_key = "django-insecure-!ff578td7c0)r&pz9!d0bdq#yam$cd!im8%!v!h_*@*l@^se1="
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", _default_insecure_key)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "1") == "1"

# Reject insecure secret key in production (skip during collectstatic build)
_is_collectstatic = len(sys.argv) > 1 and sys.argv[1] == "collectstatic"
if not DEBUG and SECRET_KEY == _default_insecure_key and not _is_collectstatic:
    raise ValueError("DJANGO_SECRET_KEY must be set in production (DEBUG=False).")

DEFAULT_ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    ".evalon.tech",
    ".herokuapp.com",
]
env_allowed_hosts = [
    host.strip()
    for host in os.environ.get("ALLOWED_HOSTS", "").split(",")
    if host.strip()
]
ALLOWED_HOSTS = list({*DEFAULT_ALLOWED_HOSTS, *env_allowed_hosts})
if not ALLOWED_HOSTS:
    ALLOWED_HOSTS = DEFAULT_ALLOWED_HOSTS

DEFAULT_CSRF_TRUSTED_ORIGINS = [
    "https://evalon.tech",
    "https://www.evalon.tech",
    "https://assesment-7249edfd30d7.herokuapp.com",
]
env_csrf_origins = [
    origin.strip()
    for origin in os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
]
CSRF_TRUSTED_ORIGINS = list({*DEFAULT_CSRF_TRUSTED_ORIGINS, *env_csrf_origins})

# Session cookie: must be sent when Google redirects back (SameSite=Lax, Secure on HTTPS)
SESSION_ENGINE = "django.contrib.sessions.backends.db"
SESSION_COOKIE_AGE = 1209600  # 2 weeks
SESSION_SAVE_EVERY_REQUEST = False  # Don't extend session on every request (defeats timeout)
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = os.environ.get("SESSION_COOKIE_SECURE", "0" if DEBUG else "1") == "1"
SESSION_COOKIE_SAMESITE = "Lax"  # allow cookie on redirect from Google back to us
# Set SESSION_COOKIE_DOMAIN=.evalon.tech on Heroku when using www.evalon.tech so the session cookie
# is sent when Google redirects back (fixes "unknown" / session lost for both login and sign-up).
_session_domain = os.environ.get("SESSION_COOKIE_DOMAIN", "").strip()
SESSION_COOKIE_DOMAIN = _session_domain or None

# Security headers (enabled in production only)
if not DEBUG:
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_SSL_REDIRECT = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'django.contrib.humanize',
    # Allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.linkedin_oauth2',
    # Project apps
    'marketing',
    'console',
    'candidate',
    'pages',
    'blog',
    'assessments',
    'marketing_assessments',
    'pm_assessments',
    'behavioral_assessments',
    'custom_assessments',
    'ux_assessments',
    'hr_assessments',
    'finance_assessments',
    'clients',
    'seo',
    'hiring_agent',
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'config.middleware.SessionCookieDomainMiddleware',  # set Domain=.evalon.tech for www so Google callback gets cookie
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'marketing.context_processors.marketing_settings',
                'seo.context_processors.seo_metadata',
                'clients.context_processors.portal_navigation',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        ssl_require=False,
    )
}


def _configure_test_database():
    """Ensure tests use a writable database even on hosted Postgres (e.g. Heroku)."""

    if "test" not in sys.argv:
        return

    # Allow overriding via TEST_DATABASE_URL if a disposable database exists.
    test_database_url = os.environ.get("TEST_DATABASE_URL")
    if test_database_url:
        DATABASES["default"] = dj_database_url.parse(
            test_database_url, conn_max_age=0, ssl_require=False
        )
        return

    if os.environ.get("TEST_USE_SQLITE", "1") == "1":
        DATABASES["default"] = {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "test.sqlite3",
        }
        # Django skips creating/dropping databases for SQLite if TEST NAME matches NAME.
        DATABASES["default"]["TEST"] = {"NAME": BASE_DIR / "test.sqlite3"}


_configure_test_database()

# Cache for OAuth state fallback when session cookie is lost on redirect (e.g. Google callback).
# State is stashed in session AND in cache; callback can restore from cache if session is missing.
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "default",
    },
    "oauth_state": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "oauth_state_cache",
        "OPTIONS": {"MAX_ENTRIES": 1000},
        "TIMEOUT": 600,  # 10 minutes
    },
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'
STATICFILES_DIRS = (
    [BASE_DIR / 'static']
    if (BASE_DIR / 'static').exists()
    else []
)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
# Allow missing source-map files referenced in third-party CSS (e.g. jazzmin/bootswatch)
import whitenoise.storage
whitenoise.storage.CompressedManifestStaticFilesStorage.manifest_strict = False
if "test" in sys.argv:
    WHITENOISE_USE_FINDERS = True

# Media uploads
MEDIA_URL = os.environ.get("MEDIA_URL", "/media/")
MEDIA_ROOT = Path(os.environ.get("MEDIA_ROOT", str(BASE_DIR / "media")))

# Email
DEFAULT_EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_BACKEND = os.environ.get("EMAIL_BACKEND", DEFAULT_EMAIL_BACKEND)
EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.sendgrid.net")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "apikey")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "1") == "1"
EMAIL_USE_SSL = os.environ.get("EMAIL_USE_SSL", "0") == "1"
DEFAULT_FROM_EMAIL = os.environ.get(
    "DEFAULT_FROM_EMAIL", "Evalon Hiring <talent@evalon.com>"
)
EMAIL_ENABLED = EMAIL_BACKEND != "django.core.mail.backends.console.EmailBackend"

# Site URL for generating absolute URLs in emails
SITE_URL = os.environ.get("SITE_URL", "https://www.evalon.tech")

# Admin notification emails (for client approval notifications)
ADMIN_NOTIFICATION_EMAILS = [
    email.strip()
    for email in os.environ.get("ADMIN_NOTIFICATION_EMAILS", "info@evalon.tech").split(",")
    if email.strip()
]

ASSESSMENT_PASSING_SCORE = float(os.environ.get("ASSESSMENT_PASSING_SCORE", "70"))

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

API_ACCESS_TOKEN = os.environ.get("API_ACCESS_TOKEN", "")

# Anthropic API for AI question generation
ANTHROPIC_API_KEY = os.environ.get("ANTHROPIC_API_KEY", "")
ANTHROPIC_MODEL = os.environ.get("ANTHROPIC_MODEL", "claude-sonnet-4-20250514")

# Django-allauth settings
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_VERIFICATION = 'none'  # Social providers verify emails
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_USER_MODEL_USERNAME_FIELD = "username"
ACCOUNT_ADAPTER = 'clients.adapters.ClientAccountAdapter'
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
SOCIALACCOUNT_ADAPTER = 'clients.adapters.ClientSocialAccountAdapter'
SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_STORE_TOKENS = True

LOGIN_URL = 'clients:login'
LOGIN_REDIRECT_URL = 'clients:complete_profile'
ACCOUNT_LOGOUT_REDIRECT_URL = 'pages:home'

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
        'APP': {
            'client_id': os.environ.get('GOOGLE_CLIENT_ID', ''),
            'secret': os.environ.get('GOOGLE_CLIENT_SECRET', ''),
        }
    },
    'linkedin_oauth2': {
        'SCOPE': ['openid', 'profile', 'email'],
        'APP': {
            'client_id': os.environ.get('LINKEDIN_CLIENT_ID', ''),
            'secret': os.environ.get('LINKEDIN_CLIENT_SECRET', ''),
        }
    },
}

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'clients': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# ---------------------------------------------------------------------------
# Django Jazzmin — Modern admin UI
# ---------------------------------------------------------------------------

JAZZMIN_SETTINGS = {
    # Window / tab title
    "site_title": "Evalon Admin",
    # Brand text in top-left of sidebar
    "site_header": "Evalon",
    "site_brand": "Evalon",
    # Logo — shown in sidebar and login page
    "site_logo": "img/logo-glyph.svg",
    "site_logo_classes": "",
    "site_icon": "img/logo-glyph.svg",
    "login_logo": "img/evalon-logo.png",
    "login_logo_dark": None,
    # Welcome text on login page
    "welcome_sign": "Welcome to Evalon Admin",
    "copyright": "Evalon",
    # Search bar in top nav — most common lookups
    "search_model": [
        "clients.ClientAccount",
        "assessments.CandidateProfile",
        "assessments.AssessmentSession",
    ],
    # Top menu links (shown above page content)
    "topmenu_links": [
        {"name": "Dashboard", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "View Site", "url": "/", "new_window": True},
    ],
    # ----- Sidebar -----
    "show_sidebar": True,
    "navigation_expanded": False,
    # Hide cluttering allauth / sites / auth models
    "hide_apps": [
        "sites",
        "socialaccount",
        "account",
    ],
    "hide_models": [
        "auth.Group",
    ],
    # Sidebar app ordering (most important first)
    "order_with_respect_to": [
        "clients",
        "hiring_agent",
        "assessments",
        "custom_assessments",
        "marketing_assessments",
        "pm_assessments",
        "behavioral_assessments",
        "ux_assessments",
        "hr_assessments",
        "finance_assessments",
        "pages",
        "blog",
        "seo",
        "marketing",
        "console",
        "candidate",
        "auth",
    ],
    # ----- Icons (Font Awesome 5) -----
    "icons": {
        # Auth
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user-shield",
        # Clients
        "clients.ClientAccount": "fas fa-building",
        "clients.SupportRequest": "fas fa-life-ring",
        # AI Hiring
        "hiring_agent.HiringPipeline": "fas fa-robot",
        "hiring_agent.PipelineCandidate": "fas fa-user-check",
        "hiring_agent.AgentActionLog": "fas fa-clipboard-list",
        # Core Assessments
        "assessments.RoleCategory": "fas fa-layer-group",
        "assessments.Assessment": "fas fa-clipboard-check",
        "assessments.Question": "fas fa-question-circle",
        "assessments.CandidateProfile": "fas fa-user-graduate",
        "assessments.CompanyProfile": "fas fa-city",
        "assessments.PositionTask": "fas fa-tasks",
        "assessments.AssessmentSession": "fas fa-play-circle",
        "assessments.Response": "fas fa-reply",
        # Custom Assessments
        "custom_assessments.CustomAssessment": "fas fa-puzzle-piece",
        "custom_assessments.CustomQuestion": "fas fa-edit",
        "custom_assessments.CustomAssessmentSession": "fas fa-laptop-code",
        # Marketing Assessments
        "marketing_assessments.DigitalMarketingQuestion": "fas fa-bullhorn",
        "marketing_assessments.DigitalMarketingAssessmentSession": "fas fa-chart-line",
        # Product Management
        "pm_assessments.ProductQuestion": "fas fa-box-open",
        "pm_assessments.ProductAssessmentSession": "fas fa-project-diagram",
        # Behavioral
        "behavioral_assessments.BehavioralQuestion": "fas fa-brain",
        "behavioral_assessments.BehavioralAssessmentSession": "fas fa-user-friends",
        # UX Design
        "ux_assessments.UXDesignQuestion": "fas fa-palette",
        "ux_assessments.UXDesignAssessmentSession": "fas fa-pencil-ruler",
        # HR
        "hr_assessments.HRQuestion": "fas fa-id-badge",
        "hr_assessments.HRAssessmentSession": "fas fa-handshake",
        # Finance
        "finance_assessments.FinanceQuestion": "fas fa-dollar-sign",
        "finance_assessments.FinanceAssessmentSession": "fas fa-file-invoice-dollar",
        # Pages & Leads
        "pages.DemoRequest": "fas fa-calendar-check",
        "pages.APIAccessRequest": "fas fa-key",
        "pages.NewsletterSubscriber": "fas fa-envelope-open-text",
        "pages.PublicAssessment": "fas fa-star",
        "pages.Role": "fas fa-briefcase",
        "pages.InterviewQuestion": "fas fa-comments",
        # Blog
        "blog.BlogCategory": "fas fa-folder",
        "blog.BlogPost": "fas fa-newspaper",
        # SEO
        "seo.SeoPage": "fas fa-search",
        # Marketing Settings
        "marketing.MarketingSettings": "fas fa-cog",
        "marketing.MarketingEmailSettings": "fas fa-mail-bulk",
        # Console
        "console.SiteContentBlock": "fas fa-cubes",
        "console.ResourceAsset": "fas fa-file-download",
        # Candidate
        "candidate.CandidateSupportRequest": "fas fa-headset",
    },
    "default_icon_parents": "fas fa-folder-open",
    "default_icon_children": "fas fa-circle",
    # ----- Change form layout -----
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "clients.ClientAccount": "horizontal_tabs",
        "pages.PublicAssessment": "horizontal_tabs",
        "custom_assessments.CustomAssessmentSession": "horizontal_tabs",
    },
    # Modals for related objects
    "related_modal_active": True,
    "show_ui_builder": False,
    "language_chooser": False,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": True,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-warning",
    "navbar": "navbar-dark",
    "no_navbar_border": True,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-warning",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "darkly",
    "dark_mode_theme": "darkly",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
    "actions_sticky_top": True,
}
