# Generated by Django 4.2.26 on 2026-02-14 14:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0008_assessmentsession_telemetry_log'),
        ('clients', '0023_alter_clientsessionnote_assessment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiringPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('job_description', models.TextField()),
                ('required_skills', models.JSONField(blank=True, default=list)),
                ('preferred_skills', models.JSONField(blank=True, default=list)),
                ('experience_range', models.CharField(blank=True, max_length=50)),
                ('seniority_level', models.CharField(choices=[('junior', 'Junior'), ('mid', 'Mid-Level'), ('senior', 'Senior'), ('lead', 'Lead'), ('executive', 'Executive')], default='mid', max_length=20)),
                ('assessment_types', models.JSONField(blank=True, default=list, help_text='Assessment type codes to send, e.g. ["marketing", "behavioral"]')),
                ('automation_mode', models.CharField(choices=[('recommend', 'Recommend (human approves all)'), ('semi_auto', 'Semi-Auto (auto-screen, human decides)'), ('full_auto', 'Full Auto (AI handles all)')], default='recommend', max_length=20)),
                ('screening_threshold', models.PositiveIntegerField(default=60, help_text='Minimum AI resume score (0-100) to shortlist a candidate')),
                ('passing_score', models.PositiveIntegerField(default=70, help_text='Minimum assessment score (0-100) to advance a candidate')),
                ('max_candidates', models.PositiveIntegerField(default=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiring_pipelines', to='clients.clientaccount')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hiring_pipelines', to='clients.clientproject')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PipelineCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume_file', models.FileField(blank=True, upload_to='resumes/')),
                ('resume_text', models.TextField(blank=True)),
                ('stage', models.CharField(choices=[('uploaded', 'Resume Uploaded'), ('screening', 'AI Screening'), ('shortlisted', 'Shortlisted'), ('rejected_at_screen', 'Rejected (Screening)'), ('assessment_pending', 'Assessment Pending'), ('assessment_sent', 'Assessment Sent'), ('assessment_completed', 'Assessment Completed'), ('decision_made', 'Decision Made'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='uploaded', max_length=30)),
                ('ai_screen_score', models.PositiveIntegerField(blank=True, null=True)),
                ('ai_screen_summary', models.TextField(blank=True)),
                ('ai_screen_skills_matched', models.JSONField(blank=True, default=list)),
                ('ai_screen_skills_missing', models.JSONField(blank=True, default=list)),
                ('ai_final_score', models.PositiveIntegerField(blank=True, null=True)),
                ('ai_final_summary', models.TextField(blank=True)),
                ('ai_final_recommendation', models.CharField(blank=True, choices=[('', 'Pending'), ('advance', 'Advance'), ('hold', 'Hold'), ('reject', 'Reject')], max_length=20)),
                ('human_decision', models.CharField(blank=True, choices=[('', 'Pending'), ('advance', 'Advance'), ('hold', 'Hold'), ('reject', 'Reject')], max_length=20)),
                ('human_notes', models.TextField(blank=True)),
                ('assessment_sessions', models.JSONField(blank=True, default=list, help_text='[{"type": "marketing", "session_uuid": "...", "score": null, "status": "invited"}]')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_entries', to='assessments.candidateprofile')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='hiring_agent.hiringpipeline')),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('pipeline', 'candidate')},
            },
        ),
        migrations.CreateModel(
            name='AgentActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('resume_screen', 'Resume Screen'), ('assessment_select', 'Assessment Selection'), ('assessment_send', 'Assessment Send'), ('score_check', 'Score Check'), ('final_decision', 'Final Decision')], max_length=30)),
                ('input_data', models.JSONField(blank=True, default=dict)),
                ('output_data', models.JSONField(blank=True, default=dict)),
                ('ai_model', models.CharField(blank=True, max_length=100)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], default='success', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='hiring_agent.pipelinecandidate')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='hiring_agent.hiringpipeline')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
