# Generated by Django 4.2.26 on 2026-02-16 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0008_assessmentsession_telemetry_log'),
        ('hiring_agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelinecandidate',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pipeline_entries', to='assessments.candidateprofile'),
        ),
    ]
