# Generated by Django 4.2.26 on 2025-11-17 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm_assessments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productquestion',
            name='category',
            field=models.CharField(choices=[('product', 'Product sense'), ('execution', 'Execution & delivery'), ('strategy', 'Strategy'), ('analytics', 'Analytics'), ('technical', 'Technical'), ('design', 'UX & research'), ('behavioral', 'Behavioral & leadership')], max_length=32),
        ),
        migrations.AlterField(
            model_name='productquestion',
            name='options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='productquestion',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple choice'), ('open_ended', 'Open ended'), ('prioritization', 'Prioritization'), ('estimation', 'Estimation'), ('reasoning', 'Reasoning / open response'), ('behavioral_most', 'Behavioral - most like me'), ('behavioral_least', 'Behavioral - least like me')], max_length=32),
        ),
    ]
