# Generated by Django 4.2.26 on 2025-11-17 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_clientaccount_requested_assessment_and_more'),
        ('pm_assessments', '0002_alter_productquestion_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productassessmentsession',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_sessions', to='clients.clientaccount'),
        ),
    ]
