# Generated by Django 4.2.26 on 2025-11-21 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_clientproject'),
        ('pm_assessments', '0008_productassessmentsession_telemetry_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='productassessmentsession',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_sessions', to='clients.clientproject'),
        ),
    ]
