# Generated by Django 4.2.26 on 2026-01-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm_assessments', '0011_productassessmentsession_deadline_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productassessmentsession',
            name='level',
            field=models.CharField(choices=[('junior', 'Junior (0-2 years)'), ('mid', 'Mid-Level (2-5 years)'), ('senior', 'Senior (5+ years)')], default='mid', help_text='Target experience level for this assessment', max_length=10),
        ),
    ]
