# Generated by Django 4.2.26 on 2026-02-16 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0023_alter_clientsessionnote_assessment_type'),
        ('pm_assessments', '0012_productassessmentsession_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productassessmentsession',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_sessions', to='clients.clientproject'),
        ),
    ]
