# Generated by Django 4.2.26 on 2025-11-21 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0008_assessmentsession_telemetry_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateSupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.CharField(choices=[('technical', 'Technical issue'), ('question', 'Question about instructions'), ('accessibility', 'Accessibility support'), ('other', 'Something else')], default='technical', max_length=32)),
                ('message', models.TextField()),
                ('contact_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('chat', 'Chat handle')], default='email', max_length=20)),
                ('contact_value', models.CharField(blank=True, max_length=255)),
                ('candidate_name', models.CharField(blank=True, max_length=160)),
                ('candidate_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(default='new', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_requests', to='assessments.assessmentsession')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
