# Generated by Django 4.2.26 on 2025-11-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalmarketingassessmentsession',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='digitalmarketingassessmentsession',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='digitalmarketingquestion',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple choice'), ('scenario', 'Scenario based'), ('ranking', 'Ranking / Ordering'), ('behavioral_most', 'Behavioral - most like me'), ('behavioral_least', 'Behavioral - least like me'), ('reasoning', 'Reasoning / open response')], max_length=32),
        ),
    ]
