# Generated by Django 4.2.26 on 2025-11-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_assessments', '0003_digitalmarketingassessmentsession_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalmarketingassessmentsession',
            name='last_reminder_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='digitalmarketingassessmentsession',
            name='reminder_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='digitalmarketingassessmentsession',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
