# Generated by Django 4.2.26 on 2025-11-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_assessments', '0005_digitalmarketingassessmentsession_candidate_feedback_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalmarketingassessmentsession',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='digitalmarketingassessmentsession',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='digitalmarketingassessmentsession',
            name='total_paused_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
