# Generated by Django 4.2.26 on 2025-11-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_assessments', '0007_digitalmarketingassessmentsession_candidate_feedback_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalmarketingassessmentsession',
            name='telemetry_log',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
