# Generated by Django 4.2.26 on 2025-11-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_assessments', '0009_digitalmarketingassessmentsession_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalmarketingassessmentsession',
            name='pipeline_stage',
            field=models.CharField(choices=[('invited', 'Invited'), ('in_progress', 'In progress'), ('submitted', 'Assessment submitted'), ('interview', 'Interview'), ('offer', 'Offer extended'), ('hired', 'Hired / onboarded'), ('rejected', 'Not moving forward')], default='invited', max_length=32),
        ),
        migrations.AddField(
            model_name='digitalmarketingassessmentsession',
            name='pipeline_stage_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
