# Generated by Django 4.2.26 on 2026-01-11 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_assessments', '0010_digitalmarketingassessmentsession_pipeline_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalmarketingassessmentsession',
            name='deadline_at',
            field=models.DateTimeField(blank=True, help_text='Absolute deadline', null=True),
        ),
        migrations.AddField(
            model_name='digitalmarketingassessmentsession',
            name='deadline_days',
            field=models.PositiveIntegerField(blank=True, help_text='Days from invite to complete', null=True),
        ),
        migrations.AddField(
            model_name='digitalmarketingassessmentsession',
            name='deadline_type',
            field=models.CharField(choices=[('none', 'No deadline'), ('relative', 'Days from invite'), ('absolute', 'Specific date')], default='none', max_length=16),
        ),
    ]
