# Generated by Django 4.2.26 on 2026-01-23 23:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0018_add_notification_preferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('role_description', models.TextField(blank=True, help_text='Role this assessment targets')),
                ('skills_to_test', models.TextField(blank=True, help_text='Skills/knowledge areas')),
                ('ai_generated', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('time_limit_minutes', models.PositiveIntegerField(default=30)),
                ('passing_score', models.PositiveIntegerField(default=70, help_text='Minimum percentage to pass', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_assessments', to='clients.clientaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(max_length=500)),
                ('option_b', models.CharField(max_length=500)),
                ('option_c', models.CharField(blank=True, max_length=500)),
                ('option_d', models.CharField(blank=True, max_length=500)),
                ('correct_answer', models.CharField(help_text='A, B, C, or D', max_length=1)),
                ('explanation', models.TextField(blank=True)),
                ('difficulty_level', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('category', models.CharField(blank=True, max_length=100)),
                ('ai_generated', models.BooleanField(default=False)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='custom_assessments.customassessment')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CustomAssessmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('candidate_id', models.CharField(db_index=True, max_length=120)),
                ('candidate_email', models.EmailField(blank=True, max_length=254)),
                ('level', models.CharField(choices=[('junior', 'Junior (0-2 years)'), ('mid', 'Mid-Level (2-5 years)'), ('senior', 'Senior (5+ years)')], default='mid', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('submitted', 'Submitted')], default='draft', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('current_question_index', models.PositiveIntegerField(default=0)),
                ('answers', models.JSONField(default=dict)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('question_order', models.JSONField(default=list)),
                ('pipeline_stage', models.CharField(choices=[('invited', 'Invited'), ('in_progress', 'In progress'), ('submitted', 'Assessment submitted'), ('interview', 'Interview'), ('offer', 'Offer extended'), ('hired', 'Hired / onboarded'), ('rejected', 'Not moving forward')], default='invited', max_length=32)),
                ('pipeline_stage_updated_at', models.DateTimeField(blank=True, null=True)),
                ('deadline_at', models.DateTimeField(blank=True, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='custom_assessments.customassessment')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_sessions', to='clients.clientaccount')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_sessions', to='clients.clientproject')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['candidate_id'], name='custom_asse_candida_b98aca_idx'), models.Index(fields=['assessment', 'status'], name='custom_asse_assessm_f32636_idx')],
            },
        ),
    ]
