# Generated by Django 4.2.26 on 2026-01-25 14:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customassessment',
            name='detect_tab_switches',
            field=models.BooleanField(default=True, help_text='Track when candidates switch tabs/windows'),
        ),
        migrations.AddField(
            model_name='customassessment',
            name='max_tab_switches',
            field=models.PositiveIntegerField(default=3, help_text='Max allowed tab switches before flagging (0 = unlimited)'),
        ),
        migrations.AddField(
            model_name='customassessment',
            name='prevent_copy_paste',
            field=models.BooleanField(default=True, help_text='Prevent copying question text'),
        ),
        migrations.AddField(
            model_name='customassessment',
            name='require_fullscreen',
            field=models.BooleanField(default=False, help_text='Require candidates to use full-screen mode'),
        ),
        migrations.AddField(
            model_name='customassessmentsession',
            name='copy_attempt_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customassessmentsession',
            name='flagged_for_review',
            field=models.BooleanField(default=False, help_text='Flagged for manual review due to suspicious activity'),
        ),
        migrations.AddField(
            model_name='customassessmentsession',
            name='fullscreen_exit_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customassessmentsession',
            name='tab_switch_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customassessmentsession',
            name='telemetry_log',
            field=models.JSONField(default=list, help_text='Activity log for anti-cheating analysis'),
        ),
        migrations.AddField(
            model_name='customassessmentsession',
            name='trust_score',
            field=models.PositiveIntegerField(default=100, help_text='Trust score based on behavior (100 = fully trusted)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
