# Generated by Django 4.2.26 on 2026-01-25 19:09

import custom_assessments.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_assessments', '0002_add_anti_cheating_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='customquestion',
            name='file_allowed_extensions',
            field=models.CharField(blank=True, default='pdf,doc,docx,txt,py,js,java,cpp', help_text='Comma-separated list of allowed file extensions', max_length=200),
        ),
        migrations.AddField(
            model_name='customquestion',
            name='file_max_size_mb',
            field=models.PositiveIntegerField(default=10, help_text='Maximum file size in MB'),
        ),
        migrations.AddField(
            model_name='customquestion',
            name='points',
            field=models.PositiveIntegerField(default=1, help_text='Points for this question (for weighted scoring)'),
        ),
        migrations.AddField(
            model_name='customquestion',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('text_short', 'Short Text'), ('text_long', 'Long Text / Essay'), ('video', 'Video Response'), ('file_upload', 'File Upload')], default='multiple_choice', max_length=20),
        ),
        migrations.AddField(
            model_name='customquestion',
            name='requires_manual_scoring',
            field=models.BooleanField(default=False, help_text='Whether this question requires manual scoring'),
        ),
        migrations.AddField(
            model_name='customquestion',
            name='text_ideal_answer',
            field=models.TextField(blank=True, help_text='Ideal answer for AI scoring reference'),
        ),
        migrations.AddField(
            model_name='customquestion',
            name='text_max_length',
            field=models.PositiveIntegerField(default=5000, help_text='Maximum character count for text responses'),
        ),
        migrations.AddField(
            model_name='customquestion',
            name='text_min_length',
            field=models.PositiveIntegerField(default=0, help_text='Minimum character count for text responses'),
        ),
        migrations.AddField(
            model_name='customquestion',
            name='video_max_duration_seconds',
            field=models.PositiveIntegerField(default=120, help_text='Maximum video duration in seconds'),
        ),
        migrations.AlterField(
            model_name='customquestion',
            name='correct_answer',
            field=models.CharField(blank=True, help_text='A, B, C, or D (for multiple choice)', max_length=1),
        ),
        migrations.AlterField(
            model_name='customquestion',
            name='option_a',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='customquestion',
            name='option_b',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='CandidateResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text_response', models.TextField(blank=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to=custom_assessments.models.candidate_upload_path)),
                ('video_duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to=custom_assessments.models.candidate_upload_path)),
                ('uploaded_file_name', models.CharField(blank=True, max_length=255)),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Score out of 100 for this response', max_digits=5, null=True)),
                ('score_feedback', models.TextField(blank=True, help_text='Feedback from evaluator or AI')),
                ('scored_by', models.CharField(choices=[('pending', 'Pending'), ('manual', 'Manual'), ('ai', 'AI')], default='pending', max_length=20)),
                ('scored_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_responses', to='custom_assessments.customquestion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='custom_assessments.customassessmentsession')),
            ],
            options={
                'ordering': ['question__order'],
                'unique_together': {('session', 'question')},
            },
        ),
    ]
