# Generated by Django 4.2.26 on 2026-02-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeoPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('path', models.CharField(blank=True, help_text='Leading slash paths (e.g., /pricing) or regex when match_type=regex.', max_length=255)),
                ('match_type', models.CharField(choices=[('exact', 'Exact path match'), ('prefix', 'Path prefix match'), ('regex', 'Regex match')], default='exact', max_length=16)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('description', models.CharField(blank=True, max_length=320)),
                ('canonical_url', models.URLField(blank=True)),
                ('og_title', models.CharField(blank=True, max_length=160)),
                ('og_description', models.CharField(blank=True, max_length=320)),
                ('og_type', models.CharField(blank=True, default='website', max_length=50)),
                ('twitter_title', models.CharField(blank=True, max_length=160)),
                ('twitter_description', models.CharField(blank=True, max_length=320)),
                ('image_url', models.URLField(blank=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=400)),
                ('schema_type', models.CharField(blank=True, max_length=100)),
                ('structured_data', models.JSONField(blank=True, null=True)),
                ('noindex', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'SEO Page',
                'verbose_name_plural': 'SEO Pages',
                'ordering': ['order', 'slug'],
            },
        ),
    ]
